/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 4 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "MATADEROS", destino: "BARRACAS", kmReal: 17, kmConv: 15 },
  { origen: "ZONA PORTUARIA", destino: "ARROYITO", kmReal: 650, kmConv: 650 },
  { origen: "SUSANA", destino: "MAR DEL PLATA", kmReal: 943, kmConv: 945 },
  { origen: "LIBERTAD", destino: "CONCEPCION DEL URUGUAY", kmReal: 355, kmConv: 355 },
  { origen: "TUCUMAN", destino: "ARROYITO", kmReal: 684, kmConv: 685 },
  { origen: "PILAR", destino: "SOLDINI", kmReal: 263, kmConv: 265 },
  { origen: "RAFAELA", destino: "SANTA FE", kmReal: 193, kmConv: 195 },
  { origen: "POSADAS", destino: "LEANDRO N ALEM", kmReal: 87, kmConv: 85 },
  { origen: "RAFAELA", destino: "LIBERTAD", kmReal: 725, kmConv: 725 },
  { origen: "SAN MIGUEL DE TUCUMAN", destino: "CAMPANA", kmReal: 1180, kmConv: 1180 },
  { origen: "MONTEROS", destino: "SAN MIGUEL DE TUCUMAN", kmReal: 52, kmConv: 50 },
  { origen: "EZEIZA", destino: "SAN JUSTO", kmReal: 24, kmConv: 25 },
  { origen: "LOMAS DE ZAMORA", destino: "MONTE GRANDE", kmReal: 11, kmConv: 10 },
  { origen: "LONGCHAMPS", destino: "SAN ANDRES DE GILES", kmReal: 155, kmConv: 155 },
  { origen: "VILLA SOLDATI", destino: "VILLA MERCEDES", kmReal: 693, kmConv: 695 },
  { origen: "SUSANA", destino: "MONTEROS", kmReal: 693, kmConv: 695 },
  { origen: "SUSANA", destino: "EZEIZA", kmReal: 553, kmConv: 555 },
  { origen: "SAN ANTONIO DE ARECO", destino: "CORDOBA", kmReal: 691, kmConv: 690 },
  { origen: "SAN ANTONIO DE ARECO", destino: "CORONEL MOLDES", kmReal: 691, kmConv: 690 },
  { origen: "VILLA SOLDATI", destino: "SAN ANTONIO DE ARECO", kmReal: 126, kmConv: 125 },
  { origen: "CATRILO", destino: "PARANÁ", kmReal: 772, kmConv: 770 },
  { origen: "GENERAL PICO", destino: "CATRILO", kmReal: 96, kmConv: 95 },
  { origen: "AROCENA", destino: "SAUCE VIEJO", kmReal: 39, kmConv: 40 },
  { origen: "ZARATE", destino: "AROCENA", kmReal: 323, kmConv: 325 },
  { origen: "EZEIZA", destino: "SAN ANDRES DE GILES", kmReal: 133, kmConv: 135 },
  { origen: "SAN MARTIN", destino: "EZEIZA", kmReal: 37, kmConv: 35 },
  { origen: "VILLA CELINA", destino: "BARADERO", kmReal: 156, kmConv: 155 },
  { origen: "SAN JORGE", destino: "JOSE C. PAZ", kmReal: 471, kmConv: 470 },
  { origen: "TORTUGUITAS", destino: "GARIN", kmReal: 9, kmConv: 10 },
  { origen: "VILLA SOLDATI", destino: "AROCENA", kmReal: 412, kmConv: 410 },
  { origen: "GALVEZ", destino: "PORTE&#209;A", kmReal: 181, kmConv: 180 },
  { origen: "SARANDI", destino: "RIO SEGUNDO", kmReal: 668, kmConv: 670 },
  { origen: "SANTA ELENA", destino: "LUIS GUILLON", kmReal: 71, kmConv: 70 },
  { origen: "VILLA MARIA", destino: "SANTA ELENA", kmReal: 522, kmConv: 520 },
  { origen: "ITUZAINGO", destino: "MONTE GRANDE", kmReal: 51, kmConv: 50 },
  { origen: "ZARATE", destino: "GENERAL PICO", kmReal: 547, kmConv: 545 },
  { origen: "CHACABUCO", destino: "ZARATE", kmReal: 167, kmConv: 165 },
  { origen: "VALENTIN ALSINA", destino: "VILLA CELINA", kmReal: 10, kmConv: 10 },
  { origen: "TANDIL", destino: "VALENTIN ALSINA", kmReal: 349, kmConv: 350 },
  { origen: "VILLA SOLDATI", destino: "TANDIL", kmReal: 346, kmConv: 345 },
  { origen: "VILLA CELINA", destino: "VILLA SOLDATI", kmReal: 6, kmConv: 5 },
  { origen: "LA MATANZA", destino: "VILLA CELINA", kmReal: 12, kmConv: 10 },
  { origen: "MORTEROS", destino: "EZEIZA", kmReal: 671, kmConv: 670 },
  { origen: "ESPERANZA", destino: "CHACABUCO", kmReal: 429, kmConv: 430 },
  { origen: "PARANÁ", destino: "ESPERANZA", kmReal: 66, kmConv: 65 },
  { origen: "SAN SALVADOR", destino: "LA PLATA", kmReal: 457, kmConv: 455 },
  { origen: "TIGRE", destino: "EZEIZA", kmReal: 57, kmConv: 55 },
  { origen: "GOBERNADOR VIRASORO", destino: "GUALEGUAYCHU", kmReal: 685, kmConv: 685 },
  { origen: "SAN FRANCISCO", destino: "VILLA TESEI", kmReal: 554, kmConv: 555 },
  { origen: "COLONIA CAROYA", destino: "MONTE GRANDE", kmReal: 770, kmConv: 770 },
  { origen: "SAN ANDRES DE GILES", destino: "RECONQUISTA", kmReal: 715, kmConv: 715 },
  { origen: "9 DE ABRIL", destino: "SAN ANDRES DE GILES", kmReal: 109, kmConv: 110 },
  { origen: "PABLO NOGUES", destino: "VILLA SOLDATI", kmReal: 42, kmConv: 40 },
  { origen: "LONGCHAMPS", destino: "GARIN", kmReal: 72, kmConv: 70 },
  { origen: "PILAR", destino: "MONTE GRANDE", kmReal: 88, kmConv: 90 },
  { origen: "DOCK SUD", destino: "SAUCE VIEJO", kmReal: 453, kmConv: 455 },
  { origen: "VILLA SOLDATI", destino: "BOSQUES", kmReal: 53, kmConv: 55 },
  { origen: "ZARATE", destino: "SANTA ROSA DE CALAMUCHITA", kmReal: 673, kmConv: 675 },
  { origen: "JOSE LEON SUAREZ", destino: "SAN JUSTO", kmReal: 32, kmConv: 30 },
  { origen: "VILLA LUZURIAGA", destino: "9 DE ABRIL", kmReal: 15, kmConv: 15 },
  { origen: "VILLA DEL PARQUE", destino: "EZEIZA", kmReal: 36, kmConv: 35 },
  { origen: "SANTO TOME", destino: "VILLA MARTELLI", kmReal: 444, kmConv: 445 },
  { origen: "SANTO TOME", destino: "CONCEPCION DEL URUGUAY", kmReal: 300, kmConv: 300 },
  { origen: "SANTO TOME", destino: "RESISTENCIA", kmReal: 552, kmConv: 550 },
  { origen: "SAN FRANCISCO", destino: "JOSE LEON SUAREZ", kmReal: 541, kmConv: 540 },
  { origen: "GENERAL PACHECO", destino: "EZEIZA", kmReal: 60, kmConv: 60 },
  { origen: "CHACARITA", destino: "GENERAL PACHECO", kmReal: 28, kmConv: 30 },
  { origen: "VILLA SOLDATI", destino: "MONTE GRANDE", kmReal: 32, kmConv: 35 },
  { origen: "BRINKMANN", destino: "TORTUGUITAS", kmReal: 596, kmConv: 595 },
  { origen: "SAN JORGE", destino: "BRINKMANN", kmReal: 153, kmConv: 155 },
  { origen: "ARROYITO", destino: "ZARATE", kmReal: 566, kmConv: 565 },
  { origen: "VALENTIN ALSINA", destino: "ROSARIO", kmReal: 310, kmConv: 310 },
  { origen: "LANUS", destino: "VALENTIN ALSINA", kmReal: 5, kmConv: 5 },
  { origen: "ESCOBAR", destino: "CAMPANA", kmReal: 30, kmConv: 30 },
  { origen: "PABLO NOGUES", destino: "FATIMA", kmReal: 30, kmConv: 30 },
  { origen: "SAUCE VIEJO", destino: "SAN FRANCISCO", kmReal: 143, kmConv: 145 },
  { origen: "CORRAL DE BUSTOS", destino: "LANUS", kmReal: 440, kmConv: 440 },
  { origen: "CORDOBA", destino: "CORRAL DE BUSTOS", kmReal: 332, kmConv: 330 },
  { origen: "AROCENA", destino: "FRANCK", kmReal: 74, kmConv: 75 },
  { origen: "LA COCHA", destino: "ZARATE", kmReal: 1085, kmConv: 1085 },
  { origen: "TUCUMAN", destino: "LA COCHA", kmReal: 128, kmConv: 130 },
  { origen: "ALEJANDRO ROCA", destino: "DOCK SUD", kmReal: 568, kmConv: 570 },
  { origen: "DOCK SUD", destino: "ALEJANDRO ROCA", kmReal: 559, kmConv: 560 },
  { origen: "RESISTENCIA", destino: "SAN JORGE", kmReal: 693, kmConv: 695 },
  { origen: "ZARATE", destino: "MORENO", kmReal: 92, kmConv: 90 },
  { origen: "BARRACAS", destino: "ARROYITO", kmReal: 656, kmConv: 655 },
  { origen: "CINCO SALTOS", destino: "SAN VICENTE", kmReal: 1127, kmConv: 1125 },
  { origen: "NEUQUEN", destino: "CINCO SALTOS", kmReal: 22, kmConv: 20 },
  { origen: "SALSIPUEDE", destino: "SAN FRANCISCO", kmReal: 253, kmConv: 255 },
  { origen: "CAPITAN SARMIENTO", destino: "CORDOBA", kmReal: 584, kmConv: 585 },
  { origen: "BARADERO", destino: "CAPITAN SARMIENTO", kmReal: 85, kmConv: 85 },
  { origen: "PABLO NOGUES", destino: "CARLOS SPEGAZZINI", kmReal: 76, kmConv: 75 },
  { origen: "GUALEGUAYCHU", destino: "SAN SALVADOR", kmReal: 175, kmConv: 175 },
  { origen: "BURZACO", destino: "DON TORCUATO", kmReal: 53, kmConv: 55 },
  { origen: "NOGOYÁ", destino: "GARIN", kmReal: 331, kmConv: 330 },
  { origen: "FRANCK", destino: "NOGOYÁ", kmReal: 176, kmConv: 175 },
  { origen: "SAN SALVADOR", destino: "MUNRO", kmReal: 381, kmConv: 380 },
  { origen: "CAPITAN SARMIENTO", destino: "VILLA MARIA", kmReal: 440, kmConv: 440 },
  { origen: "GENERAL PACHECO", destino: "CAPITAN SARMIENTO", kmReal: 120, kmConv: 120 },
  { origen: "ZARATE", destino: "SALSIPUEDE", kmReal: 642, kmConv: 640 },
  { origen: "RESISTENCIA", destino: "GUALEGUAYCHU", kmReal: 713, kmConv: 715 },
  { origen: "CORRIENTES", destino: "RESISTENCIA", kmReal: 20, kmConv: 20 },
  { origen: "LA MATANZA", destino: "MONTE GRANDE", kmReal: 25, kmConv: 25 },
  { origen: "GRAND BOURG", destino: "MORENO", kmReal: 44, kmConv: 45 },
  { origen: "MATADEROS", destino: "PILAR", kmReal: 61, kmConv: 60 },
  { origen: "LONGCHAMPS", destino: "TORTUGUITAS", kmReal: 75, kmConv: 75 },
  { origen: "TORTUGUITAS", destino: "SAN PEDRO", kmReal: 140, kmConv: 140 },
  { origen: "VILLA SOLDATI", destino: "SAN FERNANDO", kmReal: 35, kmConv: 35 },
  { origen: "VILLA MERCEDES", destino: "GRAND BOURG", kmReal: 707, kmConv: 705 },
  { origen: "9 DE ABRIL", destino: "MORENO", kmReal: 45, kmConv: 45 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "DOCK SUD", kmReal: 1551, kmConv: 1550 },
  { origen: "NEUQUEN", destino: "SAN JORGE", kmReal: 1285, kmConv: 1285 },
  { origen: "CERRITO", destino: "SUSANA", kmReal: 181, kmConv: 180 },
  { origen: "ARISTOBULO DEL VALLE", destino: "SAN VICENTE", kmReal: 47, kmConv: 45 },
  { origen: "SAN FRANCISCO", destino: "ARISTOBULO DEL VALLE", kmReal: 1011, kmConv: 1010 },
  { origen: "VILLA TESEI", destino: "SAN FRANCISCO", kmReal: 553, kmConv: 555 },
  { origen: "VILLA TESEI", destino: "PILAR", kmReal: 45, kmConv: 45 },
  { origen: "VILLA URQUIZA", destino: "FLORENCIO VARELA", kmReal: 50, kmConv: 50 },
  { origen: "GARIN", destino: "MORENO", kmReal: 45, kmConv: 45 },
  { origen: "EZEIZA", destino: "DON TORCUATO", kmReal: 55, kmConv: 55 },
  { origen: "GARIN", destino: "DON TORCUATO", kmReal: 15, kmConv: 15 },
  { origen: "VICENTE LOPEZ", destino: "DON TORCUATO", kmReal: 20, kmConv: 20 },
  { origen: "ESCOBAR", destino: "BARRACAS", kmReal: 62, kmConv: 60 },
  { origen: "LANUS", destino: "9 DE ABRIL", kmReal: 12, kmConv: 10 },
  { origen: "DOCK SUD", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1541, kmConv: 1540 },
  { origen: "SAN NICOLAS", destino: "SAN PEDRO", kmReal: 87, kmConv: 85 },
  { origen: "VILLA MADERO", destino: "SAN ANDRES DE GILES", kmReal: 100, kmConv: 100 },
  { origen: "MATADEROS", destino: "VILLA MADERO", kmReal: 5, kmConv: 5 },
  { origen: "CERRO AZUL", destino: "SANTA FE", kmReal: 763, kmConv: 765 },
  { origen: "CAMPO GRANDE", destino: "CERRO AZUL", kmReal: 87, kmConv: 85 },
  { origen: "VILLA SOLDATI", destino: "APÓSTOLES", kmReal: 944, kmConv: 945 },
  { origen: "CARLOS SPEGAZZINI", destino: "PILAR", kmReal: 100, kmConv: 100 },
  { origen: "RETIRO", destino: "NEUQUEN", kmReal: 1145, kmConv: 1145 },
  { origen: "SALTA", destino: "DOCK SUD", kmReal: 1486, kmConv: 1485 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "SALTA", kmReal: 164, kmConv: 165 },
  { origen: "VILLA SOLDATI", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1565, kmConv: 1566 },
  { origen: "EZEIZA", destino: "LA HORQUETA", kmReal: 55, kmConv: 55 },
  { origen: "MORENO", destino: "DON TORCUATO", kmReal: 33, kmConv: 35 },
  { origen: "SARANDI", destino: "BARRACAS", kmReal: 6, kmConv: 5 },
  { origen: "INGENIERO ALLAN", destino: "PARANÁ", kmReal: 498, kmConv: 500 },
  { origen: "VILLA SOLDATI", destino: "INGENIERO ALLAN", kmReal: 53, kmConv: 55 },
  { origen: "MORENO", destino: "MONTE GRANDE", kmReal: 58, kmConv: 60 },
  { origen: "VILLA URQUIZA", destino: "EZEIZA", kmReal: 38, kmConv: 40 },
  { origen: "CARLOS SPEGAZZINI", destino: "NAVARRO", kmReal: 89, kmConv: 90 },
  { origen: "CORDOBA", destino: "LOMAS DE ZAMORA", kmReal: 709, kmConv: 709 },
  { origen: "PUERTO ESPERANZA", destino: "ESTEBAN ECHEVERRIA", kmReal: 1254, kmConv: 1255 },
  { origen: "CARLOS SPEGAZZINI", destino: "GENERAL RODRIGUEZ", kmReal: 82, kmConv: 80 },
  { origen: "BARRACAS", destino: "RECREO", kmReal: 487, kmConv: 485 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "SAN FRANCISCO", kmReal: 1066, kmConv: 1065 },
  { origen: "SANTO TOME", destino: "LEANDRO N ALEM", kmReal: 804, kmConv: 805 },
  { origen: "TAPIALES", destino: "SAN FRANCISCO", kmReal: 569, kmConv: 570 },
  { origen: "MONTE VERA", destino: "SANTO TOME", kmReal: 33, kmConv: 35 },
  { origen: "MONTE CRISTO", destino: "MONTE VERA", kmReal: 360, kmConv: 360 },
  { origen: "NEUQUEN", destino: "SAN MARTIN", kmReal: 747, kmConv: 745 },
  { origen: "MERCEDES", destino: "SAN JORGE", kmReal: 444, kmConv: 445 },
  { origen: "MORENO", destino: "SAN JORGE", kmReal: 497, kmConv: 495 },
  { origen: "PUERTO BOSSETTI", destino: "SANTA FE", kmReal: 1023, kmConv: 1025 },
  { origen: "VILLA DEL PARQUE", destino: "PILAR", kmReal: 55, kmConv: 55 },
  { origen: "TORTUGUITAS", destino: "PABLO NOGUES", kmReal: null, kmConv: 5 },
  { origen: "SAN FRANCISCO", destino: "RIO CEBALLOS", kmReal: 261, kmConv: 260 },
  { origen: "SANTA ROSA", destino: "VILLA SOLDATI", kmReal: 604, kmConv: 605 },
  { origen: "SAN FRANCISCO", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1029, kmConv: 1030 },
  { origen: "CANNING", destino: "9 DE ABRIL", kmReal: 22, kmConv: 20 },
  { origen: "RAMONA", destino: "SAN FRANCISCO", kmReal: 59, kmConv: 59 },
  { origen: "BARILOCHE", destino: "NEUQUEN", kmReal: 439, kmConv: 440 },
  { origen: "RETIRO", destino: "BARILOCHE", kmReal: 1615, kmConv: 1615 },
  { origen: "CAMPANA", destino: "RETIRO", kmReal: 80, kmConv: 80 },
  { origen: "TUCUMAN", destino: "ZONA PORTUARIA", kmReal: 1254, kmConv: 1255 },
  { origen: "ESCOBAR", destino: "LANUS", kmReal: 85, kmConv: 85 },
  { origen: "ARROYITO", destino: "DOCK SUD", kmReal: 668, kmConv: 670 },
  { origen: "SARANDI", destino: "ARROYITO", kmReal: 662, kmConv: 660 },
  { origen: "SANTA ROSA DE RIO PRIMERO", destino: "SAN FRANCISCO", kmReal: 195, kmConv: 195 },
  { origen: "SANTA ROSA DE CONLARA", destino: "CORDOBA", kmReal: 230, kmConv: 230 },
  { origen: "SAN SALVADOR", destino: "BURZACO", kmReal: 420, kmConv: 420 },
  { origen: "RETIRO", destino: "SANTA ROSA", kmReal: 614, kmConv: 615 },
  { origen: "ITUZAINGO", destino: "RETIRO", kmReal: 35, kmConv: 35 },
  { origen: "VILLA LUZURIAGA", destino: "VILLA SOLDATI", kmReal: 19, kmConv: 20 },
  { origen: "SAN MARTIN", destino: "TAPIALES", kmReal: 23, kmConv: 25 },
  { origen: "VILLA MERCEDES", destino: "VILLA LUZURIAGA", kmReal: 680, kmConv: 680 },
  { origen: "SANTA ROSA DE CONLARA", destino: "SANTA ROSA DE RIO PRIMERO", kmReal: 324, kmConv: 325 },
  { origen: "LOMAS DE ZAMORA", destino: "GARIN", kmReal: 58, kmConv: 60 },
  { origen: "MONTEVIDEO", destino: "MONTE GRANDE", kmReal: 684, kmConv: 685 },
  { origen: "SAN ANDRES DE GILES", destino: "VILLA SOLDATI", kmReal: 99, kmConv: 100 },
  { origen: "ALTA GRACIA", destino: "RIO SEGUNDO", kmReal: 51, kmConv: 50 },
  { origen: "CAMPANA", destino: "ALTA GRACIA", kmReal: 631, kmConv: 630 },
  { origen: "JARDIN AMERICA", destino: "PUERTO ESPERANZA", kmReal: 152, kmConv: 150 },
  { origen: "ARISTOBULO DEL VALLE", destino: "JARDIN AMERICA", kmReal: 39, kmConv: 40 },
  { origen: "CAMPO GRANDE", destino: "ARISTOBULO DEL VALLE", kmReal: 19, kmConv: 20 },
  { origen: "RIO CUARTO", destino: "CATRILO", kmReal: 410, kmConv: 410 },
  { origen: "GENERAL JUAN MADARIAGA", destino: "GARIN", kmReal: 366, kmConv: 365 },
  { origen: "SAN JORGE", destino: "LA MATANZA", kmReal: 535, kmConv: 535 },
  { origen: "LOS POLVORINES", destino: "GENERAL RODRIGUEZ", kmReal: 29, kmConv: 30 },
  { origen: "VILLA SOLDATI", destino: "LOS POLVORINES", kmReal: 43, kmConv: 45 },
  { origen: "ZARATE", destino: "MONTE GRANDE", kmReal: 116, kmConv: 115 },
  { origen: "DON TORCUATO", destino: "GENERAL PACHECO", kmReal: 6, kmConv: 5 },
  { origen: "VICENTE LOPEZ", destino: "SAN JUSTO", kmReal: 24, kmConv: 25 },
  { origen: "GARIN", destino: "LANUS", kmReal: 56, kmConv: 55 },
  { origen: "BARRACAS", destino: "GOBERNADOR CRESPO", kmReal: 623, kmConv: 625 },
  { origen: "RECONQUISTA", destino: "RAFAELA", kmReal: 371, kmConv: 370 },
  { origen: "CARLOS SPEGAZZINI", destino: "9 DE ABRIL", kmReal: 35, kmConv: 35 },
  { origen: "RAFAELA", destino: "GENERAL JUAN MADARIAGA", kmReal: 869, kmConv: 870 },
  { origen: "VILLA MERCEDES", destino: "TAPIALES", kmReal: 694, kmConv: 695 },
  { origen: "TUCUMAN", destino: "ZARATE", kmReal: 1172, kmConv: 1170 },
  { origen: "LULES", destino: "TUCUMAN", kmReal: 21, kmConv: 21 },
  { origen: "SALTA", destino: "LULES", kmReal: 335, kmConv: 335 },
  { origen: "RAFAELA", destino: "9 DE ABRIL", kmReal: 553, kmConv: 555 },
  { origen: "PUERTO ESPERANZA", destino: "RECONQUISTA", kmReal: 800, kmConv: 800 },
  { origen: "MORON", destino: "BARRACAS", kmReal: 32, kmConv: 30 },
  { origen: "ESCOBAR", destino: "EZEIZA", kmReal: 80, kmConv: 80 },
  { origen: "SANTO TOME", destino: "EL TALAR", kmReal: 425, kmConv: 425 },
  { origen: "RIO SEGUNDO", destino: "ESPERANZA", kmReal: 342, kmConv: 340 },
  { origen: "GOBERNADOR VIRASORO", destino: "VILLA SOLDATI", kmReal: 912, kmConv: 910 },
  { origen: "CARLOS SPEGAZZINI", destino: "VALENTIN ALSINA", kmReal: 47, kmConv: 45 },
  { origen: "DON TORCUATO", destino: "MONTE GRANDE", kmReal: 56, kmConv: 55 },
  { origen: "DON TORCUATO", destino: "TAPIALES", kmReal: 37, kmConv: 35 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "RETIRO", kmReal: 42, kmConv: 40 },
  { origen: "TORTUGUITAS", destino: "SAN ANDRES DE GILES", kmReal: 84, kmConv: 85 },
  { origen: "9 DE ABRIL", destino: "LOMAS DE ZAMORA", kmReal: 8, kmConv: 10 },
  { origen: "SUSANA", destino: "9 DE ABRIL", kmReal: 541, kmConv: 540 },
  { origen: "TORTUGUITAS", destino: "TAPIALES", kmReal: 51, kmConv: 50 },
  { origen: "NUEVA POMPEYA", destino: "TORTUGUITAS", kmReal: 51, kmConv: 50 },
  { origen: "CARLOS SPEGAZZINI", destino: "FLORENCIO VARELA", kmReal: 51, kmConv: 50 },
  { origen: "PUERTO MADERO", destino: "TORTUGUITAS", kmReal: 48, kmConv: 50 },
  { origen: "CORDOBA", destino: "GENERAL LAS HERAS", kmReal: 711, kmConv: 710 },
  { origen: "GENERAL LAS HERAS", destino: "VILLA SOLDATI", kmReal: 90, kmConv: 90 },
  { origen: "RIO CUARTO", destino: "SAN FRANCISCO", kmReal: 295, kmConv: 295 },
  { origen: "SAN FRANCISCO", destino: "RIO CUARTO", kmReal: 295, kmConv: 295 },
  { origen: "CORDOBA", destino: "EZEIZA", kmReal: 733, kmConv: 735 },
  { origen: "POSADAS", destino: "PUERTO IGUAZU", kmReal: 307, kmConv: 305 },
  { origen: "SAN MARTIN", destino: "POSADAS", kmReal: 1656, kmConv: 1655 },
  { origen: "NUEVA POMPEYA", destino: "CAMPANA", kmReal: 87, kmConv: 85 },
  { origen: "MORTEROS", destino: "VICENTE LOPEZ", kmReal: 635, kmConv: 635 },
  { origen: "RAFAELA", destino: "ITUZAINGO", kmReal: 542, kmConv: 540 },
  { origen: "SAN LUIS", destino: "MENDOZA", kmReal: 258, kmConv: 260 },
  { origen: "SAN FRANCISCO", destino: "SAN LUIS", kmReal: 515, kmConv: 515 },
  { origen: "SAN FRANCISCO", destino: "VIRREY DEL PINO", kmReal: 601, kmConv: 600 },
  { origen: "ESCOBAR", destino: "MORENO", kmReal: 55, kmConv: 55 },
  { origen: "ESCOBAR", destino: "PUERTO MADERO", kmReal: 58, kmConv: 60 },
  { origen: "MALAGUE&#209;O", destino: "RECREO", kmReal: 409, kmConv: 410 },
  { origen: "LOMAS DE ZAMORA", destino: "ZARATE", kmReal: 105, kmConv: 105 },
  { origen: "VILLA TESEI", destino: "ZARATE", kmReal: 83, kmConv: 85 },
  { origen: "JOSE INGENIEROS", destino: "CAMPANA", kmReal: 75, kmConv: 75 },
  { origen: "BURZACO", destino: "EL PALOMAR", kmReal: 35, kmConv: 35 },
  { origen: "SAN FRANCISCO", destino: "PERGAMINO", kmReal: 377, kmConv: 375 },
  { origen: "25 DE MAYO", destino: "PUERTO ESPERANZA", kmReal: 185, kmConv: 185 },
  { origen: "VICENTE LOPEZ", destino: "ZARATE", kmReal: 80, kmConv: 80 },
  { origen: "VILLA SOLDATI", destino: "EL TALAR", kmReal: 38, kmConv: 40 },
  { origen: "APÓSTOLES", destino: "ZONA PORTUARIA", kmReal: 938, kmConv: 940 },
  { origen: "BARRACAS", destino: "APÓSTOLES", kmReal: 953, kmConv: 955 },
  { origen: "DOCK SUD", destino: "ARROYITO", kmReal: 659, kmConv: 660 },
  { origen: "SANTA FE", destino: "AROCENA", kmReal: 67, kmConv: 65 },
  { origen: "LAS HERAS", destino: "VICENTE LOPEZ", kmReal: 1051, kmConv: 1050 },
  { origen: "RESISTENCIA", destino: "PUERTO ESPERANZA", kmReal: 578, kmConv: 580 },
  { origen: "POSADAS", destino: "25 DE MAYO", kmReal: 176, kmConv: 175 },
  { origen: "RETIRO", destino: "ZARATE", kmReal: 90, kmConv: 90 },
  { origen: "PUERTO MADERO", destino: "9 DE ABRIL", kmReal: 25, kmConv: 25 },
  { origen: "ARROYITO", destino: "ZONA PORTUARIA", kmReal: 648, kmConv: 650 },
  { origen: "BERAZATEGUI", destino: "CORDOBA", kmReal: 726, kmConv: 725 },
  { origen: "ESCOBAR", destino: "LOS POLVORINES", kmReal: 25, kmConv: 25 },
  { origen: "RECREO", destino: "PUERTO MADERO", kmReal: 485, kmConv: 485 },
  { origen: "GRAND BOURG", destino: "BARADERO", kmReal: 120, kmConv: 120 },
  { origen: "CORDOBA", destino: "SUSANA", kmReal: 306, kmConv: 305 },
  { origen: "ZARATE", destino: "MAR DEL PLATA", kmReal: 505, kmConv: 505 },
  { origen: "SAN FRANCISCO", destino: "ZARATE", kmReal: 477, kmConv: 475 },
  { origen: "FAMAILLA", destino: "SAN FRANCISCO", kmReal: 720, kmConv: 720 },
  { origen: "ZARATE", destino: "FAMAILLA", kmReal: 1135, kmConv: 1135 },
  { origen: "MORTEROS", destino: "SAN JORGE", kmReal: 171, kmConv: 170 },
  { origen: "VICENTE LOPEZ", destino: "MONTE GRANDE", kmReal: 45, kmConv: 45 },
  { origen: "FREYRE", destino: "PILAR", kmReal: 552, kmConv: 550 },
  { origen: "VILLA LUZURIAGA", destino: "VILLA DEL TOTORAL", kmReal: 782, kmConv: 780 },
  { origen: "TAPIALES", destino: "VILLA LUZURIAGA", kmReal: 13, kmConv: 15 },
  { origen: "CIUDADELA", destino: "LANUS", kmReal: 19, kmConv: 20 },
  { origen: "CARLOS SPEGAZZINI", destino: "BARRACAS", kmReal: 52, kmConv: 50 },
  { origen: "BELL VILLE", destino: "TIO PUJIO", kmReal: 85, kmConv: 85 },
  { origen: "RAFAELA", destino: "CIUDADELA", kmReal: 537, kmConv: 540 },
  { origen: "TORTUGUITAS", destino: "MONTE GRANDE", kmReal: 68, kmConv: 70 },
  { origen: "PUERTO PIRAY", destino: "ITUZAINGO", kmReal: 1174, kmConv: 1175 },
  { origen: "CIUDADELA", destino: "TORTUGUITAS", kmReal: 43, kmConv: 45 },
  { origen: "VILLA MERCEDES", destino: "9 DE ABRIL", kmReal: 700, kmConv: 700 },
  { origen: "PILAR", destino: "COLONIA CAROYA", kmReal: 700, kmConv: 700 },
  { origen: "LOMAS DE ZAMORA", destino: "MATADEROS", kmReal: 15, kmConv: 15 },
  { origen: "ZONA PORTUARIA", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1530, kmConv: 1530 },
  { origen: "EZEIZA", destino: "VICENTE LOPEZ", kmReal: 44, kmConv: 45 },
  { origen: "MONTEVIDEO", destino: "SAN FRANCISCO", kmReal: 789, kmConv: 780 },
  { origen: "LA PLATA", destino: "SAN ANDRES DE GILES", kmReal: 162, kmConv: 160 },
  { origen: "CHIVILCOY", destino: "PARANÁ", kmReal: 471, kmConv: 470 },
  { origen: "MATADEROS", destino: "CHIVILCOY", kmReal: 155, kmConv: 155 },
  { origen: "ZONA PORTUARIA", destino: "ZARATE", kmReal: 88, kmConv: 90 },
  { origen: "GALVEZ", destino: "SAUCE VIEJO", kmReal: 66, kmConv: 65 },
  { origen: "ZARATE", destino: "GALVEZ", kmReal: 344, kmConv: 345 },
  { origen: "TIGRE", destino: "DOCK SUD", kmReal: 41, kmConv: 40 },
  { origen: "ARROYITO", destino: "SUSANA", kmReal: 184, kmConv: 185 },
  { origen: "SUSANA", destino: "LOMAS DE ZAMORA", kmReal: 542, kmConv: 540 },
  { origen: "MONTEVIDEO", destino: "BELL VILLE", kmReal: 815, kmConv: 815 },
  { origen: "RECREO", destino: "MATADEROS", kmReal: 484, kmConv: 485 },
  { origen: "SAN SALVADOR", destino: "BERAZATEGUI", kmReal: 427, kmConv: 425 },
  { origen: "MERCEDES", destino: "SAN SALVADOR", kmReal: 311, kmConv: 310 },
  { origen: "SANTO TOME", destino: "POSADAS", kmReal: 788, kmConv: 790 },
  { origen: "RAFAELA", destino: "SANTO TOME", kmReal: 106, kmConv: 105 },
  { origen: "SANTO TOME", destino: "GOBERNADOR CRESPO", kmReal: 166, kmConv: 165 },
  { origen: "SAN LUIS", destino: "TORTUGUITAS", kmReal: 769, kmConv: 770 },
  { origen: "MONTE GRANDE", destino: "SANTO TOME", kmReal: 483, kmConv: 485 },
  { origen: "EZEIZA", destino: "MONTE GRANDE", kmReal: 9, kmConv: 10 },
  { origen: "CLUCELLAS", destino: "SUSANA", kmReal: 30, kmConv: 30 },
  { origen: "ROSARIO", destino: "ARROYITO", kmReal: 356, kmConv: 355 },
  { origen: "SANTA CATALINA", destino: "CAMPANA", kmReal: 560, kmConv: 560 },
  { origen: "RIO CUARTO", destino: "SANTA CATALINA", kmReal: 13, kmConv: 15 },
  { origen: "VILLA MERCEDES", destino: "ROSARIO", kmReal: 521, kmConv: 520 },
  { origen: "TAPIALES", destino: "BARRACAS", kmReal: 20, kmConv: 20 },
  { origen: "SANTO TOME", destino: "CAMPANA", kmReal: 380, kmConv: 380 },
  { origen: "BRINKMANN", destino: "SAN GUILLERMO", kmReal: 59, kmConv: 60 },
  { origen: "BURZACO", destino: "BRINKMANN", kmReal: 652, kmConv: 650 },
  { origen: "GENERAL PACHECO", destino: "BARADERO", kmReal: 118, kmConv: 120 },
  { origen: "ARROYITO", destino: "VILLA MERCEDES", kmReal: 462, kmConv: 460 },
  { origen: "SANTO TOME", destino: "ITUZAINGO", kmReal: 458, kmConv: 460 },
  { origen: "9 DE ABRIL", destino: "RIO CUARTO", kmReal: 623, kmConv: 625 },
  { origen: "PILAR", destino: "CLUCELLAS", kmReal: 489, kmConv: 490 },
  { origen: "ESPERANZA", destino: "SAN JORGE", kmReal: 149, kmConv: 150 },
  { origen: "CARLOS SPEGAZZINI", destino: "SAN PEDRO", kmReal: 223, kmConv: 225 },
  { origen: "BAHIA BLANCA", destino: "CARLOS SPEGAZZINI", kmReal: 589, kmConv: 590 },
  { origen: "SAN PEDRO", destino: "SANTA FE", kmReal: 315, kmConv: 315 },
  { origen: "9 DE ABRIL", destino: "SAN PEDRO", kmReal: 185, kmConv: 185 },
  { origen: "9 DE ABRIL", destino: "SANTA FE", kmReal: 482, kmConv: 480 },
  { origen: "SANTO TOME", destino: "OBERA", kmReal: 830, kmConv: 830 },
  { origen: "DOCK SUD", destino: "TORTUGUITAS", kmReal: 54, kmConv: 55 },
  { origen: "SAN MARTIN", destino: "PABLO NOGUES", kmReal: 47, kmConv: 45 },
  { origen: "BECCAR", destino: "EZEIZA", kmReal: 53, kmConv: 55 },
  { origen: "CAMPANA", destino: "MORENO", kmReal: 82, kmConv: 80 },
  { origen: "GENERAL PACHECO", destino: "TAPIALES", kmReal: 42, kmConv: 40 },
  { origen: "LA CRUZ", destino: "GOBERNADOR VIRASORO", kmReal: 161, kmConv: 160 },
  { origen: "TAPIALES", destino: "RETIRO", kmReal: 20, kmConv: 20 },
  { origen: "EL TALAR", destino: "ZARATE", kmReal: 60, kmConv: 60 },
  { origen: "GOBERNADOR VIRASORO", destino: "DOCK SUD", kmReal: 914, kmConv: 915 },
  { origen: "CAMPO GRANDE", destino: "GOBERNADOR VIRASORO", kmReal: 164, kmConv: 165 },
  { origen: "CORDOBA", destino: "ZONA PORTUARIA", kmReal: 694, kmConv: 695 },
  { origen: "GALVEZ", destino: "SUSANA", kmReal: 99, kmConv: 100 },
  { origen: "RAFAELA", destino: "LA CRUZ", kmReal: 656, kmConv: 655 },
  { origen: "SANTO TOME", destino: "TAPIALES", kmReal: 463, kmConv: 465 },
  { origen: "ESCOBAR", destino: "EL TALAR", kmReal: 22, kmConv: 20 },
  { origen: "SAN AGUSTIN", destino: "SAN FRANCISCO", kmReal: 294, kmConv: 295 },
  { origen: "PUERTO PIRAY", destino: "SAN LUIS", kmReal: 1604, kmConv: 1605 },
  { origen: "PUERTO MADERO", destino: "VALENTIN ALSINA", kmReal: 11, kmConv: 10 },
  { origen: "ROJAS", destino: "BIGAND", kmReal: 125, kmConv: 125 },
  { origen: "9 DE ABRIL", destino: "ALTA GRACIA", kmReal: 719, kmConv: 720 },
  { origen: "SUSANA", destino: "CARLOS SPEGAZZINI", kmReal: 567, kmConv: 565 },
  { origen: "CORDOBA", destino: "PUERTO MADERO", kmReal: 699, kmConv: 700 },
  { origen: "VICENTE LOPEZ", destino: "CANNING", kmReal: 46, kmConv: 45 },
  { origen: "OBERA", destino: "25 DE MAYO", kmReal: 80, kmConv: 80 },
  { origen: "SAN GUILLERMO", destino: "RAFAELA", kmReal: 155, kmConv: 155 },
  { origen: "VILLA MARIA", destino: "ALTA GRACIA", kmReal: 162, kmConv: 160 },
  { origen: "PASO DEL REY", destino: "VILLA URQUIZA", kmReal: 35, kmConv: 35 },
  { origen: "LA MATANZA", destino: "MORENO", kmReal: 24, kmConv: 25 },
  { origen: "VICENTE LOPEZ", destino: "GARIN", kmReal: 32, kmConv: 30 },
  { origen: "SAN FRANCISCO", destino: "SAN GUILLERMO", kmReal: 127, kmConv: 125 },
  { origen: "GENERAL PACHECO", destino: "VILLA MARIA", kmReal: 520, kmConv: 520 },
  { origen: "GARIN", destino: "CARLOS SPEGAZZINI", kmReal: 85, kmConv: 85 },
  { origen: "GENERAL PACHECO", destino: "DON TORCUATO", kmReal: 6, kmConv: 5 },
  { origen: "PERGAMINO", destino: "BURZACO", kmReal: 257, kmConv: 255 },
  { origen: "SAN PEDRO", destino: "TIGRE", kmReal: 156, kmConv: 155 },
  { origen: "GENERAL DEHEZA", destino: "PILAR", kmReal: 577, kmConv: 575 },
  { origen: "CORDOBA", destino: "GENERAL DEHEZA", kmReal: 200, kmConv: 200 },
  { origen: "PILAR", destino: "VICENTE LOPEZ", kmReal: 48, kmConv: 50 },
  { origen: "NOGOYÁ", destino: "SAN SALVADOR", kmReal: 182, kmConv: 180 },
  { origen: "QUILMES", destino: "CARLOS SPEGAZZINI", kmReal: 68, kmConv: 70 },
  { origen: "ZARATE", destino: "PUERTO PIRAY", kmReal: 1088, kmConv: 1090 },
  { origen: "SALTO", destino: "TORTUGUITAS", kmReal: 174, kmConv: 175 },
  { origen: "RIO CUARTO", destino: "MONTE CRISTO", kmReal: 242, kmConv: 240 },
  { origen: "GALVEZ", destino: "RECREO", kmReal: 102, kmConv: 100 },
  { origen: "ZONA PORTUARIA", destino: "GALVEZ", kmReal: 426, kmConv: 425 },
  { origen: "QUILMES", destino: "GENERAL PACHECO", kmReal: 56, kmConv: 55 },
  { origen: "COLONIA CAROYA", destino: "QUILMES", kmReal: 764, kmConv: 765 },
  { origen: "BECCAR", destino: "CARLOS SPEGAZZINI", kmReal: 67, kmConv: 65 },
  { origen: "GENERAL PACHECO", destino: "DESVIO ARIJON", kmReal: 387, kmConv: 385 },
  { origen: "SAN ANDRES DE GILES", destino: "NOGOYÁ", kmReal: 339, kmConv: 340 },
  { origen: "LANUS", destino: "SAN ANDRES DE GILES", kmReal: 108, kmConv: 110 },
  { origen: "MONTE GRANDE", destino: "TAPIALES", kmReal: 20, kmConv: 20 },
  { origen: "EZEIZA", destino: "BECCAR", kmReal: 54, kmConv: 55 },
  { origen: "RAFAELA", destino: "EZEIZA", kmReal: 565, kmConv: 565 },
  { origen: "LANUS", destino: "BURZACO", kmReal: 15, kmConv: 15 },
  { origen: "RAFAELA", destino: "TAPIALES", kmReal: 547, kmConv: 545 },
  { origen: "GENERAL LAGOS", destino: "SAUCE VIEJO", kmReal: 172, kmConv: 170 },
  { origen: "ZARATE", destino: "GENERAL LAGOS", kmReal: 194, kmConv: 195 },
  { origen: "GENERAL LAGOS", destino: "CORDOBA", kmReal: 423, kmConv: 425 },
  { origen: "GENERAL RODRIGUEZ", destino: "GENERAL LAGOS", kmReal: 255, kmConv: 255 },
  { origen: "VILLA URQUIZA", destino: "CORDOBA", kmReal: 686, kmConv: 685 },
  { origen: "VILLA SOLDATI", destino: "VILLA URQUIZA", kmReal: 19, kmConv: 20 },
  { origen: "VILLA SOLDATI", destino: "GRAND BOURG", kmReal: 48, kmConv: 50 },
  { origen: "SAN LUIS", destino: "VILLA SOLDATI", kmReal: 783, kmConv: 785 },
  { origen: "SARANDI", destino: "SAUCE VIEJO", kmReal: 455, kmConv: 455 },
  { origen: "CAMPANA", destino: "BARADERO", kmReal: 74, kmConv: 75 },
  { origen: "SUNCHALES", destino: "SUSANA", kmReal: 55, kmConv: 55 },
  { origen: "GENERAL PACHECO", destino: "EL PALOMAR", kmReal: 44, kmConv: 45 },
  { origen: "SAUCE VIEJO", destino: "SUSANA", kmReal: 108, kmConv: 110 },
  { origen: "ARROYITO", destino: "GARIN", kmReal: 610, kmConv: 610 },
  { origen: "ARROYITO", destino: "PILAR", kmReal: 612, kmConv: 610 },
  { origen: "PUERTO ESPERANZA", destino: "PILAR", kmReal: 1187, kmConv: 1190 },
  { origen: "LEANDRO N ALEM", destino: "PUERTO ESPERANZA", kmReal: 245, kmConv: 245 },
  { origen: "TORTUGUITAS", destino: "BARRACAS", kmReal: 50, kmConv: 50 },
  { origen: "SANTA ROSA DE CONLARA", destino: "CONCARAN", kmReal: 33, kmConv: 35 },
  { origen: "SAN LUIS", destino: "DON TORCUATO", kmReal: 806, kmConv: 805 },
  { origen: "SAN JUSTO", destino: "MORENO", kmReal: 27, kmConv: 25 },
  { origen: "MATADEROS", destino: "SAN JUSTO", kmReal: 7, kmConv: 5 },
  { origen: "SAUCE VIEJO", destino: "ZARATE", kmReal: 361, kmConv: 360 },
  { origen: "LA MATANZA", destino: "SAN JUSTO", kmReal: 3, kmConv: 5 },
  { origen: "MERLO", destino: "MATADEROS", kmReal: 29, kmConv: 30 },
  { origen: "SUSANA", destino: "MERLO", kmReal: 529, kmConv: 530 },
  { origen: "RIO PRIMERO", destino: "CORDOBA", kmReal: 61, kmConv: 60 },
  { origen: "CORDOBA", destino: "MALAGUE&#209;O", kmReal: 19, kmConv: 20 },
  { origen: "ROSARIO", destino: "TIO PUJIO", kmReal: 276, kmConv: 275 },
  { origen: "PUERTO PIRAY", destino: "BECCAR", kmReal: 1153, kmConv: 1155 },
  { origen: "RETIRO", destino: "VILLA SOLDATI", kmReal: 18, kmConv: 20 },
  { origen: "SAN JUSTO", destino: "CAPILLA DEL MONTE", kmReal: 793, kmConv: 795 },
  { origen: "BERAZATEGUI", destino: "SAUCE VIEJO", kmReal: 474, kmConv: 475 },
  { origen: "PILAR", destino: "RETIRO", kmReal: 59, kmConv: 60 },
  { origen: "VILLA MERCEDES", destino: "VILLA SOLDATI", kmReal: 692, kmConv: 690 },
  { origen: "SALTO", destino: "EZEIZA", kmReal: 211, kmConv: 210 },
  { origen: "SAN MARTIN", destino: "SANTA ROSA DE CONLARA", kmReal: 499, kmConv: 500 },
  { origen: "ARROYITO", destino: "LA PLATA", kmReal: 718, kmConv: 720 },
  { origen: "LANUS", destino: "SAN PEDRO", kmReal: 183, kmConv: 185 },
  { origen: "VILLA SOLDATI", destino: "HAEDO", kmReal: 17, kmConv: 15 },
  { origen: "VILLA MERCEDES", destino: "MERCEDES", kmReal: 606, kmConv: 605 },
  { origen: "SANTO TOME", destino: "SAUCE VIEJO", kmReal: 14, kmConv: 15 },
  { origen: "SANTO TOME", destino: "SANTA FE", kmReal: 18, kmConv: 20 },
  { origen: "SALTO", destino: "GARIN", kmReal: 185, kmConv: 185 },
  { origen: "SAUCE VIEJO", destino: "DOCK SUD", kmReal: 453, kmConv: 455 },
  { origen: "BRINKMANN", destino: "SUSANA", kmReal: 104, kmConv: 105 },
  { origen: "CAMPANA", destino: "BARRACAS", kmReal: 85, kmConv: 85 },
  { origen: "LANUS", destino: "TORTUGUITAS", kmReal: 58, kmConv: 60 },
  { origen: "ESPERANZA", destino: "LANUS", kmReal: 505, kmConv: 505 },
  { origen: "SAN LUIS", destino: "GRAND BOURG", kmReal: 800, kmConv: 800 },
  { origen: "SAN LUIS", destino: "GENERAL PACHECO", kmReal: 805, kmConv: 805 },
  { origen: "RIO CUARTO", destino: "SAN JUSTO", kmReal: 614, kmConv: 615 },
  { origen: "PABLO NOGUES", destino: "SAN JUSTO", kmReal: 52, kmConv: 50 },
  { origen: "PATERNAL", destino: "LANUS", kmReal: 20, kmConv: 20 },
  { origen: "ROSARIO", destino: "RECREO", kmReal: 187, kmConv: 185 },
  { origen: "MORON", destino: "PATERNAL", kmReal: 25, kmConv: 25 },
  { origen: "ARROYITO", destino: "HURLINGHAM", kmReal: 639, kmConv: 640 },
  { origen: "VILLA DEL ROSARIO", destino: "ARROYITO", kmReal: 78, kmConv: 80 },
  { origen: "SAN MARTIN", destino: "RIO TERCERO", kmReal: 575, kmConv: 575 },
  { origen: "PERGAMINO", destino: "BARRACAS", kmReal: 247, kmConv: 245 },
  { origen: "TRISTÁN SUAREZ", destino: "VILLA SOLDATI", kmReal: 36, kmConv: 35 },
  { origen: "ZONA PORTUARIA", destino: "ROSARIO", kmReal: 297, kmConv: 295 },
  { origen: "LOS POLVORINES", destino: "9 DE ABRIL", kmReal: 50, kmConv: 50 },
  { origen: "BARRACAS", destino: "ZARATE", kmReal: 96, kmConv: 95 },
  { origen: "DON TORCUATO", destino: "CARLOS SPEGAZZINI", kmReal: 69, kmConv: 70 },
  { origen: "VILLA SOLDATI", destino: "TRISTÁN SUAREZ", kmReal: 35, kmConv: 35 },
  { origen: "MORENO", destino: "CA&#209;UELAS", kmReal: 62, kmConv: 60 },
  { origen: "MORENO", destino: "TRISTÁN SUAREZ", kmReal: 42, kmConv: 40 },
  { origen: "VILLA MERCEDES", destino: "MORENO", kmReal: 660, kmConv: 660 },
  { origen: "PILAR", destino: "LOS POLVORINES", kmReal: 29, kmConv: 30 },
  { origen: "MONTE GRANDE", destino: "VICENTE LOPEZ", kmReal: 45, kmConv: 45 },
  { origen: "MATADEROS", destino: "EZEIZA", kmReal: 26, kmConv: 25 },
  { origen: "VILLA DEL TOTORAL", destino: "RAMALLO", kmReal: 579, kmConv: 580 },
  { origen: "SANTO TOME", destino: "PUERTO ESPERANZA", kmReal: 1017, kmConv: 1015 },
  { origen: "CONCORDIA", destino: "ESCOBAR", kmReal: 376, kmConv: 375 },
  { origen: "CORRAL DE BUSTOS", destino: "TIO PUJIO", kmReal: 208, kmConv: 210 },
  { origen: "SANTO TOME", destino: "ESPERANZA", kmReal: 41, kmConv: 40 },
  { origen: "LA MATANZA", destino: "GENERAL RODRIGUEZ", kmReal: 40, kmConv: 40 },
  { origen: "ELORTONDO", destino: "CORRAL DE BUSTOS", kmReal: 109, kmConv: 110 },
  { origen: "LANUS", destino: "ELORTONDO", kmReal: 354, kmConv: 355 },
  { origen: "FREYRE", destino: "POSADAS", kmReal: 958, kmConv: 960 },
  { origen: "BURZACO", destino: "GARIN", kmReal: 66, kmConv: 65 },
  { origen: "SAN JORGE", destino: "JUJUY", kmReal: 1058, kmConv: 1060 },
  { origen: "BARADERO", destino: "GENERAL RODRIGUEZ", kmReal: 130, kmConv: 130 },
  { origen: "REMEDIOS DE ESCALADA", destino: "VILLA SOLDATI", kmReal: 11, kmConv: 10 },
  { origen: "FREYRE", destino: "EZEIZA", kmReal: 617, kmConv: 615 },
  { origen: "CONCORDIA", destino: "GENERAL PACHECO", kmReal: 397, kmConv: 400 },
  { origen: "HURLINGHAM", destino: "RETIRO", kmReal: 42, kmConv: 40 },
  { origen: "SANTA CATALINA", destino: "VILLA MERCEDES", kmReal: 112, kmConv: 110 },
  { origen: "VILLA MARIA", destino: "SANTA CATALINA", kmReal: 152, kmConv: 150 },
  { origen: "REMEDIOS DE ESCALADA", destino: "SAN JUSTO", kmReal: 23, kmConv: 25 },
  { origen: "SAUCE VIEJO", destino: "MORTEROS", kmReal: 226, kmConv: 225 },
  { origen: "ZARATE", destino: "SAUCE VIEJO", kmReal: 361, kmConv: 360 },
  { origen: "SAUCE VIEJO", destino: "MONTE GRANDE", kmReal: 470, kmConv: 470 },
  { origen: "SUSANA", destino: "SAUCE VIEJO", kmReal: 109, kmConv: 110 },
  { origen: "SAN PEDRO", destino: "RECREO", kmReal: 330, kmConv: 330 },
  { origen: "ZONA PORTUARIA", destino: "SAN PEDRO", kmReal: 170, kmConv: 170 },
  { origen: "CATRILO", destino: "AVELLANEDA", kmReal: 530, kmConv: 530 },
  { origen: "VILLA SOLDATI", destino: "CATRILO", kmReal: 520, kmConv: 520 },
  { origen: "CAMPANA", destino: "BURZACO", kmReal: 108, kmConv: 108 },
  { origen: "SAN JORGE", destino: "REMEDIOS DE ESCALADA", kmReal: 508, kmConv: 510 },
  { origen: "LANUS", destino: "ROSARIO", kmReal: 313, kmConv: 315 },
  { origen: "TORTUGUITAS", destino: "CARLOS SPEGAZZINI", kmReal: 84, kmConv: 85 },
  { origen: "BURZACO", destino: "MORTEROS", kmReal: 668, kmConv: 670 },
  { origen: "EZEIZA", destino: "BURZACO", kmReal: 30, kmConv: 30 },
  { origen: "LOMAS DE ZAMORA", destino: "LANUS", kmReal: 10, kmConv: 10 },
  { origen: "VILLA MARIA", destino: "RIO CUARTO", kmReal: 134, kmConv: 135 },
  { origen: "9 DE ABRIL", destino: "VILLA MARIA", kmReal: 569, kmConv: 570 },
  { origen: "PARQUE PATRICIOS", destino: "EZEIZA", kmReal: 35, kmConv: 35 },
  { origen: "CARAPACHAY", destino: "PARQUE PATRICIOS", kmReal: 27, kmConv: 25 },
  { origen: "SAN FRANCISCO", destino: "CARAPACHAY", kmReal: 545, kmConv: 545 },
  { origen: "CORDOBA", destino: "LANUS", kmReal: 709, kmConv: 710 },
  { origen: "ARROYITO", destino: "ROSARIO", kmReal: 356, kmConv: 355 },
  { origen: "RECREO", destino: "PERGAMINO", kmReal: 298, kmConv: 300 },
  { origen: "SAN ANDRES DE GILES", destino: "CONCORDIA", kmReal: 397, kmConv: 395 },
  { origen: "TIGRE", destino: "SAN ANDRES DE GILES", kmReal: 107, kmConv: 110 },
  { origen: "CHASCOMUS", destino: "JUAREZ CELMAN", kmReal: 836, kmConv: 835 },
  { origen: "TAPIALES", destino: "FRANCK", kmReal: 481, kmConv: 480 },
  { origen: "RECREO", destino: "LA PLATA", kmReal: 540, kmConv: 540 },
  { origen: "RIO CUARTO", destino: "VILLA MARIA", kmReal: 134, kmConv: 135 },
  { origen: "ZARATE", destino: "RIO CUARTO", kmReal: 548, kmConv: 550 },
  { origen: "SAN FRANCISCO", destino: "CANNING", kmReal: 588, kmConv: 590 },
  { origen: "SANTO TOME", destino: "MONTE GRANDE", kmReal: 484, kmConv: 485 },
  { origen: "ZONA PORTUARIA", destino: "CAMPANA", kmReal: 77, kmConv: 75 },
  { origen: "PERGAMINO", destino: "SAN FRANCISCO", kmReal: 360, kmConv: 360 },
  { origen: "ROSARIO", destino: "PERGAMINO", kmReal: 122, kmConv: 120 },
  { origen: "FRANCK", destino: "ROSARIO", kmReal: 180, kmConv: 180 },
  { origen: "PERGAMINO", destino: "ROSARIO", kmReal: 122, kmConv: 120 },
  { origen: "BURZACO", destino: "CARLOS SPEGAZZINI", kmReal: 39, kmConv: 40 },
  { origen: "VILLA MARIA", destino: "RIO TERCERO", kmReal: 91, kmConv: 90 },
  { origen: "ROJAS", destino: "NAVARRO", kmReal: 200, kmConv: 200 },
  { origen: "SAN ANDRES DE GILES", destino: "MORTEROS", kmReal: 572, kmConv: 570 },
  { origen: "MATADEROS", destino: "SAN ANDRES DE GILES", kmReal: 96, kmConv: 95 },
  { origen: "CA&#209;UELAS", destino: "ZARATE", kmReal: 121, kmConv: 120 },
  { origen: "ZONA PORTUARIA", destino: "FLORENCIO VARELA", kmReal: 28, kmConv: 30 },
  { origen: "DON TORCUATO", destino: "VICENTE LOPEZ", kmReal: 20, kmConv: 20 },
  { origen: "TIO PUJIO", destino: "DON TORCUATO", kmReal: 549, kmConv: 550 },
  { origen: "PABLO NOGUES", destino: "BURZACO", kmReal: 63, kmConv: 65 },
  { origen: "RETIRO", destino: "9 DE ABRIL", kmReal: 27, kmConv: 25 },
  { origen: "RAMALLO", destino: "SAN FRANCISCO", kmReal: 366, kmConv: 365 },
  { origen: "CAMPANA", destino: "RAMALLO", kmReal: 142, kmConv: 140 },
  { origen: "RAMALLO", destino: "ZONA PORTUARIA", kmReal: 216, kmConv: 215 },
  { origen: "SAN FRANCISCO", destino: "VILLA DEL TOTORAL", kmReal: 260, kmConv: 260 },
  { origen: "MATADEROS", destino: "VALENTIN ALSINA", kmReal: 14, kmConv: 15 },
  { origen: "BAHIA BLANCA", destino: "DON TORCUATO", kmReal: 655, kmConv: 655 },
  { origen: "CASEROS", destino: "GENERAL RODRIGUEZ", kmReal: 39, kmConv: 40 },
  { origen: "ARROYITO", destino: "FLORENCIO VARELA", kmReal: 678, kmConv: 680 },
  { origen: "SALTO", destino: "CA&#209;UELAS", kmReal: 186, kmConv: 185 },
  { origen: "VILLA MERCEDES", destino: "RETIRO", kmReal: 742, kmConv: 740 },
  { origen: "MALVINAS ARGENTINAS", destino: "VILLA MARTELLI", kmReal: 38, kmConv: 40 },
  { origen: "PUERTO PIRAY", destino: "POSADAS", kmReal: 202, kmConv: 200 },
  { origen: "MERCEDES", destino: "VILLA CELINA", kmReal: 97, kmConv: 95 },
  { origen: "SAN NICOLAS", destino: "ZONA PORTUARIA", kmReal: 238, kmConv: 240 },
  { origen: "RIO SEGUNDO", destino: "SAN NICOLAS", kmReal: 430, kmConv: 430 },
  { origen: "ZARATE", destino: "RIO SEGUNDO", kmReal: 573, kmConv: 575 },
  { origen: "BARRACAS", destino: "DESVIO ARIJON", kmReal: 424, kmConv: 425 },
  { origen: "SANTO TOME", destino: "MATADEROS", kmReal: 459, kmConv: 460 },
  { origen: "SUSANA", destino: "SANTO TOME", kmReal: 97, kmConv: 95 },
  { origen: "QUILMES", destino: "ZARATE", kmReal: 111, kmConv: 110 },
  { origen: "PASO DEL REY", destino: "GARIN", kmReal: 46, kmConv: 45 },
  { origen: "ARROYO SECO", destino: "PILAR", kmReal: 229, kmConv: 230 },
  { origen: "CORDOBA", destino: "ARROYO SECO", kmReal: 430, kmConv: 430 },
  { origen: "MORENO", destino: "VILLA CELINA", kmReal: 33, kmConv: 35 },
  { origen: "DON TORCUATO", destino: "ESTEBAN ECHEVERRIA", kmReal: 58, kmConv: 60 },
  { origen: "MATADEROS", destino: "9 DE ABRIL", kmReal: 14, kmConv: 15 },
  { origen: "SUSANA", destino: "VILLA SOLDATI", kmReal: 533, kmConv: 535 },
  { origen: "VILLA MERCEDES", destino: "LOS POLVORINES", kmReal: 712, kmConv: 710 },
  { origen: "PABLO NOGUES", destino: "DON TORCUATO", kmReal: 9, kmConv: 10 },
  { origen: "FATIMA", destino: "VILLA SOLDATI", kmReal: 70, kmConv: 70 },
  { origen: "POSADAS", destino: "JARDIN AMERICA", kmReal: 103, kmConv: 105 },
  { origen: "SAN PEDRO", destino: "VICENTE LOPEZ", kmReal: 162, kmConv: 160 },
  { origen: "JUJUY", destino: "SAN FRANCISCO", kmReal: 990, kmConv: 990 },
  { origen: "SAN JORGE", destino: "FATIMA", kmReal: 446, kmConv: 445 },
  { origen: "MATADEROS", destino: "LANUS", kmReal: 16, kmConv: 15 },
  { origen: "VICENTE LOPEZ", destino: "VILLA CELINA", kmReal: 24, kmConv: 25 },
  { origen: "9 DE ABRIL", destino: "FATIMA", kmReal: 80, kmConv: 80 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "SANTA FE", kmReal: 496, kmConv: 495 },
  { origen: "VICENTE LOPEZ", destino: "ESTEBAN ECHEVERRIA", kmReal: 48, kmConv: 50 },
  { origen: "LAS HERAS", destino: "CORDOBA", kmReal: 695, kmConv: 695 },
  { origen: "VILLAVICENCIO", destino: "CORDOBA", kmReal: 693, kmConv: 695 },
  { origen: "ALTA GRACIA", destino: "SAN FRANCISCO", kmReal: 261, kmConv: 260 },
  { origen: "PERGAMINO", destino: "BIGAND", kmReal: 87, kmConv: 85 },
  { origen: "PUERTO ESPERANZA", destino: "QUILMES", kmReal: 1249, kmConv: 1250 },
  { origen: "ITUZAINGO", destino: "CAMPANA", kmReal: 82, kmConv: 85 },
  { origen: "BECCAR", destino: "ITUZAINGO", kmReal: 35, kmConv: 35 },
  { origen: "SAN JORGE", destino: "VILLA MERCEDES", kmReal: 467, kmConv: 465 },
  { origen: "RAMONA", destino: "PERGAMINO", kmReal: 442, kmConv: 440 },
  { origen: "ARROYITO", destino: "9 DE ABRIL", kmReal: 665, kmConv: 665 },
  { origen: "COLONIA CAROYA", destino: "ARROYITO", kmReal: 168, kmConv: 170 },
  { origen: "MORON", destino: "VILLA SOLDATI", kmReal: 22, kmConv: 20 },
  { origen: "SAN MIGUEL DE TUCUMAN", destino: "DON TORCUATO", kmReal: 1235, kmConv: 1235 },
  { origen: "TIO PUJIO", destino: "MORON", kmReal: 577, kmConv: 575 },
  { origen: "COLONIA CAROYA", destino: "VILLA MERCEDES", kmReal: 397, kmConv: 395 },
  { origen: "EL JAGUEL", destino: "9 DE ABRIL", kmReal: 19, kmConv: 20 },
  { origen: "BANFIELD", destino: "BURZACO", kmReal: 10, kmConv: 10 },
  { origen: "CORDOBA", destino: "EL JAGUEL", kmReal: 720, kmConv: 720 },
  { origen: "COLONIA CAROYA", destino: "TIO PUJIO", kmReal: 179, kmConv: 180 },
  { origen: "ESCOBAR", destino: "FATIMA", kmReal: 28, kmConv: 30 },
  { origen: "LOS CARDALES", destino: "SAN MIGUEL DE TUCUMAN", kmReal: 1172, kmConv: 1170 },
  { origen: "SAN FRANCISCO", destino: "BANFIELD", kmReal: 577, kmConv: 575 },
  { origen: "ZONA PORTUARIA", destino: "BURZACO", kmReal: 42, kmConv: 40 },
  { origen: "GONZALEZ CATAN", destino: "GENERAL RODRIGUEZ", kmReal: 50, kmConv: 50 },
  { origen: "SAN PEDRO", destino: "ESCOBAR", kmReal: 120, kmConv: 120 },
  { origen: "HURLINGHAM", destino: "GARIN", kmReal: 32, kmConv: 30 },
  { origen: "VILLA MERCEDES", destino: "COLONIA CAROYA", kmReal: 398, kmConv: 400 },
  { origen: "LOS CARDALES", destino: "CORDOBA", kmReal: 636, kmConv: 635 },
  { origen: "TAPIALES", destino: "LOS CARDALES", kmReal: 86, kmConv: 85 },
  { origen: "CAMPANA", destino: "FATIMA", kmReal: 33, kmConv: 35 },
  { origen: "SAN JUSTO", destino: "TORTUGUITAS", kmReal: 50, kmConv: 50 },
  { origen: "SAN JORGE", destino: "VILLA ALLENDE", kmReal: 295, kmConv: 295 },
  { origen: "COLONIA CAROYA", destino: "SAN JUSTO", kmReal: 746, kmConv: 745 },
  { origen: "TAPIALES", destino: "FATIMA", kmReal: 68, kmConv: 70 },
  { origen: "BARRACAS", destino: "PORTE&#209;A", kmReal: 614, kmConv: 615 },
  { origen: "SANTA FE", destino: "SUSANA", kmReal: 82, kmConv: 80 },
  { origen: "BARADERO", destino: "LOS CARDALES", kmReal: 90, kmConv: 90 },
  { origen: "SAN LUIS", destino: "CONCARAN", kmReal: 161, kmConv: 160 },
  { origen: "PASO DEL REY", destino: "TORTUGUITAS", kmReal: 48, kmConv: 50 },
  { origen: "RIO CEBALLOS", destino: "ALTA GRACIA", kmReal: 73, kmConv: 75 },
  { origen: "LA FRANCIA", destino: "MORTEROS", kmReal: 137, kmConv: 135 },
  { origen: "SAN MARTIN", destino: "LA FRANCIA", kmReal: 712, kmConv: 710 },
  { origen: "JARDIN AMERICA", destino: "PUERTO PIRAY", kmReal: 98, kmConv: 100 },
  { origen: "ESCOBAR", destino: "AVELLANEDA", kmReal: 60, kmConv: 60 },
  { origen: "VILLA GENERAL BELGRANO", destino: "CORDOBA", kmReal: 87, kmConv: 90 },
  { origen: "VILLA GESELL", destino: "ZARATE", kmReal: 466, kmConv: 465 },
  { origen: "VILLA SOLDATI", destino: "VILLA GESELL", kmReal: 385, kmConv: 385 },
  { origen: "OLIVOS", destino: "VILLA SOLDATI", kmReal: 37, kmConv: 35 },
  { origen: "TORTUGUITAS", destino: "OLIVOS", kmReal: 28, kmConv: 30 },
  { origen: "VILLA MARTELLI", destino: "VICENTE LOPEZ", kmReal: 4, kmConv: 5 },
  { origen: "TIO PUJIO", destino: "VILLA MARTELLI", kmReal: 558, kmConv: 560 },
  { origen: "RAFAELA", destino: "VILLA GESELL", kmReal: 916, kmConv: 915 },
  { origen: "RETIRO", destino: "GARIN", kmReal: 42, kmConv: 40 },
  { origen: "GRAND BOURG", destino: "TORTUGUITAS", kmReal: 3, kmConv: 5 },
  { origen: "SUSANA", destino: "MONTE GRANDE", kmReal: 554, kmConv: 555 },
  { origen: "CORDOBA", destino: "PUERTO ESPERANZA", kmReal: 1371, kmConv: 1370 },
  { origen: "PARQUE PATRICIOS", destino: "RETIRO", kmReal: 7, kmConv: 10 },
  { origen: "VILLA MERCEDES", destino: "PARQUE PATRICIOS", kmReal: 698, kmConv: 700 },
  { origen: "MATADEROS", destino: "GARIN", kmReal: 44, kmConv: 45 },
  { origen: "RETIRO", destino: "BURZACO", kmReal: 40, kmConv: 40 },
  { origen: "SAN FRANCISCO", destino: "RETIRO", kmReal: 561, kmConv: 560 },
  { origen: "BURZACO", destino: "RAFAELA", kmReal: 563, kmConv: 565 },
  { origen: "ZARATE", destino: "VILLA GENERAL BELGRANO", kmReal: 672, kmConv: 670 },
  { origen: "BURZACO", destino: "BARRACAS", kmReal: 23, kmConv: 25 },
  { origen: "SIERRA DE LOS PADRES", destino: "SANTO TOME", kmReal: 872, kmConv: 870 },
  { origen: "VILLA SOLDATI", destino: "EL PALOMAR", kmReal: 16, kmConv: 15 },
  { origen: "LA MATANZA", destino: "CANNING", kmReal: 26, kmConv: 25 },
  { origen: "BAHIA BLANCA", destino: "SIERRA DE LOS PADRES", kmReal: 453, kmConv: 455 },
  { origen: "DESPE&#209;ADEROS", destino: "CORDOBA", kmReal: 50, kmConv: 50 },
  { origen: "CORDOBA", destino: "DESPE&#209;ADEROS", kmReal: 50, kmConv: 50 },
  { origen: "GARIN", destino: "VILLA MERCEDES", kmReal: 706, kmConv: 705 },
  { origen: "VILLA DEL PARQUE", destino: "GARIN", kmReal: 38, kmConv: 40 },
  { origen: "GENERAL LAGOS", destino: "MATADEROS", kmReal: 280, kmConv: 280 },
  { origen: "SUSANA", destino: "GENERAL LAGOS", kmReal: 281, kmConv: 280 },
  { origen: "LAMARQUE", destino: "RIO COLORADO", kmReal: 159, kmConv: 160 },
  { origen: "BARILOCHE", destino: "LAMARQUE", kmReal: 680, kmConv: 680 },
  { origen: "ARROYITO", destino: "BURZACO", kmReal: 674, kmConv: 675 },
  { origen: "SAN SALVADOR", destino: "SAN FRANCISCO", kmReal: 371, kmConv: 370 },
  { origen: "MATADEROS", destino: "TORTUGUITAS", kmReal: 47, kmConv: 45 },
  { origen: "MORENO", destino: "FATIMA", kmReal: 33, kmConv: 35 },
  { origen: "MALVINAS ARGENTINAS", destino: "TORTUGUITAS", kmReal: 69, kmConv: 70 },
  { origen: "TORTUGUITAS", destino: "RAFAELA", kmReal: 509, kmConv: 510 },
  { origen: "SAN FRANCISCO", destino: "BAHIA BLANCA", kmReal: 943, kmConv: 945 },
  { origen: "RAMALLO", destino: "SAN LORENZO", kmReal: 129, kmConv: 130 },
  { origen: "FATIMA", destino: "RAMALLO", kmReal: 168, kmConv: 170 },
  { origen: "VILLA SOLDATI", destino: "FATIMA", kmReal: 71, kmConv: 70 },
  { origen: "ESPERANZA", destino: "SUSANA", kmReal: 74, kmConv: 75 },
  { origen: "ARROYITO", destino: "MALVINAS ARGENTINAS", kmReal: 673, kmConv: 675 },
  { origen: "SANTO TOME", destino: "ARROYITO", kmReal: 228, kmConv: 230 },
  { origen: "MAR DEL PLATA", destino: "RECREO", kmReal: 894, kmConv: 895 },
  { origen: "JOSE C. PAZ", destino: "9 DE ABRIL", kmReal: 54, kmConv: 55 },
  { origen: "SAN PEDRO", destino: "PABLO NOGUES", kmReal: 139, kmConv: 140 },
  { origen: "SIERRA DE LOS PADRES", destino: "RECREO", kmReal: 891, kmConv: 890 },
  { origen: "RECREO", destino: "SANTA FE", kmReal: 17, kmConv: 20 },
  { origen: "PUERTO PIRAY", destino: "SANTO TOME", kmReal: 960, kmConv: 860 },
  { origen: "GENERAL RODRIGUEZ", destino: "RIO CUARTO", kmReal: 572, kmConv: 570 },
  { origen: "SUSANA", destino: "SAN FRANCISCO", kmReal: 78, kmConv: 80 },
  { origen: "CASTELAR", destino: "TORTUGUITAS", kmReal: 33, kmConv: 35 },
  { origen: "SANTO TOME", destino: "PUERTO PIRAY", kmReal: 960, kmConv: 960 },
  { origen: "PORTE&#209;A", destino: "SUSANA", kmReal: 85, kmConv: 85 },
  { origen: "SAN FRANCISCO", destino: "CASTELAR", kmReal: 569, kmConv: 570 },
  { origen: "FRANCK", destino: "SUSANA", kmReal: 84, kmConv: 85 },
  { origen: "RESISTENCIA", destino: "PUERTO PIRAY", kmReal: 525, kmConv: 525 },
  { origen: "CAMPANA", destino: "SAN JUSTO", kmReal: 85, kmConv: 85 },
  { origen: "MARCOS JUAREZ", destino: "CORDOBA", kmReal: 265, kmConv: 265 },
  { origen: "CONCORDIA", destino: "MARCOS JUAREZ", kmReal: 498, kmConv: 500 },
  { origen: "SARANDI", destino: "SANTO TOME", kmReal: 468, kmConv: 470 },
  { origen: "GRAND BOURG", destino: "VILLA SOLDATI", kmReal: 48, kmConv: 50 },
  { origen: "GRAND BOURG", destino: "9 DE ABRIL", kmReal: 55, kmConv: 55 },
  { origen: "SANTA FE", destino: "TIO PUJIO", kmReal: 315, kmConv: 315 },
  { origen: "SANTO TOME", destino: "SUSANA", kmReal: 96, kmConv: 95 },
  { origen: "PARANÁ", destino: "SUSANA", kmReal: 136, kmConv: 135 },
  { origen: "SUSANA", destino: "CAMPANA", kmReal: 452, kmConv: 450 },
  { origen: "JOSE C. PAZ", destino: "SAN JUSTO", kmReal: 37, kmConv: 35 },
  { origen: "SAN FRANCISCO", destino: "GOBERNADOR CRESPO", kmReal: 292, kmConv: 290 },
  { origen: "CONCARAN", destino: "JOSE C. PAZ", kmReal: 739, kmConv: 740 },
  { origen: "MENDOZA", destino: "CONCARAN", kmReal: 417, kmConv: 415 },
  { origen: "VILLA MERCEDES", destino: "QUILMES", kmReal: 719, kmConv: 720 },
  { origen: "MAR DEL PLATA", destino: "SANTA FE", kmReal: 884, kmConv: 885 },
  { origen: "BAHIA BLANCA", destino: "MAR DEL PLATA", kmReal: 464, kmConv: 465 },
  { origen: "COLONIA CAROYA", destino: "GRAND BOURG", kmReal: 710, kmConv: 710 },
  { origen: "ARROYITO", destino: "COLONIA CAROYA", kmReal: 131, kmConv: 130 },
  { origen: "VALENTIN ALSINA", destino: "VILLA MERCEDES", kmReal: 699, kmConv: 700 },
  { origen: "DON TORCUATO", destino: "VALENTIN ALSINA", kmReal: 41, kmConv: 40 },
  { origen: "LOMA HERMOSA", destino: "CARLOS SPEGAZZINI", kmReal: 58, kmConv: 60 },
  { origen: "TAPIALES", destino: "VILLA CELINA", kmReal: 3, kmConv: 5 },
  { origen: "FATIMA", destino: "ROSARIO", kmReal: 249, kmConv: 250 },
  { origen: "DON TORCUATO", destino: "FATIMA", kmReal: 39, kmConv: 40 },
  { origen: "GALVEZ", destino: "RAFAELA", kmReal: 111, kmConv: 110 },
  { origen: "SARANDI", destino: "GALVEZ", kmReal: 438, kmConv: 440 },
  { origen: "MENDOZA", destino: "VILLAVICENCIO", kmReal: 5, kmConv: 5 },
  { origen: "PILAR", destino: "RIO SEGUNDO", kmReal: 618, kmConv: 620 },
  { origen: "MONTE GRANDE", destino: "GENERAL RODRIGUEZ", kmReal: 72, kmConv: 70 },
  { origen: "GENERAL PACHECO", destino: "ARROYITO", kmReal: 619, kmConv: 620 },
  { origen: "VILLA SOLDATI", destino: "VILLA BALLESTER", kmReal: 22, kmConv: 20 },
  { origen: "VILLA BALLESTER", destino: "CORDOBA", kmReal: 680, kmConv: 680 },
  { origen: "BARRACAS", destino: "PUERTO PIRAY", kmReal: 1177, kmConv: 1175 },
  { origen: "CORDOBA", destino: "ISIDRO CASANOVA", kmReal: 703, kmConv: 705 },
  { origen: "MONTECASTRO", destino: "DOCK SUD", kmReal: 22, kmConv: 20 },
  { origen: "PABLO NOGUES", destino: "LOMA HERMOSA", kmReal: 22, kmConv: 20 },
  { origen: "PABLO NOGUES", destino: "VILLA CELINA", kmReal: 60, kmConv: 60 },
  { origen: "MAR DEL PLATA", destino: "RAFAELA", kmReal: 985, kmConv: 985 },
  { origen: "VILLA REGINA", destino: "MAR DEL PLATA", kmReal: 908, kmConv: 910 },
  { origen: "BARILOCHE", destino: "VILLA REGINA", kmReal: 528, kmConv: 530 },
  { origen: "SAN JUSTO", destino: "FATIMA", kmReal: 70, kmConv: 70 },
  { origen: "PABLO NOGUES", destino: "EL PALOMAR", kmReal: 24, kmConv: 25 },
  { origen: "DOCK SUD", destino: "GALVEZ", kmReal: 436, kmConv: 435 },
  { origen: "SUSANA", destino: "ESTEBAN ECHEVERRIA", kmReal: 557, kmConv: 555 },
  { origen: "CORDOBA", destino: "ZARATE", kmReal: 612, kmConv: 610 },
  { origen: "SAN SALVADOR", destino: "MORENO", kmReal: 399, kmConv: 400 },
  { origen: "CA&#209;UELAS", destino: "PARANÁ", kmReal: 522, kmConv: 520 },
  { origen: "VILLA SOLDATI", destino: "CA&#209;UELAS", kmReal: 56, kmConv: 55 },
  { origen: "SAN NICOLAS", destino: "CA&#209;UELAS", kmReal: 270, kmConv: 270 },
  { origen: "MARCOS PAZ", destino: "SAN ANDRES DE GILES", kmReal: 90, kmConv: 90 },
  { origen: "BELL VILLE", destino: "DOCK SUD", kmReal: 505, kmConv: 505 },
  { origen: "BARRACAS", destino: "BELL VILLE", kmReal: 503, kmConv: 505 },
  { origen: "SALTO", destino: "ZARATE", kmReal: 150, kmConv: 150 },
  { origen: "ARROYITO", destino: "SALTO", kmReal: 493, kmConv: 495 },
  { origen: "PERGAMINO", destino: "ZARATE", kmReal: 168, kmConv: 170 },
  { origen: "MUNRO", destino: "BARRACAS", kmReal: 25, kmConv: 25 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "BARRACAS", kmReal: 41, kmConv: 40 },
  { origen: "MATADEROS", destino: "VILLA SOLDATI", kmReal: 8, kmConv: 10 },
  { origen: "SANTO TOME", destino: "VICENTE LOPEZ", kmReal: 448, kmConv: 450 },
  { origen: "ARROYITO", destino: "LA FRANCIA", kmReal: 41, kmConv: 40 },
  { origen: "ARROYITO", destino: "TORTUGUITAS", kmReal: 622, kmConv: 620 },
  { origen: "PARANÁ", destino: "FRANCK", kmReal: 62, kmConv: 60 },
  { origen: "HURLINGHAM", destino: "GENERAL RODRIGUEZ", kmReal: 36, kmConv: 35 },
  { origen: "MONTECASTRO", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "JUJUY", destino: "SAN JORGE", kmReal: 1325, kmConv: 1325 },
  { origen: "MORENO", destino: "CHASCOMUS", kmReal: 164, kmConv: 165 },
  { origen: "CHASCOMUS", destino: "VILLA MARIA", kmReal: 679, kmConv: 680 },
  { origen: "ITUZAINGO", destino: "GARIN", kmReal: 45, kmConv: 45 },
  { origen: "CAPILLA DEL MONTE", destino: "TIO PUJIO", kmReal: 226, kmConv: 226 },
  { origen: "CORDOBA", destino: "CAPILLA DEL MONTE", kmReal: 99, kmConv: 100 },
  { origen: "VICENTE LOPEZ", destino: "EZEIZA", kmReal: 44, kmConv: 45 },
  { origen: "SAN RAFAEL", destino: "MORENO", kmReal: 941, kmConv: 940 },
  { origen: "MENDOZA", destino: "SAN RAFAEL", kmReal: 234, kmConv: 235 },
  { origen: "SAN SALVADOR", destino: "ITUZAINGO", kmReal: 399, kmConv: 400 },
  { origen: "GARIN", destino: "CHASCOMUS", kmReal: 169, kmConv: 170 },
  { origen: "TAPIALES", destino: "BURZACO", kmReal: 21, kmConv: 20 },
  { origen: "BARRACAS", destino: "TORTUGUITAS", kmReal: 51, kmConv: 50 },
  { origen: "VILLA CELINA", destino: "JUJUY", kmReal: 1613, kmConv: 1615 },
  { origen: "GRAND BOURG", destino: "VICENTE LOPEZ", kmReal: 32, kmConv: 30 },
  { origen: "TIO PUJIO", destino: "GRAND BOURG", kmReal: 539, kmConv: 540 },
  { origen: "LOS CARDALES", destino: "ROSARIO", kmReal: 238, kmConv: 240 },
  { origen: "SAN MARTIN", destino: "VILLA MERCEDES", kmReal: 315, kmConv: 315 },
  { origen: "MORENO", destino: "FLORENCIO VARELA", kmReal: 65, kmConv: 65 },
  { origen: "MORTEROS", destino: "VILLA MARTELLI", kmReal: 571, kmConv: 570 },
  { origen: "MONTEVIDEO", destino: "CONCORDIA", kmReal: 543, kmConv: 545 },
  { origen: "CONCORDIA", destino: "BARRACAS", kmReal: 435, kmConv: 435 },
  { origen: "LA MATANZA", destino: "DON TORCUATO", kmReal: 33, kmConv: 35 },
  { origen: "VILLA CELINA", destino: "SAN MIGUEL DE TUCUMAN", kmReal: 1253, kmConv: 1255 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
