/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 6 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "SANTO TOME", destino: "CONCORDIA", kmReal: 302, kmConv: 300 },
  { origen: "CORDOBA", destino: "9 DE ABRIL", kmReal: 710, kmConv: 710 },
  { origen: "POSADAS", destino: "CUATRO BOCAS", kmReal: 450, kmConv: 450 },
  { origen: "ZONA PORTUARIA", destino: "9 DE ABRIL", kmReal: 30, kmConv: 30 },
  { origen: "PUERTO PIRAY", destino: "PILAR", kmReal: 1156, kmConv: 1155 },
  { origen: "RAMONA", destino: "RAFAELA", kmReal: 54, kmConv: 55 },
  { origen: "RAFAELA", destino: "VILLA DEL PARQUE", kmReal: 537, kmConv: 535 },
  { origen: "DESVIO ARIJON", destino: "RECREO", kmReal: 70, kmConv: 70 },
  { origen: "RECREO", destino: "DESVIO ARIJON", kmReal: 70, kmConv: 70 },
  { origen: "9 DE ABRIL", destino: "SANTO TOME", kmReal: 470, kmConv: 470 },
  { origen: "MAR DEL PLATA", destino: "9 DE ABRIL", kmReal: 435, kmConv: 435 },
  { origen: "ZARATE", destino: "VILLA SOLDATI", kmReal: null, kmConv: 100 },
  { origen: "MERCEDES", destino: "GARIN", kmReal: null, kmConv: 95 },
  { origen: "TIGRE", destino: "VALENTIN ALSINA", kmReal: 46, kmConv: 45 },
  { origen: "BARROS BLANCOS", destino: "VILLA SOLDATI", kmReal: 598, kmConv: 600 },
  { origen: "MUNRO", destino: "BURZACO", kmReal: 58, kmConv: 60 },
  { origen: "ESPERANZA", destino: "DEVOTO", kmReal: 162, kmConv: 160 },
  { origen: "DON TORCUATO", destino: "SAN FRANCISCO", kmReal: 556, kmConv: 555 },
  { origen: "VICENTE LOPEZ", destino: "CORDOBA", kmReal: 686, kmConv: 685 },
  { origen: "MERCEDES", destino: "VICENTE LOPEZ", kmReal: 121, kmConv: 120 },
  { origen: "CRUZ DEL EJE", destino: "ZONA PORTUARIA", kmReal: 879, kmConv: 880 },
  { origen: "TORTUGUITAS", destino: "TIGRE", kmReal: 28, kmConv: 30 },
  { origen: "MOISES VILLE", destino: "ARROYITO", kmReal: 245, kmConv: 245 },
  { origen: "RAFAELA", destino: "MOISES VILLE", kmReal: 74, kmConv: 75 },
  { origen: "SAN SALVADOR", destino: "ALTA GRACIA", kmReal: 632, kmConv: 630 },
  { origen: "VILLA URQUIZA", destino: "GARIN", kmReal: 31, kmConv: 30 },
  { origen: "CUATRO BOCAS", destino: "PUERTO PIRAY", kmReal: 602, kmConv: 600 },
  { origen: "ZONA PORTUARIA", destino: "CUATRO BOCAS", kmReal: 566, kmConv: 566 },
  { origen: "CUATRO BOCAS", destino: "SANTA FE", kmReal: 350, kmConv: 350 },
  { origen: "JARDIN AMERICA", destino: "CUATRO BOCAS", kmReal: 504, kmConv: 500 },
  { origen: "MORENO", destino: "EZEIZA", kmReal: 49, kmConv: 50 },
  { origen: "LA PLATA", destino: "BALCARCE", kmReal: 373, kmConv: 375 },
  { origen: "EZEIZA", destino: "SAN JORGE", kmReal: 533, kmConv: 535 },
  { origen: "LANUS", destino: "EZEIZA", kmReal: 25, kmConv: 25 },
  { origen: "UDAONDO", destino: "SAN JORGE", kmReal: 497, kmConv: 495 },
  { origen: "BARADERO", destino: "UDAONDO", kmReal: 155, kmConv: 155 },
  { origen: "BARADERO", destino: "LANUS", kmReal: 166, kmConv: 165 },
  { origen: "9 DE ABRIL", destino: "PILAR", kmReal: 75, kmConv: 75 },
  { origen: "BALCARCE", destino: "BARROS BLANCOS", kmReal: 998, kmConv: 1000 },
  { origen: "VILLA SOLDATI", destino: "BALCARCE", kmReal: 423, kmConv: 425 },
  { origen: "ROSARIO", destino: "BRINKMANN", kmReal: 338, kmConv: 340 },
  { origen: "MORENO", destino: "ROSARIO", kmReal: 288, kmConv: 290 },
  { origen: "ZARATE", destino: "9 DE ABRIL", kmReal: 127, kmConv: 130 },
  { origen: "JARDIN AMERICA", destino: "ZONA PORTUARIA", kmReal: 1073, kmConv: 1075 },
  { origen: "LA CRUZ", destino: "JARDIN AMERICA", kmReal: 328, kmConv: 330 },
  { origen: "APÓSTOLES", destino: "PUERTO PIRAY", kmReal: 241, kmConv: 240 },
  { origen: "PUERTO PIRAY", destino: "LA CRUZ", kmReal: 427, kmConv: 425 },
  { origen: "JARDIN AMERICA", destino: "POSADAS", kmReal: 103, kmConv: 100 },
  { origen: "PUERTO PIRAY", destino: "JARDIN AMERICA", kmReal: 98, kmConv: 100 },
  { origen: "SAN FRANCISCO", destino: "NUEVA POMPEYA", kmReal: 569, kmConv: 570 },
  { origen: "EL FORTIN", destino: "TIO PUJIO", kmReal: 138, kmConv: 140 },
  { origen: "CORDOBA", destino: "EL FORTIN", kmReal: 282, kmConv: 280 },
  { origen: "MUNRO", destino: "ROSARIO", kmReal: 285, kmConv: 285 },
  { origen: "VILLA MAIPU", destino: "TORTUGUITAS", kmReal: 35, kmConv: 35 },
  { origen: "CORDOBA", destino: "VILLA MAIPU", kmReal: 684, kmConv: 685 },
  { origen: "PATERNAL", destino: "TAPIALES", kmReal: 16, kmConv: 15 },
  { origen: "ITUZAINGO", destino: "MATADEROS", kmReal: 22, kmConv: 20 },
  { origen: "SAN FRANCISCO", destino: "EL JAGUEL", kmReal: 589, kmConv: 590 },
  { origen: "PUERTO ESPERANZA", destino: "9 DE ABRIL", kmReal: 1239, kmConv: 1240 },
  { origen: "MERCEDES", destino: "VILLA LUZURIAGA", kmReal: 85, kmConv: 85 },
  { origen: "SANTA TERESITA", destino: "9 DE ABRIL", kmReal: 353, kmConv: 355 },
  { origen: "ZONA PORTUARIA", destino: "FREYRE", kmReal: 588, kmConv: 590 },
  { origen: "ZONA PORTUARIA", destino: "SAN JORGE", kmReal: 493, kmConv: 495 },
  { origen: "BERAZATEGUI", destino: "PORTE&#209;A", kmReal: 644, kmConv: 645 },
  { origen: "GENERAL RODRIGUEZ", destino: "VILLA SOLDATI", kmReal: 50, kmConv: 50 },
  { origen: "BERAZATEGUI", destino: "RECREO", kmReal: 517, kmConv: 515 },
  { origen: "ESCOBAR", destino: "PILAR", kmReal: 21, kmConv: 20 },
  { origen: "JOSE INGENIEROS", destino: "VILLA SOLDATI", kmReal: 12, kmConv: 12 },
  { origen: "ALTA GRACIA", destino: "TORTUGUITAS", kmReal: 673, kmConv: 675 },
  { origen: "FREYRE", destino: "MONTE GRANDE", kmReal: 617, kmConv: 615 },
  { origen: "SAN FRANCISCO", destino: "VILLAGUAY", kmReal: 320, kmConv: 320 },
  { origen: "SARANDI", destino: "MORTEROS", kmReal: 657, kmConv: 655 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "ZARATE", kmReal: 135, kmConv: 135 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "CIUDADELA", kmReal: 1560, kmConv: 1560 },
  { origen: "DON TORCUATO", destino: "9 DE ABRIL", kmReal: 57, kmConv: 55 },
  { origen: "MONTE GRANDE", destino: "MATADEROS", kmReal: 28, kmConv: 30 },
  { origen: "CHACARITA", destino: "SAN JUSTO", kmReal: 25, kmConv: 25 },
  { origen: "VIRREY DEL PINO", destino: "VICENTE LOPEZ", kmReal: 62, kmConv: 60 },
  { origen: "AVELLANEDA", destino: "VIRREY DEL PINO", kmReal: 57, kmConv: 55 },
  { origen: "BIGAND", destino: "CORDOBA", kmReal: 390, kmConv: 390 },
  { origen: "VILLA MARIA", destino: "AVELLANEDA", kmReal: 561, kmConv: 560 },
  { origen: "ROSARIO", destino: "BIGAND", kmReal: 69, kmConv: 70 },
  { origen: "SAN FRANCISCO", destino: "JOSE INGENIEROS", kmReal: 559, kmConv: 560 },
  { origen: "LA PLATA", destino: "BARRACAS", kmReal: 59, kmConv: 60 },
  { origen: "AVELLANEDA", destino: "9 DE ABRIL", kmReal: 28, kmConv: 30 },
  { origen: "ZONA PORTUARIA", destino: "BASAVILBASO", kmReal: 323, kmConv: 325 },
  { origen: "BASAVILBASO", destino: "ZONA PORTUARIA", kmReal: 323, kmConv: 325 },
  { origen: "TIO PUJIO", destino: "TIGRE", kmReal: 555, kmConv: 555 },
  { origen: "SAN JUSTO", destino: "ITUZAINGO", kmReal: 13, kmConv: 15 },
  { origen: "BARADERO", destino: "VILLA SOLDATI", kmReal: 170, kmConv: 170 },
  { origen: "PUERTO PIRAY", destino: "ZONA PORTUARIA", kmReal: 1170, kmConv: 1170 },
  { origen: "ZONA PORTUARIA", destino: "PUERTO PIRAY", kmReal: 1170, kmConv: 1170 },
  { origen: "ZARATE", destino: "BAHIA BLANCA", kmReal: 751, kmConv: 750 },
  { origen: "BECCAR", destino: "ZARATE", kmReal: 77, kmConv: 75 },
  { origen: "SAN FRANCISCO", destino: "ALVEAR", kmReal: 281, kmConv: 280 },
  { origen: "ALVEAR", destino: "SAN FRANCISCO", kmReal: 281, kmConv: 281 },
  { origen: "ZONA PORTUARIA", destino: "CONCORDIA", kmReal: 428, kmConv: 430 },
  { origen: "CARLOS PAZ", destino: "CORDOBA", kmReal: 40, kmConv: 40 },
  { origen: "CORDOBA", destino: "CARLOS PAZ", kmReal: 41, kmConv: 40 },
  { origen: "MORENO", destino: "BARRACAS", kmReal: 44, kmConv: 45 },
  { origen: "ESCOBAR", destino: "ZARATE", kmReal: 41, kmConv: 40 },
  { origen: "TIGRE", destino: "VILLA MERCEDES", kmReal: 701, kmConv: 700 },
  { origen: "VILLA SOLDATI", destino: "TIGRE", kmReal: 44, kmConv: 45 },
  { origen: "SAN FRANCISCO SOLANO", destino: "VILLA SOLDATI", kmReal: 43, kmConv: 43 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "BECCAR", kmReal: 1552, kmConv: 1550 },
  { origen: "CORRIENTES", destino: "PUERTO PIRAY", kmReal: 505, kmConv: 505 },
  { origen: "SAN FRANCISCO", destino: "ESCOBAR", kmReal: 510, kmConv: 510 },
  { origen: "PARANÁ", destino: "SANTO TOME", kmReal: 40, kmConv: 40 },
  { origen: "LOMA HERMOSA", destino: "VILLA SOLDATI", kmReal: 23, kmConv: 25 },
  { origen: "BAHIA BLANCA", destino: "PARANÁ", kmReal: 979, kmConv: 980 },
  { origen: "LOMAS DEL MIRADOR", destino: "ZARATE", kmReal: 95, kmConv: 95 },
  { origen: "GENERAL PACHECO", destino: "RIO SEGUNDO", kmReal: 629, kmConv: 630 },
  { origen: "FRANCK", destino: "ZONA PORTUARIA", kmReal: 479, kmConv: 480 },
  { origen: "DOCK SUD", destino: "FRANCK", kmReal: 493, kmConv: 495 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "TORTUGUITAS", kmReal: 78, kmConv: 78 },
  { origen: "ISIDRO CASANOVA", destino: "LANUS", kmReal: 25, kmConv: 25 },
  { origen: "VICENTE LOPEZ", destino: "LANUS", kmReal: 28, kmConv: 30 },
  { origen: "PARANÁ", destino: "SAN FRANCISCO", kmReal: 169, kmConv: 169 },
  { origen: "PUERTO ESPERANZA", destino: "HURLINGHAM", kmReal: 1220, kmConv: 1200 },
  { origen: "MONTE CARLO", destino: "PUERTO ESPERANZA", kmReal: 71, kmConv: 70 },
  { origen: "PUERTO ESPERANZA", destino: "LOMAS DEL MIRADOR", kmReal: 1226, kmConv: 1225 },
  { origen: "WILDE", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "MERCEDES", destino: "9 DE ABRIL", kmReal: 105, kmConv: 105 },
  { origen: "RETIRO", destino: "ZONA PORTUARIA", kmReal: 3, kmConv: 3 },
  { origen: "SUNCHALES", destino: "GARIN", kmReal: 537, kmConv: 535 },
  { origen: "DOCK SUD", destino: "CALCHIN", kmReal: 650, kmConv: 650 },
  { origen: "CALCHIN", destino: "DOCK SUD", kmReal: 650, kmConv: 650 },
  { origen: "QUILMES", destino: "CORDOBA", kmReal: 717, kmConv: 720 },
  { origen: "LA PLATA", destino: "QUILMES", kmReal: 39, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "QUILMES", kmReal: 25, kmConv: 25 },
  { origen: "LANUS", destino: "VICENTE LOPEZ", kmReal: 28, kmConv: 30 },
  { origen: "BURZACO", destino: "LANUS", kmReal: 16, kmConv: 15 },
  { origen: "VILLA MARIA", destino: "BURZACO", kmReal: 593, kmConv: 595 },
  { origen: "RECREO", destino: "SANTO TOME", kmReal: 28, kmConv: 30 },
  { origen: "CORDOBA", destino: "GARIN", kmReal: 655, kmConv: 655 },
  { origen: "SIERRA DE LOS PADRES", destino: "CORDOBA", kmReal: 1117, kmConv: 1115 },
  { origen: "ITUZAINGO", destino: "LANUS", kmReal: 34, kmConv: 35 },
  { origen: "VILLA SOLDATI", destino: "MATADEROS", kmReal: 7, kmConv: 5 },
  { origen: "VILLA SOLDATI", destino: "RETIRO", kmReal: 14, kmConv: 15 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "VILLA SOLDATI", kmReal: 1567, kmConv: 1565 },
  { origen: "QUILMES", destino: "LANUS", kmReal: 18, kmConv: 20 },
  { origen: "CONCORDIA", destino: "QUILMES", kmReal: 450, kmConv: 450 },
  { origen: "SANTA FE", destino: "DEVOTO", kmReal: 169, kmConv: 170 },
  { origen: "BERAZATEGUI", destino: "ALEJANDRO ROCA", kmReal: 583, kmConv: 585 },
  { origen: "GENERAL DEHEZA", destino: "ZONA PORTUARIA", kmReal: 616, kmConv: 615 },
  { origen: "BERAZATEGUI", destino: "GENERAL DEHEZA", kmReal: 648, kmConv: 650 },
  { origen: "PUERTO ESPERANZA", destino: "ZONA PORTUARIA", kmReal: 1224, kmConv: 1225 },
  { origen: "ZONA PORTUARIA", destino: "PUERTO ESPERANZA", kmReal: 1223, kmConv: 1225 },
  { origen: "VILLAGUAY", destino: "CONCORDIA", kmReal: 125, kmConv: 125 },
  { origen: "MONTE GRANDE", destino: "9 DE ABRIL", kmReal: 11, kmConv: 10 },
  { origen: "CHACARITA", destino: "MONTE GRANDE", kmReal: 51, kmConv: 50 },
  { origen: "VILLA MARIA", destino: "MONTE GRANDE", kmReal: 592, kmConv: 590 },
  { origen: "PUERTO PIRAY", destino: "BRINKMANN", kmReal: 1139, kmConv: 1140 },
  { origen: "PUERTO PIRAY", destino: "BURZACO", kmReal: 1213, kmConv: 1215 },
  { origen: "MONTE GRANDE", destino: "GARIN", kmReal: 85, kmConv: 85 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "GARIN", kmReal: 105, kmConv: 105 },
  { origen: "MONTE GRANDE", destino: "PILAR", kmReal: 105, kmConv: 105 },
  { origen: "ISIDRO CASANOVA", destino: "MATADEROS", kmReal: 10, kmConv: 10 },
  { origen: "MUNRO", destino: "EZEIZA", kmReal: 58, kmConv: 60 },
  { origen: "CAMPANA", destino: "DOCK SUD", kmReal: null, kmConv: 88 },
  { origen: "SAN FRANCISCO", destino: "GARIN", kmReal: 541, kmConv: 540 },
  { origen: "CONCORDIA", destino: "MONTE GRANDE", kmReal: 470, kmConv: 470 },
  { origen: "GARIN", destino: "ZARATE", kmReal: 56, kmConv: 55 },
  { origen: "MERCEDES", destino: "MATADEROS", kmReal: 93, kmConv: 95 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "PILAR", kmReal: 102, kmConv: 100 },
  { origen: "DOCK SUD", destino: "CAMPANA", kmReal: 89, kmConv: 90 },
  { origen: "MATADEROS", destino: "CORDOBA", kmReal: 715, kmConv: 715 },
  { origen: "MUNRO", destino: "MATADEROS", kmReal: 38, kmConv: 40 },
  { origen: "CHAJARÍ", destino: "DOCK SUD", kmReal: 502, kmConv: 500 },
  { origen: "BERAZATEGUI", destino: "CHAJARÍ", kmReal: 527, kmConv: 525 },
  { origen: "BERAZATEGUI", destino: "INGENIERO LUIGGI", kmReal: 664, kmConv: 660 },
  { origen: "BURZACO", destino: "TORTUGUITAS", kmReal: 85, kmConv: 85 },
  { origen: "ISIDRO CASANOVA", destino: "ZARATE", kmReal: 127, kmConv: 125 },
  { origen: "FLORENCIO VARELA", destino: "TORTUGUITAS", kmReal: null, kmConv: 82 },
  { origen: "FREYRE", destino: "FLORENCIO VARELA", kmReal: 656, kmConv: 655 },
  { origen: "GARIN", destino: "SAN FRANCISCO", kmReal: 541, kmConv: 540 },
  { origen: "JUNIN", destino: "ZARATE", kmReal: 221, kmConv: 220 },
  { origen: "BAHIA BLANCA", destino: "ISIDRO CASANOVA", kmReal: 624, kmConv: 620 },
  { origen: "SAN ANDRES DE GILES", destino: "ZARATE", kmReal: 60, kmConv: 60 },
  { origen: "SASTRE", destino: "FRANCK", kmReal: 118, kmConv: 120 },
  { origen: "SUNCHALES", destino: "BURZACO", kmReal: 638, kmConv: 640 },
  { origen: "HURLINGHAM", destino: "LUJAN", kmReal: 53, kmConv: 53 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "FLORENCIO VARELA", kmReal: 28, kmConv: 30 },
  { origen: "CALCHIN", destino: "SAN FRANCISCO", kmReal: 135, kmConv: 135 },
  { origen: "9 DE ABRIL", destino: "VILLA SOLDATI", kmReal: null, kmConv: 20 },
  { origen: "MORENO", destino: "9 DE ABRIL", kmReal: 52, kmConv: 50 },
  { origen: "CALCHIN", destino: "ZONA PORTUARIA", kmReal: 640, kmConv: 640 },
  { origen: "CORDOBA", destino: "CALCHIN", kmReal: 115, kmConv: 115 },
  { origen: "SARANDI", destino: "DALMASIO VELEZ", kmReal: 603, kmConv: 605 },
  { origen: "VILLA SOLDATI", destino: "DALMASIO VELEZ", kmReal: 598, kmConv: 600 },
  { origen: "VILLA SOLDATI", destino: "JOSE LEON SUAREZ", kmReal: 44, kmConv: 45 },
  { origen: "DON TORCUATO", destino: "CAMPANA", kmReal: 53, kmConv: 55 },
  { origen: "DALMASIO VELEZ", destino: "DOCK SUD", kmReal: 605, kmConv: 605 },
  { origen: "VICENTE LOPEZ", destino: "BARADERO", kmReal: 140, kmConv: 140 },
  { origen: "DOCK SUD", destino: "SARANDI", kmReal: null, kmConv: 4 },
  { origen: "MORTEROS", destino: "CORDOBA", kmReal: 298, kmConv: 300 },
  { origen: "ARROYITO", destino: "TIO PUJIO", kmReal: 164, kmConv: 165 },
  { origen: "INGENIERO LUIGGI", destino: "ZONA PORTUARIA", kmReal: 643, kmConv: 640 },
  { origen: "INGENIERO LUIGGI", destino: "DOCK SUD", kmReal: 645, kmConv: 645 },
  { origen: "VILLA SOLDATI", destino: "INGENIERO LUIGGI", kmReal: 634, kmConv: 635 },
  { origen: "WILDE", destino: "DOCK SUD", kmReal: 9, kmConv: 9 },
  { origen: "VILLA REGINA", destino: "BAHIA BLANCA", kmReal: 444, kmConv: 445 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "VILLA MARIA", kmReal: 580, kmConv: 580 },
  { origen: "SAN JUSTO", destino: "EZEIZA", kmReal: 23, kmConv: 25 },
  { origen: "MENDOZA", destino: "9 DE ABRIL", kmReal: 1050, kmConv: 1050 },
  { origen: "CANDELARIA", destino: "PUERTO ESPERANZA", kmReal: 229, kmConv: 230 },
  { origen: "VERSALLES", destino: "ZARATE", kmReal: 117, kmConv: 115 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "EZEIZA", kmReal: 7, kmConv: 5 },
  { origen: "DOCK SUD", destino: "SAN JUSTO", kmReal: 30, kmConv: 30 },
  { origen: "LOMAS DE ZAMORA", destino: "TORTUGUITAS", kmReal: 59, kmConv: 59 },
  { origen: "VICENTE LOPEZ", destino: "9 DE ABRIL", kmReal: 41, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "MERCEDES", kmReal: 100, kmConv: 100 },
  { origen: "BURZACO", destino: "EZEIZA", kmReal: 16, kmConv: 15 },
  { origen: "DOCK SUD", destino: "PUERTO MADRYN", kmReal: 1310, kmConv: 1310 },
  { origen: "CIUDADELA", destino: "BURZACO", kmReal: 28, kmConv: 30 },
  { origen: "SAN JORGE", destino: "CIUDADELA", kmReal: 490, kmConv: 490 },
  { origen: "PABLO NOGUES", destino: "GARIN", kmReal: 10, kmConv: 10 },
  { origen: "CORDOBA", destino: "CIUDADELA", kmReal: 692, kmConv: 690 },
  { origen: "VILLA MARIA", destino: "ITUZAINGO", kmReal: 553, kmConv: 555 },
  { origen: "CONCORDIA", destino: "ZONA PORTUARIA", kmReal: 428, kmConv: 430 },
  { origen: "BERAZATEGUI", destino: "CONCORDIA", kmReal: 457, kmConv: 455 },
  { origen: "DOCK SUD", destino: "BERAZATEGUI", kmReal: 21, kmConv: 20 },
  { origen: "PASO DEL REY", destino: "PILAR", kmReal: 35, kmConv: 35 },
  { origen: "ZONA PORTUARIA", destino: "CORDOBA", kmReal: 695, kmConv: 695 },
  { origen: "SAN LORENZO", destino: "ROSARIO", kmReal: 31, kmConv: 30 },
  { origen: "PILAR", destino: "SAN LORENZO", kmReal: 285, kmConv: 285 },
  { origen: "9 DE ABRIL", destino: "LANUS", kmReal: 13, kmConv: 15 },
  { origen: "CHACARITA", destino: "BARADERO", kmReal: 142, kmConv: 140 },
  { origen: "MALVINAS ARGENTINAS", destino: "VICENTE LOPEZ", kmReal: 30, kmConv: 30 },
  { origen: "SAN VICENTE", destino: "BARRACAS", kmReal: 59, kmConv: 60 },
  { origen: "FREYRE", destino: "TORTUGUITAS", kmReal: 580, kmConv: 580 },
  { origen: "SANTA FE", destino: "FREYRE", kmReal: 172, kmConv: 170 },
  { origen: "VILLA MARIA", destino: "CHACARITA", kmReal: 543, kmConv: 545 },
  { origen: "TAPIALES", destino: "BARADERO", kmReal: 172, kmConv: 170 },
  { origen: "SAN FRANCISCO", destino: "SALTA", kmReal: 964, kmConv: 965 },
  { origen: "TIO PUJIO", destino: "MALVINAS ARGENTINAS", kmReal: 538, kmConv: 540 },
  { origen: "LA PLATA", destino: "9 DE ABRIL", kmReal: 81, kmConv: 80 },
  { origen: "COLONIA CAROYA", destino: "9 DE ABRIL", kmReal: 769, kmConv: 770 },
  { origen: "TIGRE", destino: "PILAR", kmReal: null, kmConv: 43 },
  { origen: "MORTEROS", destino: "DOCK SUD", kmReal: 654, kmConv: 655 },
  { origen: "BARRACAS", destino: "MORTEROS", kmReal: 686, kmConv: 685 },
  { origen: "MARCOS PAZ", destino: "SAN VICENTE", kmReal: 70, kmConv: 70 },
  { origen: "PORTE&#209;A", destino: "TIGRE", kmReal: 613, kmConv: 615 },
  { origen: "CAMPANA", destino: "TAPIALES", kmReal: 88, kmConv: 90 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "9 DE ABRIL", kmReal: 9, kmConv: 10 },
  { origen: "RECREO", destino: "ITUZAINGO", kmReal: 483, kmConv: 485 },
  { origen: "TRUJUI", destino: "ZARATE", kmReal: 90, kmConv: 90 },
  { origen: "PUERTO ESPERANZA", destino: "SAN ANDRES DE GILES", kmReal: 1195, kmConv: 1195 },
  { origen: "VILLA MAIPU", destino: "VILLA SOLDATI", kmReal: 36, kmConv: 35 },
  { origen: "JOSE C. PAZ", destino: "MORENO", kmReal: 41, kmConv: 40 },
  { origen: "RECREO", destino: "VILLA SOLDATI", kmReal: 487, kmConv: 485 },
  { origen: "EZEIZA", destino: "CHIVILCOY", kmReal: 192, kmConv: 190 },
  { origen: "PUERTO PIRAY", destino: "LOMAS DEL MIRADOR", kmReal: 1195, kmConv: 1195 },
  { origen: "HURLINGHAM", destino: "SAN ANDRES DE GILES", kmReal: 86, kmConv: 85 },
  { origen: "PUERTO PIRAY", destino: "HURLINGHAM", kmReal: 1161, kmConv: 1160 },
  { origen: "COLONIA CAROYA", destino: "DON TORCUATO", kmReal: 714, kmConv: 715 },
  { origen: "TIO PUJIO", destino: "MORENO", kmReal: 572, kmConv: 570 },
  { origen: "MENDOZA", destino: "ZONA PORTUARIA", kmReal: 1065, kmConv: 1065 },
  { origen: "AVELLANEDA", destino: "MENDOZA", kmReal: 1053, kmConv: 1055 },
  { origen: "PUERTO PIRAY", destino: "VILLA MARIA", kmReal: 1249, kmConv: 1250 },
  { origen: "BERNAL OESTE", destino: "SUNCHALES", kmReal: 619, kmConv: 620 },
  { origen: "9 DE ABRIL", destino: "BERNAL OESTE", kmReal: 40, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "GENERAL PACHECO", kmReal: 52, kmConv: 50 },
  { origen: "CAMPANA", destino: "LANUS", kmReal: 93, kmConv: 95 },
  { origen: "PUERTO MADRYN", destino: "ZONA PORTUARIA", kmReal: 1306, kmConv: 1305 },
  { origen: "VILLA SOLDATI", destino: "PUERTO MADRYN", kmReal: 1373, kmConv: 1375 },
  { origen: "RECREO", destino: "9 DE ABRIL", kmReal: 512, kmConv: 510 },
  { origen: "PUERTO PIRAY", destino: "VILLA TESEI", kmReal: 1165, kmConv: 1165 },
  { origen: "TORTUGUITAS", destino: "VALENTIN ALSINA", kmReal: 56, kmConv: 55 },
  { origen: "DON TORCUATO", destino: "ROSARIO", kmReal: 272, kmConv: 270 },
  { origen: "DON TORCUATO", destino: "LANUS", kmReal: 45, kmConv: 45 },
  { origen: "BOSQUES", destino: "ZARATE", kmReal: 134, kmConv: 135 },
  { origen: "BELEN ESCOBAR", destino: "BOSQUES", kmReal: 98, kmConv: 100 },
  { origen: "SAN FRANCISCO", destino: "BELEN ESCOBAR", kmReal: 510, kmConv: 510 },
  { origen: "VILLA SOLDATI", destino: "SANTO TOME", kmReal: 468, kmConv: 470 },
  { origen: "FLORENCIO VARELA", destino: "VILLA SOLDATI", kmReal: 38, kmConv: 40 },
  { origen: "RECREO", destino: "PARANÁ", kmReal: 58, kmConv: 60 },
  { origen: "GRAND BOURG", destino: "ZARATE", kmReal: 66, kmConv: 65 },
  { origen: "9 DE ABRIL", destino: "ZARATE", kmReal: 127, kmConv: 130 },
  { origen: "MORENO", destino: "NAVARRO", kmReal: 84, kmConv: 84 },
  { origen: "VILLA ORTUZAR", destino: "VILLA SOLDATI", kmReal: null, kmConv: 34 },
  { origen: "FEDERAL", destino: "CORDOBA", kmReal: 586, kmConv: 585 },
  { origen: "VILLA MARIA", destino: "TORTUGUITAS", kmReal: 521, kmConv: 520 },
  { origen: "ARROYITO", destino: "GENERAL PACHECO", kmReal: 622, kmConv: 620 },
  { origen: "CORDOBA", destino: "DOCK SUD", kmReal: 713, kmConv: 715 },
  { origen: "MINAS", destino: "VILLA SOLDATI", kmReal: 657, kmConv: 655 },
  { origen: "VICENTE LOPEZ", destino: "MORENO", kmReal: 45, kmConv: 45 },
  { origen: "LA TABLADA", destino: "VILLA SOLDATI", kmReal: 13, kmConv: 15 },
  { origen: "PABLO NOGUES", destino: "VICENTE LOPEZ", kmReal: 26, kmConv: 25 },
  { origen: "MERLO", destino: "LA TABLADA", kmReal: 31, kmConv: 30 },
  { origen: "RECREO", destino: "GRAND BOURG", kmReal: 451, kmConv: 450 },
  { origen: "CONCORDIA", destino: "MORENO", kmReal: 436, kmConv: 435 },
  { origen: "ALTA GRACIA", destino: "MORENO", kmReal: 708, kmConv: 710 },
  { origen: "BERAZATEGUI", destino: "RIO SEGUNDO", kmReal: 684, kmConv: 680 },
  { origen: "AVELLANEDA", destino: "MINAS", kmReal: 654, kmConv: 650 },
  { origen: "CATRILO", destino: "RESISTENCIA", kmReal: 1262, kmConv: 1260 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "VILLA ORTUZAR", kmReal: 1545, kmConv: 1545 },
  { origen: "BECCAR", destino: "MORENO", kmReal: 37, kmConv: 35 },
  { origen: "CORDOBA", destino: "FEDERAL", kmReal: 586, kmConv: 585 },
  { origen: "GONZALEZ CATAN", destino: "BARRACAS", kmReal: 36, kmConv: 35 },
  { origen: "PILAR", destino: "AVELLANEDA", kmReal: 74, kmConv: 75 },
  { origen: "VILLA SOLDATI", destino: "SAN PEDRO", kmReal: 188, kmConv: 190 },
  { origen: "PASO DEL REY", destino: "VILLA SOLDATI", kmReal: null, kmConv: 37 },
  { origen: "EL TALAR", destino: "SAN PEDRO", kmReal: 146, kmConv: 145 },
  { origen: "ISIDRO CASANOVA", destino: "EZEIZA", kmReal: 25, kmConv: 25 },
  { origen: "ZARATE", destino: "EL TALAR", kmReal: 65, kmConv: 65 },
  { origen: "BERNAL OESTE", destino: "SAN JUSTO", kmReal: 36, kmConv: 35 },
  { origen: "SAN FRANCISCO", destino: "BERNAL OESTE", kmReal: 580, kmConv: 580 },
  { origen: "BIGAND", destino: "ROSARIO", kmReal: 69, kmConv: 70 },
  { origen: "DON TORCUATO", destino: "MORTEROS", kmReal: 640, kmConv: 640 },
  { origen: "MERCEDES", destino: "DON TORCUATO", kmReal: null, kmConv: 90 },
  { origen: "PATERNAL", destino: "BURZACO", kmReal: null, kmConv: 36 },
  { origen: "CORDOBA", destino: "MORENO", kmReal: 698, kmConv: 700 },
  { origen: "LOS LAPACHOS", destino: "MONTEVIDEO", kmReal: 1689, kmConv: 1690 },
  { origen: "CORDOBA", destino: "LOS LAPACHOS", kmReal: 881, kmConv: 880 },
  { origen: "PATERNAL", destino: "VICENTE LOPEZ", kmReal: 12, kmConv: 10 },
  { origen: "TIO PUJIO", destino: "PATERNAL", kmReal: 563, kmConv: 565 },
  { origen: "PATERNAL", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "LONGCHAMPS", destino: "PATERNAL", kmReal: 40, kmConv: 40 },
  { origen: "MORENO", destino: "BURZACO", kmReal: 74, kmConv: 75 },
  { origen: "VILLA SOLDATI", destino: "BURZACO", kmReal: 22, kmConv: 20 },
  { origen: "DOCK SUD", destino: "9 DE ABRIL", kmReal: 29, kmConv: 30 },
  { origen: "MERCEDES", destino: "BARRACAS", kmReal: 108, kmConv: 110 },
  { origen: "SUNCHALES", destino: "HURLINGHAM", kmReal: 586, kmConv: 585 },
  { origen: "SALTA", destino: "DEVOTO", kmReal: 980, kmConv: 980 },
  { origen: "TAPIALES", destino: "9 DE ABRIL", kmReal: 8, kmConv: 10 },
  { origen: "HURLINGHAM", destino: "TORTUGUITAS", kmReal: 18, kmConv: 18 },
  { origen: "MERCEDES", destino: "CHIVILCOY", kmReal: 65, kmConv: 65 },
  { origen: "9 DE ABRIL", destino: "RECREO", kmReal: 512, kmConv: 510 },
  { origen: "BERNAL OESTE", destino: "FRONTERA", kmReal: 578, kmConv: 580 },
  { origen: "VICENTE LOPEZ", destino: "BERNAL OESTE", kmReal: 33, kmConv: 35 },
  { origen: "VILLA MARIA", destino: "CAMPANA", kmReal: 475, kmConv: 475 },
  { origen: "CAMPANA", destino: "VILLA MARIA", kmReal: 477, kmConv: 480 },
  { origen: "BERAZATEGUI", destino: "VILLA MERCEDES", kmReal: 776, kmConv: 775 },
  { origen: "VILLA SOLDATI", destino: "BERAZATEGUI", kmReal: 40, kmConv: 40 },
  { origen: "VILLA CA&#209;AS", destino: "CORDOBA", kmReal: 450, kmConv: 450 },
  { origen: "LAS VARILLAS", destino: "SAN FRANCISCO", kmReal: 82, kmConv: 80 },
  { origen: "SANTA FE", destino: "RECREO", kmReal: 17, kmConv: 20 },
  { origen: "MAR DEL PLATA", destino: "BARRACAS", kmReal: 415, kmConv: 415 },
  { origen: "CORDOBA", destino: "VILLA CA&#209;AS", kmReal: 451, kmConv: 450 },
  { origen: "TAPIALES", destino: "EZEIZA", kmReal: 19, kmConv: 20 },
  { origen: "TIO PUJIO", destino: "BURZACO", kmReal: 593, kmConv: 595 },
  { origen: "ZONA PORTUARIA", destino: "BERAZATEGUI", kmReal: 32, kmConv: 30 },
  { origen: "SAN JUSTO", destino: "TAPIALES", kmReal: 9, kmConv: 10 },
  { origen: "WILDE", destino: "ZARATE", kmReal: 108, kmConv: 110 },
  { origen: "PASO DEL REY", destino: "ZARATE", kmReal: 93, kmConv: 95 },
  { origen: "PILAR", destino: "LANUS", kmReal: 71, kmConv: 70 },
  { origen: "GALVEZ", destino: "SANTA FE", kmReal: 88, kmConv: 90 },
  { origen: "GALVEZ", destino: "DON TORCUATO", kmReal: 401, kmConv: 400 },
  { origen: "DEVOTO", destino: "GALVEZ", kmReal: 159, kmConv: 160 },
  { origen: "PUEBLO ESTHER", destino: "ZONA PORTUARIA", kmReal: 286, kmConv: 290 },
  { origen: "ZONA PORTUARIA", destino: "PUEBLO ESTHER", kmReal: 286, kmConv: 290 },
  { origen: "FLORENCIO VARELA", destino: "ZARATE", kmReal: 117, kmConv: 120 },
  { origen: "TORTUGUITAS", destino: "ZARATE", kmReal: 60, kmConv: 60 },
  { origen: "ITUZAINGO", destino: "ZARATE", kmReal: 92, kmConv: 90 },
  { origen: "UDAONDO", destino: "TAPIALES", kmReal: 29, kmConv: 30 },
  { origen: "LEANDRO N ALEM", destino: "SANTA ANA", kmReal: 39, kmConv: 40 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "CORDOBA", kmReal: 725, kmConv: 725 },
  { origen: "VILLA SOLDATI", destino: "ESTEBAN ECHEVERRIA", kmReal: 31, kmConv: 30 },
  { origen: "GENERAL PACHECO", destino: "LANUS", kmReal: 50, kmConv: 50 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "GENERAL RODRIGUEZ", kmReal: 70, kmConv: 70 },
  { origen: "BARRACAS", destino: "RIO SEGUNDO", kmReal: 663, kmConv: 665 },
  { origen: "LANUS", destino: "MORENO", kmReal: 43, kmConv: 45 },
  { origen: "UDAONDO", destino: "9 DE ABRIL", kmReal: 28, kmConv: 30 },
  { origen: "RECREO", destino: "VICENTE LOPEZ", kmReal: 471, kmConv: 470 },
  { origen: "PARANÁ", destino: "RECREO", kmReal: 57, kmConv: 60 },
  { origen: "CONCORDIA", destino: "ITUZAINGO", kmReal: 431, kmConv: 430 },
  { origen: "LAFERRERE", destino: "GENERAL LAS HERAS", kmReal: 85, kmConv: 85 },
  { origen: "ELDORADO", destino: "PUERTO PIRAY", kmReal: null, kmConv: 20 },
  { origen: "25 DE MAYO", destino: "PUERTO PIRAY", kmReal: 17, kmConv: 17 },
  { origen: "LOMAS DEL MIRADOR", destino: "VILLA LUZURIAGA", kmReal: 7, kmConv: 7 },
  { origen: "BECCAR", destino: "BURZACO", kmReal: 69, kmConv: 70 },
  { origen: "CORDOBA", destino: "LOMAS DEL MIRADOR", kmReal: 696, kmConv: 700 },
  { origen: "SAN FRANCISCO", destino: "FLORENCIO VARELA", kmReal: 589, kmConv: 590 },
  { origen: "RAFAELA", destino: "LEANDRO N ALEM", kmReal: 902, kmConv: 905 },
  { origen: "TORTUGUITAS", destino: "SAN JUSTO", kmReal: 48, kmConv: 50 },
  { origen: "SALTA", destino: "RAFAELA", kmReal: 929, kmConv: 930 },
  { origen: "VILLA SOLDATI", destino: "RIO CUARTO", kmReal: 609, kmConv: 610 },
  { origen: "EL JAGUEL", destino: "TORTUGUITAS", kmReal: 71, kmConv: 70 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "LAFERRERE", kmReal: 1580, kmConv: 1580 },
  { origen: "HURLINGHAM", destino: "ZARATE", kmReal: 79, kmConv: 80 },
  { origen: "MORENO", destino: "GENERAL RODRIGUEZ", kmReal: 17, kmConv: 17 },
  { origen: "RECREO", destino: "EL JAGUEL", kmReal: 507, kmConv: 510 },
  { origen: "CA&#209;UELAS", destino: "SANTA FE", kmReal: 497, kmConv: 500 },
  { origen: "PASO DEL REY", destino: "CA&#209;UELAS", kmReal: 53, kmConv: 55 },
  { origen: "MATADEROS", destino: "BURZACO", kmReal: 31, kmConv: 31 },
  { origen: "MORENO", destino: "PILAR", kmReal: 31, kmConv: 31 },
  { origen: "VILLA MARTELLI", destino: "VILLA SOLDATI", kmReal: 31, kmConv: 31 },
  { origen: "TRUJUI", destino: "PILAR", kmReal: null, kmConv: 26 },
  { origen: "GARIN", destino: "TORTUGUITAS", kmReal: null, kmConv: 10 },
  { origen: "SAN FRANCISCO", destino: "PASO DEL REY", kmReal: 608, kmConv: 610 },
  { origen: "ROSARIO", destino: "VILLA MARTELLI", kmReal: 286, kmConv: 290 },
  { origen: "MENDOZA", destino: "HURLINGHAM", kmReal: 1029, kmConv: 1030 },
  { origen: "SUSANA", destino: "MATADEROS", kmReal: 530, kmConv: 530 },
  { origen: "RECREO", destino: "SUSANA", kmReal: 124, kmConv: 124 },
  { origen: "TAPIALES", destino: "DON TORCUATO", kmReal: 51, kmConv: 50 },
  { origen: "GENERAL LAS HERAS", destino: "CORDOBA", kmReal: 710, kmConv: 710 },
  { origen: "MERCEDES", destino: "GENERAL LAS HERAS", kmReal: 80, kmConv: 80 },
  { origen: "CAMPANA", destino: "GARIN", kmReal: null, kmConv: 40 },
  { origen: "ZARATE", destino: "VILLA REGINA", kmReal: 1134, kmConv: 1035 },
  { origen: "MORENO", destino: "TAPIALES", kmReal: 55, kmConv: 55 },
  { origen: "ZARATE", destino: "TORTUGUITAS", kmReal: 67, kmConv: 65 },
  { origen: "SARANDI", destino: "SAN JORGE", kmReal: 484, kmConv: 485 },
  { origen: "MORENO", destino: "VILLA MARIA", kmReal: 556, kmConv: 555 },
  { origen: "JOSE C. PAZ", destino: "PILAR", kmReal: 20, kmConv: 20 },
  { origen: "PUERTO ESPERANZA", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1434, kmConv: 1435 },
  { origen: "CAMPO GRANDE", destino: "PUERTO ESPERANZA", kmReal: 178, kmConv: 180 },
  { origen: "CIPOLLETTI", destino: "BAHIA BLANCA", kmReal: 528, kmConv: 530 },
  { origen: "VILLA BALLESTER", destino: "VILLA SOLDATI", kmReal: 27, kmConv: 25 },
  { origen: "CORDOBA", destino: "VILLA BALLESTER", kmReal: 678, kmConv: 680 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "CONCORDIA", kmReal: 147, kmConv: 150 },
  { origen: "VILLA ASCASUBI", destino: "DOCK SUD", kmReal: 673, kmConv: 670 },
  { origen: "SARANDI", destino: "VILLA ASCASUBI", kmReal: 675, kmConv: 675 },
  { origen: "GONZALEZ CATAN", destino: "VILLA SOLDATI", kmReal: 25, kmConv: 25 },
  { origen: "MORENO", destino: "BECCAR", kmReal: 37, kmConv: 35 },
  { origen: "TUCUMAN", destino: "CORDOBA", kmReal: 570, kmConv: 570 },
  { origen: "PILAR", destino: "TORTUGUITAS", kmReal: 22, kmConv: 20 },
  { origen: "LA PLATA", destino: "DON TORCUATO", kmReal: 88, kmConv: 90 },
  { origen: "VICENTE LOPEZ", destino: "CAMPANA", kmReal: 71, kmConv: 70 },
  { origen: "SASTRE", destino: "DEVOTO", kmReal: 99, kmConv: 100 },
  { origen: "BAHIA BLANCA", destino: "FLORENCIO VARELA", kmReal: 645, kmConv: 645 },
  { origen: "DON TORCUATO", destino: "MORENO", kmReal: 51, kmConv: 50 },
  { origen: "SIERRA DE LOS PADRES", destino: "PARANÁ", kmReal: 903, kmConv: 900 },
  { origen: "EZEIZA", destino: "LANUS", kmReal: 33, kmConv: 35 },
  { origen: "TRUJUI", destino: "VILLA SOLDATI", kmReal: 37, kmConv: 35 },
  { origen: "MAR DEL PLATA", destino: "VILLA SOLDATI", kmReal: 426, kmConv: 425 },
  { origen: "VILLA SOLDATI", destino: "DESVIO ARIJON", kmReal: 427, kmConv: 425 },
  { origen: "BERAZATEGUI", destino: "VILLA SOLDATI", kmReal: 42, kmConv: 40 },
  { origen: "ZARATE", destino: "DON TORCUATO", kmReal: 70, kmConv: 70 },
  { origen: "DOCK SUD", destino: "GOBERNADOR CRESPO", kmReal: 625, kmConv: 625 },
  { origen: "GENERAL PACHECO", destino: "SAN JUSTO", kmReal: 39, kmConv: 40 },
  { origen: "JACINTO ARAUZ", destino: "MORENO", kmReal: 703, kmConv: 705 },
  { origen: "VILLA REGINA", destino: "JACINTO ARAUZ", kmReal: 480, kmConv: 480 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN PEDRO", kmReal: 150, kmConv: 150 },
  { origen: "OLAVARRIA", destino: "SIERRA DE LOS PADRES", kmReal: 289, kmConv: 290 },
  { origen: "TANDIL", destino: "OLAVARRIA", kmReal: 135, kmConv: 135 },
  { origen: "CIPOLLETTI", destino: "TANDIL", kmReal: 898, kmConv: 900 },
  { origen: "SAN FRANCISCO SOLANO", destino: "GENERAL RODRIGUEZ", kmReal: 79, kmConv: 80 },
  { origen: "ESCOBAR", destino: "CIPOLLETTI", kmReal: 1163, kmConv: 1160 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "MUNRO", kmReal: 48, kmConv: 50 },
  { origen: "TRUJUI", destino: "ESCOBAR", kmReal: 53, kmConv: 55 },
  { origen: "SANTA FE", destino: "ROSARIO", kmReal: 173, kmConv: 175 },
  { origen: "VILLA SOLDATI", destino: "SANTA FE", kmReal: 485, kmConv: 485 },
  { origen: "AVELLANEDA", destino: "ROSARIO", kmReal: 307, kmConv: 310 },
  { origen: "LA PLATA", destino: "AVELLANEDA", kmReal: 53, kmConv: 55 },
  { origen: "MERCEDES", destino: "LUJAN", kmReal: 36, kmConv: 36 },
  { origen: "JOSE LEON SUAREZ", destino: "CORDOBA", kmReal: 677, kmConv: 675 },
  { origen: "ISIDRO CASANOVA", destino: "JOSE LEON SUAREZ", kmReal: 59, kmConv: 60 },
  { origen: "GENERAL PACHECO", destino: "PILAR", kmReal: 31, kmConv: 30 },
  { origen: "LOMAS DEL MIRADOR", destino: "VILLA SOLDATI", kmReal: null, kmConv: 13 },
  { origen: "ZONA PORTUARIA", destino: "SANTO TOME", kmReal: 455, kmConv: 455 },
  { origen: "PUEBLO ESTHER", destino: "MONTEVIDEO", kmReal: 624, kmConv: 625 },
  { origen: "BURZACO", destino: "PUEBLO ESTHER", kmReal: 328, kmConv: 330 },
  { origen: "DON TORCUATO", destino: "CORDOBA", kmReal: 669, kmConv: 670 },
  { origen: "SAN JUSTO", destino: "BARRACAS", kmReal: 27, kmConv: 27 },
  { origen: "HAEDO", destino: "VILLA SOLDATI", kmReal: 17, kmConv: 15 },
  { origen: "MENDOZA", destino: "HAEDO", kmReal: 1027, kmConv: 1030 },
  { origen: "PUERTO PIRAY", destino: "ESPERANZA", kmReal: 994, kmConv: 995 },
  { origen: "CORDOBA", destino: "UDAONDO", kmReal: 694, kmConv: 695 },
  { origen: "ARROYITO", destino: "EZEIZA", kmReal: 695, kmConv: 695 },
  { origen: "FREYRE", destino: "ITUZAINGO", kmReal: 631, kmConv: 630 },
  { origen: "CONCORDIA", destino: "EZEIZA", kmReal: 454, kmConv: 455 },
  { origen: "VILLA URQUIZA", destino: "SAN FRANCISCO", kmReal: 550, kmConv: 550 },
  { origen: "MONTE GRANDE", destino: "VILLA URQUIZA", kmReal: 42, kmConv: 40 },
  { origen: "JOSE C. PAZ", destino: "TORTUGUITAS", kmReal: 6, kmConv: 5 },
  { origen: "VILLA URQUIZA", destino: "MORENO", kmReal: 34, kmConv: 35 },
  { origen: "OBERA", destino: "PUERTO ESPERANZA", kmReal: 216, kmConv: 215 },
  { origen: "CORDOBA", destino: "PUEBLO ESTHER", kmReal: 420, kmConv: 420 },
  { origen: "SAN FRANCISCO", destino: "SANTA FE", kmReal: 143, kmConv: 145 },
  { origen: "VILLA SOLDATI", destino: "CIUDADELA", kmReal: 13, kmConv: 15 },
  { origen: "RIO COLORADO", destino: "VILLA SOLDATI", kmReal: 801, kmConv: 800 },
  { origen: "BAHIA BLANCA", destino: "LOMAS DEL MIRADOR", kmReal: 626, kmConv: 625 },
  { origen: "CATRIEL", destino: "BAHIA BLANCA", kmReal: 593, kmConv: 595 },
  { origen: "VILLA SOLDATI", destino: "JOSE C. PAZ", kmReal: 45, kmConv: 45 },
  { origen: "CONCARAN", destino: "VILLA SOLDATI", kmReal: 776, kmConv: 775 },
  { origen: "NASCHEL", destino: "CONCARAN", kmReal: 48, kmConv: 50 },
  { origen: "AZUL", destino: "SAN FRANCISCO", kmReal: 774, kmConv: 775 },
  { origen: "PUERTO ESPERANZA", destino: "VILLA SOLDATI", kmReal: 1231, kmConv: 1230 },
  { origen: "TRUJUI", destino: "AVELLANEDA", kmReal: 45, kmConv: 45 },
  { origen: "DESVIO ARIJON", destino: "DOCK SUD", kmReal: 427, kmConv: 425 },
  { origen: "VILLA BALLESTER", destino: "GENERAL RODRIGUEZ", kmReal: 41, kmConv: 40 },
  { origen: "SAN FRANCISCO", destino: "VILLA BALLESTER", kmReal: 545, kmConv: 545 },
  { origen: "EZEIZA", destino: "BARADERO", kmReal: 190, kmConv: 190 },
  { origen: "VILLA SOLDATI", destino: "AZUL", kmReal: 293, kmConv: 295 },
  { origen: "CORONEL BRANDSEN", destino: "ZARATE", kmReal: 175, kmConv: 175 },
  { origen: "NEUQUEN", destino: "CIPOLLETTI", kmReal: 7, kmConv: 10 },
  { origen: "VICENTE LOPEZ", destino: "EL TALAR", kmReal: 22, kmConv: 20 },
  { origen: "CORDOBA", destino: "GENERAL PACHECO", kmReal: 663, kmConv: 665 },
  { origen: "OBERA", destino: "APÓSTOLES", kmReal: 99, kmConv: 100 },
  { origen: "CAMPANA", destino: "ZARATE", kmReal: null, kmConv: 19 },
  { origen: "ELORTONDO", destino: "ROSARIO", kmReal: 136, kmConv: 136 },
  { origen: "SARANDI", destino: "VILLA SOLDATI", kmReal: null, kmConv: 19 },
  { origen: "BIGAND", destino: "RAFAELA", kmReal: 281, kmConv: 280 },
  { origen: "PILAR", destino: "TAPIALES", kmReal: 65, kmConv: 65 },
  { origen: "TIO PUJIO", destino: "PILAR", kmReal: 532, kmConv: 530 },
  { origen: "GOBERNADOR VIRASORO", destino: "SARANDI", kmReal: 918, kmConv: 920 },
  { origen: "MATADEROS", destino: "CATRIEL", kmReal: 1033, kmConv: 1035 },
  { origen: "TAPIALES", destino: "MATADEROS", kmReal: null, kmConv: 10 },
  { origen: "SAUCE VIEJO", destino: "ZONA PORTUARIA", kmReal: 443, kmConv: 443 },
  { origen: "BARRACAS", destino: "SAUCE VIEJO", kmReal: 452, kmConv: 452 },
  { origen: "MONTE GRANDE", destino: "LANUS", kmReal: 46, kmConv: 45 },
  { origen: "MERCEDES", destino: "AVELLANEDA", kmReal: 110, kmConv: 110 },
  { origen: "SAN JORGE", destino: "RAFAELA", kmReal: 103, kmConv: 103 },
  { origen: "FLORENCIO VARELA", destino: "CORDOBA", kmReal: 723, kmConv: 725 },
  { origen: "CORDOBA", destino: "BIGAND", kmReal: 390, kmConv: 390 },
  { origen: "DON TORCUATO", destino: "BURZACO", kmReal: 69, kmConv: 70 },
  { origen: "VILLA MAIPU", destino: "CORDOBA", kmReal: 686, kmConv: 686 },
  { origen: "VILLA SOLDATI", destino: "VILLA MAIPU", kmReal: 36, kmConv: 35 },
  { origen: "PILAR", destino: "BURZACO", kmReal: 99, kmConv: 100 },
  { origen: "MERLO", destino: "VILLA SOLDATI", kmReal: null, kmConv: 36 },
  { origen: "CORDOBA", destino: "TAPIALES", kmReal: 704, kmConv: 705 },
  { origen: "TIO PUJIO", destino: "AVELLANEDA", kmReal: 580, kmConv: 580 },
  { origen: "ITUZAINGO", destino: "BURZACO", kmReal: 46, kmConv: 45 },
  { origen: "BELLA ITALIA", destino: "ITUZAINGO", kmReal: 548, kmConv: 550 },
  { origen: "CONCORDIA", destino: "TAPIALES", kmReal: 451, kmConv: 450 },
  { origen: "AVELLANEDA", destino: "CORDOBA", kmReal: 703, kmConv: 705 },
  { origen: "VILLA SOLDATI", destino: "AVELLANEDA", kmReal: null, kmConv: 5 },
  { origen: "BECCAR", destino: "TORTUGUITAS", kmReal: 26, kmConv: 26 },
  { origen: "SARANDI", destino: "VILLA MERCEDES", kmReal: 708, kmConv: 710 },
  { origen: "VILLA SOLDATI", destino: "SARANDI", kmReal: 18, kmConv: 20 },
  { origen: "SAN JORGE", destino: "MUNRO", kmReal: 477, kmConv: 475 },
  { origen: "SAN FERNANDO", destino: "LOMA HERMOSA", kmReal: 21, kmConv: 20 },
  { origen: "TIO PUJIO", destino: "SAN FERNANDO", kmReal: 553, kmConv: 555 },
  { origen: "FREYRE", destino: "LOMAS DE ZAMORA", kmReal: 637, kmConv: 635 },
  { origen: "LANUS", destino: "TAPIALES", kmReal: 22, kmConv: 20 },
  { origen: "UDAONDO", destino: "CAMPANA", kmReal: 83, kmConv: 85 },
  { origen: "MADARIAGA", destino: "VILLA SOLDATI", kmReal: 337, kmConv: 340 },
  { origen: "CIUDADELA", destino: "MORENO", kmReal: 34, kmConv: 35 },
  { origen: "SAN JORGE", destino: "LANUS", kmReal: 508, kmConv: 510 },
  { origen: "ITUZAINGO", destino: "GENERAL RODRIGUEZ", kmReal: 28, kmConv: 30 },
  { origen: "TAPIALES", destino: "GARIN", kmReal: 64, kmConv: 65 },
  { origen: "BARRACAS", destino: "VILLA SOLDATI", kmReal: 7, kmConv: 7 },
  { origen: "HUMBOLDT", destino: "RAFAELA", kmReal: 44, kmConv: 44 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "HUMBOLDT", kmReal: 345, kmConv: 345 },
  { origen: "CONCORDIA", destino: "CONCEPCION DEL URUGUAY", kmReal: 148, kmConv: 148 },
  { origen: "DON TORCUATO", destino: "PILAR", kmReal: 32, kmConv: 32 },
  { origen: "SALTA", destino: "COLONIA CAROYA", kmReal: 825, kmConv: 825 },
  { origen: "PUERTO PIRAY", destino: "CRESPO", kmReal: 933, kmConv: 933 },
  { origen: "MORENO", destino: "SAN ANDRES DE GILES", kmReal: 67, kmConv: 65 },
  { origen: "TIO PUJIO", destino: "QUILMES", kmReal: 623, kmConv: 625 },
  { origen: "RAFAELA", destino: "MORENO", kmReal: 544, kmConv: 545 },
  { origen: "CHACARITA", destino: "MUNRO", kmReal: 11, kmConv: 10 },
  { origen: "VILLA SOLDATI", destino: "CHASCOMUS", kmReal: 136, kmConv: 136 },
  { origen: "VILLA URQUIZA", destino: "TORTUGUITAS", kmReal: 34, kmConv: 34 },
  { origen: "CIPOLLETTI", destino: "LUJAN", kmReal: 1064, kmConv: 1065 },
  { origen: "WILDE", destino: "GENERAL RODRIGUEZ", kmReal: 71, kmConv: 70 },
  { origen: "LA PLATA", destino: "TORTUGUITAS", kmReal: 102, kmConv: 100 },
  { origen: "SAN JUSTO", destino: "FLORENCIO VARELA", kmReal: 38, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "SAN JUSTO", kmReal: 17, kmConv: 15 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN JUSTO", kmReal: 42, kmConv: 42 },
  { origen: "ZONA PORTUARIA", destino: "SARANDI", kmReal: 14, kmConv: 14 },
  { origen: "AROCENA", destino: "SAN JORGE", kmReal: 173, kmConv: 175 },
  { origen: "PARANÁ", destino: "AROCENA", kmReal: 93, kmConv: 95 },
  { origen: "SAN JUSTO", destino: "BURZACO", kmReal: 24, kmConv: 25 },
  { origen: "TIO PUJIO", destino: "SAN JUSTO", kmReal: 599, kmConv: 600 },
  { origen: "DON TORCUATO", destino: "GARIN", kmReal: 16, kmConv: 15 },
  { origen: "QUILMES", destino: "TAPIALES", kmReal: 36, kmConv: 35 },
  { origen: "MONTE GRANDE", destino: "DOCK SUD", kmReal: 43, kmConv: 43 },
  { origen: "LOMAS DE ZAMORA", destino: "EL JAGUEL", kmReal: 15, kmConv: 15 },
  { origen: "EL JAGUEL", destino: "VILLA SOLDATI", kmReal: 30, kmConv: 30 },
  { origen: "CHACABUCO", destino: "SAN ANDRES DE GILES", kmReal: 107, kmConv: 107 },
  { origen: "RAFAELA", destino: "CHACABUCO", kmReal: 477, kmConv: 477 },
  { origen: "LA PLATA", destino: "BERNAL OESTE", kmReal: null, kmConv: 45 },
  { origen: "ARIAS", destino: "SAN FRANCISCO", kmReal: 333, kmConv: 335 },
  { origen: "ROSARIO", destino: "ARIAS", kmReal: 210, kmConv: 210 },
  { origen: "PUERTO ESPERANZA", destino: "ESPERANZA", kmReal: 1047, kmConv: 1045 },
  { origen: "EZEIZA", destino: "VILLA SOLDATI", kmReal: 28, kmConv: 30 },
  { origen: "SAN JORGE", destino: "DON TORCUATO", kmReal: 466, kmConv: 465 },
  { origen: "AVELLANEDA", destino: "ZARATE", kmReal: 97, kmConv: 95 },
  { origen: "SAN JORGE", destino: "LOMAS DE ZAMORA", kmReal: 522, kmConv: 520 },
  { origen: "BECCAR", destino: "VALENTIN ALSINA", kmReal: 39, kmConv: 39 },
  { origen: "WILDE", destino: "EL JAGUEL", kmReal: 24, kmConv: 25 },
  { origen: "MENDOZA", destino: "MORENO", kmReal: 1009, kmConv: 1010 },
  { origen: "EZEIZA", destino: "CORDOBA", kmReal: 736, kmConv: 735 },
  { origen: "VILLA SOLDATI", destino: "EZEIZA", kmReal: 28, kmConv: 30 },
  { origen: "LONGCHAMPS", destino: "ZARATE", kmReal: 133, kmConv: 135 },
  { origen: "VILLA CRESPO", destino: "ZARATE", kmReal: 88, kmConv: 90 },
  { origen: "FRONTERA", destino: "GENERAL RODRIGUEZ", kmReal: 557, kmConv: 557 },
  { origen: "RECREO", destino: "ZONA PORTUARIA", kmReal: 480, kmConv: 480 },
  { origen: "DOCK SUD", destino: "RECREO", kmReal: 490, kmConv: 490 },
  { origen: "MASCHWITZ", destino: "VILLA SOLDATI", kmReal: 63, kmConv: 63 },
  { origen: "CARLOS SPEGAZZINI", destino: "TORTUGUITAS", kmReal: 97, kmConv: 95 },
  { origen: "BURZACO", destino: "MORENO", kmReal: 74, kmConv: 75 },
  { origen: "PABLO NOGUES", destino: "TORTUGUITAS", kmReal: 7, kmConv: 5 },
  { origen: "CAMPANA", destino: "VILLA LUGANO", kmReal: 94, kmConv: 94 },
  { origen: "PUERTO PIRAY", destino: "WILDE", kmReal: 1188, kmConv: 1188 },
  { origen: "FAMAILLA", destino: "RAFAELA", kmReal: 663, kmConv: 665 },
  { origen: "CORDOBA", destino: "BURZACO", kmReal: 737, kmConv: 735 },
  { origen: "MONTEVIDEO", destino: "VILLA SOLDATI", kmReal: 590, kmConv: 590 },
  { origen: "MONTEVIDEO", destino: "TORTUGUITAS", kmReal: 543, kmConv: 545 },
  { origen: "SUNCHALES", destino: "DOCK SUD", kmReal: 619, kmConv: 620 },
  { origen: "DON TORCUATO", destino: "TORTUGUITAS", kmReal: 17, kmConv: 15 },
  { origen: "GOBERNADOR CRESPO", destino: "DOCK SUD", kmReal: 624, kmConv: 625 },
  { origen: "ZONA PORTUARIA", destino: "GOBERNADOR CRESPO", kmReal: 615, kmConv: 615 },
  { origen: "RECREO", destino: "DOCK SUD", kmReal: 490, kmConv: 490 },
  { origen: "ZONA PORTUARIA", destino: "RECREO", kmReal: 479, kmConv: 480 },
  { origen: "ELDORADO", destino: "GOBERNADOR VIRASORO", kmReal: 272, kmConv: 270 },
  { origen: "CONCORDIA", destino: "MASCHWITZ", kmReal: 385, kmConv: 385 },
  { origen: "LOMA HERMOSA", destino: "ZARATE", kmReal: 84, kmConv: 85 },
  { origen: "MORTEROS", destino: "ZONA PORTUARIA", kmReal: 643, kmConv: 645 },
  { origen: "SANTO TOME", destino: "DESVIO ARIJON", kmReal: 26, kmConv: 26 },
  { origen: "TORTUGUITAS", destino: "POSADAS", kmReal: 971, kmConv: 970 },
  { origen: "DOCK SUD", destino: "SANTO TOME", kmReal: 464, kmConv: 464 },
  { origen: "TORTUGUITAS", destino: "ELDORADO", kmReal: 1150, kmConv: 1150 },
  { origen: "VILLA URQUIZA", destino: "GENERAL RODRIGUEZ", kmReal: 50, kmConv: 50 },
  { origen: "VILLA DEL PARQUE", destino: "VILLA SOLDATI", kmReal: 9, kmConv: 9 },
  { origen: "BAHIA BLANCA", destino: "LOMA HERMOSA", kmReal: 642, kmConv: 640 },
  { origen: "NEUQUEN", destino: "BAHIA BLANCA", kmReal: 534, kmConv: 535 },
  { origen: "BECCAR", destino: "BARRACAS", kmReal: 34, kmConv: 35 },
  { origen: "GENERAL PACHECO", destino: "TORTUGUITAS", kmReal: 15, kmConv: 15 },
  { origen: "ANGUIL", destino: "TORTUGUITAS", kmReal: 576, kmConv: 576 },
  { origen: "BERNAL OESTE", destino: "VILLA SOLDATI", kmReal: 30, kmConv: 30 },
  { origen: "CORDOBA", destino: "BERNAL OESTE", kmReal: 715, kmConv: 715 },
  { origen: "CARCARA&#209;A", destino: "TORTUGUITAS", kmReal: 313, kmConv: 315 },
  { origen: "CORDOBA", destino: "CARCARA&#209;A", kmReal: 360, kmConv: 360 },
  { origen: "CAMPANA", destino: "VILLA SOLDATI", kmReal: 94, kmConv: 95 },
  { origen: "TIO PUJIO", destino: "VILLA SOLDATI", kmReal: 587, kmConv: 590 },
  { origen: "SAN ANDRES DE GILES", destino: "VILLA MARIA", kmReal: 480, kmConv: 480 },
  { origen: "CAMPO GRANDE", destino: "PUERTO PIRAY", kmReal: 124, kmConv: 124 },
  { origen: "VILLA SOLDATI", destino: "GARIN", kmReal: 59, kmConv: 60 },
  { origen: "CORDOBA", destino: "DON TORCUATO", kmReal: 668, kmConv: 670 },
  { origen: "LA PLATA", destino: "LANUS", kmReal: 60, kmConv: 60 },
  { origen: "VERSALLES", destino: "VILLA SOLDATI", kmReal: 9, kmConv: 9 },
  { origen: "CORDOBA", destino: "LA PLATA", kmReal: 753, kmConv: 755 },
  { origen: "MORENO", destino: "CARCARA&#209;A", kmReal: 352, kmConv: 350 },
  { origen: "MONTE GRANDE", destino: "EZEIZA", kmReal: 8, kmConv: 10 },
  { origen: "EZEIZA", destino: "BELL VILLE", kmReal: 572, kmConv: 570 },
  { origen: "GOBERNADOR CRESPO", destino: "ZONA PORTUARIA", kmReal: 615, kmConv: 615 },
  { origen: "CORDOBA", destino: "GOBERNADOR CRESPO", kmReal: 520, kmConv: 520 },
  { origen: "VILLA SOLDATI", destino: "ZONA PORTUARIA", kmReal: 14, kmConv: 14 },
  { origen: "CAMPANA", destino: "VILLA LUZURIAGA", kmReal: 86, kmConv: 86 },
  { origen: "GENERAL PACHECO", destino: "GARIN", kmReal: 13, kmConv: 13 },
  { origen: "GUALEGUAYCHU", destino: "SANTA FE", kmReal: 318, kmConv: 318 },
  { origen: "ITUZAINGO", destino: "TORTUGUITAS", kmReal: 47, kmConv: 50 },
  { origen: "ZONA PORTUARIA", destino: "VILLA MERCEDES", kmReal: 716, kmConv: 716 },
  { origen: "RECREO", destino: "FRANCK", kmReal: 36, kmConv: 35 },
  { origen: "LOMA HERMOSA", destino: "TAPIALES", kmReal: 25, kmConv: 25 },
  { origen: "VILLA LUZURIAGA", destino: "CORDOBA", kmReal: 700, kmConv: 700 },
  { origen: "VILLA SOLDATI", destino: "VILLA LUZURIAGA", kmReal: 21, kmConv: 21 },
  { origen: "CONCORDIA", destino: "VILLA SOLDATI", kmReal: 445, kmConv: 445 },
  { origen: "MANUEL OCAMPO", destino: "ROSARIO", kmReal: 134, kmConv: 134 },
  { origen: "CIPOLLETTI", destino: "MANUEL OCAMPO", kmReal: 1109, kmConv: 1109 },
  { origen: "VILLA SOLDATI", destino: "EL JAGUEL", kmReal: 27, kmConv: 28 },
  { origen: "POSADAS", destino: "PUERTO ESPERANZA", kmReal: 255, kmConv: 255 },
  { origen: "AROCENA", destino: "SAN FRANCISCO", kmReal: 158, kmConv: 160 },
  { origen: "VILLA URQUIZA", destino: "VILLA SOLDATI", kmReal: 31, kmConv: 31 },
  { origen: "VILLA SOLDATI", destino: "CAMPANA", kmReal: 98, kmConv: 100 },
  { origen: "MENDOZA", destino: "ITUZAINGO", kmReal: 1020, kmConv: 1020 },
  { origen: "TIO PUJIO", destino: "LOMA HERMOSA", kmReal: 557, kmConv: 555 },
  { origen: "TAPIALES", destino: "VILLA MARIA", kmReal: 573, kmConv: 575 },
  { origen: "VILLA SOLDATI", destino: "ROSARIO", kmReal: 316, kmConv: 315 },
  { origen: "SANTA TERESITA", destino: "VILLA SOLDATI", kmReal: 354, kmConv: 354 },
  { origen: "BECCAR", destino: "VILLA SOLDATI", kmReal: 44, kmConv: 45 },
  { origen: "SAN FRANCISCO", destino: "DON TORCUATO", kmReal: 534, kmConv: 535 },
  { origen: "PABLO NOGUES", destino: "LANUS", kmReal: 54, kmConv: 55 },
  { origen: "RIO SEGUNDO", destino: "TIO PUJIO", kmReal: 94, kmConv: 95 },
  { origen: "ROSARIO", destino: "SALTO GRANDE", kmReal: 54, kmConv: 55 },
  { origen: "SALTO GRANDE", destino: "DON TORCUATO", kmReal: 322, kmConv: 320 },
  { origen: "DEVOTO", destino: "SALTO GRANDE", kmReal: 228, kmConv: 230 },
  { origen: "MUNRO", destino: "AVELLANEDA", kmReal: 26, kmConv: 25 },
  { origen: "GENERAL PACHECO", destino: "GENERAL RODRIGUEZ", kmReal: 36, kmConv: 36 },
  { origen: "ZONA PORTUARIA", destino: "TAPIALES", kmReal: 23, kmConv: 25 },
  { origen: "TORTUGUITAS", destino: "BARADERO", kmReal: 121, kmConv: 120 },
  { origen: "ISIDRO CASANOVA", destino: "VICENTE LOPEZ", kmReal: 45, kmConv: 45 },
  { origen: "QUILMES", destino: "VILLA SOLDATI", kmReal: 25, kmConv: 25 },
  { origen: "MUNRO", destino: "QUILMES", kmReal: 48, kmConv: 50 },
  { origen: "RAFAELA", destino: "SAN FRANCISCO", kmReal: null, kmConv: 85 },
  { origen: "MATADEROS", destino: "CARLOS SPEGAZZINI", kmReal: 37, kmConv: 37 },
  { origen: "VILLA DEL PARQUE", destino: "MATADEROS", kmReal: 12, kmConv: 12 },
  { origen: "VICTORIA", destino: "RIO SEGUNDO", kmReal: 640, kmConv: 640 },
  { origen: "GENERAL PACHECO", destino: "VICTORIA", kmReal: 15, kmConv: 15 },
  { origen: "VICENTE LOPEZ", destino: "GENERAL PACHECO", kmReal: 25, kmConv: 25 },
  { origen: "DON TORCUATO", destino: "ARROYITO", kmReal: 640, kmConv: 640 },
  { origen: "TORTUGUITAS", destino: "DON TORCUATO", kmReal: 15, kmConv: 15 },
  { origen: "EL TALAR", destino: "VILLA SOLDATI", kmReal: 44, kmConv: 44 },
  { origen: "TEMPERLEY", destino: "VILLA SOLDATI", kmReal: 22, kmConv: 20 },
  { origen: "PUEBLO ESTHER", destino: "TIO PUJIO", kmReal: 298, kmConv: 300 },
  { origen: "PILAR", destino: "ROSARIO", kmReal: 258, kmConv: 260 },
  { origen: "VICENTE LOPEZ", destino: "PILAR", kmReal: 50, kmConv: 50 },
  { origen: "GENERAL PACHECO", destino: "CAMPANA", kmReal: 48, kmConv: 50 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "POSADAS", kmReal: 719, kmConv: 719 },
  { origen: "MENDOZA", destino: "CONCEPCION DEL URUGUAY", kmReal: 1218, kmConv: 1218 },
  { origen: "CIUDADELA", destino: "VILLA SOLDATI", kmReal: 11, kmConv: 11 },
  { origen: "RIO COLORADO", destino: "CIUDADELA", kmReal: 870, kmConv: 870 },
  { origen: "ZARATE", destino: "MALAGUE&#209;O", kmReal: 633, kmConv: 633 },
  { origen: "VILLA SOLDATI", destino: "NAVARRO", kmReal: 117, kmConv: 117 },
  { origen: "SAN MARTIN", destino: "TORTUGUITAS", kmReal: 27, kmConv: 27 },
  { origen: "CHACARITA", destino: "VICENTE LOPEZ", kmReal: 10, kmConv: 10 },
  { origen: "TIO PUJIO", destino: "CHACARITA", kmReal: 560, kmConv: 560 },
  { origen: "COLONIA CAROYA", destino: "GENERAL PACHECO", kmReal: 710, kmConv: 710 },
  { origen: "CHACABUCO", destino: "GENERAL RODRIGUEZ", kmReal: 163, kmConv: 165 },
  { origen: "MONTE GRANDE", destino: "CARLOS SPEGAZZINI", kmReal: 21, kmConv: 20 },
  { origen: "TIO PUJIO", destino: "MONTE GRANDE", kmReal: 612, kmConv: 610 },
  { origen: "LUIS GUILLON", destino: "VILLA SOLDATI", kmReal: 22, kmConv: 20 },
  { origen: "CONCARAN", destino: "PILAR", kmReal: 724, kmConv: 724 },
  { origen: "CHACARITA", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "CORDOBA", destino: "CHACARITA", kmReal: 688, kmConv: 690 },
  { origen: "VILLA CRESPO", destino: "CAMPANA", kmReal: 78, kmConv: 80 },
  { origen: "PUERTO PIRAY", destino: "SAN JUSTO", kmReal: 1201, kmConv: 1200 },
  { origen: "CARMEN DE ARECO", destino: "NAVARRO", kmReal: 109, kmConv: 109 },
  { origen: "PERGAMINO", destino: "NAVARRO", kmReal: 215, kmConv: 215 },
  { origen: "BAHIA BLANCA", destino: "EL TALAR", kmReal: 735, kmConv: 735 },
  { origen: "SAN JORGE", destino: "ZONA PORTUARIA", kmReal: 493, kmConv: 493 },
  { origen: "BARRACAS", destino: "SAN JORGE", kmReal: 500, kmConv: 500 },
  { origen: "DOCK SUD", destino: "BARRACAS", kmReal: 6, kmConv: 6 },
  { origen: "ZONA PORTUARIA", destino: "DESVIO ARIJON", kmReal: 430, kmConv: 430 },
  { origen: "DESVIO ARIJON", destino: "ZONA PORTUARIA", kmReal: 430, kmConv: 430 },
  { origen: "DOCK SUD", destino: "DESVIO ARIJON", kmReal: 439, kmConv: 439 },
  { origen: "HURLINGHAM", destino: "VILLA SOLDATI", kmReal: 24, kmConv: 25 },
  { origen: "LOMAS DE ZAMORA", destino: "VILLA SOLDATI", kmReal: null, kmConv: 15 },
  { origen: "MUNRO", destino: "SAN JUSTO", kmReal: null, kmConv: 25 },
  { origen: "CORDOBA", destino: "VILLA CRESPO", kmReal: 688, kmConv: 690 },
  { origen: "MUNRO", destino: "TEMPERLEY", kmReal: 37, kmConv: 35 },
  { origen: "TEMPERLEY", destino: "TORTUGUITAS", kmReal: null, kmConv: 70 },
  { origen: "MUNRO", destino: "BARADERO", kmReal: 135, kmConv: 135 },
  { origen: "VILLA MARIA", destino: "LUIS GUILLON", kmReal: 571, kmConv: 570 },
  { origen: "CAMPANA", destino: "RAFAELA", kmReal: 484, kmConv: 485 },
  { origen: "MERCEDES", destino: "TAPIALES", kmReal: 99, kmConv: 100 },
  { origen: "TORTUGUITAS", destino: "CAMPANA", kmReal: 51, kmConv: 50 },
  { origen: "GOBERNADOR VIRASORO", destino: "SAN MARTIN", kmReal: 900, kmConv: 900 },
  { origen: "SAN MARTIN", destino: "VILLA SOLDATI", kmReal: 17, kmConv: 15 },
  { origen: "FRANCK", destino: "RAFAELA", kmReal: null, kmConv: 80 },
  { origen: "GARUPA", destino: "CERRO AZUL", kmReal: null, kmConv: 55 },
  { origen: "GOBERNADOR VIRASORO", destino: "CORDOBA", kmReal: 1049, kmConv: 1050 },
  { origen: "GARUPA", destino: "GOBERNADOR VIRASORO", kmReal: null, kmConv: 80 },
  { origen: "BECCAR", destino: "SAN JUSTO", kmReal: null, kmConv: 35 },
  { origen: "BARRACAS", destino: "CORDOBA", kmReal: 701, kmConv: 700 },
  { origen: "PUERTO MADERO", destino: "CAMPANA", kmReal: null, kmConv: 85 },
  { origen: "TRUJUI", destino: "TORTUGUITAS", kmReal: null, kmConv: 15 },
  { origen: "VILLA URQUIZA", destino: "NAVARRO", kmReal: 118, kmConv: 120 },
  { origen: "VIRREY DEL PINO", destino: "VILLA SOLDATI", kmReal: null, kmConv: 40 },
  { origen: "SAN FRANCISCO", destino: "PUERTO MADERO", kmReal: 566, kmConv: 565 },
  { origen: "SAN FRANCISCO", destino: "LOMAS DE ZAMORA", kmReal: 575, kmConv: 575 },
  { origen: "PORTE&#209;A", destino: "TRUJUI", kmReal: 608, kmConv: 610 },
  { origen: "CAMPANA", destino: "GENERAL RODRIGUEZ", kmReal: null, kmConv: 60 },
  { origen: "EL JAGUEL", destino: "CIPOLLETTI", kmReal: 1106, kmConv: 1105 },
  { origen: "VILLA URQUIZA", destino: "EL JAGUEL", kmReal: null, kmConv: 35 },
  { origen: "EZEIZA", destino: "TAPIALES", kmReal: 19, kmConv: 20 },
  { origen: "QUILMES", destino: "VALENTIN ALSINA", kmReal: 22, kmConv: 20 },
  { origen: "VILLA MERCEDES", destino: "DOCK SUD", kmReal: 704, kmConv: 705 },
  { origen: "SAN FRANCISCO", destino: "AVELLANEDA", kmReal: 569, kmConv: 570 },
  { origen: "RAFAELA", destino: "GARUPA", kmReal: 885, kmConv: 885 },
  { origen: "MERCEDES", destino: "SAN JUSTO", kmReal: null, kmConv: 90 },
  { origen: "MORENO", destino: "ZARATE", kmReal: null, kmConv: 95 },
  { origen: "NAVARRO", destino: "SAN FRANCISCO", kmReal: 560, kmConv: 560 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "NAVARRO", kmReal: 106, kmConv: 105 },
  { origen: "EL TALAR", destino: "PILAR", kmReal: 29, kmConv: 30 },
  { origen: "PUERTO BOSSETTI", destino: "ESPERANZA", kmReal: 1059, kmConv: 1060 },
  { origen: "PUERTO BOSSETTI", destino: "ELDORADO", kmReal: null, kmConv: 70 },
  { origen: "PUERTO BOSSETTI", destino: "PUERTO ESPERANZA", kmReal: null, kmConv: 25 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
