/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 5 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "LA MATANZA", destino: "VALENTIN ALSINA", kmReal: 22, kmConv: 20 },
  { origen: "SAN LUIS", destino: "VILLA MERCEDES", kmReal: 97, kmConv: 95 },
  { origen: "TAPIALES", destino: "RIO CUARTO", kmReal: 617, kmConv: 615 },
  { origen: "ITUZAINGO", destino: "MORENO", kmReal: 13, kmConv: 15 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "ESCOBAR", kmReal: 83, kmConv: 85 },
  { origen: "ARROYITO", destino: "DEVOTO", kmReal: 75, kmConv: 75 },
  { origen: "JOSE C. PAZ", destino: "VILLA MARTELLI", kmReal: 33, kmConv: 35 },
  { origen: "SANTA FE", destino: "CARLOS SPEGAZZINI", kmReal: 518, kmConv: 520 },
  { origen: "VILLA SOLDATI", destino: "CASEROS", kmReal: 15, kmConv: 15 },
  { origen: "PUERTO PIRAY", destino: "DOCK SUD", kmReal: 1181, kmConv: 1180 },
  { origen: "SARANDI", destino: "PUERTO PIRAY", kmReal: 1182, kmConv: 1180 },
  { origen: "CAPITAN CORTEZ", destino: "CONCORDIA", kmReal: 431, kmConv: 430 },
  { origen: "LA PLATA", destino: "CAPITAN CORTEZ", kmReal: 55, kmConv: 55 },
  { origen: "VILLA SOLDATI", destino: "SAN JORGE", kmReal: 498, kmConv: 500 },
  { origen: "9 DE ABRIL", destino: "EL PALOMAR", kmReal: 25, kmConv: 25 },
  { origen: "OLIVOS", destino: "VICENTE LOPEZ", kmReal: 4, kmConv: 5 },
  { origen: "TIO PUJIO", destino: "OLIVOS", kmReal: 555, kmConv: 555 },
  { origen: "VILLA MERCEDES", destino: "ESTEBAN ECHEVERRIA", kmReal: 716, kmConv: 715 },
  { origen: "ITUZAINGO", destino: "PILAR", kmReal: 42, kmConv: 40 },
  { origen: "SAN MARTIN", destino: "VILLA DOLORES", kmReal: 427, kmConv: 425 },
  { origen: "DOCK SUD", destino: "PUERTO PIRAY", kmReal: 1189, kmConv: 1190 },
  { origen: "ARIAS", destino: "RIO CUARTO", kmReal: 200, kmConv: 200 },
  { origen: "CONCORDIA", destino: "ARIAS", kmReal: 596, kmConv: 595 },
  { origen: "VILLA SOLDATI", destino: "LA FRANCIA", kmReal: 623, kmConv: 625 },
  { origen: "BENAVIDEZ", destino: "CORDOBA", kmReal: 659, kmConv: 660 },
  { origen: "TORTUGUITAS", destino: "BENAVIDEZ", kmReal: 11, kmConv: 10 },
  { origen: "MONTE GRANDE", destino: "SAN ANDRES DE GILES", kmReal: 123, kmConv: 125 },
  { origen: "BELLA ITALIA", destino: "BECCAR", kmReal: 528, kmConv: 530 },
  { origen: "SANTO TOME", destino: "LA FRANCIA", kmReal: 187, kmConv: 185 },
  { origen: "NUEVA POMPEYA", destino: "ZARATE", kmReal: 96, kmConv: 95 },
  { origen: "GENERAL RODRIGUEZ", destino: "CORDOBA", kmReal: 673, kmConv: 675 },
  { origen: "OLAVARRIA", destino: "VILLA SOLDATI", kmReal: 363, kmConv: 365 },
  { origen: "RAFAELA", destino: "OLAVARRIA", kmReal: 756, kmConv: 755 },
  { origen: "MORENO", destino: "BARADERO", kmReal: 142, kmConv: 140 },
  { origen: "LOS CORRALITOS", destino: "CORDOBA", kmReal: 676, kmConv: 675 },
  { origen: "CORDOBA", destino: "LOS CORRALITOS", kmReal: 676, kmConv: 675 },
  { origen: "ESCOBAR", destino: "NUEVA POMPEYA", kmReal: 60, kmConv: 60 },
  { origen: "GENERAL DEHEZA", destino: "VILLA MERCEDES", kmReal: 199, kmConv: 200 },
  { origen: "MORENO", destino: "VALENTIN ALSINA", kmReal: 39, kmConv: 40 },
  { origen: "VILLA MERCEDES", destino: "DON TORCUATO", kmReal: 716, kmConv: 715 },
  { origen: "BAHIA BLANCA", destino: "VILLA MERCEDES", kmReal: 740, kmConv: 740 },
  { origen: "MERCEDES", destino: "FATIMA", kmReal: 69, kmConv: 70 },
  { origen: "PILAR", destino: "ARROYITO", kmReal: 611, kmConv: 610 },
  { origen: "ZONA PORTUARIA", destino: "GARIN", kmReal: 41, kmConv: 40 },
  { origen: "CATRILO", destino: "RIO CUARTO", kmReal: 412, kmConv: 410 },
  { origen: "ROJAS", destino: "VILLA SOLDATI", kmReal: 229, kmConv: 230 },
  { origen: "VILLA MERCEDES", destino: "MONTE GRANDE", kmReal: 713, kmConv: 715 },
  { origen: "ITUZAINGO", destino: "GENERAL PACHECO", kmReal: 38, kmConv: 35 },
  { origen: "PILAR", destino: "GENERAL RODRIGUEZ", kmReal: 16, kmConv: 15 },
  { origen: "TIGRE", destino: "GENERAL DEHEZA", kmReal: 604, kmConv: 605 },
  { origen: "MATADEROS", destino: "TIGRE", kmReal: 33, kmConv: 35 },
  { origen: "VILLA MERCEDES", destino: "ITUZAINGO", kmReal: 671, kmConv: 670 },
  { origen: "CORDOBA", destino: "LA MATANZA", kmReal: 738, kmConv: 740 },
  { origen: "PILAR", destino: "VILLA CELINA", kmReal: 64, kmConv: 65 },
  { origen: "SAN FRANCISCO", destino: "LAS HERAS", kmReal: 780, kmConv: 780 },
  { origen: "LAS HERAS", destino: "MORENO", kmReal: 1015, kmConv: 1015 },
  { origen: "ROSARIO", destino: "TORTUGUITAS", kmReal: 270, kmConv: 270 },
  { origen: "GENERAL RODRIGUEZ", destino: "PILAR", kmReal: 16, kmConv: 15 },
  { origen: "PERGAMINO", destino: "9 DE ABRIL", kmReal: 250, kmConv: 250 },
  { origen: "ROSARIO", destino: "RIO CEBALLOS", kmReal: 427, kmConv: 425 },
  { origen: "VILLA CELINA", destino: "RIO CUARTO", kmReal: 619, kmConv: 620 },
  { origen: "VILLA SOLDATI", destino: "VILLA CELINA", kmReal: 6, kmConv: 5 },
  { origen: "GENERAL PACHECO", destino: "MORENO", kmReal: 37, kmConv: 35 },
  { origen: "SUNCHALES", destino: "PORTE&#209;A", kmReal: 63, kmConv: 65 },
  { origen: "LAS HERAS", destino: "COSQUIN", kmReal: 604, kmConv: 605 },
  { origen: "SAN ANDRES DE GILES", destino: "COLONIA CAROYA", kmReal: 668, kmConv: 670 },
  { origen: "DOCK SUD", destino: "CONCEPCION DEL URUGUAY", kmReal: 303, kmConv: 305 },
  { origen: "VILLA MERCEDES", destino: "GENERAL PACHECO", kmReal: 688, kmConv: 690 },
  { origen: "RAFAELA", destino: "MATADEROS", kmReal: 542, kmConv: 540 },
  { origen: "SUSANA", destino: "RAFAELA", kmReal: 15, kmConv: 15 },
  { origen: "RAFAELA", destino: "SUSANA", kmReal: 15, kmConv: 15 },
  { origen: "VICENTE LOPEZ", destino: "GENERAL RODRIGUEZ", kmReal: 55, kmConv: 55 },
  { origen: "LAS HERAS", destino: "SAN MARTIN", kmReal: 50, kmConv: 50 },
  { origen: "LANUS", destino: "SAN JUSTO", kmReal: 23, kmConv: 25 },
  { origen: "MARCOS PAZ", destino: "ZARATE", kmReal: 106, kmConv: 105 },
  { origen: "MATADEROS", destino: "ZARATE", kmReal: 92, kmConv: 90 },
  { origen: "SAN ANDRES DE GILES", destino: "PARANÁ", kmReal: 421, kmConv: 420 },
  { origen: "RAFAELA", destino: "LAS HERAS", kmReal: 866, kmConv: 865 },
  { origen: "SAN FRANCISCO", destino: "LANUS", kmReal: 576, kmConv: 575 },
  { origen: "SAN FRANCISCO", destino: "SUSANA", kmReal: 79, kmConv: 80 },
  { origen: "CONCORDIA", destino: "MARCOS PAZ", kmReal: 445, kmConv: 445 },
  { origen: "SAN ANDRES DE GILES", destino: "ESPERANZA", kmReal: 420, kmConv: 420 },
  { origen: "SANTOS LUGARES", destino: "GARIN", kmReal: 37, kmConv: 35 },
  { origen: "CHA&#209;AR LADEADO", destino: "CORDOBA", kmReal: 356, kmConv: 355 },
  { origen: "CORDOBA", destino: "CHA&#209;AR LADEADO", kmReal: 356, kmConv: 355 },
  { origen: "VILLA MERCEDES", destino: "EL TALAR", kmReal: 684, kmConv: 685 },
  { origen: "VILLA DEL PARQUE", destino: "MONTE GRANDE", kmReal: 35, kmConv: 35 },
  { origen: "RECREO", destino: "VILLA DEL PARQUE", kmReal: 477, kmConv: 475 },
  { origen: "MORENO", destino: "VILLA LUGANO", kmReal: 34, kmConv: 35 },
  { origen: "LAS VARILLAS", destino: "CORDOBA", kmReal: 177, kmConv: 180 },
  { origen: "CONCORDIA", destino: "LAS VARILLAS", kmReal: 511, kmConv: 510 },
  { origen: "FREYRE", destino: "VILLA MERCEDES", kmReal: 452, kmConv: 450 },
  { origen: "BURZACO", destino: "VICENTE LOPEZ", kmReal: 46, kmConv: 45 },
  { origen: "VICENTE LOPEZ", destino: "BURZACO", kmReal: 43, kmConv: 45 },
  { origen: "TAPIALES", destino: "VICENTE LOPEZ", kmReal: 28, kmConv: 30 },
  { origen: "RIO CUARTO", destino: "VILLA MERCEDES", kmReal: 125, kmConv: 125 },
  { origen: "MERCEDES", destino: "CASEROS", kmReal: 88, kmConv: 90 },
  { origen: "PILAR", destino: "CASEROS", kmReal: 56, kmConv: 55 },
  { origen: "LA MATANZA", destino: "EL PALOMAR", kmReal: 8, kmConv: 10 },
  { origen: "LA MATANZA", destino: "GENERAL PACHECO", kmReal: 38, kmConv: 40 },
  { origen: "CORONEL SUAREZ", destino: "CATRILO", kmReal: 203, kmConv: 205 },
  { origen: "JARDIN AMERICA", destino: "SANTA ANA", kmReal: 65, kmConv: 65 },
  { origen: "SAN SALVADOR", destino: "PILAR", kmReal: 359, kmConv: 360 },
  { origen: "ROJAS", destino: "GARIN", kmReal: 227, kmConv: 225 },
  { origen: "TAPIALES", destino: "MONTE GRANDE", kmReal: 18, kmConv: 20 },
  { origen: "MONTE GRANDE", destino: "SAN FRANCISCO", kmReal: 589, kmConv: 590 },
  { origen: "ESCOBAR", destino: "MONTE GRANDE", kmReal: 80, kmConv: 80 },
  { origen: "LANUS", destino: "RIO CUARTO", kmReal: 622, kmConv: 620 },
  { origen: "RECREO", destino: "ROJAS", kmReal: 340, kmConv: 340 },
  { origen: "SAN JUSTO", destino: "CORONEL SUAREZ", kmReal: 531, kmConv: 530 },
  { origen: "DOCK SUD", destino: "SUNCHALES", kmReal: 619, kmConv: 620 },
  { origen: "CHASCOMUS", destino: "PARANÁ", kmReal: 627, kmConv: 630 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "ROSARIO", kmReal: 328, kmConv: 330 },
  { origen: "CARCARA&#209;A", destino: "ROSARIO", kmReal: 49, kmConv: 50 },
  { origen: "GARUPA", destino: "PUERTO ESPERANZA", kmReal: 242, kmConv: 240 },
  { origen: "PUERTO ESPERANZA", destino: "GARUPA", kmReal: 242, kmConv: 240 },
  { origen: "SARANDI", destino: "CONCEPCION DEL URUGUAY", kmReal: 305, kmConv: 305 },
  { origen: "SANTO TOME", destino: "CERRITO", kmReal: 85, kmConv: 85 },
  { origen: "BURZACO", destino: "SANTO TOME", kmReal: 493, kmConv: 495 },
  { origen: "RECREO", destino: "ESCOBAR", kmReal: 430, kmConv: 430 },
  { origen: "RAFAELA", destino: "JARDIN AMERICA", kmReal: 977, kmConv: 980 },
  { origen: "ITUZAINGO", destino: "TAPIALES", kmReal: 28, kmConv: 30 },
  { origen: "SANTO TOME", destino: "MORENO", kmReal: 459, kmConv: 460 },
  { origen: "SAN JUSTO", destino: "CORDOBA", kmReal: 701, kmConv: 700 },
  { origen: "CORDOBA", destino: "SAN JUSTO", kmReal: 700, kmConv: 700 },
  { origen: "MUNRO", destino: "GARIN", kmReal: 29, kmConv: 30 },
  { origen: "SARANDI", destino: "SUNCHALES", kmReal: 590, kmConv: 590 },
  { origen: "BURZACO", destino: "SARANDI", kmReal: 20, kmConv: 20 },
  { origen: "BURZACO", destino: "DOCK SUD", kmReal: 20, kmConv: 20 },
  { origen: "JOSE C. PAZ", destino: "ESTEBAN ECHEVERRIA", kmReal: 69, kmConv: 70 },
  { origen: "ROSARIO", destino: "JOSE C. PAZ", kmReal: 277, kmConv: 275 },
  { origen: "TAPIALES", destino: "MUNRO", kmReal: 26, kmConv: 25 },
  { origen: "CONCORDIA", destino: "RIO CUARTO", kmReal: 752, kmConv: 750 },
  { origen: "BARRACAS", destino: "CONCEPCION DEL URUGUAY", kmReal: 300, kmConv: 300 },
  { origen: "SAUCE VIEJO", destino: "SANTO TOME", kmReal: 14, kmConv: 15 },
  { origen: "PARANÁ", destino: "SAUCE VIEJO", kmReal: 56, kmConv: 55 },
  { origen: "3 DE FEBRERO", destino: "SAN JUSTO", kmReal: 12, kmConv: 10 },
  { origen: "ROSARIO", destino: "VILLA SOLDATI", kmReal: 304, kmConv: 305 },
  { origen: "BURZACO", destino: "CHASCOMUS", kmReal: 125, kmConv: 125 },
  { origen: "SAN FRANCISCO", destino: "CARLOS SPEGAZZINI", kmReal: 600, kmConv: 600 },
  { origen: "SAN JUSTO", destino: "SUNCHALES", kmReal: 633, kmConv: 635 },
  { origen: "LA MATANZA", destino: "CARLOS SPEGAZZINI", kmReal: 39, kmConv: 40 },
  { origen: "CIUDADELA", destino: "CORDOBA", kmReal: 694, kmConv: 695 },
  { origen: "JOSE LEON SUAREZ", destino: "VILLA SOLDATI", kmReal: 32, kmConv: 30 },
  { origen: "SAUCE VIEJO", destino: "MORENO", kmReal: 446, kmConv: 445 },
  { origen: "SANTA FE", destino: "SAUCE VIEJO", kmReal: 30, kmConv: 30 },
  { origen: "CERRITO", destino: "SAUCE VIEJO", kmReal: 107, kmConv: 105 },
  { origen: "9 DE ABRIL", destino: "CARLOS SPEGAZZINI", kmReal: 27, kmConv: 25 },
  { origen: "SARANDI", destino: "PUERTO ESPERANZA", kmReal: 1235, kmConv: 1235 },
  { origen: "SAN FRANCISCO", destino: "PUERTO ESPERANZA", kmReal: 1150, kmConv: 1150 },
  { origen: "LOS POLVORINES", destino: "ZARATE", kmReal: 62, kmConv: 60 },
  { origen: "ROSARIO", destino: "MONTE GRANDE", kmReal: 339, kmConv: 340 },
  { origen: "PILAR", destino: "PABLO NOGUES", kmReal: 23, kmConv: 25 },
  { origen: "SANTA ROSA DE RIO PRIMERO", destino: "CORDOBA", kmReal: 90, kmConv: 90 },
  { origen: "CORDOBA", destino: "SANTA ROSA DE RIO PRIMERO", kmReal: 90, kmConv: 90 },
  { origen: "CARLOS SPEGAZZINI", destino: "SAN FRANCISCO", kmReal: 636, kmConv: 635 },
  { origen: "ESCOBAR", destino: "CARLOS SPEGAZZINI", kmReal: 93, kmConv: 95 },
  { origen: "DEVOTO", destino: "JOSE LEON SUAREZ", kmReal: 568, kmConv: 570 },
  { origen: "CURA BROCHERO", destino: "CORDOBA", kmReal: 149, kmConv: 150 },
  { origen: "CORDOBA", destino: "CURA BROCHERO", kmReal: 332, kmConv: 330 },
  { origen: "PARANÁ", destino: "ROSARIO", kmReal: 199, kmConv: 200 },
  { origen: "PILAR", destino: "EL TALAR", kmReal: 27, kmConv: 25 },
  { origen: "SAN FRANCISCO", destino: "SAN LORENZO", kmReal: 241, kmConv: 240 },
  { origen: "FATIMA", destino: "CORDOBA", kmReal: 647, kmConv: 645 },
  { origen: "PILAR", destino: "FATIMA", kmReal: 10, kmConv: 10 },
  { origen: "LUIS GUILLON", destino: "LANUS", kmReal: 14, kmConv: 15 },
  { origen: "CARMEN DE ARECO", destino: "ZARATE", kmReal: 101, kmConv: 100 },
  { origen: "ANGUIL", destino: "CARMEN DE ARECO", kmReal: 488, kmConv: 490 },
  { origen: "ZARATE", destino: "VILLA CARLOS PAZ", kmReal: 741, kmConv: 740 },
  { origen: "SANTOS LUGARES", destino: "ZARATE", kmReal: 84, kmConv: 85 },
  { origen: "ZARATE", destino: "CARLOS SPEGAZZINI", kmReal: 129, kmConv: 130 },
  { origen: "CARLOS SPEGAZZINI", destino: "ZARATE", kmReal: 129, kmConv: 130 },
  { origen: "CARCARA&#209;A", destino: "MORENO", kmReal: 345, kmConv: 345 },
  { origen: "LANUS", destino: "LUIS GUILLON", kmReal: 15, kmConv: 15 },
  { origen: "ROSARIO", destino: "LANUS", kmReal: 314, kmConv: 315 },
  { origen: "GUALEGUAYCHU", destino: "GUALEGUAY", kmReal: 61, kmConv: 60 },
  { origen: "TAPIALES", destino: "GUALEGUAYCHU", kmReal: 264, kmConv: 265 },
  { origen: "ESCOBAR", destino: "TAPIALES", kmReal: 72, kmConv: 70 },
  { origen: "LONGCHAMPS", destino: "DOCK SUD", kmReal: 33, kmConv: 35 },
  { origen: "LA PLATA", destino: "PILAR", kmReal: 125, kmConv: 125 },
  { origen: "BARRACAS", destino: "CARCARA&#209;A", kmReal: 349, kmConv: 350 },
  { origen: "CARCARA&#209;A", destino: "DOCK SUD", kmReal: 352, kmConv: 352 },
  { origen: "DOCK SUD", destino: "CARCARA&#209;A", kmReal: 356, kmConv: 355 },
  { origen: "LA TABLADA", destino: "ESCOBAR", kmReal: 58, kmConv: 60 },
  { origen: "VILLA MARIA", destino: "LA TABLADA", kmReal: 555, kmConv: 555 },
  { origen: "MENDOZA", destino: "SANTOS LUGARES", kmReal: 1034, kmConv: 1035 },
  { origen: "VILLA SOLDATI", destino: "FLORENCIO VARELA", kmReal: 25, kmConv: 25 },
  { origen: "VILLA SOLDATI", destino: "PILAR", kmReal: 61, kmConv: 60 },
  { origen: "VILLA URQUIZA", destino: "BURZACO", kmReal: 36, kmConv: 35 },
  { origen: "SASTRE", destino: "SAN FRANCISCO", kmReal: 50, kmConv: 50 },
  { origen: "SAN FRANCISCO", destino: "SASTRE", kmReal: 50, kmConv: 50 },
  { origen: "CORDOBA", destino: "SARGENTO CABRAL", kmReal: 455, kmConv: 455 },
  { origen: "VILLA SOLDATI", destino: "RECREO", kmReal: 488, kmConv: 490 },
  { origen: "COMODORO RIVADAVIA", destino: "TRELEW", kmReal: 376, kmConv: 375 },
  { origen: "GOBERNADOR VIRASORO", destino: "RAFAELA", kmReal: 802, kmConv: 800 },
  { origen: "FIGHIERA", destino: "BARRACAS", kmReal: 271, kmConv: 270 },
  { origen: "SAN FRANCISCO", destino: "FIGHIERA", kmReal: 302, kmConv: 300 },
  { origen: "FIGHIERA", destino: "SAN FRANCISCO", kmReal: 301, kmConv: 300 },
  { origen: "VILLA SOLDATI", destino: "FIGHIERA", kmReal: 270, kmConv: 270 },
  { origen: "VALENTIN ALSINA", destino: "RAFAELA", kmReal: 604, kmConv: 605 },
  { origen: "TORTUGUITAS", destino: "LANUS", kmReal: 59, kmConv: 60 },
  { origen: "ITUZAINGO", destino: "9 DE ABRIL", kmReal: 22, kmConv: 20 },
  { origen: "BECCAR", destino: "TAPIALES", kmReal: 44, kmConv: 45 },
  { origen: "LA REJA", destino: "VILLA SOLDATI", kmReal: 39, kmConv: 40 },
  { origen: "MERLO", destino: "LA REJA", kmReal: 11, kmConv: 10 },
  { origen: "VILLA MARIA", destino: "MERLO", kmReal: 553, kmConv: 555 },
  { origen: "CORDOBA", destino: "CASEROS", kmReal: 693, kmConv: 695 },
  { origen: "CORDOBA", destino: "GENERAL ROCA", kmReal: 1097, kmConv: 1095 },
  { origen: "LAS HERAS", destino: "RIO TERCERO", kmReal: 619, kmConv: 620 },
  { origen: "PABLO NOGUES", destino: "MATADEROS", kmReal: 39, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "PABLO NOGUES", kmReal: 42, kmConv: 40 },
  { origen: "SAN SALVADOR", destino: "VILLA SOLDATI", kmReal: 402, kmConv: 400 },
  { origen: "TRELEW", destino: "COMODORO RIVADAVIA", kmReal: 375, kmConv: 375 },
  { origen: "LA REJA", destino: "SAN VICENTE", kmReal: 64, kmConv: 65 },
  { origen: "LAS HERAS", destino: "LA REJA", kmReal: 1011, kmConv: 1010 },
  { origen: "ROSARIO", destino: "ITUZAINGO", kmReal: 300, kmConv: 300 },
  { origen: "LOS POLVORINES", destino: "VILLA SOLDATI", kmReal: 43, kmConv: 45 },
  { origen: "SAN VICENTE", destino: "CORDOBA", kmReal: 750, kmConv: 750 },
  { origen: "VILLA SOLDATI", destino: "SAN VICENTE", kmReal: 57, kmConv: 55 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN VICENTE", kmReal: 95, kmConv: 95 },
  { origen: "SAN FRANCISCO", destino: "LOS POLVORINES", kmReal: 532, kmConv: 530 },
  { origen: "TIGRE", destino: "ZARATE", kmReal: 86, kmConv: 85 },
  { origen: "CORDOBA", destino: "VILLA DOLORES", kmReal: 450, kmConv: 450 },
  { origen: "MONTE CRISTO", destino: "SAN FRANCISCO", kmReal: 197, kmConv: 195 },
  { origen: "MONTE BUEY", destino: "SAN FRANCISCO", kmReal: 197, kmConv: 195 },
  { origen: "TUNUYAN", destino: "CORDOBA", kmReal: 764, kmConv: 765 },
  { origen: "CORDOBA", destino: "TUNUYAN", kmReal: 764, kmConv: 765 },
  { origen: "VILLA SOLDATI", destino: "MERLO", kmReal: 32, kmConv: 30 },
  { origen: "SANTO TOME", destino: "VILLA SOLDATI", kmReal: 463, kmConv: 465 },
  { origen: "CORDOBA", destino: "MATADEROS", kmReal: 697, kmConv: 695 },
  { origen: "LAS HERAS", destino: "GENERAL RODRIGUEZ", kmReal: 998, kmConv: 1000 },
  { origen: "EZPELETA", destino: "MONTE GRANDE", kmReal: 26, kmConv: 25 },
  { origen: "TIO PUJIO", destino: "EZPELETA", kmReal: 603, kmConv: 605 },
  { origen: "ESCOBAR", destino: "LA TABLADA", kmReal: 57, kmConv: 55 },
  { origen: "MASCHWITZ", destino: "ESCOBAR", kmReal: 10, kmConv: 10 },
  { origen: "VILLA MARIA", destino: "MASCHWITZ", kmReal: 508, kmConv: 510 },
  { origen: "RAFAELA", destino: "FREYRE", kmReal: 61, kmConv: 60 },
  { origen: "PABLO NOGUES", destino: "ROSARIO", kmReal: 268, kmConv: 270 },
  { origen: "CERRITO", destino: "RAFAELA", kmReal: 193, kmConv: 195 },
  { origen: "ALTA GRACIA", destino: "MONTE CRISTO", kmReal: 67, kmConv: 70 },
  { origen: "VALLE DE UCO", destino: "CORDOBA", kmReal: 848, kmConv: 850 },
  { origen: "CORDOBA", destino: "VALLE DE UCO", kmReal: 848, kmConv: 850 },
  { origen: "TRELEW", destino: "BAHIA BLANCA", kmReal: 719, kmConv: 720 },
  { origen: "PARQUE PATRICIOS", destino: "VILLA ALSINA", kmReal: 4, kmConv: 5 },
  { origen: "VILLA SOLDATI", destino: "PARQUE PATRICIOS", kmReal: 5, kmConv: 5 },
  { origen: "ESCOBAR", destino: "HUDSON", kmReal: 88, kmConv: 90 },
  { origen: "DEVOTO", destino: "AVELLANEDA", kmReal: 614, kmConv: 615 },
  { origen: "EL PALOMAR", destino: "CORDOBA", kmReal: 700, kmConv: 700 },
  { origen: "GARIN", destino: "EL PALOMAR", kmReal: 46, kmConv: 45 },
  { origen: "AVELLANEDA", destino: "MATADEROS", kmReal: 19, kmConv: 20 },
  { origen: "DEVOTO", destino: "FLORENCIO VARELA", kmReal: 634, kmConv: 635 },
  { origen: "LANUS", destino: "AVELLANEDA", kmReal: 6, kmConv: 5 },
  { origen: "CHIMBAS", destino: "CORDOBA", kmReal: 645, kmConv: 645 },
  { origen: "CORDOBA", destino: "CHIMBAS", kmReal: 645, kmConv: 645 },
  { origen: "VICENTE LOPEZ", destino: "CARLOS SPEGAZZINI", kmReal: 58, kmConv: 60 },
  { origen: "CONCORDIA", destino: "VILLA DEL ROSARIO", kmReal: 599, kmConv: 600 },
  { origen: "FLORENCIO VARELA", destino: "SAN FRANCISCO", kmReal: 591, kmConv: 590 },
  { origen: "LABOULAYE", destino: "CORDOBA", kmReal: 354, kmConv: 355 },
  { origen: "CORDOBA", destino: "LABOULAYE", kmReal: 354, kmConv: 355 },
  { origen: "MEDIA AGUA", destino: "CORDOBA", kmReal: 558, kmConv: 560 },
  { origen: "CORDOBA", destino: "MEDIA AGUA", kmReal: 558, kmConv: 560 },
  { origen: "SAN JORGE", destino: "BARADERO", kmReal: 355, kmConv: 355 },
  { origen: "LANUS", destino: "SANTO TOME", kmReal: 470, kmConv: 470 },
  { origen: "PASO DEL REY", destino: "CAMPANA", kmReal: 80, kmConv: 80 },
  { origen: "PERGAMINO", destino: "VILLA SOLDATI", kmReal: 239, kmConv: 240 },
  { origen: "VILLA LUGANO", destino: "VILLA SOLDATI", kmReal: 5, kmConv: 5 },
  { origen: "BARRACAS", destino: "DOCK SUD", kmReal: 5, kmConv: 5 },
  { origen: "SAN ANDRES DE GILES", destino: "ROSARIO", kmReal: 226, kmConv: 225 },
  { origen: "ROSARIO", destino: "SAN JORGE", kmReal: 198, kmConv: 200 },
  { origen: "DOCK SUD", destino: "CHAJARÍ", kmReal: 505, kmConv: 505 },
  { origen: "BOSQUES", destino: "VILLA SOLDATI", kmReal: 50, kmConv: 50 },
  { origen: "BECCAR", destino: "VICENTE LOPEZ", kmReal: 11, kmConv: 10 },
  { origen: "PILAR", destino: "MATADEROS", kmReal: 53, kmConv: 55 },
  { origen: "RIO CUARTO", destino: "MERLO", kmReal: 174, kmConv: 175 },
  { origen: "SARANDI", destino: "RAFAELA", kmReal: 550, kmConv: 550 },
  { origen: "SAN FRANCISCO", destino: "SAN MARTIN", kmReal: 554, kmConv: 555 },
  { origen: "SAN FRANCISCO", destino: "BOSQUES", kmReal: 605, kmConv: 605 },
  { origen: "RAFAELA", destino: "LANUS", kmReal: 552, kmConv: 550 },
  { origen: "FRANCK", destino: "GARIN", kmReal: 433, kmConv: 435 },
  { origen: "CERRITO", destino: "FRANCK", kmReal: 109, kmConv: 110 },
  { origen: "CORRIENTES", destino: "POSADAS", kmReal: 320, kmConv: 320 },
  { origen: "MENDOZA", destino: "CORRIENTES", kmReal: 1471, kmConv: 1470 },
  { origen: "PUERTO PIRAY", destino: "COLONIA CAROYA", kmReal: 1322, kmConv: 1320 },
  { origen: "PUERTO IGUAZU", destino: "COLONIA CAROYA", kmReal: 1322, kmConv: 1320 },
  { origen: "SAN FRANCISCO", destino: "VILLA LUGANO", kmReal: 568, kmConv: 570 },
  { origen: "BURZACO", destino: "CERRITO", kmReal: 552, kmConv: 550 },
  { origen: "BARRACAS", destino: "PUERTO ESPERANZA", kmReal: 1232, kmConv: 1230 },
  { origen: "TIO PUJIO", destino: "9 DE ABRIL", kmReal: 583, kmConv: 585 },
  { origen: "SARANDI", destino: "PORTE&#209;A", kmReal: 620, kmConv: 620 },
  { origen: "TUCUMAN", destino: "VILLA MERCEDES", kmReal: 993, kmConv: 995 },
  { origen: "MERLO", destino: "CORDOBA", kmReal: 387, kmConv: 385 },
  { origen: "CORDOBA", destino: "MERLO", kmReal: 387, kmConv: 385 },
  { origen: "CHASCOMUS", destino: "SAUCE VIEJO", kmReal: 571, kmConv: 570 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "CHASCOMUS", kmReal: 123, kmConv: 125 },
  { origen: "PILAR", destino: "GARIN", kmReal: 22, kmConv: 20 },
  { origen: "SAN JORGE", destino: "MORENO", kmReal: 495, kmConv: 495 },
  { origen: "MORENO", destino: "SARANDI", kmReal: 51, kmConv: 50 },
  { origen: "CHACARITA", destino: "CARLOS SPEGAZZINI", kmReal: 49, kmConv: 50 },
  { origen: "BURZACO", destino: "PARANÁ", kmReal: 523, kmConv: 525 },
  { origen: "CASEROS", destino: "CORDOBA", kmReal: 694, kmConv: 695 },
  { origen: "DON TORCUATO", destino: "COLONIA CAROYA", kmReal: 714, kmConv: 715 },
  { origen: "ZONA PORTUARIA", destino: "CASEROS", kmReal: 27, kmConv: 25 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "CAMPANA", kmReal: 109, kmConv: 110 },
  { origen: "FORRES", destino: "VILLA MERCEDES", kmReal: 793, kmConv: 795 },
  { origen: "SAN MIGUEL DE TUCUMAN", destino: "FORRES", kmReal: 198, kmConv: 200 },
  { origen: "BARADERO", destino: "SAN MIGUEL DE TUCUMAN", kmReal: 1109, kmConv: 1110 },
  { origen: "SARANDI", destino: "FRANCK", kmReal: 486, kmConv: 485 },
  { origen: "DEAN FUNES", destino: "CORDOBA", kmReal: 127, kmConv: 125 },
  { origen: "CORDOBA", destino: "DEAN FUNES", kmReal: 127, kmConv: 125 },
  { origen: "ESCOBAR", destino: "PABLO NOGUES", kmReal: 21, kmConv: 20 },
  { origen: "SAUCE VIEJO", destino: "SAN JORGE", kmReal: 128, kmConv: 130 },
  { origen: "ROSARIO", destino: "SANTO TOME", kmReal: 161, kmConv: 160 },
  { origen: "VILLA SOLDATI", destino: "CARLOS SPEGAZZINI", kmReal: 41, kmConv: 40 },
  { origen: "BARADERO", destino: "TUCUMAN", kmReal: 1109, kmConv: 1110 },
  { origen: "VILLA SOLDATI", destino: "BARADERO", kmReal: 155, kmConv: 155 },
  { origen: "PABLO NOGUES", destino: "9 DE ABRIL", kmReal: 50, kmConv: 50 },
  { origen: "ZARATE", destino: "BARRACAS", kmReal: 101, kmConv: 100 },
  { origen: "COSQUIN", destino: "TIO PUJIO", kmReal: 186, kmConv: 185 },
  { origen: "ESPERANZA", destino: "SANTO TOME", kmReal: 42, kmConv: 40 },
  { origen: "SANTO TOME", destino: "FRANCK", kmReal: 25, kmConv: 25 },
  { origen: "FRANCK", destino: "SANTO TOME", kmReal: 25, kmConv: 25 },
  { origen: "VILLA DOLORES", destino: "CORDOBA", kmReal: 187, kmConv: 190 },
  { origen: "RIO CUARTO", destino: "VILLA DOLORES", kmReal: 237, kmConv: 235 },
  { origen: "PABLO NOGUES", destino: "MORENO", kmReal: 39, kmConv: 40 },
  { origen: "LANUS", destino: "SAUCE VIEJO", kmReal: 458, kmConv: 460 },
  { origen: "VILLA SOLDATI", destino: "RAFAELA", kmReal: 544, kmConv: 545 },
  { origen: "CAPITAN CORTEZ", destino: "RAFAELA", kmReal: 543, kmConv: 545 },
  { origen: "ZONA PORTUARIA", destino: "CAPITAN CORTEZ", kmReal: 7, kmConv: 5 },
  { origen: "SANTOS LUGARES", destino: "VILLA SOLDATI", kmReal: 16, kmConv: 15 },
  { origen: "PARANÁ", destino: "RAFAELA", kmReal: 150, kmConv: 150 },
  { origen: "SAN FRANCISCO", destino: "ESPERANZA", kmReal: 136, kmConv: 135 },
  { origen: "JUAREZ CELMAN", destino: "SAN FRANCISCO", kmReal: 236, kmConv: 235 },
  { origen: "LUJAN DE CUYO", destino: "CORDOBA", kmReal: 699, kmConv: 700 },
  { origen: "CORDOBA", destino: "LUJAN DE CUYO", kmReal: 699, kmConv: 700 },
  { origen: "SAN MARTIN", destino: "SAN FRANCISCO", kmReal: 736, kmConv: 735 },
  { origen: "BECCAR", destino: "ESCOBAR", kmReal: 37, kmConv: 35 },
  { origen: "SAN PEDRO", destino: "LOMA HERMOSA", kmReal: 158, kmConv: 160 },
  { origen: "HAEDO", destino: "TAPIALES", kmReal: 19, kmConv: 20 },
  { origen: "RESISTENCIA", destino: "CLORINDA", kmReal: 288, kmConv: 290 },
  { origen: "PUERTO PIRAY", destino: "PARANÁ", kmReal: 927, kmConv: 925 },
  { origen: "CLORINDA", destino: "PUERTO PIRAY", kmReal: 808, kmConv: 810 },
  { origen: "SARGENTO CABRAL", destino: "CORDOBA", kmReal: 457, kmConv: 455 },
  { origen: "PATERNAL", destino: "MORENO", kmReal: 31, kmConv: 30 },
  { origen: "SAN JUSTO", destino: "CARLOS SPEGAZZINI", kmReal: 37, kmConv: 35 },
  { origen: "LANUS", destino: "MERCEDES", kmReal: 106, kmConv: 105 },
  { origen: "ZARATE", destino: "JUAREZ CELMAN", kmReal: 620, kmConv: 620 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "PUERTO ESPERANZA", kmReal: 963, kmConv: 965 },
  { origen: "SAN FRANCISCO", destino: "CONCEPCION DEL URUGUAY", kmReal: 439, kmConv: 440 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "SAN FRANCISCO", kmReal: 431, kmConv: 430 },
  { origen: "BERAZATEGUI", destino: "CONCEPCION DEL URUGUAY", kmReal: 325, kmConv: 325 },
  { origen: "BERAZATEGUI", destino: "PUERTO ESPERANZA", kmReal: 1273, kmConv: 1270 },
  { origen: "BERAZATEGUI", destino: "25 DE MAYO", kmReal: 1273, kmConv: 1270 },
  { origen: "ESCOBAR", destino: "SAN JUSTO", kmReal: 59, kmConv: 60 },
  { origen: "LA MATANZA", destino: "PATERNAL", kmReal: 33, kmConv: 35 },
  { origen: "TAPIALES", destino: "ESCOBAR", kmReal: 62, kmConv: 60 },
  { origen: "RAFAELA", destino: "MERCEDES", kmReal: 494, kmConv: 495 },
  { origen: "MAIPU", destino: "SAN FRANCISCO", kmReal: 770, kmConv: 770 },
  { origen: "MERCEDES", destino: "CONCORDIA", kmReal: 266, kmConv: 265 },
  { origen: "LAS HERAS", destino: "SANTOS LUGARES", kmReal: 1038, kmConv: 1040 },
  { origen: "ESCOBAR", destino: "CORDOBA", kmReal: 645, kmConv: 645 },
  { origen: "TORTUGUITAS", destino: "ESCOBAR", kmReal: 24, kmConv: 25 },
  { origen: "PILAR", destino: "ESCOBAR", kmReal: 30, kmConv: 30 },
  { origen: "GARUPA", destino: "PUERTO PIRAY", kmReal: 186, kmConv: 185 },
  { origen: "BECCAR", destino: "SARANDI", kmReal: 50, kmConv: 50 },
  { origen: "TIGRE", destino: "BECCAR", kmReal: 10, kmConv: 10 },
  { origen: "VILLA TESEI", destino: "VILLA SOLDATI", kmReal: 20, kmConv: 20 },
  { origen: "PUERTO BOSSETTI", destino: "VILLA TESEI", kmReal: 1242, kmConv: 1240 },
  { origen: "OBERA", destino: "PUERTO BOSSETTI", kmReal: 235, kmConv: 235 },
  { origen: "LA MATANZA", destino: "TORTUGUITAS", kmReal: 43, kmConv: 45 },
  { origen: "PILAR", destino: "CARLOS SPEGAZZINI", kmReal: 99, kmConv: 100 },
  { origen: "MORENO", destino: "GARIN", kmReal: 46, kmConv: 45 },
  { origen: "SAN JORGE", destino: "EZEIZA", kmReal: 518, kmConv: 520 },
  { origen: "TIGRE", destino: "VICENTE LOPEZ", kmReal: 21, kmConv: 20 },
  { origen: "SAN LORENZO", destino: "CORDOBA", kmReal: 425, kmConv: 425 },
  { origen: "CORDOBA", destino: "SAN LORENZO", kmReal: 425, kmConv: 425 },
  { origen: "LUJAN DE CUYO", destino: "LOMA HERMOSA", kmReal: 1062, kmConv: 1060 },
  { origen: "BECCAR", destino: "LANUS", kmReal: 42, kmConv: 40 },
  { origen: "MUNRO", destino: "9 DE ABRIL", kmReal: 32, kmConv: 30 },
  { origen: "RESISTENCIA", destino: "FORMOSA", kmReal: 173, kmConv: 175 },
  { origen: "MAIPU", destino: "RESISTENCIA", kmReal: 1445, kmConv: 1445 },
  { origen: "MENDOZA", destino: "MAIPU", kmReal: 13, kmConv: 15 },
  { origen: "MORENO", destino: "CARLOS SPEGAZZINI", kmReal: 67, kmConv: 65 },
  { origen: "PORTE&#209;A", destino: "ROSARIO", kmReal: 315, kmConv: 315 },
  { origen: "TORTUGUITAS", destino: "RIO CUARTO", kmReal: 576, kmConv: 575 },
  { origen: "ISIDRO CASANOVA", destino: "TORTUGUITAS", kmReal: 60, kmConv: 60 },
  { origen: "CAMPANA", destino: "9 DE ABRIL", kmReal: 93, kmConv: 95 },
  { origen: "LUJAN", destino: "9 DE ABRIL", kmReal: 74, kmConv: 75 },
  { origen: "BURZACO", destino: "SAN JUSTO", kmReal: 26, kmConv: 25 },
  { origen: "MONTE GRANDE", destino: "SANTA FE", kmReal: 498, kmConv: 495 },
  { origen: "PABLO NOGUES", destino: "MONTE GRANDE", kmReal: 63, kmConv: 65 },
  { origen: "MONTE GRANDE", destino: "CORDOBA", kmReal: 724, kmConv: 725 },
  { origen: "ISIDRO CASANOVA", destino: "MONTE GRANDE", kmReal: 26, kmConv: 25 },
  { origen: "PILAR", destino: "SAN JORGE", kmReal: 453, kmConv: 450 },
  { origen: "SUCRE", destino: "CORDOBA", kmReal: 5, kmConv: 5 },
  { origen: "SAN MARTIN", destino: "SAN LUIS", kmReal: 217, kmConv: 215 },
  { origen: "LAS HERAS", destino: "GARUPA", kmReal: 1689, kmConv: 1690 },
  { origen: "CONCORDIA", destino: "LUJAN", kmReal: 399, kmConv: 400 },
  { origen: "PUERTO ESPERANZA", destino: "DOCK SUD", kmReal: 1233, kmConv: 1235 },
  { origen: "DOCK SUD", destino: "PUERTO ESPERANZA", kmReal: 1233, kmConv: 1235 },
  { origen: "TORTUGUITAS", destino: "SUCRE", kmReal: 666, kmConv: 665 },
  { origen: "LA MATANZA", destino: "9 DE ABRIL", kmReal: 12, kmConv: 10 },
  { origen: "GENERAL PACHECO", destino: "9 DE ABRIL", kmReal: 48, kmConv: 50 },
  { origen: "SAN FRANCISCO", destino: "GUAYMALLEN", kmReal: 772, kmConv: 770 },
  { origen: "GUAYMALLEN", destino: "SAN MARTIN", kmReal: 41, kmConv: 40 },
  { origen: "ROSARIO", destino: "DESVIO ARIJON", kmReal: 124, kmConv: 125 },
  { origen: "SAN NICOLAS", destino: "ESCOBAR", kmReal: 188, kmConv: 190 },
  { origen: "ESPERANZA", destino: "GENERAL PACHECO", kmReal: 459, kmConv: 460 },
  { origen: "FRANCK", destino: "ESPERANZA", kmReal: 17, kmConv: 20 },
  { origen: "GOBERNADOR VIRASORO", destino: "SAN FRANCISCO", kmReal: 823, kmConv: 825 },
  { origen: "VILLA MARIA", destino: "VILLA MERCEDES", kmReal: 262, kmConv: 260 },
  { origen: "LA PLATA", destino: "CORDOBA", kmReal: 754, kmConv: 755 },
  { origen: "MENDOZA", destino: "LAS HERAS", kmReal: 4, kmConv: 5 },
  { origen: "SAN SALVADOR", destino: "VICENTE LOPEZ", kmReal: 391, kmConv: 390 },
  { origen: "RIVADAVIA", destino: "CORDOBA", kmReal: 618, kmConv: 620 },
  { origen: "CORDOBA", destino: "RIVADAVIA", kmReal: 618, kmConv: 620 },
  { origen: "MERCEDES", destino: "GENERAL PACHECO", kmReal: 105, kmConv: 105 },
  { origen: "REMEDIOS DE ESCALADA", destino: "CAMPANA", kmReal: 95, kmConv: 95 },
  { origen: "MUNRO", destino: "CANNING", kmReal: 45, kmConv: 45 },
  { origen: "CARLOS SPEGAZZINI", destino: "SANTA FE", kmReal: 518, kmConv: 520 },
  { origen: "CANNING", destino: "CARLOS SPEGAZZINI", kmReal: 11, kmConv: 10 },
  { origen: "TAPIALES", destino: "CARLOS SPEGAZZINI", kmReal: 34, kmConv: 35 },
  { origen: "MERCEDES", destino: "EL TALAR", kmReal: 99, kmConv: 100 },
  { origen: "ISIDRO CASANOVA", destino: "VILLA SOLDATI", kmReal: 21, kmConv: 20 },
  { origen: "VILLA NUEVA", destino: "TIO PUJIO", kmReal: 21, kmConv: 20 },
  { origen: "LOMAS DE ZAMORA", destino: "REMEDIOS DE ESCALADA", kmReal: 8, kmConv: 10 },
  { origen: "SAN SALVADOR", destino: "LOMAS DE ZAMORA", kmReal: 416, kmConv: 415 },
  { origen: "LUJAN DE CUYO", destino: "ESTEBAN ECHEVERRIA", kmReal: 1077, kmConv: 1075 },
  { origen: "MENDOZA", destino: "LUJAN DE CUYO", kmReal: 15, kmConv: 15 },
  { origen: "HAEDO", destino: "CANNING", kmReal: 31, kmConv: 30 },
  { origen: "VILLA MARIA", destino: "PILAR", kmReal: 513, kmConv: 515 },
  { origen: "LA MATANZA", destino: "VILLA SOLDATI", kmReal: 16, kmConv: 15 },
  { origen: "RIO CUARTO", destino: "RAFAELA", kmReal: 381, kmConv: 380 },
  { origen: "MUNRO", destino: "CARLOS SPEGAZZINI", kmReal: 56, kmConv: 55 },
  { origen: "MENDOZA", destino: "RIO CUARTO", kmReal: 476, kmConv: 475 },
  { origen: "MAR DEL PLATA", destino: "CAMPANA", kmReal: 495, kmConv: 495 },
  { origen: "BURZACO", destino: "9 DE ABRIL", kmReal: null, kmConv: 15 },
  { origen: "MERCEDES", destino: "CARLOS SPEGAZZINI", kmReal: 122, kmConv: 120 },
  { origen: "VILLA TESEI", destino: "TORTUGUITAS", kmReal: 39, kmConv: 40 },
  { origen: "CONCORDIA", destino: "MERLO", kmReal: 435, kmConv: 435 },
  { origen: "PUERTO ESPERANZA", destino: "VILLA TESEI", kmReal: 1223, kmConv: 1225 },
  { origen: "EZEIZA", destino: "CARLOS SPEGAZZINI", kmReal: 9, kmConv: 10 },
  { origen: "BUENOS AIRES", destino: "CAMPANA", kmReal: 81, kmConv: 80 },
  { origen: "ITUZAINGO", destino: "QUILMES", kmReal: null, kmConv: 50 },
  { origen: "SAN MARTIN", destino: "JESUS MARIA", kmReal: 709, kmConv: 710 },
  { origen: "MORTEROS", destino: "ESTEBAN ECHEVERRIA", kmReal: 698, kmConv: 700 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "TAPIALES", kmReal: null, kmConv: 20 },
  { origen: "PERGAMINO", destino: "GARIN", kmReal: 196, kmConv: 195 },
  { origen: "GENERAL PACHECO", destino: "FRANCK", kmReal: 443, kmConv: 445 },
  { origen: "MUNRO", destino: "GENERAL PACHECO", kmReal: 21, kmConv: 20 },
  { origen: "BAHIA BLANCA", destino: "TORTUGUITAS", kmReal: 703, kmConv: 705 },
  { origen: "MONTE GRANDE", destino: "TORTUGUITAS", kmReal: 73, kmConv: 75 },
  { origen: "CHAJARÍ", destino: "ZONA PORTUARIA", kmReal: 497, kmConv: 495 },
  { origen: "BARRACAS", destino: "CHAJARÍ", kmReal: 499, kmConv: 500 },
  { origen: "CANNING", destino: "LANUS", kmReal: 34, kmConv: 35 },
  { origen: "TIGRE", destino: "VILLA SOLDATI", kmReal: null, kmConv: 40 },
  { origen: "JUNIN", destino: "GENERAL RODRIGUEZ", kmReal: 211, kmConv: 210 },
  { origen: "BARRACAS", destino: "VILLA MARIA", kmReal: 558, kmConv: 560 },
  { origen: "ESCOBAR", destino: "TIGRE", kmReal: 28, kmConv: 30 },
  { origen: "ARROYITO", destino: "VILLA MARIA", kmReal: 179, kmConv: 180 },
  { origen: "PABLO NOGUES", destino: "CANNING", kmReal: null, kmConv: 65 },
  { origen: "MERLO", destino: "ESTEBAN ECHEVERRIA", kmReal: 56, kmConv: 55 },
  { origen: "MONTEVIDEO", destino: "LANUS", kmReal: 584, kmConv: 585 },
  { origen: "MENDOZA", destino: "POSADAS", kmReal: 1690, kmConv: 1690 },
  { origen: "BAHIA BLANCA", destino: "9 DE ABRIL", kmReal: 620, kmConv: 620 },
  { origen: "MONTE GRANDE", destino: "BURZACO", kmReal: 9, kmConv: 9 },
  { origen: "ESCOBAR", destino: "MUNRO", kmReal: 38, kmConv: 40 },
  { origen: "BERISSO", destino: "BURZACO", kmReal: 66, kmConv: 65 },
  { origen: "CONCORDIA", destino: "BERISSO", kmReal: 497, kmConv: 495 },
  { origen: "SAN MARTIN", destino: "RIO CEBALLOS", kmReal: 640, kmConv: 640 },
  { origen: "BELL VILLE", destino: "MORTEROS", kmReal: 261, kmConv: 260 },
  { origen: "SAN MARTIN", destino: "BELL VILLE", kmReal: 659, kmConv: 660 },
  { origen: "3 DE FEBRERO", destino: "BURZACO", kmReal: 31, kmConv: 30 },
  { origen: "DALMASIO VELEZ", destino: "ZONA PORTUARIA", kmReal: 590, kmConv: 590 },
  { origen: "CORDOBA", destino: "DALMASIO VELEZ", kmReal: 175, kmConv: 175 },
  { origen: "SAN FRANCISCO", destino: "9 DE ABRIL", kmReal: 609, kmConv: 610 },
  { origen: "MORON", destino: "BURZACO", kmReal: 31, kmConv: 30 },
  { origen: "CORDOBA", destino: "PILAR", kmReal: 657, kmConv: 655 },
  { origen: "PILAR", destino: "CORDOBA", kmReal: 658, kmConv: 660 },
  { origen: "BARADERO", destino: "PILAR", kmReal: 112, kmConv: 110 },
  { origen: "VILLA MAIPU", destino: "ROSARIO", kmReal: 289, kmConv: 290 },
  { origen: "CHACARITA", destino: "LANUS", kmReal: 16, kmConv: 15 },
  { origen: "LA MATANZA", destino: "LANUS", kmReal: null, kmConv: 20 },
  { origen: "BARRACAS", destino: "PILAR", kmReal: 66, kmConv: 65 },
  { origen: "TIGRE", destino: "BURZACO", kmReal: 56, kmConv: 55 },
  { origen: "TIO PUJIO", destino: "LA MATANZA", kmReal: 575, kmConv: 575 },
  { origen: "HUINCA RENANCO", destino: "CORDOBA", kmReal: 411, kmConv: 410 },
  { origen: "VISTA ALEGRE", destino: "HUINCA RENANCO", kmReal: 766, kmConv: 765 },
  { origen: "ALLEN", destino: "VISTA ALEGRE", kmReal: null, kmConv: 50 },
  { origen: "PABLO NOGUES", destino: "VILLA MAIPU", kmReal: 26, kmConv: 25 },
  { origen: "ESCOBAR", destino: "ITUZAINGO", kmReal: 55, kmConv: 55 },
  { origen: "SAN FRANCISCO", destino: "VILLA DEL PARQUE", kmReal: 556, kmConv: 555 },
  { origen: "MONTEVIDEO", destino: "9 DE ABRIL", kmReal: 605, kmConv: 605 },
  { origen: "AVELLANEDA", destino: "TAPIALES", kmReal: null, kmConv: 20 },
  { origen: "DOCK SUD", destino: "ZARATE", kmReal: 94, kmConv: 95 },
  { origen: "SUARDI", destino: "FREYRE", kmReal: 77, kmConv: 75 },
  { origen: "SAN SALVADOR", destino: "ZARATE", kmReal: 314, kmConv: 315 },
  { origen: "MORENO", destino: "LANUS", kmReal: 43, kmConv: 45 },
  { origen: "MORENO", destino: "VICENTE LOPEZ", kmReal: 39, kmConv: 40 },
  { origen: "MUNRO", destino: "PABLO NOGUES", kmReal: 22, kmConv: 20 },
  { origen: "SAN MARTIN", destino: "HURLINGHAM", kmReal: 990, kmConv: 990 },
  { origen: "CARAPACHAY", destino: "9 DE ABRIL", kmReal: 34, kmConv: 35 },
  { origen: "FLORENCIO VARELA", destino: "BURZACO", kmReal: 15, kmConv: 15 },
  { origen: "LOMA HERMOSA", destino: "DON TORCUATO", kmReal: 17, kmConv: 15 },
  { origen: "ISIDRO CASANOVA", destino: "BURZACO", kmReal: 27, kmConv: 25 },
  { origen: "ESCOBAR", destino: "ISIDRO CASANOVA", kmReal: null, kmConv: 65 },
  { origen: "CIUDADELA", destino: "DOCK SUD", kmReal: 23, kmConv: 23 },
  { origen: "ARROYITO", destino: "FRANCK", kmReal: 225, kmConv: 225 },
  { origen: "ESCOBAR", destino: "VICENTE LOPEZ", kmReal: 43, kmConv: 45 },
  { origen: "QUILMES", destino: "FLORENCIO VARELA", kmReal: 13, kmConv: 13 },
  { origen: "VILLA SOLDATI", destino: "PORTE&#209;A", kmReal: 660, kmConv: 660 },
  { origen: "PILAR", destino: "CARAPACHAY", kmReal: 42, kmConv: 45 },
  { origen: "BARILOCHE", destino: "ALLEN", kmReal: 468, kmConv: 470 },
  { origen: "SAN FRANCISCO", destino: "BARILOCHE", kmReal: 1757, kmConv: 1755 },
  { origen: "CONCORDIA", destino: "PILAR", kmReal: 391, kmConv: 390 },
  { origen: "GENERAL JUAN MADARIAGA", destino: "BURZACO", kmReal: 330, kmConv: 330 },
  { origen: "FRANCK", destino: "GENERAL JUAN MADARIAGA", kmReal: 804, kmConv: 805 },
  { origen: "BURZACO", destino: "CORDOBA", kmReal: 720, kmConv: 720 },
  { origen: "MADARIAGA", destino: "BURZACO", kmReal: 19, kmConv: 20 },
  { origen: "FRANCK", destino: "MADARIAGA", kmReal: 486, kmConv: 485 },
  { origen: "MAR DEL PLATA", destino: "BURZACO", kmReal: 413, kmConv: 415 },
  { origen: "HURLINGHAM", destino: "9 DE ABRIL", kmReal: 29, kmConv: 30 },
  { origen: "AROCENA", destino: "RAFAELA", kmReal: 159, kmConv: 160 },
  { origen: "MERCEDES", destino: "HURLINGHAM", kmReal: 85, kmConv: 85 },
  { origen: "SAN FERNANDO", destino: "TORTUGUITAS", kmReal: 29, kmConv: 29 },
  { origen: "VILLA DEL PARQUE", destino: "DOCK SUD", kmReal: 24, kmConv: 24 },
  { origen: "INGENIERO BUDGE", destino: "VILLA SOLDATI", kmReal: 11, kmConv: 11 },
  { origen: "SAN MARTIN", destino: "ALTA GRACIA", kmReal: 592, kmConv: 590 },
  { origen: "PUERTO PIRAY", destino: "SAN FERNANDO", kmReal: 1160, kmConv: 1160 },
  { origen: "LEANDRO N ALEM", destino: "PUERTO PIRAY", kmReal: 191, kmConv: 190 },
  { origen: "TRUJUI", destino: "9 DE ABRIL", kmReal: 41, kmConv: 40 },
  { origen: "ALMIRANTE BROWN", destino: "CORDOBA", kmReal: 724, kmConv: 725 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "ALMIRANTE BROWN", kmReal: 14, kmConv: 15 },
  { origen: "MONTE GRANDE", destino: "BARRACAS", kmReal: 40, kmConv: 40 },
  { origen: "BARRACAS", destino: "DALMASIO VELEZ", kmReal: 604, kmConv: 605 },
  { origen: "MONTE GRANDE", destino: "SARANDI", kmReal: 48, kmConv: 50 },
  { origen: "TIO PUJIO", destino: "EZEIZA", kmReal: 595, kmConv: 595 },
  { origen: "BERAZATEGUI", destino: "RAFAELA", kmReal: 632, kmConv: 630 },
  { origen: "TIO PUJIO", destino: "SAN PEDRO", kmReal: 418, kmConv: 420 },
  { origen: "RAFAELA", destino: "ALEM", kmReal: 458, kmConv: 460 },
  { origen: "SIERRA DE LOS PADRES", destino: "SANTA FE", kmReal: 886, kmConv: 885 },
  { origen: "SANTA TERESITA", destino: "SIERRA DE LOS PADRES", kmReal: 212, kmConv: 210 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "BURZACO", kmReal: 15, kmConv: 15 },
  { origen: "CAMPO GRANDE", destino: "SANTA ANA", kmReal: 92, kmConv: 90 },
  { origen: "MERCEDES", destino: "FLORENCIO VARELA", kmReal: 128, kmConv: 130 },
  { origen: "HUDSON", destino: "VILLA SOLDATI", kmReal: 45, kmConv: 45 },
  { origen: "SAN PEDRO", destino: "DON TORCUATO", kmReal: 145, kmConv: 145 },
  { origen: "EZEIZA", destino: "ARROYITO", kmReal: 677, kmConv: 675 },
  { origen: "MERCEDES", destino: "BURZACO", kmReal: 115, kmConv: 115 },
  { origen: "SANTO TOME", destino: "CAMPO GRANDE", kmReal: 858, kmConv: 860 },
  { origen: "LA MATANZA", destino: "VICENTE LOPEZ", kmReal: 42, kmConv: 45 },
  { origen: "VILLA MARIA", destino: "LA MATANZA", kmReal: 556, kmConv: 555 },
  { origen: "TIO PUJIO", destino: "GENERAL PACHECO", kmReal: 538, kmConv: 540 },
  { origen: "SAN JORGE", destino: "BURZACO", kmReal: 534, kmConv: 535 },
  { origen: "EL TALAR", destino: "TORTUGUITAS", kmReal: null, kmConv: 15 },
  { origen: "CHASCOMUS", destino: "RAFAELA", kmReal: 686, kmConv: 685 },
  { origen: "VILLA SOLDATI", destino: "DON TORCUATO", kmReal: 35, kmConv: 35 },
  { origen: "CONCORDIA", destino: "MUNRO", kmReal: 417, kmConv: 415 },
  { origen: "VILLA MARIA", destino: "VICENTE LOPEZ", kmReal: 541, kmConv: 540 },
  { origen: "CRUZ DEL EJE", destino: "FRIAS", kmReal: 283, kmConv: 285 },
  { origen: "FREYRE", destino: "CIUDADELA", kmReal: 607, kmConv: 605 },
  { origen: "MENDOZA", destino: "SAN MARTIN", kmReal: 45, kmConv: 45 },
  { origen: "RANCHOS", destino: "VILLA SOLDATI", kmReal: 129, kmConv: 130 },
  { origen: "VICENTE LOPEZ", destino: "TAPIALES", kmReal: 25, kmConv: 25 },
  { origen: "CAMPANA", destino: "ROSARIO", kmReal: 222, kmConv: 220 },
  { origen: "VICENTE LOPEZ", destino: "VILLA MAIPU", kmReal: 10, kmConv: 10 },
  { origen: "PUERTO PIRAY", destino: "JOSE C. PAZ", kmReal: 1155, kmConv: 1155 },
  { origen: "VILLA MADERO", destino: "CORDOBA", kmReal: 700, kmConv: 700 },
  { origen: "VILLA SOLDATI", destino: "VILLA MADERO", kmReal: null, kmConv: 10 },
  { origen: "TAPIALES", destino: "PILAR", kmReal: 65, kmConv: 65 },
  { origen: "PABLO NOGUES", destino: "TAPIALES", kmReal: 46, kmConv: 45 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "CORDOBA", kmReal: 942, kmConv: 940 },
  { origen: "CASEROS", destino: "VILLA SOLDATI", kmReal: 15, kmConv: 15 },
  { origen: "SANTO TOME", destino: "SAN VICENTE", kmReal: 919, kmConv: 920 },
  { origen: "MUNRO", destino: "ZARATE", kmReal: 78, kmConv: 80 },
  { origen: "SAN ANDRES DE GILES", destino: "SANTO TOME", kmReal: 406, kmConv: 405 },
  { origen: "ITUZAINGO", destino: "FLORENCIO VARELA", kmReal: 68, kmConv: 68 },
  { origen: "LOMA HERMOSA", destino: "PABLO NOGUES", kmReal: 25, kmConv: 25 },
  { origen: "DEVOTO", destino: "ITUZAINGO", kmReal: 589, kmConv: 590 },
  { origen: "VILLA DEL TOTORAL", destino: "DOCK SUD", kmReal: 790, kmConv: 790 },
  { origen: "GOBERNADOR VIRASORO", destino: "CAMPANA", kmReal: 829, kmConv: 830 },
  { origen: "VILLA SOLDATI", destino: "MORTEROS", kmReal: 650, kmConv: 650 },
  { origen: "RAFAELA", destino: "ESPERANZA", kmReal: 60, kmConv: 60 },
  { origen: "BURZACO", destino: "ZARATE", kmReal: 119, kmConv: 120 },
  { origen: "LUIS GUILLON", destino: "9 DE ABRIL", kmReal: 8, kmConv: 10 },
  { origen: "EZEIZA", destino: "9 DE ABRIL", kmReal: 21, kmConv: 20 },
  { origen: "MUNRO", destino: "SAN ANDRES DE GILES", kmReal: 105, kmConv: 105 },
  { origen: "TIGRE", destino: "LUIS GUILLON", kmReal: 51, kmConv: 50 },
  { origen: "CONCORDIA", destino: "TIGRE", kmReal: 418, kmConv: 420 },
  { origen: "BECCAR", destino: "9 DE ABRIL", kmReal: 41, kmConv: 40 },
  { origen: "VILLA DEL PARQUE", destino: "CAMPANA", kmReal: 75, kmConv: 75 },
  { origen: "ITUZAINGO", destino: "ISIDRO CASANOVA", kmReal: 21, kmConv: 20 },
  { origen: "VILLA MERCEDES", destino: "EZEIZA", kmReal: 712, kmConv: 710 },
  { origen: "JESUS MARIA", destino: "CORDOBA", kmReal: 55, kmConv: 55 },
  { origen: "PUERTO IGUAZU", destino: "PUERTO PIRAY", kmReal: 116, kmConv: 115 },
  { origen: "MUNRO", destino: "PILAR", kmReal: 45, kmConv: 45 },
  { origen: "PABLO NOGUES", destino: "EZEIZA", kmReal: 83, kmConv: 85 },
  { origen: "ISIDRO CASANOVA", destino: "9 DE ABRIL", kmReal: 15, kmConv: 15 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "LANUS", kmReal: 25, kmConv: 25 },
  { origen: "BECCAR", destino: "ESTEBAN ECHEVERRIA", kmReal: 72, kmConv: 70 },
  { origen: "CAPILLA DEL MONTE", destino: "CORDOBA", kmReal: 98, kmConv: 100 },
  { origen: "VILLA MERCEDES", destino: "SAN JORGE", kmReal: 463, kmConv: 465 },
  { origen: "MENDOZA", destino: "JESUS MARIA", kmReal: 750, kmConv: 750 },
  { origen: "LA TABLADA", destino: "ZARATE", kmReal: 96, kmConv: 95 },
  { origen: "GENERAL RODRIGUEZ", destino: "TORTUGUITAS", kmReal: 30, kmConv: 30 },
  { origen: "SAN JUSTO", destino: "RIO CUARTO", kmReal: 602, kmConv: 600 },
  { origen: "ZARATE", destino: "SARANDI", kmReal: 108, kmConv: 110 },
  { origen: "TORTUGUITAS", destino: "UDAONDO", kmReal: 38, kmConv: 40 },
  { origen: "VALENTIN ALSINA", destino: "DON TORCUATO", kmReal: 43, kmConv: 45 },
  { origen: "SARANDI", destino: "VILLA MARIA", kmReal: 563, kmConv: 565 },
  { origen: "VILLA MARIA", destino: "DOCK SUD", kmReal: 560, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "BECCAR", kmReal: 543, kmConv: 545 },
  { origen: "SANTO TOME", destino: "9 DE ABRIL", kmReal: 470, kmConv: 470 },
  { origen: "CAMPANA", destino: "QUILMES", kmReal: 100, kmConv: 100 },
  { origen: "CAMPANA", destino: "LA TABLADA", kmReal: 83, kmConv: 85 },
  { origen: "CONCORDIA", destino: "CAMPANA", kmReal: 351, kmConv: 350 },
  { origen: "ESCOBAR", destino: "9 DE ABRIL", kmReal: 74, kmConv: 75 },
  { origen: "BAHIA BLANCA", destino: "BURZACO", kmReal: 633, kmConv: 635 },
  { origen: "VILLA SOLDATI", destino: "LA PLATA", kmReal: 67, kmConv: 65 },
  { origen: "ESCOBAR", destino: "BECCAR", kmReal: 35, kmConv: 35 },
  { origen: "GENERAL LAGOS", destino: "SAN FRANCISCO", kmReal: 310, kmConv: 310 },
  { origen: "VILLA SOLDATI", destino: "GENERAL LAGOS", kmReal: 290, kmConv: 290 },
  { origen: "MORON", destino: "MUNRO", kmReal: 27, kmConv: 25 },
  { origen: "ESCOBAR", destino: "MORON", kmReal: 62, kmConv: 60 },
  { origen: "VILLA MARIA", destino: "ESCOBAR", kmReal: 500, kmConv: 500 },
  { origen: "ROSARIO", destino: "RIO SEGUNDO", kmReal: 362, kmConv: 360 },
  { origen: "DOCK SUD", destino: "ROSARIO", kmReal: 307, kmConv: 305 },
  { origen: "BARADERO", destino: "TAPIALES", kmReal: 174, kmConv: 175 },
  { origen: "GENERAL LAGOS", destino: "BECCAR", kmReal: 308, kmConv: 310 },
  { origen: "DOCK SUD", destino: "VILLA MERCEDES", kmReal: 707, kmConv: 705 },
  { origen: "BURZACO", destino: "ROSARIO", kmReal: 337, kmConv: 335 },
  { origen: "CANNING", destino: "BURZACO", kmReal: 27, kmConv: 25 },
  { origen: "TIO PUJIO", destino: "CANNING", kmReal: 615, kmConv: 615 },
  { origen: "MERCEDES", destino: "MORON", kmReal: 82, kmConv: 80 },
  { origen: "GENERAL PACHECO", destino: "BURZACO", kmReal: 60, kmConv: 60 },
  { origen: "GARIN", destino: "VICENTE LOPEZ", kmReal: 32, kmConv: 30 },
  { origen: "TIO PUJIO", destino: "GARIN", kmReal: 530, kmConv: 530 },
  { origen: "JOSE C. PAZ", destino: "BURZACO", kmReal: 64, kmConv: 65 },
  { origen: "ESCOBAR", destino: "BURZACO", kmReal: 77, kmConv: 75 },
  { origen: "VILLA SOLDATI", destino: "RIO SEGUNDO", kmReal: 666, kmConv: 665 },
  { origen: "CANNING", destino: "VILLA SOLDATI", kmReal: 29, kmConv: 30 },
  { origen: "VILLA SOLDATI", destino: "CANNING", kmReal: 29, kmConv: 30 },
  { origen: "RAFAELA", destino: "ESTEBAN ECHEVERRIA", kmReal: 564, kmConv: 565 },
  { origen: "RAFAELA", destino: "ESCOBAR", kmReal: 487, kmConv: 490 },
  { origen: "RIO CUARTO", destino: "CONCARAN", kmReal: 169, kmConv: 170 },
  { origen: "MUNRO", destino: "CORDOBA", kmReal: 680, kmConv: 680 },
  { origen: "MAR DEL PLATA", destino: "MUNRO", kmReal: 433, kmConv: 435 },
  { origen: "ZARATE", destino: "GOBERNADOR VIRASORO", kmReal: 823, kmConv: 825 },
  { origen: "PILAR", destino: "DON TORCUATO", kmReal: 32, kmConv: 30 },
  { origen: "QUILMES", destino: "SAN ANDRES DE GILES", kmReal: 125, kmConv: 125 },
  { origen: "MAR DEL PLATA", destino: "TORTUGUITAS", kmReal: 459, kmConv: 460 },
  { origen: "BECCAR", destino: "ISIDRO CASANOVA", kmReal: 36, kmConv: 35 },
  { origen: "VALENTIN ALSINA", destino: "TORTUGUITAS", kmReal: 58, kmConv: 60 },
  { origen: "PUERTO RICO", destino: "MONTE CARLO", kmReal: 49, kmConv: 50 },
  { origen: "LOMAS DEL MIRADOR", destino: "SAN JUSTO", kmReal: 5, kmConv: 5 },
  { origen: "CONCORDIA", destino: "LOMAS DEL MIRADOR", kmReal: 434, kmConv: 435 },
  { origen: "ITUZAINGO", destino: "SANTA ANA", kmReal: 140, kmConv: 140 },
  { origen: "ALTA GRACIA", destino: "GARIN", kmReal: 668, kmConv: 670 },
  { origen: "9 DE ABRIL", destino: "CAMPANA", kmReal: 97, kmConv: 95 },
  { origen: "ESTACION MATILDE", destino: "DOCK SUD", kmReal: 457, kmConv: 455 },
  { origen: "ESTACION MATILDE", destino: "ZONA PORTUARIA", kmReal: 465, kmConv: 465 },
  { origen: "DOCK SUD", destino: "ESTACION MATILDE", kmReal: 457, kmConv: 455 },
  { origen: "CHACARITA", destino: "SAN FRANCISCO", kmReal: 553, kmConv: 555 },
  { origen: "OBERA", destino: "CAMPO GRANDE", kmReal: null, kmConv: 43 },
  { origen: "VILLA MERCEDES", destino: "PILAR", kmReal: 676, kmConv: 675 },
  { origen: "ITUZAINGO", destino: "MORON", kmReal: null, kmConv: 7 },
  { origen: "PUERTO MADERO", destino: "MORENO", kmReal: 42, kmConv: 40 },
  { origen: "MERCEDES", destino: "ZARATE", kmReal: 101, kmConv: 100 },
  { origen: "BARRACAS", destino: "SANTO TOME", kmReal: 462, kmConv: 460 },
  { origen: "HAEDO", destino: "BURZACO", kmReal: 35, kmConv: 35 },
  { origen: "SAN JORGE", destino: "HAEDO", kmReal: 497, kmConv: 495 },
  { origen: "MUNRO", destino: "CHACARITA", kmReal: 11, kmConv: 10 },
  { origen: "FREYRE", destino: "CHACARITA", kmReal: 582, kmConv: 580 },
  { origen: "ITUZAINGO", destino: "PUERTO MADERO", kmReal: 34, kmConv: 35 },
  { origen: "PILAR", destino: "9 DE ABRIL", kmReal: 101, kmConv: 100 },
  { origen: "DON TORCUATO", destino: "ZARATE", kmReal: 66, kmConv: 65 },
  { origen: "SAN MARTIN", destino: "ZARATE", kmReal: 83, kmConv: 85 },
  { origen: "SANTA ANA", destino: "CORDOBA", kmReal: 25, kmConv: 25 },
  { origen: "CORDOBA", destino: "SANTA ANA", kmReal: 25, kmConv: 25 },
  { origen: "VICENTE LOPEZ", destino: "ROSARIO", kmReal: 289, kmConv: 290 },
  { origen: "RAMALLO", destino: "ISIDRO CASANOVA", kmReal: 250, kmConv: 250 },
  { origen: "VILLA SOLDATI", destino: "RAMALLO", kmReal: 235, kmConv: 235 },
  { origen: "SAN JORGE", destino: "PILAR", kmReal: 455, kmConv: 455 },
  { origen: "GENERAL PACHECO", destino: "VICENTE LOPEZ", kmReal: 24, kmConv: 25 },
  { origen: "TORTUGUITAS", destino: "GENERAL PACHECO", kmReal: 15, kmConv: 15 },
  { origen: "PUERTO PIRAY", destino: "SAN MARTIN", kmReal: 1165, kmConv: 1165 },
  { origen: "PILAR", destino: "MALVINAS ARGENTINAS", kmReal: 23, kmConv: 25 },
  { origen: "ITUZAINGO", destino: "BECCAR", kmReal: 37, kmConv: 35 },
  { origen: "NUEVA POMPEYA", destino: "SAN ANDRES DE GILES", kmReal: 102, kmConv: 100 },
  { origen: "MENDOZA", destino: "NUEVA POMPEYA", kmReal: 1040, kmConv: 1040 },
  { origen: "ZARATE", destino: "LANUS", kmReal: 107, kmConv: 105 },
  { origen: "BAHIA BLANCA", destino: "ZARATE", kmReal: 751, kmConv: 750 },
  { origen: "ZARATE", destino: "DOCK SUD", kmReal: 101, kmConv: 100 },
  { origen: "VILLA SOLDATI", destino: "SAN NICOLAS", kmReal: 255, kmConv: 255 },
  { origen: "SAN NICOLAS", destino: "ISIDRO CASANOVA", kmReal: 270, kmConv: 270 },
  { origen: "TIO PUJIO", destino: "SAN NICOLAS", kmReal: 343, kmConv: 345 },
  { origen: "SAN MARTIN", destino: "LOMA HERMOSA", kmReal: null, kmConv: 10 },
  { origen: "GUALEGUAYCHU", destino: "TORTUGUITAS", kmReal: 203, kmConv: 205 },
  { origen: "CONSTITUCION", destino: "MORON", kmReal: 32, kmConv: 30 },
  { origen: "SAN FRANCISCO", destino: "CONSTITUCION", kmReal: 571, kmConv: 570 },
  { origen: "VILLA URQUIZA", destino: "CAMPANA", kmReal: 69, kmConv: 70 },
  { origen: "RIO PRIMERO", destino: "SAN FRANCISCO", kmReal: 153, kmConv: 155 },
  { origen: "CORDOBA", destino: "RIO PRIMERO", kmReal: 61, kmConv: 60 },
  { origen: "VILLA CONSTITUCION", destino: "BIGAND", kmReal: 100, kmConv: 100 },
  { origen: "ZARATE", destino: "ZONA PORTUARIA", kmReal: 88, kmConv: 90 },
  { origen: "SAN JUSTO", destino: "9 DE ABRIL", kmReal: 11, kmConv: 10 },
  { origen: "VILLA URQUIZA", destino: "PILAR", kmReal: 56, kmConv: 55 },
  { origen: "ITUZAINGO", destino: "GOBERNADOR VIRASORO", kmReal: 102, kmConv: 100 },
  { origen: "VILLA ORTUZAR", destino: "PILAR", kmReal: 50, kmConv: 50 },
  { origen: "SAN FRANCISCO", destino: "VILLA ORTUZAR", kmReal: 555, kmConv: 555 },
  { origen: "VILLA SOLDATI", destino: "PUERTO ESPERANZA", kmReal: 1237, kmConv: 1240 },
  { origen: "BARRACAS", destino: "SAN ANDRES DE GILES", kmReal: 110, kmConv: 110 },
  { origen: "GONZALEZ CATAN", destino: "TORTUGUITAS", kmReal: 71, kmConv: 70 },
  { origen: "VILLA SOLDATI", destino: "MORON", kmReal: 25, kmConv: 25 },
  { origen: "BARRACAS", destino: "ROSARIO", kmReal: 305, kmConv: 305 },
  { origen: "FREYRE", destino: "ESTEBAN ECHEVERRIA", kmReal: 619, kmConv: 620 },
  { origen: "RECREO", destino: "EZEIZA", kmReal: 510, kmConv: 510 },
  { origen: "RAMOS MEJIA", destino: "ZARATE", kmReal: 89, kmConv: 90 },
  { origen: "9 DE ABRIL", destino: "TORTUGUITAS", kmReal: 66, kmConv: 65 },
  { origen: "MONTEVIDEO", destino: "DON TORCUATO", kmReal: 546, kmConv: 545 },
  { origen: "MONTEVIDEO", destino: "GENERAL PACHECO", kmReal: 541, kmConv: 540 },
  { origen: "SAN VICENTE", destino: "VILLA SOLDATI", kmReal: 52, kmConv: 50 },
  { origen: "GARIN", destino: "ROSARIO", kmReal: 261, kmConv: 260 },
  { origen: "BECCAR", destino: "CAMPANA", kmReal: 63, kmConv: 63 },
  { origen: "GARIN", destino: "9 DE ABRIL", kmReal: 58, kmConv: 58 },
  { origen: "RECREO", destino: "SAN JORGE", kmReal: 171, kmConv: 170 },
  { origen: "VILLA SOLDATI", destino: "PUERTO PIRAY", kmReal: 1178, kmConv: 1180 },
  { origen: "TAPIALES", destino: "VALENTIN ALSINA", kmReal: 13, kmConv: 15 },
  { origen: "MORTEROS", destino: "ZARATE", kmReal: 583, kmConv: 580 },
  { origen: "ZARATE", destino: "MORTEROS", kmReal: 583, kmConv: 580 },
  { origen: "EZEIZA", destino: "TORTUGUITAS", kmReal: 84, kmConv: 85 },
  { origen: "UDAONDO", destino: "GARIN", kmReal: 37, kmConv: 35 },
  { origen: "TORTUGUITAS", destino: "9 DE ABRIL", kmReal: 72, kmConv: 70 },
  { origen: "COLONIA CAROYA", destino: "TORTUGUITAS", kmReal: 712, kmConv: 710 },
  { origen: "SUNCHALES", destino: "RAMOS MEJIA", kmReal: 585, kmConv: 585 },
  { origen: "LOMAS DE ZAMORA", destino: "9 DE ABRIL", kmReal: 8, kmConv: 8 },
  { origen: "MENDOZA", destino: "LOMAS DE ZAMORA", kmReal: 1055, kmConv: 1055 },
  { origen: "MORON", destino: "CORDOBA", kmReal: 709, kmConv: 710 },
  { origen: "MORENO", destino: "MORON", kmReal: 19, kmConv: 19 },
  { origen: "ISIDRO CASANOVA", destino: "DON TORCUATO", kmReal: 66, kmConv: 65 },
  { origen: "VILLA DEL PARQUE", destino: "9 DE ABRIL", kmReal: 23, kmConv: 25 },
  { origen: "AVELLANEDA", destino: "VICENTE LOPEZ", kmReal: 22, kmConv: 20 },
  { origen: "VILLA DEL TOTORAL", destino: "ZONA PORTUARIA", kmReal: 773, kmConv: 775 },
  { origen: "BARRACAS", destino: "VILLA DEL TOTORAL", kmReal: 781, kmConv: 780 },
  { origen: "TORTUGUITAS", destino: "COLONIA CAROYA", kmReal: 711, kmConv: 710 },
  { origen: "ZONA PORTUARIA", destino: "VILLA MARIA", kmReal: 560, kmConv: 560 },
  { origen: "PILAR", destino: "MORENO", kmReal: 31, kmConv: 30 },
  { origen: "GUALEGUAYCHU", destino: "CONCORDIA", kmReal: 206, kmConv: 205 },
  { origen: "BIGAND", destino: "SAN JORGE", kmReal: 190, kmConv: 190 },
  { origen: "SAN JUSTO", destino: "MATADEROS", kmReal: 16, kmConv: 15 },
  { origen: "MALVINAS ARGENTINAS", destino: "VILLA SOLDATI", kmReal: 45, kmConv: 45 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
