/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 7 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "CORDOBA", destino: "CARLOS SPEGAZZINI", kmReal: 745, kmConv: 745 },
  { origen: "TORTUGUITAS", destino: "SAN FRANCISCO", kmReal: 552, kmConv: 550 },
  { origen: "RAFAELA", destino: "EL TALAR", kmReal: 508, kmConv: 510 },
  { origen: "ZONA PORTUARIA", destino: "LANUS", kmReal: 25, kmConv: 25 },
  { origen: "PABLO NOGUES", destino: "BARADERO", kmReal: 120, kmConv: 120 },
  { origen: "TIO PUJIO", destino: "PABLO NOGUES", kmReal: 538, kmConv: 540 },
  { origen: "VILLA SOLDATI", destino: "VILLA LA RIVERA", kmReal: 346, kmConv: 345 },
  { origen: "VILLA LA RIVERA", destino: "ZONA PORTUARIA", kmReal: 338, kmConv: 340 },
  { origen: "SUNCHALES", destino: "VILLA LA RIVERA", kmReal: 262, kmConv: 260 },
  { origen: "PUERTO PIRAY", destino: "VIRREY DEL PINO", kmReal: 1234, kmConv: 1235 },
  { origen: "MUNRO", destino: "TAPIALES", kmReal: 42, kmConv: 40 },
  { origen: "ITUZAINGO", destino: "PUERTO PIRAY", kmReal: 278, kmConv: 280 },
  { origen: "VILLA SOLDATI", destino: "TAPIALES", kmReal: 10, kmConv: 10 },
  { origen: "CARLOS SPEGAZZINI", destino: "RIO CUARTO", kmReal: 675, kmConv: 675 },
  { origen: "GENERAL PACHECO", destino: "CORDOBA", kmReal: 664, kmConv: 665 },
  { origen: "ZONA PORTUARIA", destino: "GENERAL PACHECO", kmReal: 34, kmConv: 35 },
  { origen: "DOCK SUD", destino: "CORDOBA", kmReal: 713, kmConv: 705 },
  { origen: "LA PLATA", destino: "DOCK SUD", kmReal: null, kmConv: 50 },
  { origen: "SAN JORGE", destino: "ISIDRO CASANOVA", kmReal: 524, kmConv: 525 },
  { origen: "ESCOBAR", destino: "TORTUGUITAS", kmReal: 24, kmConv: 25 },
  { origen: "TIO PUJIO", destino: "ESCOBAR", kmReal: 519, kmConv: 520 },
  { origen: "ISIDRO CASANOVA", destino: "VALENTIN ALSINA", kmReal: 28, kmConv: 30 },
  { origen: "TORTUGUITAS", destino: "MORENO", kmReal: 33, kmConv: 30 },
  { origen: "ZONA PORTUARIA", destino: "TORTUGUITAS", kmReal: 42, kmConv: 40 },
  { origen: "ZONA PORTUARIA", destino: "VALENTIN ALSINA", kmReal: 15, kmConv: 15 },
  { origen: "! ELDORADO", destino: "PUERTO BOSSETTI", kmReal: null, kmConv: 70 },
  { origen: "SAN JORGE", destino: "FRANCK", kmReal: 132, kmConv: 130 },
  { origen: "GARIN", destino: "VILLA SOLDATI", kmReal: 59, kmConv: 60 },
  { origen: "SAN JORGE", destino: "SUNCHALES", kmReal: 142, kmConv: 140 },
  { origen: "SUNCHALES", destino: "ZONA PORTUARIA", kmReal: 596, kmConv: 595 },
  { origen: "PARQUE PATRICIO", destino: "VILLA MARIA", kmReal: 562, kmConv: 560 },
  { origen: "JOSE C. PAZ", destino: "VILLA SOLDATI", kmReal: 45, kmConv: 45 },
  { origen: "VILLA MARIA", destino: "JOSE C. PAZ", kmReal: 530, kmConv: 530 },
  { origen: "MUNRO", destino: "VICENTE LOPEZ", kmReal: 6, kmConv: 5 },
  { origen: "TIO PUJIO", destino: "MUNRO", kmReal: 554, kmConv: 555 },
  { origen: "SAN MARTIN", destino: "MUNRO", kmReal: 8, kmConv: 10 },
  { origen: "CORDOBA", destino: "SAN MARTIN", kmReal: 688, kmConv: 690 },
  { origen: "EL TALAR", destino: "CORDOBA", kmReal: 665, kmConv: 665 },
  { origen: "GARIN", destino: "CORDOBA", kmReal: 655, kmConv: 655 },
  { origen: "VICENTE LOPEZ", destino: "VALENTIN ALSINA", kmReal: 24, kmConv: 25 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "VILLA SOLDATI", kmReal: 30, kmConv: 30 },
  { origen: "VILLA MARIA", destino: "ESTEBAN ECHEVERRIA", kmReal: 580, kmConv: 580 },
  { origen: "ESPERANZA", destino: "FRANCK", kmReal: null, kmConv: 20 },
  { origen: "BECCAR", destino: "GARIN", kmReal: 25, kmConv: 25 },
  { origen: "SAN JORGE", destino: "BECCAR", kmReal: 474, kmConv: 475 },
  { origen: "LA PLATA", destino: "TAPIALES", kmReal: 73, kmConv: 75 },
  { origen: "MUNRO", destino: "LA PLATA", kmReal: 77, kmConv: 80 },
  { origen: "SAN MARTIN", destino: "VICENTE LOPEZ", kmReal: 11, kmConv: 10 },
  { origen: "TIO PUJIO", destino: "SAN MARTIN", kmReal: 563, kmConv: 565 },
  { origen: "LOMA HERMOSA", destino: "TORTUGUITAS", kmReal: 31, kmConv: 30 },
  { origen: "TORTUGUITAS", destino: "LOMA HERMOSA", kmReal: 31, kmConv: 30 },
  { origen: "VALENTIN ALSINA", destino: "CORDOBA", kmReal: 708, kmConv: 710 },
  { origen: "! MONTEVIDEO", destino: "EL TALAR", kmReal: 540, kmConv: 540 },
  { origen: "CIUDADELA", destino: "SAN JUSTO", kmReal: 10, kmConv: 10 },
  { origen: "SAN FRANCISCO", destino: "CIUDADELA", kmReal: 558, kmConv: 560 },
  { origen: "SAN JUSTO", destino: "GENERAL RODRIGUEZ", kmReal: 43, kmConv: 45 },
  { origen: "ISIDRO CASANOVA", destino: "PILAR", kmReal: 74, kmConv: 75 },
  { origen: "EZEIZA", destino: "GENERAL RODRIGUEZ", kmReal: 71, kmConv: 70 },
  { origen: "ISIDRO CASANOVA", destino: "GENERAL RODRIGUEZ", kmReal: 43, kmConv: 45 },
  { origen: "DON TORCUATO", destino: "BARADERO", kmReal: 125, kmConv: 125 },
  { origen: "VILLA MERCEDES", destino: "PARANÁ", kmReal: 590, kmConv: 590 },
  { origen: "! VILLA ESPIL", destino: "BURZACO", kmReal: 105, kmConv: 105 },
  { origen: "BURZACO", destino: "SANTA FE", kmReal: 492, kmConv: 490 },
  { origen: "AVELLANEDA", destino: "VILLA SOLDATI", kmReal: null, kmConv: 20 },
  { origen: "GENERAL PACHECO", destino: "VILLA SOLDATI", kmReal: 52, kmConv: 50 },
  { origen: "LONGCHAMPS", destino: "VILLA SOLDATI", kmReal: 27, kmConv: 25 },
  { origen: "FRANCK", destino: "GENERAL PACHECO", kmReal: 442, kmConv: 440 },
  { origen: "PILAR", destino: "LONGCHAMPS", kmReal: null, kmConv: 90 },
  { origen: "PORTE&#209;A", destino: "PILAR", kmReal: 568, kmConv: 570 },
  { origen: "9 DE ABRIL", destino: "GENERAL RODRIGUEZ", kmReal: null, kmConv: 60 },
  { origen: "CIPOLLETTI", destino: "VILLA ESPIL", kmReal: 1069, kmConv: 1070 },
  { origen: "CATRILO", destino: "CORDOBA", kmReal: 623, kmConv: 625 },
  { origen: "NEUQUEN", destino: "CATRILO", kmReal: 612, kmConv: 615 },
  { origen: "MONTE GRANDE", destino: "CAMPANA", kmReal: 109, kmConv: 110 },
  { origen: "! SAN JERONIMO NORTE", destino: "SAN FRANCISCO", kmReal: 584, kmConv: 585 },
  { origen: "TORTUGUITAS", destino: "SAN JERONIMO NORTE", kmReal: null, kmConv: 70 },
  { origen: "BENAVIDEZ", destino: "TORTUGUITAS", kmReal: null, kmConv: 15 },
  { origen: "LA PLATA", destino: "VILLA SOLDATI", kmReal: null, kmConv: 65 },
  { origen: "DOCK SUD", destino: "SAN JORGE", kmReal: 501, kmConv: 500 },
  { origen: "SAN JORGE", destino: "DOCK SUD", kmReal: 501, kmConv: 500 },
  { origen: "ESCOBAR", destino: "BENAVIDEZ", kmReal: null, kmConv: 15 },
  { origen: "RIO COLORADO", destino: "LA PLATA", kmReal: 798, kmConv: 780 },
  { origen: "NEUQUEN", destino: "RIO COLORADO", kmReal: 365, kmConv: 365 },
  { origen: "CRUCECITA", destino: "CORDOBA", kmReal: 705, kmConv: 705 },
  { origen: "VILLA SOLDATI", destino: "CRUCECITA", kmReal: null, kmConv: 20 },
  { origen: "! LANUS ESTE", destino: "MONTE GRANDE", kmReal: null, kmConv: 20 },
  { origen: "! CONCORDIA", destino: "LANUS ESTE", kmReal: 446, kmConv: 445 },
  { origen: "! EL JAGUEL", destino: "CIPOLETTI", kmReal: null, kmConv: 25 },
  { origen: "! PABLO NOGUES", destino: "EL JAGUEL", kmReal: null, kmConv: 80 },
  { origen: "SAN JUSTO", destino: "SAN FRANCISCO", kmReal: 565, kmConv: 565 },
  { origen: "MORENO", destino: "SAN JUSTO", kmReal: null, kmConv: 25 },
  { origen: "GENERAL RODRIGUEZ", destino: "BAHIA BLANCA", kmReal: 631, kmConv: 630 },
  { origen: "CORONEL BRANDSEN", destino: "GENERAL RODRIGUEZ", kmReal: 120, kmConv: 120 },
  { origen: "! PARQUE PATRICIOS", destino: "CHIVILCOY", kmReal: 164, kmConv: 165 },
  { origen: "GOBERNADOR VIRASORO", destino: "AVELLANEDA", kmReal: 914, kmConv: 915 },
  { origen: "DOCK SUD", destino: "MORTEROS", kmReal: 654, kmConv: 655 },
  { origen: "ZONA PORTUARIA", destino: "MORTEROS", kmReal: 643, kmConv: 645 },
  { origen: "SAN FRANCISCO", destino: "PABLO NOGUES", kmReal: 529, kmConv: 530 },
  { origen: "SAN NICOLAS", destino: "VILLA SOLDATI", kmReal: 240, kmConv: 240 },
  { origen: "! FRONTERA", destino: "SAN NICOLAS", kmReal: 347, kmConv: 350 },
  { origen: "PARQUE PATRICIO", destino: "ZARATE", kmReal: 101, kmConv: 100 },
  { origen: "CAPITAL FEDERAL", destino: "ZARATE", kmReal: null, kmConv: 85 },
  { origen: "ZARATE", destino: "NEUQUEN", kmReal: 1138, kmConv: 1140 },
  { origen: "GENERAL PACHECO", destino: "SAN FRANCISCO", kmReal: 529, kmConv: 530 },
  { origen: "CIPOLLETTI", destino: "CORONEL BRANDSEN", kmReal: 1133, kmConv: 1135 },
  { origen: "VILLA LUGANO", destino: "SAN FRANCISCO", kmReal: 567, kmConv: 570 },
  { origen: "! MONTE GRANDE", destino: "VILLA LUGANO", kmReal: null, kmConv: 25 },
  { origen: "GENERAL RODRIGUEZ", destino: "ZARATE", kmReal: null, kmConv: 70 },
  { origen: "PILAR", destino: "ZARATE", kmReal: null, kmConv: 50 },
  { origen: "TIGRE", destino: "LANUS", kmReal: null, kmConv: 45 },
  { origen: "DOCK SUD", destino: "RIO SEGUNDO", kmReal: 665, kmConv: 665 },
  { origen: "RIO SEGUNDO", destino: "DOCK SUD", kmReal: 665, kmConv: 665 },
  { origen: "COLONIA CAROYA", destino: "EZEIZA", kmReal: 781, kmConv: 780 },
  { origen: "FREYRE", destino: "ZONA PORTUARIA", kmReal: 588, kmConv: 590 },
  { origen: "! HAEDO", destino: "SAN JUSTO", kmReal: null, kmConv: 10 },
  { origen: "TIO PUJIO", destino: "HAEDO", kmReal: 574, kmConv: 575 },
  { origen: "DON TORCUATO", destino: "VILLA SOLDATI", kmReal: 46, kmConv: 45 },
  { origen: "DEVOTO", destino: "DON TORCUATO", kmReal: 561, kmConv: 560 },
  { origen: "BAHIA BLANCA", destino: "VILLA SOLDATI", kmReal: 632, kmConv: 630 },
  { origen: "ITUZAINGO", destino: "VILLA SOLDATI", kmReal: 25, kmConv: 25 },
  { origen: "TIO PUJIO", destino: "ITUZAINGO", kmReal: 572, kmConv: 570 },
  { origen: "BARADERO", destino: "TORTUGUITAS", kmReal: 121, kmConv: 120 },
  { origen: "BARRACAS", destino: "RAFAELA", kmReal: 549, kmConv: 540 },
  { origen: "! ISIDRO CASANOVA", destino: "CAMPANA", kmReal: 107, kmConv: 110 },
  { origen: "FREYRE", destino: "MORENO", kmReal: 593, kmConv: 595 },
  { origen: "PARANÁ", destino: "SANTA FE", kmReal: 31, kmConv: 30 },
  { origen: "! PUERTO PIRAY", destino: "PARANA", kmReal: 927, kmConv: 930 },
  { origen: "CONCORDIA", destino: "GENERAL RODRIGUEZ", kmReal: 408, kmConv: 410 },
  { origen: "! POMPEYA", destino: "CAPITAL FEDERAL", kmReal: null, kmConv: 10 },
  { origen: "! VILLA MERCEDES", destino: "POMPEYA", kmReal: 694, kmConv: 695 },
  { origen: "VILLA SOLDATI", destino: "VALENTIN ALSINA", kmReal: null, kmConv: 4 },
  { origen: "! HURLINGHAM", destino: "PILAR", kmReal: 49, kmConv: 50 },
  { origen: "LAFERRERE", destino: "ZARATE", kmReal: 108, kmConv: 110 },
  { origen: "BARRACAS", destino: "VILLA MERCEDES", kmReal: 699, kmConv: 700 },
  { origen: "VILLA SOLDATI", destino: "BARRACAS", kmReal: null, kmConv: 5 },
  { origen: "VILLA SOLDATI", destino: "DOCK SUD", kmReal: null, kmConv: 10 },
  { origen: "! BARRACAS", destino: "DESVIO ARIJON", kmReal: 424, kmConv: 425 },
  { origen: "DOCK SUD", destino: "ZONA PORTUARIA", kmReal: null, kmConv: 10 },
  { origen: "FRONTERA", destino: "LAFERRERE", kmReal: 576, kmConv: 600 },
  { origen: "MONTE CARLO", destino: "PUERTO IGUAZU", kmReal: 123, kmConv: 125 },
  { origen: "CONCORDIA", destino: "9 DE ABRIL", kmReal: 443, kmConv: 445 },
  { origen: "MUNRO", destino: "GENERAL RODRIGUEZ", kmReal: null, kmConv: 55 },
  { origen: "VILLA SOLDATI", destino: "9 DE ABRIL", kmReal: null, kmConv: 20 },
  { origen: "LA PLATA", destino: "VALENTIN ALSINA", kmReal: null, kmConv: 60 },
  { origen: "VALENTIN ALSINA", destino: "NEUQUEN", kmReal: 1136, kmConv: 1135 },
  { origen: "DON TORCUATO", destino: "SAN ANDRES DE GILES", kmReal: null, kmConv: 100 },
  { origen: "CIPOLLETTI", destino: "MERCEDES", kmReal: 1044, kmConv: 1045 },
  { origen: "MONTE GRANDE", destino: "VILLA SOLDATI", kmReal: 33, kmConv: 35 },
  { origen: "SAN FRANCISCO", destino: "MONTE GRANDE", kmReal: 589, kmConv: 590 },
  { origen: "VILLA SOLDATI", destino: "TORTUGUITAS", kmReal: 61, kmConv: 60 },
  { origen: "ZONA PORTUARIA", destino: "BARRACAS", kmReal: null, kmConv: 10 },
  { origen: "! CONCORDIA", destino: "MUNRO", kmReal: 413, kmConv: 415 },
  { origen: "! CONCORDIA", destino: "SALSIPUEDES", kmReal: 687, kmConv: 685 },
  { origen: "ROSARIO", destino: "CONCORDIA", kmReal: 360, kmConv: 360 },
  { origen: "GARIN", destino: "TAPIALES", kmReal: 50, kmConv: 50 },
  { origen: "GARIN", destino: "FRANCK", kmReal: 435, kmConv: 435 },
  { origen: "! ESTEBAN ECHEVERRIA", destino: "CARLOS SPEGAZZINI", kmReal: null, kmConv: 15 },
  { origen: "LAFERRERE", destino: "CORDOBA", kmReal: 714, kmConv: 715 },
  { origen: "! CARLOS SPEGAZZINI", destino: "LAFERRERERE", kmReal: null, kmConv: 25 },
  { origen: "TAPIALES", destino: "CAMPANA", kmReal: null, kmConv: 90 },
  { origen: "SAN FRANCISCO", destino: "MORENO", kmReal: 563, kmConv: 565 },
  { origen: "ESCOBAR", destino: "ESTEBAN ECHEVERRIA", kmReal: null, kmConv: 80 },
  { origen: "VILLA SOLDATI", destino: "LANUS", kmReal: 8, kmConv: 10 },
  { origen: "FRANCK", destino: "TAPIALES", kmReal: 482, kmConv: 480 },
  { origen: "! CAMPOR GRANDE", destino: "PUERTO PIRAY", kmReal: 124, kmConv: 125 },
  { origen: "! PUERTO PIRAY", destino: "SAN LUIS", kmReal: 1601, kmConv: 1600 },
  { origen: "! AZUL", destino: "RETIRO", kmReal: 304, kmConv: 305 },
  { origen: "RETIRO", destino: "CORDOBA", kmReal: 696, kmConv: 695 },
  { origen: "GENERAL RODRIGUEZ", destino: "VALENTIN ALSINA", kmReal: null, kmConv: 55 },
  { origen: "SAN ANDRES DE GILES", destino: "SANTA FE", kmReal: 396, kmConv: 395 },
  { origen: "VILLA URQUIZA", destino: "LANUS", kmReal: null, kmConv: 25 },
  { origen: "SAN JUSTO", destino: "VILLA SOLDATI", kmReal: 16, kmConv: 15 },
  { origen: "BURZACO", destino: "VILLA SOLDATI", kmReal: null, kmConv: 20 },
  { origen: "TORTUGUITAS", destino: "ARROYITO", kmReal: 623, kmConv: 625 },
  { origen: "! ESTEBAN ECHEVERRIA", destino: "CHASCOMUS", kmReal: 123, kmConv: 125 },
  { origen: "CHASCOMUS", destino: "SAN FRANCISCO", kmReal: 688, kmConv: 690 },
  { origen: "! DOCK SUD", destino: "VILLA MERCEDES", kmReal: 705, kmConv: 705 },
  { origen: "VILLA MERCEDES", destino: "ZONA PORTUARIA", kmReal: 706, kmConv: 705 },
  { origen: "! SUARDI", destino: "BRINKMANN", kmReal: null, kmConv: 40 },
  { origen: "ESCOBAR", destino: "GENERAL RODRIGUEZ", kmReal: 73, kmConv: 75 },
  { origen: "SAN FRANCISCO", destino: "BURZACO", kmReal: 585, kmConv: 585 },
  { origen: "! CHIVILCOY", destino: "FRONTERA", kmReal: 525, kmConv: 525 },
  { origen: "CIPOLLETTI", destino: "AZUL", kmReal: 952, kmConv: 950 },
  { origen: "VILLA URQUIZA", destino: "SAN ANDRES DE GILES", kmReal: 111, kmConv: 110 },
  { origen: "TORTUGUITAS", destino: "SANTO TOME", kmReal: 427, kmConv: 425 },
  { origen: "VILLA SOLDATI", destino: "FRANCK", kmReal: 479, kmConv: 480 },
  { origen: "9 DE JULIO", destino: "VILLA SOLDATI", kmReal: 262, kmConv: 260 },
  { origen: "LA PLATA", destino: "MUNRO", kmReal: 78, kmConv: 80 },
  { origen: "TAPIALES", destino: "MORENO", kmReal: 55, kmConv: 55 },
  { origen: "TIO PUJIO", destino: "ZONA PORTUARIA", kmReal: 567, kmConv: 565 },
  { origen: "MORENO", destino: "RIO CUARTO", kmReal: 572, kmConv: 570 },
  { origen: "! ESCOBAR", destino: "MORENO", kmReal: null, kmConv: 55 },
  { origen: "ISIDRO CASANOVA", destino: "MORENO", kmReal: 45, kmConv: 45 },
  { origen: "! FRANCK", destino: "LOS CARDALES", kmReal: 414, kmConv: 415 },
  { origen: "CONCORDIA", destino: "ESTEBAN ECHEVERRIA", kmReal: 458, kmConv: 460 },
  { origen: "PABLO NOGUES", destino: "VALENTIN ALSINA", kmReal: 47, kmConv: 50 },
  { origen: "! LINIERS", destino: "FLORENCIO VARELA", kmReal: 39, kmConv: 40 },
  { origen: "VILLA URQUIZA", destino: "ZARATE", kmReal: null, kmConv: 80 },
  { origen: "! PARQUE PATRICIOS", destino: "CAMPANA", kmReal: null, kmConv: 85 },
  { origen: "QUILMES", destino: "TORTUGUITAS", kmReal: 65, kmConv: 65 },
  { origen: "DOCK SUD", destino: "VILLA MARIA", kmReal: 560, kmConv: 560 },
  { origen: "PILAR", destino: "TUCUMAN", kmReal: 1227, kmConv: 1230 },
  { origen: "TORTUGUITAS", destino: "PILAR", kmReal: 22, kmConv: 20 },
  { origen: "MORENO", destino: "ZONA PORTUARIA", kmReal: null, kmConv: 45 },
  { origen: "MORENO", destino: "TORTUGUITAS", kmReal: 48, kmConv: 50 },
  { origen: "MORENO", destino: "VILLA SOLDATI", kmReal: 44, kmConv: 45 },
  { origen: "UDAONDO", destino: "VILLA SOLDATI", kmReal: 25, kmConv: 25 },
  { origen: "FREYRE", destino: "9 DE ABRIL", kmReal: 604, kmConv: 605 },
  { origen: "SAN FRANCISCO", destino: "LINIERS", kmReal: 561, kmConv: 560 },
  { origen: "TIO PUJIO", destino: "TAPIALES", kmReal: 580, kmConv: 580 },
  { origen: "MUNRO", destino: "TORTUGUITAS", kmReal: 30, kmConv: 30 },
  { origen: "UDAONDO", destino: "TORTUGUITAS", kmReal: 39, kmConv: 40 },
  { origen: "! ELORTONDO", destino: "FRANCK", kmReal: 339, kmConv: 340 },
  { origen: "! TIGRE", destino: "PABLO NOGUES", kmReal: null, kmConv: 20 },
  { origen: "! FRANCK", destino: "TIGRE", kmReal: 459, kmConv: 460 },
  { origen: "SANTA FE", destino: "SANTO TOME", kmReal: 15, kmConv: 15 },
  { origen: "FRANCK", destino: "PABLO NOGUES", kmReal: 444, kmConv: 445 },
  { origen: "! CATRILO", destino: "LINIERS", kmReal: 515, kmConv: 515 },
  { origen: "LINIERS", destino: "VALENTIN ALSINA", kmReal: null, kmConv: 15 },
  { origen: "VALENTIN ALSINA", destino: "CIPOLLETTI", kmReal: 1130, kmConv: 1130 },
  { origen: "! PARQUE PATRICIOS", destino: "LANUS", kmReal: null, kmConv: 10 },
  { origen: "CAMPANA", destino: "TORTUGUITAS", kmReal: 50, kmConv: 50 },
  { origen: "DOCK SUD", destino: "VILLA SOLDATI", kmReal: null, kmConv: 10 },
  { origen: "! VILLA URQUIZA", destino: "DOCK SUD", kmReal: null, kmConv: 25 },
  { origen: "TAPIALES", destino: "TORTUGUITAS", kmReal: 65, kmConv: 65 },
  { origen: "! SAN JORGE", destino: "MORENO", kmReal: 506, kmConv: 505 },
  { origen: "VILLA MARIA", destino: "ISIDRO CASANOVA", kmReal: 559, kmConv: 560 },
  { origen: "! FREYRE", destino: "DOCK SUD", kmReal: 599, kmConv: 600 },
  { origen: "DOCK SUD", destino: "SAN FRANCISCO", kmReal: 570, kmConv: 570 },
  { origen: "! TIO PUJIO", destino: "VILLA MARIA", kmReal: 18, kmConv: 20 },
  { origen: "RAFAELA", destino: "ZONA PORTUARIA", kmReal: 536, kmConv: 535 },
  { origen: "ZONA PORTUARIA", destino: "RAFAELA", kmReal: 536, kmConv: 535 },
  { origen: "VICENTE LOPEZ", destino: "TORTUGUITAS", kmReal: 33, kmConv: 35 },
  { origen: "VILLA SOLDATI", destino: "GENERAL RODRIGUEZ", kmReal: 47, kmConv: 50 },
  { origen: "TIO PUJIO", destino: "DOCK SUD", kmReal: 579, kmConv: 580 },
  { origen: "BARRACAS", destino: "TIO PUJIO", kmReal: 577, kmConv: 575 },
  { origen: "TAPIALES", destino: "GENERAL RODRIGUEZ", kmReal: 49, kmConv: 50 },
  { origen: "VICENTE LOPEZ", destino: "VILLA SOLDATI", kmReal: 30, kmConv: 30 },
  { origen: "DOCK SUD", destino: "TIO PUJIO", kmReal: 579, kmConv: 580 },
  { origen: "ZONA PORTUARIA", destino: "TIO PUJIO", kmReal: 568, kmConv: 570 },
  { origen: "MERCEDES", destino: "VALENTIN ALSINA", kmReal: 102, kmConv: 100 },
  { origen: "! PARQUE PATRICIOS", destino: "SAN ANDRES DE GILES", kmReal: 105, kmConv: 105 },
  { origen: "PARQUE PATRICIO", destino: "VILLA SOLDATI", kmReal: null, kmConv: 5 },
  { origen: "! MENDOZA", destino: "SAN MARTIN(MZA)", kmReal: null, kmConv: 45 },
  { origen: "TIO PUJIO", destino: "VICENTE LOPEZ", kmReal: 559, kmConv: 560 },
  { origen: "CARLOS SPEGAZZINI", destino: "VILLA SOLDATI", kmReal: 41, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "MORENO", kmReal: 45, kmConv: 45 },
  { origen: "ZONA PORTUARIA", destino: "DOCK SUD", kmReal: null, kmConv: 11 },
  { origen: "SAN FRANCISCO", destino: "CA&#209;UELAS", kmReal: 592, kmConv: 590 },
  { origen: "TORTUGUITAS", destino: "VILLA SOLDATI", kmReal: 61, kmConv: 60 },
  { origen: "LANUS", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "TORTUGUITAS", destino: "GENERAL RODRIGUEZ", kmReal: 29, kmConv: 30 },
  { origen: "! VICENTE LOPEZ", destino: "BARADERO", kmReal: 140, kmConv: 140 },
  { origen: "FRONTERA", destino: "ESCOBAR", kmReal: 507, kmConv: 505 },
  { origen: "MUNRO", destino: "MORENO", kmReal: 56, kmConv: 55 },
  { origen: "TIGRE", destino: "TORTUGUITAS", kmReal: null, kmConv: 30 },
  { origen: "PILAR", destino: "VILLA SOLDATI", kmReal: null, kmConv: 80 },
  { origen: "PARANÁ", destino: "CORDOBA", kmReal: 394, kmConv: 395 },
  { origen: "SAN FRANCISCO", destino: "TIGRE", kmReal: 546, kmConv: 545 },
  { origen: "RAFAELA", destino: "TIGRE", kmReal: 525, kmConv: 525 },
  { origen: "MERCEDES", destino: "MORENO", kmReal: null, kmConv: 65 },
  { origen: "MORENO", destino: "SAN FRANCISCO", kmReal: 564, kmConv: 565 },
  { origen: "MORENO", destino: "CAMPANA", kmReal: 84, kmConv: 85 },
  { origen: "VILLA SOLDATI", destino: "SAN ANDRES DE GILES", kmReal: 103, kmConv: 105 },
  { origen: "DOCK SUD", destino: "RAFAELA", kmReal: 547, kmConv: 545 },
  { origen: "RAFAELA", destino: "DOCK SUD", kmReal: 547, kmConv: 545 },
  { origen: "SAN FRANCISCO", destino: "VILLA URQUIZA", kmReal: 550, kmConv: 550 },
  { origen: "FRONTERA", destino: "MORENO", kmReal: 561, kmConv: 560 },
  { origen: "MONTE GRANDE", destino: "ZARATE", kmReal: 118, kmConv: 120 },
  { origen: "VILLA DEL PARQUE", destino: "TORTUGUITAS", kmReal: null, kmConv: 40 },
  { origen: "PARQUE PATRICIO", destino: "VALENTIN ALSINA", kmReal: 10, kmConv: 10 },
  { origen: "VALENTIN ALSINA", destino: "ARROYITO", kmReal: 662, kmConv: 660 },
  { origen: "FRANCK", destino: "TORTUGUITAS", kmReal: 444, kmConv: 445 },
  { origen: "MERCEDES", destino: "LANUS", kmReal: 104, kmConv: 105 },
  { origen: "LANUS", destino: "SAN FRANCISCO", kmReal: 575, kmConv: 575 },
  { origen: "TORTUGUITAS", destino: "ROSARIO", kmReal: 270, kmConv: 270 },
  { origen: "CORDOBA", destino: "TORTUGUITAS", kmReal: 667, kmConv: 670 },
  { origen: "VILLA LUGANO", destino: "CORDOBA", kmReal: 702, kmConv: 700 },
  { origen: "! PILAR", destino: "VILLA LUGANO", kmReal: null, kmConv: 65 },
  { origen: "VILLA SOLDATI", destino: "ZARATE", kmReal: null, kmConv: 100 },
  { origen: "ZONA PORTUARIA", destino: "VILLA SOLDATI", kmReal: 14, kmConv: 14 },
  { origen: "EL TIO", destino: "SAN FRANCISCO", kmReal: 70, kmConv: 70 },
  { origen: "RIO SEGUNDO", destino: "ZONA PORTUARIA", kmReal: 654, kmConv: 655 },
  { origen: "ZONA PORTUARIA", destino: "RIO SEGUNDO", kmReal: 654, kmConv: 655 },
  { origen: "CORDOBA", destino: "SAN FRANCISCO", kmReal: 225, kmConv: 225 },
  { origen: "RAMONA", destino: "VILLA DEL PARQUE", kmReal: 587, kmConv: 590 },
  { origen: "TIO PUJIO", destino: "LANUS", kmReal: 585, kmConv: 585 },
  { origen: "! FRONTERA", destino: "MONTE GRANDE", kmReal: 586, kmConv: 585 },
  { origen: "PILAR", destino: "MUNRO", kmReal: 43, kmConv: 45 },
  { origen: "UDAONDO", destino: "MORENO", kmReal: 28, kmConv: 30 },
  { origen: "SAN JORGE", destino: "TORTUGUITAS", kmReal: 463, kmConv: 465 },
  { origen: "TORTUGUITAS", destino: "VICENTE LOPEZ", kmReal: 33, kmConv: 35 },
  { origen: "TIO PUJIO", destino: "TORTUGUITAS", kmReal: 540, kmConv: 540 },
  { origen: "POSADAS", destino: "PUERTO BOSSETTI", kmReal: 274, kmConv: 275 },
  { origen: "MORENO", destino: "CORDOBA", kmReal: 698, kmConv: 700 },
  { origen: "! BAHIA BLANCA", destino: "MORENO", kmReal: 670, kmConv: 670 },
  { origen: "UDAONDO", destino: "GENERAL RODRIGUEZ", kmReal: 26, kmConv: 25 },
  { origen: "MUNRO", destino: "LANUS", kmReal: 31, kmConv: 30 },
  { origen: "LANUS", destino: "CORDOBA", kmReal: 709, kmConv: 710 },
  { origen: "TAPIALES", destino: "LANUS", kmReal: 22, kmConv: 20 },
  { origen: "TAPIALES", destino: "CORDOBA", kmReal: 704, kmConv: 705 },
  { origen: "MERCEDES", destino: "SAN FRANCISCO", kmReal: 530, kmConv: 530 },
  { origen: "TAPIALES", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "MUNRO", destino: "CAMPANA", kmReal: 67, kmConv: 65 },
  { origen: "CORDOBA", destino: "COSQUIN", kmReal: 55, kmConv: 55 },
  { origen: "! CATRILO", destino: "MERCEDES", kmReal: 429, kmConv: 430 },
  { origen: "! MERCEDES", destino: "CARLOS SPEGZZINI", kmReal: 128, kmConv: 130 },
  { origen: "MUNRO", destino: "VILLA SOLDATI", kmReal: 36, kmConv: 35 },
  { origen: "VILLA SOLDATI", destino: "VILLA MARIA", kmReal: 558, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "VILLA CONSTITUCION", kmReal: 322, kmConv: 320 },
  { origen: "VILLA MARIA", destino: "ZONA PORTUARIA", kmReal: 549, kmConv: 550 },
  { origen: "ZONA PORTUARIA", destino: "SAN FRANCISCO", kmReal: 559, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "DOCK SUD", kmReal: 570, kmConv: 570 },
  { origen: "SAN FRANCISCO", destino: "ZONA PORTUARIA", kmReal: 559, kmConv: 560 },
  { origen: "SAN JORGE", destino: "UDAONDO", kmReal: 488, kmConv: 490 },
  { origen: "FRONTERA", destino: "MUNRO", kmReal: 542, kmConv: 540 },
  { origen: "ISIDRO CASANOVA", destino: "TAPIALES", kmReal: 12, kmConv: 10 },
  { origen: "RESISTENCIA", destino: "GOBERNADOR VIRASORO", kmReal: 347, kmConv: 350 },
  { origen: "TORTUGUITAS", destino: "RECREO", kmReal: 453, kmConv: 455 },
  { origen: "PARQUE PATRICIO", destino: "LUJAN", kmReal: null, kmConv: 72 },
  { origen: "MERCEDES", destino: "VILLA SOLDATI", kmReal: 100, kmConv: 100 },
  { origen: "TIO PUJIO", destino: "ISIDRO CASANOVA", kmReal: 587, kmConv: 590 },
  { origen: "TORTUGUITAS", destino: "CORDOBA", kmReal: 667, kmConv: 670 },
  { origen: "MERCEDES", destino: "TORTUGUITAS", kmReal: 95, kmConv: 95 },
  { origen: "TAPIALES", destino: "SAN JUSTO", kmReal: 9, kmConv: 10 },
  { origen: "CORDOBA", destino: "VILLA SOLDATI", kmReal: 699, kmConv: 700 },
  { origen: "SAN FRANCISCO", destino: "PARQUE PATRICIO", kmReal: 568, kmConv: 570 },
  { origen: "SAN FRANCISCO", destino: "VILLA SOLDATI", kmReal: 587, kmConv: 590 },
  { origen: "SAN JORGE", destino: "TAPIALES", kmReal: 500, kmConv: 500 },
  { origen: "FRIAS", destino: "CORDOBA", kmReal: 347, kmConv: 350 },
  { origen: "SAN FRANCISCO", destino: "CORDOBA", kmReal: 225, kmConv: 225 },
  { origen: "VILLA SOLDATI", destino: "CORDOBA", kmReal: 699, kmConv: 700 },
  { origen: "CA&#209;UELAS", destino: "VILLA SOLDATI", kmReal: 56, kmConv: 55 },
  { origen: "MUNRO", destino: "CA&#209;UELAS", kmReal: 76, kmConv: 75 },
  { origen: "CORDOBA", destino: "MUNRO", kmReal: 680, kmConv: 680 },
  { origen: "! CAMPANA", destino: "BERNAL", kmReal: null, kmConv: 100 },
  { origen: "CARLOS SPEGAZZINI", destino: "CORDOBA", kmReal: 730, kmConv: 730 },
  { origen: "! MERCEDES", destino: "SPEGAZZINI", kmReal: 122, kmConv: 120 },
  { origen: "FORMOSA", destino: "GOBERNADOR VIRASORO", kmReal: 516, kmConv: 515 },
  { origen: "SANTA FE", destino: "RAMONA", kmReal: 173, kmConv: 175 },
  { origen: "ARMSTRONG", destino: "SAN FRANCISCO", kmReal: 202, kmConv: 200 },
  { origen: "BERNAL OESTE", destino: "CORDOBA", kmReal: 716, kmConv: 715 },
  { origen: "BERNAL OESTE", destino: "SAN FRANCISCO", kmReal: 580, kmConv: 580 },
  { origen: "! BARROS BLANCOS", destino: "BERNAL", kmReal: 600, kmConv: 600 },
  { origen: "BARROS BLANCOS", destino: "GENERAL RODRIGUEZ", kmReal: 558, kmConv: 560 },
  { origen: "! CERRO AZUL", destino: "SANTA FE", kmReal: 763, kmConv: 765 },
  { origen: "! CHASCOMUS", destino: "SANTO TOME", kmReal: 582, kmConv: 580 },
  { origen: "! BUENOS AIRES", destino: "LA FRANCIA", kmReal: 618, kmConv: 620 },
  { origen: "ANGUIL", destino: "GENERAL RODRIGUEZ", kmReal: 530, kmConv: 530 },
  { origen: "SUNCHALES", destino: "DON TORCUATO", kmReal: 551, kmConv: 550 },
  { origen: "! DEL GUAZU", destino: "ZARATE", kmReal: null, kmConv: 35 },
  { origen: "! BUENOS AIRES", destino: "BERNAL", kmReal: 18, kmConv: 20 },
  { origen: "! BERNAL", destino: "ARROYITO", kmReal: 669, kmConv: 670 },
  { origen: "! BUENOS AIRES", destino: "BARROS BLANCOS", kmReal: 580, kmConv: 580 },
  { origen: "! LIBERTAD(URUGUAY)", destino: "GRAL RODRIGUEZ", kmReal: 498, kmConv: 500 },
  { origen: "COSTA DE ARAUJO", destino: "CORDOBA", kmReal: 692, kmConv: 690 },
  { origen: "! MENDOZA", destino: "COSTA DE ARAUJO", kmReal: 53, kmConv: 55 },
  { origen: "! BUENOS AIRES", destino: "ARRECIFES", kmReal: 180, kmConv: 180 },
  { origen: "! ESPERANZA", destino: "SUSANA", kmReal: null, kmConv: 75 },
  { origen: "! FRANCK", destino: "DEL GUAZU", kmReal: 423, kmConv: 425 },
  { origen: "LA PLATA", destino: "GENERAL RODRIGUEZ", kmReal: 113, kmConv: 115 },
  { origen: "! SANTO TOME", destino: "FRANCK", kmReal: 24, kmConv: 25 },
  { origen: "! CAMPANA", destino: "SANTO TOME", kmReal: 380, kmConv: 380 },
  { origen: "LA PLATA", destino: "CHASCOMUS", kmReal: null, kmConv: 80 },
  { origen: "ZARATE", destino: "SANTO TOME", kmReal: 372, kmConv: 375 },
  { origen: "! LIBERTAD(SAN JOSE)", destino: "BUENOS AIRES", kmReal: 519, kmConv: 520 },
  { origen: "! LIBERTAD(URUGUAY)", destino: "SAN JORGE", kmReal: 709, kmConv: 710 },
  { origen: "! TIO PUJIO", destino: "LIBERTAD(URUGUAY)", kmReal: 818, kmConv: 820 },
  { origen: "! ROSARIO", destino: "PARANA", kmReal: 199, kmConv: 200 },
  { origen: "! CATRILO", destino: "BUENOS AIRES", kmReal: 531, kmConv: 530 },
  { origen: "! CATRILO", destino: "SANTA FE", kmReal: 723, kmConv: 725 },
  { origen: "ANGUIL", destino: "CATRILO", kmReal: 58, kmConv: 58 },
  { origen: "! SAN FRANCISCO", destino: "PERGAMINO", kmReal: 380, kmConv: 380 },
  { origen: "! GOB VIRASORO", destino: "SAN FRANCISCO", kmReal: 823, kmConv: 825 },
  { origen: "! CHASCOMUS", destino: "SANTA FE", kmReal: 595, kmConv: 595 },
  { origen: "SAN FRANCISCO", destino: "VILLA DEL ROSARIO", kmReal: 169, kmConv: 170 },
  { origen: "! AROCENA", destino: "PARANA", kmReal: 93, kmConv: 95 },
  { origen: "! PERGAMINO", destino: "BARROS BLANCOS", kmReal: 675, kmConv: 675 },
  { origen: "! MERCEDES", destino: "PERGARMINO", kmReal: 163, kmConv: 165 },
  { origen: "! MENDOZA", destino: "BELL VILLE", kmReal: 685, kmConv: 685 },
  { origen: "MONTEVIDEO", destino: "ZARATE", kmReal: 504, kmConv: 504 },
  { origen: "VILLA DEL ROSARIO", destino: "CORDOBA", kmReal: null, kmConv: 82 },
  { origen: "ZARATE", destino: "VILLA DEL ROSARIO", kmReal: 570, kmConv: 570 },
  { origen: "SANTA FE", destino: "ARROYITO", kmReal: 241, kmConv: 240 },
  { origen: "! AYACUCHO", destino: "PUEBLO ESTHER", kmReal: 560, kmConv: 560 },
  { origen: "! BUENOS AIRES", destino: "AYACUCHO", kmReal: 324, kmConv: 325 },
  { origen: "PILAR", destino: "RIO CEBALLOS", kmReal: 682, kmConv: 680 },
  { origen: "! PARANA", destino: "FRANCK", kmReal: 63, kmConv: 65 },
  { origen: "POSADAS", destino: "GOBERNADOR VIRASORO", kmReal: 94, kmConv: 95 },
  { origen: "DOS DE MAYO", destino: "CORDOBA", kmReal: 1251, kmConv: 1250 },
  { origen: "! OBERA", destino: "DOS DE MAYO", kmReal: 81, kmConv: 80 },
  { origen: "BARROS BLANCOS", destino: "ZARATE", kmReal: 511, kmConv: 510 },
  { origen: "! BARROS BLANCOS", destino: "GUALEGUAYCHU", kmReal: 349, kmConv: 350 },
  { origen: "PILAR", destino: "SAN ANDRES DE GILES", kmReal: 60, kmConv: 60 },
  { origen: "! SANTA FE", destino: "PARANA", kmReal: 31, kmConv: 30 },
  { origen: "! LAS VARILLAS", destino: "VILLA MARIA", kmReal: 83, kmConv: 85 },
  { origen: "! PUERTO PIRAY", destino: "COLONIA CAROYA", kmReal: 1359, kmConv: 1360 },
  { origen: "CORONDA", destino: "RAFAELA", kmReal: 147, kmConv: 150 },
  { origen: "! VILLA MARIA", destino: "RESISTENCIA", kmReal: 827, kmConv: 830 },
  { origen: "! TANDIL", destino: "BUENOS AIRES", kmReal: 352, kmConv: 355 },
  { origen: "! LAS VARILLAS", destino: "SAN JORGE", kmReal: 104, kmConv: 105 },
  { origen: "ARROYITO", destino: "LAS VARILLAS", kmReal: 68, kmConv: 70 },
  { origen: "! PUERTO PIRAY", destino: "ESPERANZA", kmReal: 994, kmConv: 995 },
  { origen: "CANDELARIA", destino: "GOBERNADOR VIRASORO", kmReal: 92, kmConv: 92 },
  { origen: "TUCUMAN", destino: "VILLA OJO DE AGUA", kmReal: 362, kmConv: 360 },
  { origen: "! RECREO", destino: "AROCENA", kmReal: 82, kmConv: 80 },
  { origen: "MONTEVIDEO", destino: "PILAR", kmReal: 535, kmConv: 535 },
  { origen: "! CHASCOMUS", destino: "BUENOS AIRES", kmReal: 128, kmConv: 128 },
  { origen: "MERCEDES", destino: "SAN ANDRES DE GILES", kmReal: 25, kmConv: 25 },
  { origen: "! BAHIA BLANCA", destino: "CORONEL MOLDES", kmReal: 687, kmConv: 690 },
  { origen: "! SIERRA DE LOS PADRES", destino: "SAN FRANCISCO", kmReal: 980, kmConv: 980 },
  { origen: "! APOSTOLES", destino: "GOB. VIRASORO", kmReal: 41, kmConv: 41 },
  { origen: "! SAN BERNARDO", destino: "BUENOS AIRES", kmReal: 375, kmConv: 375 },
  { origen: "! MAR DEL PLATA", destino: "CHASCOMUS", kmReal: 290, kmConv: 290 },
  { origen: "ANGUIL", destino: "PILAR", kmReal: 538, kmConv: 538 },
  { origen: "ANGUIL", destino: "CORDOBA", kmReal: 538, kmConv: 538 },
  { origen: "SAN ANDRES DE GILES", destino: "CORDOBA", kmReal: 625, kmConv: 625 },
  { origen: "! ARROYITO", destino: "FRANCK", kmReal: 224, kmConv: 225 },
  { origen: "! MONTECARLO", destino: "GOB. VIRASORO", kmReal: 250, kmConv: 250 },
  { origen: "! 25 DE MAYO", destino: "PTO ESPERANZA", kmReal: 185, kmConv: 185 },
  { origen: "! MERCEDES", destino: "BERNAL", kmReal: 120, kmConv: 120 },
  { origen: "! SIERRA DE LOS PADRES", destino: "RECREO", kmReal: 891, kmConv: 890 },
  { origen: "OBERA", destino: "GOBERNADOR VIRASORO", kmReal: 125, kmConv: 125 },
  { origen: "VILLA MARIA", destino: "SAN JORGE", kmReal: 185, kmConv: 185 },
  { origen: "RAFAELA", destino: "25 DE MAYO", kmReal: 1005, kmConv: 1005 },
  { origen: "ANGUIL", destino: "SAN ANDRES DE GILES", kmReal: 512, kmConv: 515 },
  { origen: "SAN ANDRES DE GILES", destino: "SAN FRANCISCO", kmReal: 488, kmConv: 490 },
  { origen: "SAN FRANCISCO", destino: "TRELEW", kmReal: 1564, kmConv: 1565 },
  { origen: "! GOYA", destino: "GUALEGUAYCHU", kmReal: 486, kmConv: 485 },
  { origen: "! CHASCOMUS", destino: "RAFELA", kmReal: 666, kmConv: 666 },
  { origen: "! GENERAL ROCA", destino: "MALAGUE&#209;O", kmReal: 1112, kmConv: 1112 },
  { origen: "! PEAJE FRANCK", destino: "SAN FRANCISCO", kmReal: 113, kmConv: 115 },
  { origen: "MAR DEL PLATA", destino: "ZARATE", kmReal: 504, kmConv: 505 },
  { origen: "! MAR DE AJO", destino: "CHASCOMUS", kmReal: 241, kmConv: 240 },
  { origen: "SUNCHALES", destino: "MAR DE AJO", kmReal: 951, kmConv: 950 },
  { origen: "SIERRA DE LOS PADRES", destino: "RAFAELA", kmReal: 949, kmConv: 950 },
  { origen: "! VILLA MARIA", destino: "ALEJANDRO ROCA", kmReal: 160, kmConv: 160 },
  { origen: "! CONCORDIA", destino: "RIOCUARTO", kmReal: 724, kmConv: 725 },
  { origen: "! MERCEDES", destino: "CHASCOMUS", kmReal: 227, kmConv: 230 },
  { origen: "! GENERAL CABRERA", destino: "BUENOS AIRES", kmReal: 627, kmConv: 630 },
  { origen: "! BUENOS AIRES", destino: "GENERAL CABRERA", kmReal: 627, kmConv: 630 },
  { origen: "! CHASCOMUS", destino: "PARANA", kmReal: 620, kmConv: 620 },
  { origen: "! BUENOS AIRES", destino: "CHASCOMUS", kmReal: 126, kmConv: 125 },
  { origen: "CORDOBA", destino: "VILLA OJO DE AGUA", kmReal: 231, kmConv: 230 },
  { origen: "VILLA OJO DE AGUA", destino: "PUEBLO ESTHER", kmReal: 643, kmConv: 645 },
  { origen: "CHASCOMUS", destino: "CORDOBA", kmReal: 823, kmConv: 825 },
  { origen: "! PILAR", destino: "CHASCOMUS", kmReal: 205, kmConv: 205 },
  { origen: "CONCORDIA", destino: "LA PLATA", kmReal: 487, kmConv: 490 },
  { origen: "BRINKMANN", destino: "PORTE&#209;A", kmReal: 19, kmConv: 20 },
  { origen: "SANTA ANA", destino: "POSADAS", kmReal: 65, kmConv: 65 },
  { origen: "! SANTO TOME", destino: "SAN ESTEBAN", kmReal: 1074, kmConv: 1075 },
  { origen: "POSADAS", destino: "SANTO TOME", kmReal: 158, kmConv: 160 },
  { origen: "CORDOBA", destino: "AROCENA", kmReal: 416, kmConv: 415 },
  { origen: "RAFAELA", destino: "TIO PUJIO", kmReal: 262, kmConv: 265 },
  { origen: "! CERRO AZUL", destino: "CARLOS PAZ", kmReal: 1169, kmConv: 1170 },
  { origen: "! POSADAS", destino: "CERRO AZUL", kmReal: 68, kmConv: 70 },
  { origen: "ZARATE", destino: "BARADERO", kmReal: null, kmConv: 70 },
  { origen: "BELL VILLE", destino: "SAN FRANCISCO", kmReal: 180, kmConv: 180 },
  { origen: "! LA FRANCIA", destino: "BELL VILLE", kmReal: 157, kmConv: 160 },
  { origen: "! COMODORO RIVADABIA", destino: "BUENOS AIRES", kmReal: 1775, kmConv: 1775 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "ROSARIO", kmReal: 275, kmConv: 275 },
  { origen: "! ROSARIO", destino: "CONCEPCION DEL URUGUAY", kmReal: 275, kmConv: 275 },
  { origen: "! MERCEDES", destino: "BALCARCE", kmReal: 413, kmConv: 415 },
  { origen: "! BELLA VISTA", destino: "CONCORDIA", kmReal: 399, kmConv: 400 },
  { origen: "! GOYA", destino: "BELLA VISTA", kmReal: 84, kmConv: 85 },
  { origen: "! SANTO TOME", destino: "GOBERNADOR CRESPO", kmReal: 163, kmConv: 165 },
  { origen: "GOBERNADOR VIRASORO", destino: "ZARATE", kmReal: 823, kmConv: 825 },
  { origen: "ZARATE", destino: "PILAR", kmReal: null, kmConv: 52 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "SAN SALVADOR", kmReal: 116, kmConv: 115 },
  { origen: "! ALEM", destino: "PUERTO PIRAY", kmReal: 191, kmConv: 190 },
  { origen: "! JACINTO ARAUZ", destino: "BUENOS AIRES", kmReal: 691, kmConv: 690 },
  { origen: "! BAHIA BLANCA", destino: "JACINTO ARAUZ", kmReal: 133, kmConv: 135 },
  { origen: "! SANTO TOME", destino: "ALEM", kmReal: 792, kmConv: 790 },
  { origen: "! TRELEW", destino: "BAHIA BLANCA", kmReal: 766, kmConv: 765 },
  { origen: "! BAHIA BLANCA", destino: "TRELEW", kmReal: 766, kmConv: 765 },
  { origen: "ZARATE", destino: "BRINKMANN", kmReal: 544, kmConv: 545 },
  { origen: "! COMODORO RIVADAVIA", destino: "BAHIA BLANCA", kmReal: 1139, kmConv: 1140 },
  { origen: "! BAHIA BLANCA", destino: "COMODORO RIVADAVIA", kmReal: 1139, kmConv: 1140 },
  { origen: "RAFAELA", destino: "BELLA ITALIA", kmReal: null, kmConv: 9 },
  { origen: "CORONEL MOLDES", destino: "ZARATE", kmReal: 601, kmConv: 600 },
  { origen: "! SUARDI", destino: "RAMONA", kmReal: 102, kmConv: 100 },
  { origen: "! CANELONES", destino: "CONCORDIA", kmReal: 555, kmConv: 555 },
  { origen: "! RIO CUARTO", destino: "CORONEL MOLDES", kmReal: null, kmConv: 76 },
  { origen: "ANGUIL", destino: "ROSARIO", kmReal: 596, kmConv: 600 },
  { origen: "PUERTO ESPERANZA", destino: "POSADAS", kmReal: 254, kmConv: 255 },
  { origen: "SAN VICENTE", destino: "PUERTO ESPERANZA", kmReal: 158, kmConv: 160 },
  { origen: "SAN FRANCISCO", destino: "ALEJANDRO ROCA", kmReal: 322, kmConv: 325 },
  { origen: "ROSARIO", destino: "ANGUIL", kmReal: 596, kmConv: 600 },
  { origen: "RANCHOS", destino: "ZARATE", kmReal: 220, kmConv: 220 },
  { origen: "SUARDI", destino: "RANCHOS", kmReal: 815, kmConv: 815 },
  { origen: "LA FRANCIA", destino: "CORDOBA", kmReal: 164, kmConv: 165 },
  { origen: "CORDOBA", destino: "LA FRANCIA", kmReal: 164, kmConv: 165 },
  { origen: "ANGUIL", destino: "ZARATE", kmReal: 590, kmConv: 590 },
  { origen: "ANGUIL", destino: "BUENOS AIRES", kmReal: 585, kmConv: 585 },
  { origen: "CORDOBA", destino: "ANGUIL", kmReal: 637, kmConv: 640 },
  { origen: "! EMBARCACION", destino: "SAN PEDRO", kmReal: 1513, kmConv: 1515 },
  { origen: "! MONTEVIDEO", destino: "FRANCK", kmReal: 695, kmConv: 695 },
  { origen: "CORRIENTES", destino: "GOBERNADOR VIRASORO", kmReal: 327, kmConv: 330 },
  { origen: "! EMBARCACION", destino: "BUENOS AIRES", kmReal: 1666, kmConv: 1665 },
  { origen: "! SALTA", destino: "EMBARCACION", kmReal: 268, kmConv: 270 },
  { origen: "PORTE&#209;A", destino: "FREYRE", kmReal: 19, kmConv: 20 },
  { origen: "! MERCEDES", destino: "SAN FRANCISCO", kmReal: 532, kmConv: 530 },
  { origen: "MINAS", destino: "ZARATE", kmReal: 561, kmConv: 560 },
  { origen: "! LAS LAJITAS", destino: "SAN FRANCIS0CO", kmReal: 954, kmConv: 955 },
  { origen: "! SALTA", destino: "LAS LAJITAS", kmReal: 210, kmConv: 210 },
  { origen: "MONTEVIDEO", destino: "BARADERO", kmReal: 553, kmConv: 555 },
  { origen: "TIO PUJIO", destino: "CORDOBA", kmReal: 134, kmConv: 135 },
  { origen: "! ESPERANZA", destino: "ROSARIO", kmReal: 197, kmConv: 195 },
  { origen: "CORONDA", destino: "SUNCHALES", kmReal: 185, kmConv: 185 },
  { origen: "! BUENOS AIRES", destino: "VILLA NUEVA", kmReal: 743, kmConv: 745 },
  { origen: "BUENOS AIRES", destino: "VILLA NUEVA", kmReal: 500, kmConv: 500 },
  { origen: "LA PLATA", destino: "ZARATE", kmReal: 148, kmConv: 150 },
  { origen: "CORDOBA", destino: "POSADAS", kmReal: 1147, kmConv: 1150 },
  { origen: "! GRAL DEHEZA", destino: "BUENOS AIRES", kmReal: 618, kmConv: 620 },
  { origen: "! BUENOS AIRES", destino: "GRAL DEHEZA", kmReal: 618, kmConv: 620 },
  { origen: "! MENDOZA", destino: "VILLA ALLENDE", kmReal: 718, kmConv: 720 },
  { origen: "COLONIA CAROYA", destino: "BARADERO", kmReal: 603, kmConv: 600 },
  { origen: "! BUENOS AIRES", destino: "VILLA ASCASUBI", kmReal: 664, kmConv: 665 },
  { origen: "! VILLA ASCASUBI", destino: "BUENOS AIRES", kmReal: 664, kmConv: 665 },
  { origen: "! VILLA MARIA", destino: "VILLA ASCASUBI", kmReal: 74, kmConv: 75 },
  { origen: "! BARROS BLANCOS", destino: "MONTEVIDEO", kmReal: 22, kmConv: 20 },
  { origen: "CONCORDIA", destino: "ALTA GRACIA", kmReal: 698, kmConv: 700 },
  { origen: "SUNCHALES", destino: "ELDORADO", kmReal: 1109, kmConv: 1110 },
  { origen: "POSADAS", destino: "RECREO", kmReal: 806, kmConv: 805 },
  { origen: "! SALTA", destino: "MENDOZA", kmReal: 1270, kmConv: 1270 },
  { origen: "AROCENA", destino: "SUNCHALES", kmReal: 176, kmConv: 175 },
  { origen: "! RIO CUARTO", destino: "FRANCK", kmReal: 410, kmConv: 410 },
  { origen: "! VILLA NUEVA", destino: "TIO PUJIO", kmReal: null, kmConv: 21 },
  { origen: "! VILLA NUEVA", destino: "VILLA MARIA", kmReal: null, kmConv: 4 },
  { origen: "! MERCEDES(BS AS)", destino: "TIO PUJIO", kmReal: 522, kmConv: 520 },
  { origen: "RAFAELA", destino: "RAMONA", kmReal: 54, kmConv: 55 },
  { origen: "BRAGADO", destino: "ZARATE", kmReal: 205, kmConv: 205 },
  { origen: "! MENDOZA", destino: "CRUZ DEL EJE", kmReal: 575, kmConv: 575 },
  { origen: "SAN FRANCISCO", destino: "GENERAL DEHEZA", kmReal: 228, kmConv: 230 },
  { origen: "! LIB. GRAL SAN MARTIN", destino: "BRAGADO", kmReal: 1572, kmConv: 1575 },
  { origen: "! LANDETA", destino: "SAN JORGE", kmReal: null, kmConv: 38 },
  { origen: "! SAN FRANCISCO", destino: "LANDETA", kmReal: null, kmConv: 78 },
  { origen: "CORDOBA", destino: "NEUQUEN", kmReal: 1109, kmConv: 1110 },
  { origen: "! PUEBLO ESTHER", destino: "SAN JORGE", kmReal: 220, kmConv: 220 },
  { origen: "! RIO CUARTO", destino: "PUEBLO ESTHER", kmReal: 415, kmConv: 415 },
  { origen: "! MERCEDES", destino: "LUJAN", kmReal: 35, kmConv: 35 },
  { origen: "! MERCEDES(CTES)", destino: "CONCORDIA", kmReal: 360, kmConv: 360 },
  { origen: "SAN FRANCISCO", destino: "CORONDA", kmReal: 168, kmConv: 170 },
  { origen: "! LIBERTAD(SAN JOSE)", destino: "SAN FRANCISCO", kmReal: 755, kmConv: 755 },
  { origen: "BARADERO", destino: "CAMPANA", kmReal: null, kmConv: 75 },
  { origen: "! LIBERTAD(SAN JOSE)", destino: "MONTEVIDEO", kmReal: null, kmConv: 55 },
  { origen: "! RAFAELA", destino: "LIBERTAD(SAN JOSE)", kmReal: 826, kmConv: 825 },
  { origen: "! MERCEDES", destino: "ARRECIFES", kmReal: 114, kmConv: 115 },
  { origen: "! ARRECIFES", destino: "BUENOS AIRES", kmReal: 180, kmConv: 180 },
  { origen: "! AZARA", destino: "LUJAN", kmReal: 889, kmConv: 890 },
  { origen: "LUJAN", destino: "ZARATE", kmReal: 59, kmConv: 60 },
  { origen: "LEHMANN", destino: "SAN FRANCISCO", kmReal: 105, kmConv: 105 },
  { origen: "! ORAN", destino: "LIB. GRAL SAN MARTIN", kmReal: 113, kmConv: 115 },
  { origen: "! MENDOZA", destino: "ORAN", kmReal: 1450, kmConv: 1450 },
  { origen: "! PUERTO ESPERANZA", destino: "LIB. GRAL SAN MARTIN", kmReal: 1434, kmConv: 1435 },
  { origen: "SUNCHALES", destino: "POSADAS", kmReal: 921, kmConv: 925 },
  { origen: "PUERTO PIRAY", destino: "RIO CUARTO", kmReal: 1380, kmConv: 1380 },
  { origen: "! TRELEW", destino: "CIPOLLETTI", kmReal: 722, kmConv: 720 },
  { origen: "! SAN JAVIER", destino: "APOSTOLES", kmReal: 76, kmConv: 75 },
  { origen: "! APOSTOLES", destino: "MENDOZA", kmReal: 1628, kmConv: 1630 },
  { origen: "! GARUPA", destino: "APOSTOLES", kmReal: 57, kmConv: 55 },
  { origen: "SUNCHALES", destino: "MENDOZA", kmReal: 882, kmConv: 880 },
  { origen: "CORDOBA", destino: "CORDOBA", kmReal: 10, kmConv: 10 },
  { origen: "MERCEDES", destino: "CORDOBA", kmReal: 645, kmConv: 645 },
  { origen: "RAFAELA", destino: "MONTEVIDEO", kmReal: 791, kmConv: 790 },
  { origen: "! PASO DE LOS LIBRES", destino: "OBERA", kmReal: 384, kmConv: 385 },
  { origen: "SAN FRANCISCO", destino: "PASO DE LOS LIBRES", kmReal: 599, kmConv: 600 },
  { origen: "! AZARA", destino: "BUENOS AIRES", kmReal: 920, kmConv: 920 },
  { origen: "! POSADAS", destino: "AZARA", kmReal: 88, kmConv: 90 },
  { origen: "! SANTIAGO DE CHILE", destino: "TIO PUJIO", kmReal: 982, kmConv: 980 },
  { origen: "PUEBLO ESTHER", destino: "ROSARIO", kmReal: 27, kmConv: 25 },
  { origen: "! RIO CUARTO", destino: "SANTA ISABEL", kmReal: 561, kmConv: 560 },
  { origen: "GENERAL RODRIGUEZ", destino: "CAMPANA", kmReal: 58, kmConv: 60 },
  { origen: "PORTE&#209;A", destino: "GENERAL RODRIGUEZ", kmReal: 608, kmConv: 610 },
  { origen: "! LAMARQUE", destino: "TIO PUJIO", kmReal: 1370, kmConv: 1370 },
  { origen: "SANTA MARIA DE PUNILLA", destino: "CORDOBA", kmReal: 48, kmConv: 50 },
  { origen: "GOBERNADOR VIRASORO", destino: "SANTA MARIA DE PUNILLA", kmReal: 1102, kmConv: 1100 },
  { origen: "! CLORINDA", destino: "VIRASORO", kmReal: 630, kmConv: 630 },
  { origen: "VILLA ALLENDE", destino: "CORDOBA", kmReal: 22, kmConv: 20 },
  { origen: "CORDOBA", destino: "VILLA ALLENDE", kmReal: 22, kmConv: 20 },
  { origen: "SAN FRANCISCO", destino: "CLORINDA", kmReal: 963, kmConv: 965 },
  { origen: "! MENDOZA", destino: "SALTA", kmReal: 1270, kmConv: 1270 },
  { origen: "MONTE CARLO", destino: "PUERTO PIRAY", kmReal: 17, kmConv: 20 },
  { origen: "! MALAGUE&#209;O", destino: "ALTA GRACIA", kmReal: 33, kmConv: 35 },
  { origen: "! VIRASORO", destino: "SAN FRANCISCO", kmReal: 823, kmConv: 825 },
  { origen: "RAFAELA", destino: "MONTE CARLO", kmReal: 1060, kmConv: 1060 },
  { origen: "ALEJANDRO ROCA", destino: "ZONA PORTUARIA", kmReal: 553, kmConv: 555 },
  { origen: "! BUENOS AIRES", destino: "ALEJANDRO ROCA", kmReal: 553, kmConv: 555 },
  { origen: "! SANTA EUFEMIA", destino: "BUENOS AIRES", kmReal: 529, kmConv: 530 },
  { origen: "! BUENOS AIRES", destino: "SANTA EUFEMIA", kmReal: 529, kmConv: 530 },
  { origen: "SAN VICENTE", destino: "GOBERNADOR VIRASORO", kmReal: 225, kmConv: 225 },
  { origen: "! GENERAL GUEMES", destino: "BUENOS AIRES", kmReal: 1449, kmConv: 1450 },
  { origen: "! SAN VICENTE", destino: "APOSTOLES", kmReal: 201, kmConv: 200 },
  { origen: "! ALEM", destino: "PARANA", kmReal: 759, kmConv: 760 },
  { origen: "RIO CUARTO", destino: "TIO PUJIO", kmReal: 148, kmConv: 150 },
  { origen: "! RIO CUARTO", destino: "SAN JORGE", kmReal: 317, kmConv: 318 },
  { origen: "! MONTEVIDEO", destino: "SANTO TOME", kmReal: 689, kmConv: 690 },
  { origen: "! AROCENA", destino: "BELLA ITALIA", kmReal: 148, kmConv: 148 },
  { origen: "SAN FRANCISCO", destino: "AROCENA", kmReal: 161, kmConv: 160 },
  { origen: "! BUENOS AIRES", destino: "MALAGUE&#209;O", kmReal: 717, kmConv: 715 },
  { origen: "! OBERA", destino: "LEANDRO ALEM", kmReal: 28, kmConv: 30 },
  { origen: "! LEANDRO ALEM", destino: "BUENOS AIRES", kmReal: 1005, kmConv: 1005 },
  { origen: "! JARDIN AMERICA", destino: "PUERTO ESPERANZA", kmReal: 152, kmConv: 150 },
  { origen: "! HUERGO", destino: "CIPOLLETTI", kmReal: null, kmConv: 77 },
  { origen: "! CHICHINALES", destino: "HUERGO", kmReal: 31, kmConv: 31 },
  { origen: "! ALLEN", destino: "CIPOLLETTI", kmReal: null, kmConv: 15 },
  { origen: "! GENERAL ROCA", destino: "ALLEN", kmReal: null, kmConv: 24 },
  { origen: "! CHICHINALES", destino: "GRAL ROCA", kmReal: null, kmConv: 60 },
  { origen: "! PUERTO PIRAY", destino: "VILLA MARIA", kmReal: 1249, kmConv: 1250 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "CONCORDIA", kmReal: 144, kmConv: 145 },
  { origen: "! MENDOZA", destino: "LA FRANCIA", kmReal: 750, kmConv: 750 },
  { origen: "! SAN FRANCISCO", destino: "GENERAL SAN MARTIN", kmReal: 1037, kmConv: 1040 },
  { origen: "! BUENOS AIRES", destino: "PARANA", kmReal: 501, kmConv: 500 },
  { origen: "MONTE CRISTO", destino: "CORDOBA", kmReal: 29, kmConv: 30 },
  { origen: "CORDOBA", destino: "MONTE CRISTO", kmReal: 29, kmConv: 30 },
  { origen: "! VIRASORO", destino: "SANTO TOME", kmReal: 64, kmConv: 65 },
  { origen: "! SANTO TOME", destino: "DESVIO ARIJON", kmReal: 27, kmConv: 30 },
  { origen: "ELDORADO", destino: "PUERTO ESPERANZA", kmReal: 49, kmConv: 50 },
  { origen: "! CAMPO GRANDE", destino: "PUERTO ESPERANZA", kmReal: 178, kmConv: 180 },
  { origen: "! BUENOS AIRES", destino: "COLONIA TIROLESA", kmReal: 714, kmConv: 714 },
  { origen: "! SANTIAGO DE CHILE", destino: "MAULE", kmReal: 267, kmConv: 268 },
  { origen: "CAMPANA", destino: "SASTRE", kmReal: 427, kmConv: 428 },
  { origen: "BUENOS AIRES", destino: "POSADAS", kmReal: 1000, kmConv: 1000 },
  { origen: "! SANTA ISABEL", destino: "PUEBLO ESTHER", kmReal: 834, kmConv: 835 },
  { origen: "POSADAS", destino: "OBERA", kmReal: 99, kmConv: 100 },
  { origen: "TUCUMAN", destino: "SAN PEDRO", kmReal: 1045, kmConv: 1045 },
  { origen: "SAN PEDRO", destino: "ZARATE", kmReal: 88, kmConv: 90 },
  { origen: "! PUERTO IGUAZU", destino: "PUERTO ESPERANZA", kmReal: 57, kmConv: 60 },
  { origen: "! URUGUAIANA", destino: "SAN LUIS", kmReal: 1107, kmConv: 1110 },
  { origen: "! SAN VICENTE", destino: "POSADAS", kmReal: 189, kmConv: 190 },
  { origen: "! POSADAS", destino: "RIO CUARTO", kmReal: 1208, kmConv: 1210 },
  { origen: "! BUENOS AIRES", destino: "PUERTO IGUAZU", kmReal: 1277, kmConv: 1280 },
  { origen: "SANTA FE", destino: "FRANCK", kmReal: 37, kmConv: 37 },
  { origen: "DON TORCUATO", destino: "SANTA FE", kmReal: 441, kmConv: 440 },
  { origen: "! ROSARIO", destino: "LUQUE", kmReal: 375, kmConv: 375 },
  { origen: "PUERTO ESPERANZA", destino: "NASCHEL", kmReal: 1651, kmConv: 1650 },
  { origen: "PUERTO RICO", destino: "PUERTO ESPERANZA", kmReal: 118, kmConv: 120 },
  { origen: "GOYA", destino: "CONCORDIA", kmReal: 354, kmConv: 355 },
  { origen: "SAN GUILLERMO", destino: "SUNCHALES", kmReal: 117, kmConv: 120 },
  { origen: "! MENDOZA", destino: "SAN GUILLERMO", kmReal: 898, kmConv: 900 },
  { origen: "! JARDIN AMERICA", destino: "PUERTO PIRAY", kmReal: 98, kmConv: 100 },
  { origen: "! SAN SALVADOR", destino: "MENDOZA", kmReal: 1144, kmConv: 1145 },
  { origen: "! APOSTOLES", destino: "SANTA ANA", kmReal: 105, kmConv: 105 },
  { origen: "! MENDOZA", destino: "OBERA", kmReal: 1727, kmConv: 1730 },
  { origen: "! CANDELARIA", destino: "APOSTOLES", kmReal: 67, kmConv: 70 },
  { origen: "! VILLA DEL ROSARIO(ENTRE RIOS)", destino: "MONTEVIDEO", kmReal: 634, kmConv: 635 },
  { origen: "! ROSARIO", destino: "VILLA DEL ROSARIO (ENTRE RIOSS)", kmReal: 437, kmConv: 440 },
  { origen: "! NEUQUEN", destino: "SANTA ISABEL", kmReal: 339, kmConv: 340 },
  { origen: "! PUEBLO ESTHER(SANTA FE)", destino: "FRANCK", kmReal: 202, kmConv: 200 },
  { origen: "! LUJAN", destino: "SAN FRANCISCO", kmReal: 541, kmConv: 540 },
  { origen: "APÓSTOLES", destino: "PARANÁ", kmReal: 694, kmConv: 695 },
  { origen: "! POSADAS", destino: "APOSTOLES", kmReal: 69, kmConv: 70 },
  { origen: "FRANCK", destino: "RECREO", kmReal: 35, kmConv: 35 },
  { origen: "! DALMACIO VELEZ", destino: "SAN FRANCISCO", kmReal: 202, kmConv: 200 },
  { origen: "! CHIVILCOY", destino: "DALMACIO VELEZ", kmReal: 493, kmConv: 495 },
  { origen: "! MENDOZA", destino: "RIO TERCERO", kmReal: 616, kmConv: 615 },
  { origen: "! SAN FRANCISCO", destino: "CURUZU CUATIA", kmReal: 531, kmConv: 530 },
  { origen: "! VENADO TUERTO", destino: "CHIVILCOY", kmReal: 253, kmConv: 255 },
  { origen: "! CHIVILCOY", destino: "OBERA", kmReal: 1093, kmConv: 1095 },
  { origen: "! CAMPANA", destino: "CHIVILCOY", kmReal: 150, kmConv: 150 },
  { origen: "! VIRASORO", destino: "BUENOS AIRES", kmReal: 930, kmConv: 930 },
  { origen: "NASCHEL", destino: "CORDOBA", kmReal: 436, kmConv: 435 },
  { origen: "! PUERTO IGUAZU", destino: "APOSTOLES", kmReal: 347, kmConv: 350 },
  { origen: "URUGUAIANA", destino: "RAFAELA", kmReal: 571, kmConv: 570 },
  { origen: "! HUMBOLDT", destino: "ITUZAINGO", kmReal: 514, kmConv: 514 },
  { origen: "! BELLA ITALIA", destino: "HUMBOLDT", kmReal: 36, kmConv: 36 },
  { origen: "! JARDIN AMERICA", destino: "SANTA ANA", kmReal: 55, kmConv: 55 },
  { origen: "SALTO GRANDE", destino: "CORDOBA", kmReal: 389, kmConv: 390 },
  { origen: "! BUENOS AIRES", destino: "SALTO GRANDE", kmReal: 350, kmConv: 350 },
  { origen: "! LAMARQUE", destino: "RIO COLORADO", kmReal: 160, kmConv: 160 },
  { origen: "! ALEM", destino: "SANTA ANA", kmReal: 39, kmConv: 40 },
  { origen: "SAN FRANCISCO", destino: "RIO TERCERO", kmReal: 292, kmConv: 290 },
  { origen: "SAN FRANCISCO", destino: "PUERTO IGUAZU", kmReal: 1202, kmConv: 1205 },
  { origen: "! SAN FRANCISCO", destino: "ALEM", kmReal: 930, kmConv: 930 },
  { origen: "SASTRE", destino: "SAN JORGE", kmReal: 17, kmConv: 18 },
  { origen: "! BUENOS AIRES", destino: "SASTRE", kmReal: 503, kmConv: 505 },
  { origen: "! AZUL", destino: "BUENOS AIRES", kmReal: 303, kmConv: 305 },
  { origen: "! BUENOS AIRES", destino: "AZUL", kmReal: 303, kmConv: 305 },
  { origen: "MERCEDES", destino: "NAVARRO", kmReal: 51, kmConv: 50 },
  { origen: "PILAR", destino: "CAMPANA", kmReal: 42, kmConv: 45 },
  { origen: "! SAN ANTONIO", destino: "BUENOS AIRES", kmReal: 1523, kmConv: 1525 },
  { origen: "VILLA REGINA", destino: "RIO COLORADO", kmReal: 275, kmConv: 275 },
  { origen: "SAN FRANCISCO", destino: "OBERA", kmReal: 956, kmConv: 960 },
  { origen: "! VILLAGUAY", destino: "SAN SALVADOR", kmReal: 63, kmConv: 65 },
  { origen: "! LOS BERROS", destino: "ROSARIO", kmReal: 1013, kmConv: 1015 },
  { origen: "ESPERANZA", destino: "SUNCHALES", kmReal: 101, kmConv: 100 },
  { origen: "! NASCHEL", destino: "MENDOZA", kmReal: 370, kmConv: 370 },
  { origen: "! SAN FRANCISCO", destino: "VIRASORO", kmReal: 832, kmConv: 835 },
  { origen: "VILLA MERCEDES", destino: "TUCUMAN", kmReal: 905, kmConv: 905 },
  { origen: "! NASCHEL", destino: "VILLA MERCEDES", kmReal: 97, kmConv: 100 },
  { origen: "! SAN SALVADOR", destino: "SAN FRANCISCO", kmReal: 371, kmConv: 370 },
  { origen: "! CIPOLLETTI", destino: "BUENOS AIRES", kmReal: 1165, kmConv: 1165 },
  { origen: "! VILLA MERCEDES", destino: "NASCHEL", kmReal: 97, kmConv: 100 },
  { origen: "! POSADAS", destino: "VIRASORO", kmReal: 93, kmConv: 95 },
  { origen: "! SAN JERONIMO", destino: "RECREO", kmReal: 48, kmConv: 50 },
  { origen: "! CORRIENTES", destino: "APOSTOLES", kmReal: 358, kmConv: 360 },
  { origen: "! MENDOZA", destino: "EL DORADO", kmReal: 1876, kmConv: 1880 },
  { origen: "ZARATE", destino: "PARANÁ", kmReal: 416, kmConv: 420 },
  { origen: "! POSADAS", destino: "CORRIENTES", kmReal: 320, kmConv: 320 },
  { origen: "CONCORDIA", destino: "VILLA MARIA", kmReal: 592, kmConv: 595 },
  { origen: "! SAO GABRIEL", destino: "URUGUAIANA", kmReal: 310, kmConv: 310 },
  { origen: "SANTO TOME", destino: "RECREO", kmReal: 28, kmConv: 30 },
  { origen: "MENDOZA", destino: "VILLA MARIA", kmReal: 615, kmConv: 615 },
  { origen: "CONCORDIA", destino: "GUALEGUAYCHU", kmReal: 207, kmConv: 210 },
  { origen: "VILLA REGINA", destino: "GENERAL ROCA", kmReal: 47, kmConv: 47 },
  { origen: "! CONCORDIA", destino: "RIO TERCERO", kmReal: 721, kmConv: 720 },
  { origen: "SAN FRANCISCO", destino: "VILLA MERCEDES", kmReal: 426, kmConv: 430 },
  { origen: "! URUGUAIANA", destino: "SAN NICOLAS", kmReal: 647, kmConv: 650 },
  { origen: "! URUGUAIANA", destino: "SAO GABRIEL", kmReal: 306, kmConv: 310 },
  { origen: "! SAN LORENZO", destino: "URUGUAIANA", kmReal: 295, kmConv: 295 },
  { origen: "! GUALEGUAYCHU", destino: "RECREO", kmReal: 342, kmConv: 340 },
  { origen: "CORDOBA", destino: "RIO SEGUNDO", kmReal: 47, kmConv: 40 },
  { origen: "LA PLATA", destino: "BARADERO", kmReal: 208, kmConv: 210 },
  { origen: "BELLA ITALIA", destino: "LA PLATA", kmReal: 587, kmConv: 590 },
  { origen: "! ROSARIO", destino: "MERCEDES", kmReal: 253, kmConv: 255 },
  { origen: "LAMARQUE", destino: "VILLA REGINA", kmReal: 154, kmConv: 154 },
  { origen: "PUERTO PIRAY", destino: "LAS VARILLAS", kmReal: 1167, kmConv: 1170 },
  { origen: "! URUGUAIANA", destino: "SAO BERNARDO DO CAMPO", kmReal: 1793, kmConv: 1795 },
  { origen: "! BALCARCE", destino: "URUGUAYANA", kmReal: 1073, kmConv: 1075 },
  { origen: "! ARRECIFES", destino: "ROSARIO", kmReal: 155, kmConv: 155 },
  { origen: "! SAUCE VIEJO", destino: "ROSARIO", kmReal: 150, kmConv: 150 },
  { origen: "! VILLA MERCEDES", destino: "MENDOZA", kmReal: 355, kmConv: 355 },
  { origen: "! MENDOZA", destino: "PUERTO IGUAZU", kmReal: 1974, kmConv: 1975 },
  { origen: "! ROSARIO", destino: "ARRECIFES", kmReal: 155, kmConv: 155 },
  { origen: "! VENADO TUERTO", destino: "ROSARIO", kmReal: 169, kmConv: 170 },
  { origen: "! VILLA MARIA", destino: "JAMES CRAIK", kmReal: 44, kmConv: 45 },
  { origen: "! ANDRESITO", destino: "PUERTO PIRAY", kmReal: 146, kmConv: 145 },
  { origen: "MINAS", destino: "CONCORDIA", kmReal: 622, kmConv: 625 },
  { origen: "ALLEN", destino: "CORDOBA", kmReal: 1121, kmConv: 1125 },
  { origen: "VILLA REGINA", destino: "ALLEN", kmReal: 72, kmConv: 70 },
  { origen: "BELLA ITALIA", destino: "SAN FRANCISCO", kmReal: 92, kmConv: 92 },
  { origen: "! MONTEVIDEO", destino: "HUMBOLDT", kmReal: 711, kmConv: 710 },
  { origen: "VILLA REGINA", destino: "RIO CUARTO", kmReal: 844, kmConv: 845 },
  { origen: "! URUGUAIANA", destino: "VILLA MERCEDES", kmReal: 1012, kmConv: 1015 },
  { origen: "! MENDOZA", destino: "ANDRESITO", kmReal: 2003, kmConv: 2005 },
  { origen: "SUNCHALES", destino: "BAHIA BLANCA", kmReal: 1000, kmConv: 1000 },
  { origen: "! BARROS BLANCOS", destino: "CONCORDIA", kmReal: 555, kmConv: 555 },
  { origen: "! BELLA ITALIA", destino: "BUENOS AIRES", kmReal: 528, kmConv: 530 },
  { origen: "CORDOBA", destino: "BELLA ITALIA", kmReal: 320, kmConv: 320 },
  { origen: "VILLA REGINA", destino: "CHICHINALES", kmReal: 14, kmConv: 14 },
  { origen: "ALLEN", destino: "VILLA REGINA", kmReal: 72, kmConv: 72 },
  { origen: "! BALCARCE", destino: "BARROS BLANCOS", kmReal: 959, kmConv: 960 },
  { origen: "! RIO SEGUNDO", destino: "BUENOS AIRES", kmReal: 658, kmConv: 660 },
  { origen: "! BUENOS AIRES", destino: "RIO SEGUNDO", kmReal: 658, kmConv: 660 },
  { origen: "! SAO BERNARDO DO CAMPO", destino: "JARAGUA DO SUL", kmReal: 580, kmConv: 580 },
  { origen: "! BUENOS AIRES", destino: "SANTIAGO DE CHILE", kmReal: 1407, kmConv: 1408 },
  { origen: "! SAN JAVIER", destino: "PUERTO PIRAY", kmReal: 232, kmConv: 230 },
  { origen: "! SAN FRANCISCO", destino: "BELLA ITALIA", kmReal: 92, kmConv: 95 },
  { origen: "BELLA ITALIA", destino: "NEUQUEN", kmReal: 1345, kmConv: 1345 },
  { origen: "! MONTEVIDEO", destino: "SALTO(URUGUAY)", kmReal: 490, kmConv: 490 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
