/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 3 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "LOMAS DEL MIRADOR", destino: "GARIN", kmReal: 43, kmConv: 45 },
  { origen: "MONTE GRANDE", destino: "VALENTIN ALSINA", kmReal: 36, kmConv: 35 },
  { origen: "JOSE C. PAZ", destino: "LANUS", kmReal: 54, kmConv: 55 },
  { origen: "SAN JORGE", destino: "GENERAL PACHECO", kmReal: 461, kmConv: 460 },
  { origen: "CORDOBA", destino: "JUJUY", kmReal: 901, kmConv: 900 },
  { origen: "LULES", destino: "SAN JUSTO", kmReal: 1238, kmConv: 1240 },
  { origen: "SAN MIGUEL DE TUCUMAN", destino: "LULES", kmReal: 20, kmConv: 20 },
  { origen: "GENERAL PACHECO", destino: "MALVINAS ARGENTINAS", kmReal: 11, kmConv: 10 },
  { origen: "LA MATANZA", destino: "CASEROS", kmReal: 34, kmConv: 35 },
  { origen: "LONGCHAMPS", destino: "MUNRO", kmReal: 49, kmConv: 50 },
  { origen: "JUNIN", destino: "9 DE ABRIL", kmReal: 266, kmConv: 265 },
  { origen: "TUCUMAN", destino: "FREYRE", kmReal: 676, kmConv: 675 },
  { origen: "SAN ANDRES DE GILES", destino: "SUNCHALES", kmReal: 507, kmConv: 505 },
  { origen: "EZEIZA", destino: "PARANÁ", kmReal: 478, kmConv: 480 },
  { origen: "RECONQUISTA", destino: "SUSANA", kmReal: 385, kmConv: 385 },
  { origen: "NEUQUEN", destino: "TIO PUJIO", kmReal: 1055, kmConv: 1055 },
  { origen: "CERES", destino: "SAN FRANCISCO", kmReal: 203, kmConv: 205 },
  { origen: "BURZACO", destino: "TAPIALES", kmReal: 20, kmConv: 20 },
  { origen: "PEREZ", destino: "TORTUGUITAS", kmReal: 272, kmConv: 270 },
  { origen: "SAN ANDRES DE GILES", destino: "SAN MIGUEL DE TUCUMAN", kmReal: 1184, kmConv: 1185 },
  { origen: "TANDIL", destino: "SAN ANDRES DE GILES", kmReal: 375, kmConv: 375 },
  { origen: "VILLA SOLDATI", destino: "CHAJARÍ", kmReal: 498, kmConv: 500 },
  { origen: "SAN FRANCISCO", destino: "PEREZ", kmReal: 272, kmConv: 270 },
  { origen: "VILLA MERCEDES", destino: "TANDIL", kmReal: 813, kmConv: 815 },
  { origen: "GENERAL PIRAN", destino: "BURZACO", kmReal: 328, kmConv: 330 },
  { origen: "LIBERTAD", destino: "MONTEVIDEO", kmReal: 54, kmConv: 55 },
  { origen: "SAN FRANCISCO", destino: "GENERAL PIRAN", kmReal: 888, kmConv: 890 },
  { origen: "LAS HERAS", destino: "RECONQUISTA", kmReal: 1229, kmConv: 1230 },
  { origen: "RIO CUARTO", destino: "LAS HERAS", kmReal: 478, kmConv: 480 },
  { origen: "GENERAL JUAN MADARIAGA", destino: "9 DE ABRIL", kmReal: 350, kmConv: 350 },
  { origen: "SAN CRISTOBAL", destino: "CERES", kmReal: 94, kmConv: 95 },
  { origen: "SAN ANDRES DE GILES", destino: "SAN CRISTOBAL", kmReal: 562, kmConv: 560 },
  { origen: "VILLA URQUIZA", destino: "JOSE LEON SUAREZ", kmReal: 10, kmConv: 10 },
  { origen: "CHACABUCO", destino: "CORDOBA", kmReal: 580, kmConv: 580 },
  { origen: "DOLORES", destino: "VILLA SOLDATI", kmReal: 228, kmConv: 230 },
  { origen: "ARROYITO", destino: "CORONDA", kmReal: 273, kmConv: 275 },
  { origen: "MARIA GRANDE", destino: "SUSANA", kmReal: 192, kmConv: 190 },
  { origen: "MATADEROS", destino: "VILLA URQUIZA", kmReal: 16, kmConv: 15 },
  { origen: "RETIRO", destino: "MATADEROS", kmReal: 17, kmConv: 15 },
  { origen: "CIPOLLETTI", destino: "ZARATE", kmReal: 1120, kmConv: 1120 },
  { origen: "MORENO", destino: "MALVINAS ARGENTINAS", kmReal: 25, kmConv: 25 },
  { origen: "CORDOBA", destino: "BARRACAS", kmReal: 701, kmConv: 700 },
  { origen: "ESPERANZA", destino: "MALVINAS ARGENTINAS", kmReal: 513, kmConv: 515 },
  { origen: "TIO PUJIO", destino: "LIBERTAD", kmReal: 817, kmConv: 815 },
  { origen: "SEGUÍ", destino: "MARIA GRANDE", kmReal: 48, kmConv: 50 },
  { origen: "SUSANA", destino: "SEGUÍ", kmReal: 190, kmConv: 190 },
  { origen: "BARILOCHE", destino: "VILLA MERCEDES", kmReal: 1203, kmConv: 1200 },
  { origen: "MATADEROS", destino: "RETIRO", kmReal: 18, kmConv: 20 },
  { origen: "LA MATANZA", destino: "PILAR", kmReal: 58, kmConv: 60 },
  { origen: "LIBERTAD", destino: "SAN FRANCISCO", kmReal: 737, kmConv: 735 },
  { origen: "TORTUGUITAS", destino: "BURZACO", kmReal: 66, kmConv: 65 },
  { origen: "COLONIA CAROYA", destino: "SAN JORGE", kmReal: 285, kmConv: 285 },
  { origen: "VILLA SOLDATI", destino: "MALVINAS ARGENTINAS", kmReal: 45, kmConv: 45 },
  { origen: "LA PLATA", destino: "VILLA LUGANO", kmReal: 68, kmConv: 70 },
  { origen: "TRELEW", destino: "VALENTIN ALSINA", kmReal: 1351, kmConv: 1350 },
  { origen: "ROSARIO", destino: "GARIN", kmReal: 258, kmConv: 260 },
  { origen: "SAN MARTIN", destino: "BARADERO", kmReal: 143, kmConv: 145 },
  { origen: "CARLOS SPEGAZZINI", destino: "MATADEROS", kmReal: 36, kmConv: 35 },
  { origen: "SAN ANDRES DE GILES", destino: "BURZACO", kmReal: 117, kmConv: 115 },
  { origen: "DON TORCUATO", destino: "SAN MARTIN", kmReal: 16, kmConv: 15 },
  { origen: "ESCOBAR", destino: "COLONIA CAROYA", kmReal: 689, kmConv: 690 },
  { origen: "ARISTOBULO DEL VALLE", destino: "PUERTO PIRAY", kmReal: 107, kmConv: 105 },
  { origen: "MATADEROS", destino: "CIUDADELA", kmReal: 7, kmConv: 10 },
  { origen: "LOMAS DEL MIRADOR", destino: "MATADEROS", kmReal: 3, kmConv: 5 },
  { origen: "MERCEDES", destino: "SAN VICENTE", kmReal: 138, kmConv: 140 },
  { origen: "GUALEGUAY", destino: "LOMAS DEL MIRADOR", kmReal: 232, kmConv: 230 },
  { origen: "LIBERTAD", destino: "GUALEGUAY", kmReal: 385, kmConv: 385 },
  { origen: "LIBERTAD", destino: "CAMPANA", kmReal: 455, kmConv: 455 },
  { origen: "MAR DEL PLATA", destino: "CATRILO", kmReal: 647, kmConv: 645 },
  { origen: "RETIRO", destino: "TRELEW", kmReal: 1355, kmConv: 1355 },
  { origen: "RAFAELA", destino: "ARISTOBULO DEL VALLE", kmReal: 990, kmConv: 990 },
  { origen: "GENERAL RODRIGUEZ", destino: "BURZACO", kmReal: 68, kmConv: 70 },
  { origen: "BURZACO", destino: "PABLO NOGUES", kmReal: 60, kmConv: 60 },
  { origen: "GALVEZ", destino: "MORTEROS", kmReal: 219, kmConv: 220 },
  { origen: "ESPERANZA", destino: "VILLA SOLDATI", kmReal: 496, kmConv: 495 },
  { origen: "MERCEDES", destino: "MUNRO", kmReal: 103, kmConv: 105 },
  { origen: "PONTEVEDRA", destino: "BARADERO", kmReal: 166, kmConv: 165 },
  { origen: "NUEVA POMPEYA", destino: "9 DE ABRIL", kmReal: 18, kmConv: 20 },
  { origen: "CAMPANA", destino: "VALENTIN ALSINA", kmReal: 90, kmConv: 90 },
  { origen: "RETIRO", destino: "LANUS", kmReal: 14, kmConv: 15 },
  { origen: "PUERTO PIRAY", destino: "VILLA SOLDATI", kmReal: 1178, kmConv: 1180 },
  { origen: "SAN AGUSTIN", destino: "RECREO", kmReal: 454, kmConv: 455 },
  { origen: "PONTEVEDRA", destino: "VILLA SOLDATI", kmReal: 52, kmConv: 50 },
  { origen: "PILAR", destino: "CORRIENTES", kmReal: 879, kmConv: 880 },
  { origen: "MERCEDES", destino: "EL PALOMAR", kmReal: 82, kmConv: 80 },
  { origen: "PILAR", destino: "PONTEVEDRA", kmReal: 53, kmConv: 55 },
  { origen: "ESPERANZA", destino: "9 DE ABRIL", kmReal: 504, kmConv: 505 },
  { origen: "RETIRO", destino: "CIPOLLETTI", kmReal: 1140, kmConv: 1140 },
  { origen: "VILLA CRESPO", destino: "VICENTE LOPEZ", kmReal: 12, kmConv: 10 },
  { origen: "TIO PUJIO", destino: "VILLA CRESPO", kmReal: 569, kmConv: 570 },
  { origen: "FATIMA", destino: "ESTEBAN ECHEVERRIA", kmReal: 93, kmConv: 93 },
  { origen: "SAN SALVADOR", destino: "FATIMA", kmReal: 350, kmConv: 350 },
  { origen: "MALVINAS ARGENTINAS", destino: "ESPERANZA", kmReal: 513, kmConv: 515 },
  { origen: "TAPIALES", destino: "MALVINAS ARGENTINAS", kmReal: 17, kmConv: 15 },
  { origen: "TIGRE", destino: "GENERAL PACHECO", kmReal: 9, kmConv: 10 },
  { origen: "ENSENADA", destino: "VILLA SOLDATI", kmReal: 69, kmConv: 70 },
  { origen: "ESPERANZA", destino: "CORONDA", kmReal: 78, kmConv: 80 },
  { origen: "CORDOBA", destino: "RAMONA", kmReal: 277, kmConv: 275 },
  { origen: "LUJAN DE CUYO", destino: "ENSENADA", kmReal: 1116, kmConv: 1115 },
  { origen: "GONZALEZ CATAN", destino: "RETIRO", kmReal: 37, kmConv: 35 },
  { origen: "SANTA TERESITA", destino: "FLORENCIO VARELA", kmReal: 317, kmConv: 315 },
  { origen: "LOMAS DEL MIRADOR", destino: "DON TORCUATO", kmReal: 29, kmConv: 30 },
  { origen: "CERRITO", destino: "ROSARIO", kmReal: 245, kmConv: 245 },
  { origen: "AROCENA", destino: "RECREO", kmReal: 81, kmConv: 80 },
  { origen: "9 DE ABRIL", destino: "AROCENA", kmReal: 420, kmConv: 420 },
  { origen: "GENERAL JUAN MADARIAGA", destino: "EZEIZA", kmReal: 326, kmConv: 325 },
  { origen: "ITUZAINGO", destino: "VILLA LUGANO", kmReal: 25, kmConv: 25 },
  { origen: "RETIRO", destino: "SANTA FE", kmReal: 468, kmConv: 470 },
  { origen: "ISIDRO CASANOVA", destino: "LOMAS DEL MIRADOR", kmReal: 7, kmConv: 10 },
  { origen: "GUALEGUAY", destino: "ISIDRO CASANOVA", kmReal: 248, kmConv: 250 },
  { origen: "MATADEROS", destino: "ROSARIO", kmReal: 300, kmConv: 300 },
  { origen: "MORENO", destino: "MATADEROS", kmReal: 30, kmConv: 30 },
  { origen: "CARLOS SPEGAZZINI", destino: "MONTE GRANDE", kmReal: 25, kmConv: 25 },
  { origen: "ROSARIO", destino: "VILLA MARIA", kmReal: 257, kmConv: 255 },
  { origen: "EZEIZA", destino: "ZONA PORTUARIA", kmReal: 41, kmConv: 40 },
  { origen: "GALVEZ", destino: "CORDOBA", kmReal: 361, kmConv: 360 },
  { origen: "PONTEVEDRA", destino: "9 DE ABRIL", kmReal: 45, kmConv: 45 },
  { origen: "BERAZATEGUI", destino: "SAN JORGE", kmReal: 523, kmConv: 525 },
  { origen: "VILLA MERCEDES", destino: "PONTEVEDRA", kmReal: 683, kmConv: 685 },
  { origen: "MARTINEZ", destino: "CORDOBA", kmReal: 677, kmConv: 675 },
  { origen: "MERCEDES", destino: "MARTINEZ", kmReal: 101, kmConv: 100 },
  { origen: "RECONQUISTA", destino: "SANTO TOME", kmReal: 333, kmConv: 335 },
  { origen: "CHASCOMUS", destino: "SAN GERONIMO", kmReal: 939, kmConv: 940 },
  { origen: "MAR DEL PLATA", destino: "CHASCOMUS", kmReal: 289, kmConv: 290 },
  { origen: "ITUZAINGO", destino: "BARADERO", kmReal: 152, kmConv: 150 },
  { origen: "SINSACATE", destino: "CORDOBA", kmReal: 59, kmConv: 60 },
  { origen: "POZO DEL TIGRE", destino: "SINSACATE", kmReal: 28, kmConv: 30 },
  { origen: "CORDOBA", destino: "POZO DEL TIGRE", kmReal: 54, kmConv: 55 },
  { origen: "SAN LUIS", destino: "LUJAN DE CUYO", kmReal: 270, kmConv: 270 },
  { origen: "GUALEGUAY", destino: "VILLA MARIA", kmReal: 428, kmConv: 430 },
  { origen: "GARIN", destino: "SANTA FE", kmReal: 601, kmConv: 600 },
  { origen: "TIGRE", destino: "TICINO", kmReal: 582, kmConv: 580 },
  { origen: "LA MATANZA", destino: "EL JAGUEL", kmReal: 25, kmConv: 25 },
  { origen: "BANFIELD", destino: "VILLA SOLDATI", kmReal: 16, kmConv: 15 },
  { origen: "MONTE GRANDE", destino: "CHASCOMUS", kmReal: 126, kmConv: 125 },
  { origen: "BOSQUES", destino: "9 DE ABRIL", kmReal: 65, kmConv: 65 },
  { origen: "VILLA MERCEDES", destino: "TORTUGUITAS", kmReal: 706, kmConv: 705 },
  { origen: "UNQUILLO", destino: "CORDOBA", kmReal: 31, kmConv: 30 },
  { origen: "ESCOBAR", destino: "BOSQUES", kmReal: 97, kmConv: 95 },
  { origen: "RETIRO", destino: "AVELLANEDA", kmReal: 9, kmConv: 10 },
  { origen: "RETIRO", destino: "RIO CUARTO", kmReal: 609, kmConv: 610 },
  { origen: "MERCEDES", destino: "ESCOBAR", kmReal: 95, kmConv: 95 },
  { origen: "CHASCOMUS", destino: "UNQUILLO", kmReal: 849, kmConv: 850 },
  { origen: "GENERAL PIRAN", destino: "CHASCOMUS", kmReal: 204, kmConv: 205 },
  { origen: "RECREO", destino: "CORONDA", kmReal: 69, kmConv: 70 },
  { origen: "CAMPANA", destino: "FLORENCIO VARELA", kmReal: 107, kmConv: 105 },
  { origen: "ESCOBAR", destino: "BANFIELD", kmReal: 70, kmConv: 70 },
  { origen: "RAFAELA", destino: "GALVEZ", kmReal: 112, kmConv: 110 },
  { origen: "ESCOBAR", destino: "SAN JORGE", kmReal: 442, kmConv: 440 },
  { origen: "CHASCOMUS", destino: "SAN LUIS", kmReal: 914, kmConv: 915 },
  { origen: "DOLORES", destino: "CHASCOMUS", kmReal: 93, kmConv: 95 },
  { origen: "PARQUE PATRICIOS", destino: "MALVINAS ARGENTINAS", kmReal: 32, kmConv: 30 },
  { origen: "MATADEROS", destino: "PARQUE PATRICIOS", kmReal: 13, kmConv: 15 },
  { origen: "ESCOBAR", destino: "FLORENCIO VARELA", kmReal: 81, kmConv: 80 },
  { origen: "SAN FRANCISCO", destino: "DOLORES", kmReal: 779, kmConv: 780 },
  { origen: "SAN JOSE JACHEL", destino: "CORDOBA", kmReal: 610, kmConv: 610 },
  { origen: "CORDOBA", destino: "SAN JOSE JACHEL", kmReal: 611, kmConv: 610 },
  { origen: "FREYRE", destino: "RAMONA", kmReal: 28, kmConv: 30 },
  { origen: "VILLA TESEI", destino: "MORON", kmReal: 5, kmConv: 5 },
  { origen: "EZEIZA", destino: "CHASCOMUS", kmReal: 123, kmConv: 125 },
  { origen: "VILLA DEL PARQUE", destino: "CHASCOMUS", kmReal: 149, kmConv: 150 },
  { origen: "JOSE INGENIEROS", destino: "VILLA LUGANO", kmReal: 13, kmConv: 15 },
  { origen: "MONTEROS", destino: "CORDOBA", kmReal: 524, kmConv: 525 },
  { origen: "ROSARIO", destino: "CORONDA", kmReal: 126, kmConv: 125 },
  { origen: "EZEIZA", destino: "FLORENCIO VARELA", kmReal: 30, kmConv: 30 },
  { origen: "SAN FRANCISCO", destino: "PUERTO PIRAY", kmReal: 1097, kmConv: 1095 },
  { origen: "CHACABUCO", destino: "RAFAELA", kmReal: 478, kmConv: 480 },
  { origen: "PABLO NOGUES", destino: "CHACABUCO", kmReal: 193, kmConv: 195 },
  { origen: "VILLA URQUIZA", destino: "CARLOS SPEGAZZINI", kmReal: 53, kmConv: 55 },
  { origen: "CHASCOMUS", destino: "CONCEPCION DEL URUGUAY", kmReal: 422, kmConv: 420 },
  { origen: "SANTA TERESITA", destino: "CHASCOMUS", kmReal: 220, kmConv: 220 },
  { origen: "ZONA PORTUARIA", destino: "RETIRO", kmReal: 5, kmConv: 5 },
  { origen: "GENERAL RODRIGUEZ", destino: "9 DE ABRIL", kmReal: 60, kmConv: 60 },
  { origen: "SANTO TOME", destino: "VILLA MARIA", kmReal: 290, kmConv: 290 },
  { origen: "VICTORIA", destino: "SAN FRANCISCO", kmReal: 318, kmConv: 320 },
  { origen: "VICTORIA", destino: "CORDOBA", kmReal: 467, kmConv: 465 },
  { origen: "SAN FRANCISCO", destino: "VICTORIA", kmReal: 318, kmConv: 320 },
  { origen: "CORDOBA", destino: "VICTORIA", kmReal: 467, kmConv: 465 },
  { origen: "PARQUE PATRICIOS", destino: "TORTUGUITAS", kmReal: 51, kmConv: 50 },
  { origen: "RIO GALLEGOS", destino: "VILLA SOLDATI", kmReal: 2495, kmConv: 2495 },
  { origen: "GALVEZ", destino: "GOBERNADOR CRESPO", kmReal: 243, kmConv: 245 },
  { origen: "SAN FRANCISCO", destino: "ALTA GRACIA", kmReal: 262, kmConv: 260 },
  { origen: "GALVEZ", destino: "SANTO TOME", kmReal: 76, kmConv: 75 },
  { origen: "SAN ANTONIO DE PADUA", destino: "ZARATE", kmReal: 94, kmConv: 95 },
  { origen: "TORTUGUITAS", destino: "ALTA GRACIA", kmReal: 678, kmConv: 680 },
  { origen: "CARLOS SPEGAZZINI", destino: "CHASCOMUS", kmReal: 130, kmConv: 130 },
  { origen: "VILLA URQUIZA", destino: "MORON", kmReal: 20, kmConv: 20 },
  { origen: "DOCK SUD", destino: "LANUS", kmReal: 9, kmConv: 10 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "MATADEROS", kmReal: 29, kmConv: 30 },
  { origen: "SAN PEDRO", destino: "TORTUGUITAS", kmReal: 141, kmConv: 140 },
  { origen: "PUEBLO ESTHER", destino: "CORDOBA", kmReal: 420, kmConv: 420 },
  { origen: "MONTEVIDEO", destino: "PUEBLO ESTHER", kmReal: 634, kmConv: 635 },
  { origen: "PARQUE PATRICIOS", destino: "VILLA SOLDATI", kmReal: 6, kmConv: 5 },
  { origen: "CAMPANA", destino: "ZONA PORTUARIA", kmReal: 78, kmConv: 80 },
  { origen: "WILDE", destino: "SAN ANTONIO DE PADUA", kmReal: 47, kmConv: 45 },
  { origen: "SAN FRANCISCO", destino: "WILDE", kmReal: 577, kmConv: 575 },
  { origen: "VILLA URQUIZA", destino: "MATADEROS", kmReal: 14, kmConv: 15 },
  { origen: "SANTO TOME", destino: "CORONDA", kmReal: 43, kmConv: 45 },
  { origen: "FLORESTA", destino: "PARQUE PATRICIOS", kmReal: 10, kmConv: 10 },
  { origen: "SAN FRANCISCO", destino: "FLORESTA", kmReal: 559, kmConv: 560 },
  { origen: "RETIRO", destino: "RIO GALLEGOS", kmReal: 2590, kmConv: 2590 },
  { origen: "VILLA GESELL", destino: "VILLA SOLDATI", kmReal: 386, kmConv: 385 },
  { origen: "SAN FRANCISCO", destino: "VILLA GESELL", kmReal: 938, kmConv: 940 },
  { origen: "SAN LUIS", destino: "RIO CUARTO", kmReal: 217, kmConv: 215 },
  { origen: "BARRACAS", destino: "ESCOBAR", kmReal: 60, kmConv: 60 },
  { origen: "RIO SEGUNDO", destino: "SAN FRANCISCO", kmReal: 209, kmConv: 210 },
  { origen: "TORTUGUITAS", destino: "MALVINAS ARGENTINAS", kmReal: 83, kmConv: 85 },
  { origen: "TIO PUJIO", destino: "INGENIERO BUDGE", kmReal: 584, kmConv: 585 },
  { origen: "CAMPANA", destino: "PABLO NOGUES", kmReal: 47, kmConv: 45 },
  { origen: "TIGRE", destino: "BARRACAS", kmReal: 38, kmConv: 40 },
  { origen: "ESCOBAR", destino: "DON TORCUATO", kmReal: 26, kmConv: 25 },
  { origen: "CARLOS PAZ", destino: "COSQUIN", kmReal: 28, kmConv: 30 },
  { origen: "SAN JORGE", destino: "ARROYO SECO", kmReal: 246, kmConv: 245 },
  { origen: "EZEIZA", destino: "ZARATE", kmReal: 118, kmConv: 120 },
  { origen: "EZEIZA", destino: "BARRACAS", kmReal: 37, kmConv: 35 },
  { origen: "EZEIZA", destino: "VILLA MADERO", kmReal: 22, kmConv: 20 },
  { origen: "VILLA MADERO", destino: "MONTE GRANDE", kmReal: 26, kmConv: 25 },
  { origen: "SAN JUAN", destino: "SAN LUIS", kmReal: 325, kmConv: 325 },
  { origen: "PILAR", destino: "JOSE LEON SUAREZ", kmReal: 39, kmConv: 40 },
  { origen: "LA TOMA", destino: "CORDOBA", kmReal: 345, kmConv: 345 },
  { origen: "CORDOBA", destino: "LA TOMA", kmReal: 345, kmConv: 345 },
  { origen: "SAN NICOLAS", destino: "CORDOBA", kmReal: 478, kmConv: 480 },
  { origen: "CORDOBA", destino: "SAN NICOLAS", kmReal: 478, kmConv: 480 },
  { origen: "MUNRO", destino: "VILLA LUGANO", kmReal: 24, kmConv: 25 },
  { origen: "BAHIA BLANCA", destino: "BARADERO", kmReal: 727, kmConv: 725 },
  { origen: "GENERAL ALVEAR", destino: "CORDOBA", kmReal: 670, kmConv: 670 },
  { origen: "CORDOBA", destino: "GENERAL ALVEAR", kmReal: 672, kmConv: 670 },
  { origen: "SAN LUIS", destino: "MUNRO", kmReal: 817, kmConv: 815 },
  { origen: "RIO CUARTO", destino: "SAN LUIS", kmReal: 217, kmConv: 215 },
  { origen: "SAN JUSTO", destino: "CAMPANA", kmReal: 85, kmConv: 85 },
  { origen: "SAN FERNANDO", destino: "VILLA SOLDATI", kmReal: 35, kmConv: 35 },
  { origen: "BAHIA BLANCA", destino: "LANUS", kmReal: 632, kmConv: 630 },
  { origen: "DON TORCUATO", destino: "PABLO NOGUES", kmReal: 9, kmConv: 10 },
  { origen: "CONCORDIA", destino: "SAN JUSTO", kmReal: 434, kmConv: 435 },
  { origen: "EZEIZA", destino: "VILLA LUGANO", kmReal: 23, kmConv: 25 },
  { origen: "BERAZATEGUI", destino: "ZARATE", kmReal: 120, kmConv: 120 },
  { origen: "RAFAELA", destino: "BERAZATEGUI", kmReal: 569, kmConv: 570 },
  { origen: "SAN MARTIN", destino: "CORDOBA", kmReal: 644, kmConv: 645 },
  { origen: "CAMPANA", destino: "SAN MARTIN", kmReal: 72, kmConv: 70 },
  { origen: "LAS HERAS", destino: "FRANCK", kmReal: 885, kmConv: 885 },
  { origen: "CATRILO", destino: "LANUS", kmReal: 531, kmConv: 530 },
  { origen: "JUNIN", destino: "VILLA SOLDATI", kmReal: 258, kmConv: 260 },
  { origen: "RECREO", destino: "TORTUGUITAS", kmReal: 452, kmConv: 450 },
  { origen: "SALTA", destino: "RECREO", kmReal: 602, kmConv: 600 },
  { origen: "COMODORO RIVADAVIA", destino: "VILLA SOLDATI", kmReal: 1801, kmConv: 1800 },
  { origen: "PARANÁ", destino: "CATRILO", kmReal: 765, kmConv: 765 },
  { origen: "MONTEVIDEO", destino: "TAPIALES", kmReal: 579, kmConv: 580 },
  { origen: "LAS HERAS", destino: "SAN FRANCISCO", kmReal: 773, kmConv: 775 },
  { origen: "BURZACO", destino: "GALVEZ", kmReal: 451, kmConv: 450 },
  { origen: "WILDE", destino: "BARRACAS", kmReal: 10, kmConv: 10 },
  { origen: "PUERTO PIRAY", destino: "TIGRE", kmReal: 1157, kmConv: 1155 },
  { origen: "ESCOBAR", destino: "BARADERO", kmReal: 99, kmConv: 100 },
  { origen: "TUCUMAN", destino: "GENERAL PACHECO", kmReal: 1224, kmConv: 1225 },
  { origen: "MATADEROS", destino: "WILDE", kmReal: 27, kmConv: 25 },
  { origen: "RAMONA", destino: "MATADEROS", kmReal: 589, kmConv: 590 },
  { origen: "CATAMARCA", destino: "TUCUMAN", kmReal: 227, kmConv: 225 },
  { origen: "RETIRO", destino: "COMODORO RIVADAVIA", kmReal: 1812, kmConv: 1810 },
  { origen: "LA MATANZA", destino: "RETIRO", kmReal: 38, kmConv: 40 },
  { origen: "OLAVARRIA", destino: "9 DE ABRIL", kmReal: 338, kmConv: 340 },
  { origen: "AZUL", destino: "FLORENCIO VARELA", kmReal: 311, kmConv: 310 },
  { origen: "CHASCOMUS", destino: "RIO CUARTO", kmReal: 737, kmConv: 735 },
  { origen: "LOMAS DE ZAMORA", destino: "CHASCOMUS", kmReal: 148, kmConv: 150 },
  { origen: "SANTA FE", destino: "CORONDA", kmReal: 50, kmConv: 50 },
  { origen: "RETIRO", destino: "POSADAS", kmReal: 1000, kmConv: 1000 },
  { origen: "EL TIO", destino: "CORDOBA", kmReal: 144, kmConv: 145 },
  { origen: "SAN FRANCISCO", destino: "EL TIO", kmReal: 72, kmConv: 70 },
  { origen: "PILAR", destino: "VILLA LUGANO", kmReal: 64, kmConv: 65 },
  { origen: "GENERAL RODRIGUEZ", destino: "AZUL", kmReal: 319, kmConv: 320 },
  { origen: "GARIN", destino: "GENERAL RODRIGUEZ", kmReal: 40, kmConv: 40 },
  { origen: "FLORENCIO VARELA", destino: "9 DE ABRIL", kmReal: 27, kmConv: 25 },
  { origen: "GENERAL PIRAN", destino: "EZEIZA", kmReal: 324, kmConv: 325 },
  { origen: "GALVEZ", destino: "ARROYITO", kmReal: 230, kmConv: 230 },
  { origen: "SAN FRANCISCO", destino: "INGENIERO ALLAN", kmReal: 605, kmConv: 605 },
  { origen: "GUALEGUAY", destino: "ITUZAINGO", kmReal: 233, kmConv: 235 },
  { origen: "SUSANA", destino: "GENERAL PIRAN", kmReal: 857, kmConv: 855 },
  { origen: "HAEDO", destino: "VICENTE LOPEZ", kmReal: 24, kmConv: 25 },
  { origen: "TORTUGUITAS", destino: "FATIMA", kmReal: 28, kmConv: 30 },
  { origen: "SAN MARTIN", destino: "EL TIO", kmReal: 629, kmConv: 630 },
  { origen: "TIGRE", destino: "SAN MARTIN", kmReal: 25, kmConv: 25 },
  { origen: "CLUCELLAS", destino: "SAN FRANCISCO", kmReal: 40, kmConv: 40 },
  { origen: "CIPOLLETTI", destino: "VILLA MERCEDES", kmReal: 783, kmConv: 785 },
  { origen: "MORON", destino: "TORTUGUITAS", kmReal: 54, kmConv: 55 },
  { origen: "RETIRO", destino: "PUERTO IGUAZU", kmReal: 1276, kmConv: 1275 },
  { origen: "MORENO", destino: "RETIRO", kmReal: 44, kmConv: 45 },
  { origen: "CORRAL DE BUSTOS", destino: "RIO CUARTO", kmReal: 215, kmConv: 215 },
  { origen: "CONCORDIA", destino: "CORRAL DE BUSTOS", kmReal: 542, kmConv: 540 },
  { origen: "BARRACAS", destino: "SARANDI", kmReal: 6, kmConv: 5 },
  { origen: "SALTO", destino: "MONTEVIDEO", kmReal: 659, kmConv: 660 },
  { origen: "SAN FRANCISCO", destino: "MORON", kmReal: 570, kmConv: 570 },
  { origen: "SAN JUSTO", destino: "LANUS", kmReal: 23, kmConv: 25 },
  { origen: "ZARATE", destino: "CIPOLLETTI", kmReal: 1121, kmConv: 1120 },
  { origen: "AZUL", destino: "9 DE ABRIL", kmReal: 286, kmConv: 285 },
  { origen: "GARIN", destino: "AZUL", kmReal: 384, kmConv: 385 },
  { origen: "TORTUGUITAS", destino: "LOMAS DE ZAMORA", kmReal: 57, kmConv: 55 },
  { origen: "GENERAL PACHECO", destino: "SANTA FE", kmReal: 436, kmConv: 435 },
  { origen: "CAMPANA", destino: "GENERAL PACHECO", kmReal: 48, kmConv: 50 },
  { origen: "HAEDO", destino: "9 DE ABRIL", kmReal: 28, kmConv: 30 },
  { origen: "SAN JORGE", destino: "9 DE ABRIL", kmReal: 506, kmConv: 505 },
  { origen: "9 DE ABRIL", destino: "CORDOBA", kmReal: 710, kmConv: 710 },
  { origen: "PABLO NOGUES", destino: "HAEDO", kmReal: 46, kmConv: 45 },
  { origen: "GRAND BOURG", destino: "TAPIALES", kmReal: 50, kmConv: 50 },
  { origen: "BURZACO", destino: "MONTE GRANDE", kmReal: 9, kmConv: 10 },
  { origen: "ESCOBAR", destino: "SARANDI", kmReal: 65, kmConv: 65 },
  { origen: "LAS VARILLAS", destino: "ARROYITO", kmReal: 70, kmConv: 70 },
  { origen: "LAS VARILLAS", destino: "VILLA MERCEDES", kmReal: 345, kmConv: 345 },
  { origen: "BERNAL OESTE", destino: "9 DE ABRIL", kmReal: 40, kmConv: 40 },
  { origen: "CORDOBA", destino: "BERAZATEGUI", kmReal: 725, kmConv: 725 },
  { origen: "RAMONA", destino: "MUNRO", kmReal: 571, kmConv: 570 },
  { origen: "ENSENADA", destino: "9 DE ABRIL", kmReal: 79, kmConv: 80 },
  { origen: "VILLA SOLDATI", destino: "ENSENADA", kmReal: 64, kmConv: 65 },
  { origen: "MERCEDES", destino: "MONTE GRANDE", kmReal: 118, kmConv: 120 },
  { origen: "SAN JUSTO", destino: "VILLA MERCEDES", kmReal: 685, kmConv: 685 },
  { origen: "MERCEDES", destino: "EZEIZA", kmReal: 117, kmConv: 115 },
  { origen: "CAMPANA", destino: "DON TORCUATO", kmReal: 53, kmConv: 55 },
  { origen: "BALNEARIA", destino: "DON TORCUATO", kmReal: 656, kmConv: 655 },
  { origen: "MONTE GRANDE", destino: "MENDOZA", kmReal: 1067, kmConv: 1065 },
  { origen: "RAMONA", destino: "VILLA CRESPO", kmReal: 585, kmConv: 585 },
  { origen: "SANTO TOME", destino: "RAMONA", kmReal: 156, kmConv: 155 },
  { origen: "GUALEGUAY", destino: "CORDOBA", kmReal: 572, kmConv: 570 },
  { origen: "MONTE GRANDE", destino: "EL PALOMAR", kmReal: 42, kmConv: 40 },
  { origen: "MATADEROS", destino: "VILLA LUZURIAGA", kmReal: 10, kmConv: 10 },
  { origen: "LONGCHAMPS", destino: "BURZACO", kmReal: 4, kmConv: 5 },
  { origen: "GONZALEZ CATAN", destino: "GARIN", kmReal: 66, kmConv: 65 },
  { origen: "SAN SALVADOR", destino: "9 DE ABRIL", kmReal: 410, kmConv: 410 },
  { origen: "SALTO", destino: "RIO CUARTO", kmReal: 438, kmConv: 440 },
  { origen: "MONTEVIDEO", destino: "SALTO", kmReal: 658, kmConv: 660 },
  { origen: "CONCORDIA", destino: "SAN JORGE", kmReal: 446, kmConv: 445 },
  { origen: "MERCEDES", destino: "CARCARA&#209;A", kmReal: 295, kmConv: 295 },
  { origen: "VILLA LUZURIAGA", destino: "SAN FRANCISCO", kmReal: 567, kmConv: 565 },
  { origen: "BRINKMANN", destino: "SAN JORGE", kmReal: 153, kmConv: 155 },
  { origen: "VILLA CRESPO", destino: "TORTUGUITAS", kmReal: 39, kmConv: 40 },
  { origen: "CONCORDIA", destino: "RIO TERCERO", kmReal: 745, kmConv: 745 },
  { origen: "MENDOZA", destino: "FLORENCIO VARELA", kmReal: 1073, kmConv: 1075 },
  { origen: "TIGRE", destino: "RETIRO", kmReal: 32, kmConv: 30 },
  { origen: "LOMAS DE ZAMORA", destino: "BURZACO", kmReal: 9, kmConv: 10 },
  { origen: "SAN BERNARDO", destino: "VILLA SOLDATI", kmReal: 370, kmConv: 370 },
  { origen: "PABLO NOGUES", destino: "TIGRE", kmReal: 22, kmConv: 20 },
  { origen: "SAN FRANCISCO", destino: "MATADEROS", kmReal: 564, kmConv: 565 },
  { origen: "MONTE VERA", destino: "RAFAELA", kmReal: 85, kmConv: 85 },
  { origen: "COL SANTA ROSA", destino: "MONTE VERA", kmReal: 585, kmConv: 585 },
  { origen: "BERISSO", destino: "VILLA SOLDATI", kmReal: 73, kmConv: 75 },
  { origen: "MENDOZA", destino: "SAN LUIS", kmReal: 258, kmConv: 260 },
  { origen: "SAN JUSTO", destino: "MONTE GRANDE", kmReal: 24, kmConv: 25 },
  { origen: "BARADERO", destino: "MONTE GRANDE", kmReal: 178, kmConv: 180 },
  { origen: "SANTA TERESITA", destino: "SAN BERNARDO", kmReal: 22, kmConv: 20 },
  { origen: "ESCOBAR", destino: "GENERAL PACHECO", kmReal: 21, kmConv: 20 },
  { origen: "MORTEROS", destino: "MENDOZA", kmReal: 848, kmConv: 850 },
  { origen: "SANTA FE", destino: "MONTE VERA", kmReal: 12, kmConv: 10 },
  { origen: "COL SANTA ROSA", destino: "SANTA FE", kmReal: 573, kmConv: 575 },
  { origen: "SANTO TOME", destino: "EZEIZA", kmReal: 482, kmConv: 480 },
  { origen: "SANTO TOME", destino: "ZONA PORTUARIA", kmReal: 455, kmConv: 455 },
  { origen: "GOBERNADOR CRESPO", destino: "SANTO TOME", kmReal: 162, kmConv: 160 },
  { origen: "CORDOBA", destino: "SAUCE VIEJO", kmReal: 369, kmConv: 370 },
  { origen: "SAN PEDRO", destino: "VILLA MARIA", kmReal: 400, kmConv: 400 },
  { origen: "SAN JORGE", destino: "ROSARIO", kmReal: 198, kmConv: 200 },
  { origen: "SUSANA", destino: "TAPIALES", kmReal: 535, kmConv: 535 },
  { origen: "VILLA MERCEDES", destino: "SAN FRANCISCO", kmReal: 427, kmConv: 425 },
  { origen: "SAN ISIDRO", destino: "CORDOBA", kmReal: 677, kmConv: 675 },
  { origen: "VILLA SOLDATI", destino: "SAN ISIDRO", kmReal: 33, kmConv: 35 },
  { origen: "BARRACAS", destino: "GARIN", kmReal: 48, kmConv: 50 },
  { origen: "CORRIENTES", destino: "APÓSTOLES", kmReal: 347, kmConv: 345 },
  { origen: "BRINKMANN", destino: "VILLA MERCEDES", kmReal: 489, kmConv: 490 },
  { origen: "GUALEGUAY", destino: "SANTA FE", kmReal: 253, kmConv: 255 },
  { origen: "TAPIALES", destino: "VILLA MAIPU", kmReal: 23, kmConv: 25 },
  { origen: "DESVIO ARIJON", destino: "MAR DEL PLATA", kmReal: 846, kmConv: 845 },
  { origen: "BARADERO", destino: "SAN ANDRES DE GILES", kmReal: 78, kmConv: 80 },
  { origen: "VILLA SOLDATI", destino: "BRINKMANN", kmReal: 632, kmConv: 630 },
  { origen: "MUNRO", destino: "MONTE GRANDE", kmReal: 45, kmConv: 45 },
  { origen: "VICENTE LOPEZ", destino: "MUNRO", kmReal: 9, kmConv: 10 },
  { origen: "ROSARIO", destino: "CAMPANA", kmReal: 222, kmConv: 220 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "BRINKMANN", kmReal: 496, kmConv: 495 },
  { origen: "SAN FRANCISCO", destino: "NEUQUEN", kmReal: 1292, kmConv: 1290 },
  { origen: "EZEIZA", destino: "MORENO", kmReal: 54, kmConv: 55 },
  { origen: "PUEBLO ESTHER", destino: "SAN FRANCISCO", kmReal: 307, kmConv: 305 },
  { origen: "PUEBLO ESTHER", destino: "CAMPANA", kmReal: 211, kmConv: 210 },
  { origen: "VILLA MERCEDES", destino: "PUEBLO ESTHER", kmReal: 537, kmConv: 535 },
  { origen: "ISIDRO CASANOVA", destino: "PABLO NOGUES", kmReal: 44, kmConv: 45 },
  { origen: "RAFAELA", destino: "ISIDRO CASANOVA", kmReal: 548, kmConv: 550 },
  { origen: "APÓSTOLES", destino: "BARRACAS", kmReal: 945, kmConv: 945 },
  { origen: "GONZALEZ CATAN", destino: "SAN ANDRES DE GILES", kmReal: 101, kmConv: 100 },
  { origen: "GENERAL RODRIGUEZ", destino: "SANTO TOME", kmReal: 433, kmConv: 435 },
  { origen: "ISIDRO CASANOVA", destino: "VILLA MADERO", kmReal: 10, kmConv: 10 },
  { origen: "SUSANA", destino: "ISIDRO CASANOVA", kmReal: 536, kmConv: 535 },
  { origen: "VILLA MADERO", destino: "VILLA SOLDATI", kmReal: 8, kmConv: 10 },
  { origen: "SAN ISIDRO", destino: "VILLA MADERO", kmReal: 30, kmConv: 30 },
  { origen: "SUSANA", destino: "SAN ISIDRO", kmReal: 509, kmConv: 510 },
  { origen: "SAN JORGE", destino: "PATERNAL", kmReal: 486, kmConv: 485 },
  { origen: "VILLA SOLDATI", destino: "GONZALEZ CATAN", kmReal: 27, kmConv: 25 },
  { origen: "RECREO", destino: "CA&#209;UELAS", kmReal: 513, kmConv: 515 },
  { origen: "SAUCE VIEJO", destino: "RECREO", kmReal: 43, kmConv: 45 },
  { origen: "TRENQUE LAUQUEN", destino: "VILLA MERCEDES", kmReal: 475, kmConv: 475 },
  { origen: "GARIN", destino: "RETIRO", kmReal: 42, kmConv: 40 },
  { origen: "GARIN", destino: "PEDRO LURO", kmReal: 42, kmConv: 40 },
  { origen: "BERAZATEGUI", destino: "SANTO TOME", kmReal: 486, kmConv: 485 },
  { origen: "ZARATE", destino: "BERAZATEGUI", kmReal: 120, kmConv: 120 },
  { origen: "TORTUGUITAS", destino: "MATADEROS", kmReal: 45, kmConv: 45 },
  { origen: "FIGHIERA", destino: "ITUZAINGO", kmReal: 266, kmConv: 265 },
  { origen: "RAFAELA", destino: "FIGHIERA", kmReal: 280, kmConv: 280 },
  { origen: "LAS HERAS", destino: "RESISTENCIA", kmReal: 1448, kmConv: 1450 },
  { origen: "GARIN", destino: "MONTE GRANDE", kmReal: 69, kmConv: 70 },
  { origen: "TORTUGUITAS", destino: "TEMPERLEY", kmReal: 62, kmConv: 60 },
  { origen: "SUSANA", destino: "TORTUGUITAS", kmReal: 500, kmConv: 500 },
  { origen: "VILLA BALLESTER", destino: "RIO TERCERO", kmReal: 670, kmConv: 670 },
  { origen: "BARRACAS", destino: "VILLA BALLESTER", kmReal: 30, kmConv: 30 },
  { origen: "BOLIVAR", destino: "TRENQUE LAUQUEN", kmReal: 165, kmConv: 165 },
  { origen: "RETIRO", destino: "BOLIVAR", kmReal: 336, kmConv: 335 },
  { origen: "GENERAL LAVALLE", destino: "VILLA SOLDATI", kmReal: 320, kmConv: 320 },
  { origen: "VILLA MARIA", destino: "BARRACAS", kmReal: 557, kmConv: 555 },
  { origen: "BARADERO", destino: "ZARATE", kmReal: 67, kmConv: 67 },
  { origen: "CORONDA", destino: "ROSARIO", kmReal: 127, kmConv: 125 },
  { origen: "SIERRA DE LOS PADRES", destino: "VILLA SOLDATI", kmReal: 427, kmConv: 425 },
  { origen: "LA MATANZA", destino: "ZARATE", kmReal: 114, kmConv: 115 },
  { origen: "WILDE", destino: "CORONDA", kmReal: 438, kmConv: 440 },
  { origen: "VILLA SOLDATI", destino: "WILDE", kmReal: 25, kmConv: 25 },
  { origen: "FLORENCIO VARELA", destino: "MONTE GRANDE", kmReal: 21, kmConv: 20 },
  { origen: "CATRILO", destino: "SANTA FE", kmReal: 739, kmConv: 740 },
  { origen: "LA PLATA", destino: "CATRILO", kmReal: 584, kmConv: 585 },
  { origen: "RETIRO", destino: "GENERAL LAVALLE", kmReal: 312, kmConv: 310 },
  { origen: "ESCOBAR", destino: "RETIRO", kmReal: 54, kmConv: 55 },
  { origen: "BARRACAS", destino: "MONTE CRISTO", kmReal: 713, kmConv: 715 },
  { origen: "GENERAL RODRIGUEZ", destino: "BARRACAS", kmReal: 59, kmConv: 60 },
  { origen: "EZEIZA", destino: "ALTA GRACIA", kmReal: 733, kmConv: 735 },
  { origen: "CORONDA", destino: "CORDOBA", kmReal: 395, kmConv: 395 },
  { origen: "GENERAL PACHECO", destino: "CORONDA", kmReal: 389, kmConv: 390 },
  { origen: "PABLO NOGUES", destino: "GENERAL PACHECO", kmReal: 10, kmConv: 10 },
  { origen: "PABLO NOGUES", destino: "CORONDA", kmReal: 390, kmConv: 390 },
  { origen: "LA PATERNAL", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "BRINKMANN", destino: "DEVOTO", kmReal: 85, kmConv: 85 },
  { origen: "CORDOBA", destino: "FLORENCIO VARELA", kmReal: 723, kmConv: 725 },
  { origen: "PORTE&#209;A", destino: "LA PATERNAL", kmReal: 603, kmConv: 605 },
  { origen: "NEUQUEN", destino: "TAPIALES", kmReal: 1124, kmConv: 1125 },
  { origen: "RECREO", destino: "GENERAL RODRIGUEZ", kmReal: 461, kmConv: 460 },
  { origen: "COL SANTA ROSA", destino: "SAUCE VIEJO", kmReal: 598, kmConv: 600 },
  { origen: "RESISTENCIA", destino: "COL SANTA ROSA", kmReal: 177, kmConv: 175 },
  { origen: "GUALEGUAY", destino: "BRINKMANN", kmReal: 487, kmConv: 485 },
  { origen: "CAMPANA", destino: "ESCOBAR", kmReal: 30, kmConv: 30 },
  { origen: "SAN JORGE", destino: "ITUZAINGO", kmReal: 495, kmConv: 495 },
  { origen: "VILLA CARLOS PAZ", destino: "TIO PUJIO", kmReal: 171, kmConv: 170 },
  { origen: "NEUQUEN", destino: "VILLA SOLDATI", kmReal: 1131, kmConv: 1130 },
  { origen: "LA MATANZA", destino: "CAMPANA", kmReal: 105, kmConv: 105 },
  { origen: "CONCORDIA", destino: "LA MATANZA", kmReal: 471, kmConv: 471 },
  { origen: "TEMPERLEY", destino: "9 DE ABRIL", kmReal: 15, kmConv: 15 },
  { origen: "SUSANA", destino: "TEMPERLEY", kmReal: 547, kmConv: 545 },
  { origen: "CAMPANA", destino: "CARLOS PAZ", kmReal: 657, kmConv: 655 },
  { origen: "VILLA TESEI", destino: "CAMPANA", kmReal: 75, kmConv: 75 },
  { origen: "SAN JORGE", destino: "SUSANA", kmReal: 83, kmConv: 85 },
  { origen: "RECREO", destino: "VILLA MERCEDES", kmReal: 580, kmConv: 580 },
  { origen: "ARISTOBULO DEL VALLE", destino: "SANTA ANA", kmReal: 95, kmConv: 95 },
  { origen: "LOMA HERMOSA", destino: "LA PLATA", kmReal: 85, kmConv: 85 },
  { origen: "APÓSTOLES", destino: "LOMA HERMOSA", kmReal: 926, kmConv: 925 },
  { origen: "CLORINDA", destino: "APÓSTOLES", kmReal: 651, kmConv: 650 },
  { origen: "MAR DEL PLATA", destino: "SAN ANDRES DE GILES", kmReal: 486, kmConv: 485 },
  { origen: "GENERAL ROCA", destino: "RIO CUARTO", kmReal: 885, kmConv: 885 },
  { origen: "SAN LORENZO", destino: "IBARLUCEA", kmReal: 20, kmConv: 20 },
  { origen: "ALVEAR", destino: "ARROYO SECO", kmReal: 21, kmConv: 20 },
  { origen: "IBARLUCEA", destino: "ALVEAR", kmReal: 33, kmConv: 35 },
  { origen: "COLONIA CAROYA", destino: "SAN LORENZO", kmReal: 470, kmConv: 470 },
  { origen: "LONGCHAMPS", destino: "CARLOS SPEGAZZINI", kmReal: 33, kmConv: 35 },
  { origen: "MENDOZA", destino: "DOCK SUD", kmReal: 1054, kmConv: 1055 },
  { origen: "VILLA SOLDATI", destino: "MENDOZA", kmReal: 1041, kmConv: 1040 },
  { origen: "FREYRE", destino: "CLORINDA", kmReal: 932, kmConv: 930 },
  { origen: "MORENO", destino: "SANTA FE", kmReal: 472, kmConv: 470 },
  { origen: "OBERA", destino: "ARISTOBULO DEL VALLE", kmReal: 58, kmConv: 60 },
  { origen: "SAN ANDRES DE GILES", destino: "ESCOBAR", kmReal: 91, kmConv: 90 },
  { origen: "CARMEN DE ARECO", destino: "SAN ANDRES DE GILES", kmReal: 42, kmConv: 40 },
  { origen: "EZEIZA", destino: "RIO CUARTO", kmReal: 635, kmConv: 635 },
  { origen: "MORENO", destino: "ESTEBAN ECHEVERRIA", kmReal: 59, kmConv: 60 },
  { origen: "ARROYO SECO", destino: "TAPIALES", kmReal: 277, kmConv: 275 },
  { origen: "ROSARIO", destino: "ARROYO SECO", kmReal: 34, kmConv: 35 },
  { origen: "GARIN", destino: "BARADERO", kmReal: 110, kmConv: 110 },
  { origen: "LAMARQUE", destino: "CORDOBA", kmReal: 1046, kmConv: 1045 },
  { origen: "CHICHINALES", destino: "LAMARQUE", kmReal: 140, kmConv: 140 },
  { origen: "GENERAL ROCA", destino: "CHICHINALES", kmReal: 59, kmConv: 60 },
  { origen: "NEUQUEN", destino: "GENERAL ROCA", kmReal: 45, kmConv: 45 },
  { origen: "SANTO TOME", destino: "ESCOBAR", kmReal: 409, kmConv: 410 },
  { origen: "SAN JOSE", destino: "SALTO", kmReal: 573, kmConv: 575 },
  { origen: "BURZACO", destino: "SAN GUILLERMO", kmReal: 711, kmConv: 710 },
  { origen: "GARUPA", destino: "SANTA ANA", kmReal: 36, kmConv: 35 },
  { origen: "VILLA MERCEDES", destino: "JOSE LEON SUAREZ", kmReal: 686, kmConv: 685 },
  { origen: "ARROYITO", destino: "MUNRO", kmReal: 634, kmConv: 635 },
  { origen: "FREYRE", destino: "GARUPA", kmReal: 942, kmConv: 940 },
  { origen: "MUNRO", destino: "ARROYITO", kmReal: 637, kmConv: 635 },
  { origen: "VILLA SOLDATI", destino: "MUNRO", kmReal: 24, kmConv: 25 },
  { origen: "GONZALEZ CATAN", destino: "EZEIZA", kmReal: 27, kmConv: 25 },
  { origen: "POSADAS", destino: "ELDORADO", kmReal: 209, kmConv: 210 },
  { origen: "ESCOBAR", destino: "GONZALEZ CATAN", kmReal: 73, kmConv: 75 },
  { origen: "MORENO", destino: "QUILMES", kmReal: 60, kmConv: 60 },
  { origen: "VILLA SOLDATI", destino: "SAUCE VIEJO", kmReal: 450, kmConv: 450 },
  { origen: "RAFAELA", destino: "GENERAL ROCA", kmReal: 1335, kmConv: 1335 },
  { origen: "SANTO TOME", destino: "DOCK SUD", kmReal: 465, kmConv: 465 },
  { origen: "CORONDA", destino: "SUSANA", kmReal: 135, kmConv: 135 },
  { origen: "SAN JOSE", destino: "ROSARIO", kmReal: 533, kmConv: 535 },
  { origen: "PABLO NOGUES", destino: "CAMPANA", kmReal: 49, kmConv: 50 },
  { origen: "BERAZATEGUI", destino: "SARANDI", kmReal: 21, kmConv: 20 },
  { origen: "LA PLATA", destino: "MATADEROS", kmReal: 70, kmConv: 70 },
  { origen: "SUSANA", destino: "LA PLATA", kmReal: 585, kmConv: 585 },
  { origen: "ROSARIO", destino: "SUSANA", kmReal: 232, kmConv: 230 },
  { origen: "EZEIZA", destino: "RIO TERCERO", kmReal: 713, kmConv: 715 },
  { origen: "MONTE GRANDE", destino: "MORON", kmReal: 30, kmConv: 30 },
  { origen: "SUSANA", destino: "SAN LUIS", kmReal: 589, kmConv: 590 },
  { origen: "APÓSTOLES", destino: "CORDOBA", kmReal: 1082, kmConv: 1080 },
  { origen: "RESISTENCIA", destino: "APÓSTOLES", kmReal: 368, kmConv: 370 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "VILLA MARIA", kmReal: 524, kmConv: 525 },
  { origen: "CORONDA", destino: "FRANCK", kmReal: 63, kmConv: 65 },
  { origen: "SUSANA", destino: "MENDOZA", kmReal: 843, kmConv: 845 },
  { origen: "VICENTE LOPEZ", destino: "FATIMA", kmReal: 49, kmConv: 50 },
  { origen: "PABLO NOGUES", destino: "RAFAELA", kmReal: 508, kmConv: 510 },
  { origen: "TAPIALES", destino: "PABLO NOGUES", kmReal: 44, kmConv: 45 },
  { origen: "CHASCOMUS", destino: "RESISTENCIA", kmReal: 1062, kmConv: 1060 },
  { origen: "LONGCHAMPS", destino: "CHASCOMUS", kmReal: 106, kmConv: 105 },
  { origen: "SAN FERNANDO", destino: "CORDOBA", kmReal: 680, kmConv: 680 },
  { origen: "SAN MARTIN", destino: "SAN FERNANDO", kmReal: 24, kmConv: 25 },
  { origen: "ITUZAINGO", destino: "SAN MARTIN", kmReal: 24, kmConv: 25 },
  { origen: "SAN LUIS", destino: "VILLA MARIA", kmReal: 353, kmConv: 355 },
  { origen: "9 DE ABRIL", destino: "CATRILO", kmReal: 530, kmConv: 530 },
  { origen: "CORONDA", destino: "SAN JORGE", kmReal: 187, kmConv: 185 },
  { origen: "CORDOBA", destino: "CORONDA", kmReal: 394, kmConv: 395 },
  { origen: "RAMALLO", destino: "DOCK SUD", kmReal: 235, kmConv: 235 },
  { origen: "DOCK SUD", destino: "RAMALLO", kmReal: 235, kmConv: 235 },
  { origen: "JUAREZ CELMAN", destino: "TIO PUJIO", kmReal: 148, kmConv: 150 },
  { origen: "ESCOBAR", destino: "RECREO", kmReal: 431, kmConv: 430 },
  { origen: "MONTE GRANDE", destino: "ESCOBAR", kmReal: 82, kmConv: 80 },
  { origen: "RIO CUARTO", destino: "JUAREZ CELMAN", kmReal: 242, kmConv: 240 },
  { origen: "MORENO", destino: "EL PALOMAR", kmReal: 19, kmConv: 20 },
  { origen: "GOBERNADOR CRESPO", destino: "RECREO", kmReal: 136, kmConv: 136 },
  { origen: "RAFAELA", destino: "GOBERNADOR CRESPO", kmReal: 199, kmConv: 200 },
  { origen: "MAR DEL PLATA", destino: "PILAR", kmReal: 476, kmConv: 475 },
  { origen: "RETIRO", destino: "VILLA MERCEDES", kmReal: 708, kmConv: 710 },
  { origen: "VICTORIA", destino: "RIO CUARTO", kmReal: 589, kmConv: 589 },
  { origen: "BARADERO", destino: "VICTORIA", kmReal: 131, kmConv: 130 },
  { origen: "BERAZATEGUI", destino: "VALENTIN ALSINA", kmReal: 30, kmConv: 30 },
  { origen: "ITUZAINGO", destino: "VICENTE LOPEZ", kmReal: 30, kmConv: 30 },
  { origen: "ARROYO SECO", destino: "BARADERO", kmReal: 132, kmConv: 130 },
  { origen: "VILLA MERCEDES", destino: "ARROYO SECO", kmReal: 558, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "BERAZATEGUI", kmReal: 590, kmConv: 590 },
  { origen: "EZEIZA", destino: "CAMPANA", kmReal: 106, kmConv: 105 },
  { origen: "BARRACAS", destino: "GALVEZ", kmReal: 433, kmConv: 435 },
  { origen: "TUCUMAN", destino: "COLONIA CAROYA", kmReal: 520, kmConv: 520 },
  { origen: "SAN ANTONIO DE ARECO", destino: "ZARATE", kmReal: 55, kmConv: 55 },
  { origen: "GENERAL PAZ", destino: "SAN ANTONIO DE ARECO", kmReal: 627, kmConv: 625 },
  { origen: "CORDOBA", destino: "GENERAL PAZ", kmReal: 48, kmConv: 50 },
  { origen: "ROSARIO", destino: "SANTA FE", kmReal: 173, kmConv: 175 },
  { origen: "VILLA SOLDATI", destino: "ESCOBAR", kmReal: 58, kmConv: 60 },
  { origen: "PILAR", destino: "CAPITAN SARMIENTO", kmReal: 94, kmConv: 95 },
  { origen: "VILLA MERCEDES", destino: "AVELLANEDA", kmReal: 703, kmConv: 705 },
  { origen: "SAN JERONIMO", destino: "SUSANA", kmReal: 199, kmConv: 200 },
  { origen: "CORDOBA", destino: "TRISTÁN SUAREZ", kmReal: 728, kmConv: 730 },
  { origen: "GRAND BOURG", destino: "PILAR", kmReal: 25, kmConv: 25 },
  { origen: "PILAR", destino: "GRAND BOURG", kmReal: 25, kmConv: 25 },
  { origen: "SAN LORENZO", destino: "TUCUMAN", kmReal: 892, kmConv: 890 },
  { origen: "ROSARIO", destino: "SAN LORENZO", kmReal: 30, kmConv: 30 },
  { origen: "ROSARIO", destino: "SALTO", kmReal: 165, kmConv: 165 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "VILLA NUEVA", kmReal: 525, kmConv: 525 },
  { origen: "NOGOYÁ", destino: "FRANCK", kmReal: 168, kmConv: 170 },
  { origen: "GARIN", destino: "NOGOYÁ", kmReal: 335, kmConv: 335 },
  { origen: "DESVIO ARIJON", destino: "CAMPANA", kmReal: 342, kmConv: 340 },
  { origen: "CAMPANA", destino: "DESVIO ARIJON", kmReal: 342, kmConv: 340 },
  { origen: "LOMA HERMOSA", destino: "VICENTE LOPEZ", kmReal: 20, kmConv: 20 },
  { origen: "GUALEGUAY", destino: "ROSARIO", kmReal: 179, kmConv: 180 },
  { origen: "SAN JOSE", destino: "GUALEGUAY", kmReal: 354, kmConv: 355 },
  { origen: "SAN JOSE", destino: "CAPITAN SARMIENTO", kmReal: 501, kmConv: 500 },
  { origen: "LAVALLOL", destino: "VILLA SOLDATI", kmReal: 20, kmConv: 20 },
  { origen: "CORDOBA", destino: "LAVALLOL", kmReal: 716, kmConv: 715 },
  { origen: "ARROYITO", destino: "SAN JERONIMO", kmReal: 325, kmConv: 325 },
  { origen: "MORTEROS", destino: "RAMONA", kmReal: 60, kmConv: 60 },
  { origen: "LOS CHARRUAS", destino: "CHAJARÍ", kmReal: 89, kmConv: 90 },
  { origen: "BARRACAS", destino: "LOS CHARRUAS", kmReal: 454, kmConv: 455 },
  { origen: "BERNARDO DE IRIGOYEN", destino: "SAN JORGE", kmReal: 100, kmConv: 100 },
  { origen: "VILLA MERCEDES", destino: "LA PLATA", kmReal: 754, kmConv: 755 },
  { origen: "SALTO", destino: "SANTA FE", kmReal: 335, kmConv: 335 },
  { origen: "PILAR", destino: "SALTO", kmReal: 152, kmConv: 150 },
  { origen: "LA PLATA", destino: "MONTE GRANDE", kmReal: 92, kmConv: 90 },
  { origen: "PUERTO PIRAY", destino: "MORENO", kmReal: 1174, kmConv: 1175 },
  { origen: "LONGCHAMPS", destino: "EZEIZA", kmReal: 28, kmConv: 30 },
  { origen: "CAMPANA", destino: "EZEIZA", kmReal: 105, kmConv: 105 },
  { origen: "LA REJA", destino: "VIRREY DEL PINO", kmReal: 33, kmConv: 35 },
  { origen: "VILLA MARIA", destino: "LA REJA", kmReal: 644, kmConv: 645 },
  { origen: "ROSARIO", destino: "BERNARDO DE IRIGOYEN", kmReal: 114, kmConv: 115 },
  { origen: "SALTO", destino: "ROSARIO", kmReal: 165, kmConv: 165 },
  { origen: "TAPIALES", destino: "SALTO", kmReal: 193, kmConv: 195 },
  { origen: "MARCOS PAZ", destino: "LUJAN", kmReal: 57, kmConv: 55 },
  { origen: "GENERAL ROCA", destino: "NEUQUEN", kmReal: 45, kmConv: 45 },
  { origen: "SAN FRANCISCO", destino: "GENERAL ROCA", kmReal: 1249, kmConv: 1250 },
  { origen: "SAN JUSTO", destino: "CAPITAN SARMIENTO", kmReal: 151, kmConv: 150 },
  { origen: "VILLA MARIA", destino: "NEUQUEN", kmReal: 1040, kmConv: 1040 },
  { origen: "RAFAELA", destino: "VILLA MARIA", kmReal: 250, kmConv: 250 },
  { origen: "CAMPANA", destino: "MARCOS PAZ", kmReal: 95, kmConv: 95 },
  { origen: "SAN MIGUEL", destino: "CORDOBA", kmReal: 674, kmConv: 675 },
  { origen: "MATADEROS", destino: "SAN MIGUEL", kmReal: 35, kmConv: 35 },
  { origen: "LA PLATA", destino: "ZONA PORTUARIA", kmReal: 60, kmConv: 60 },
  { origen: "SAN PEDRO", destino: "RIO CUARTO", kmReal: 493, kmConv: 495 },
  { origen: "SAN JOSE", destino: "SAN PEDRO", kmReal: 503, kmConv: 505 },
  { origen: "GUALEGUAY", destino: "PILAR", kmReal: 194, kmConv: 195 },
  { origen: "MONTEVIDEO", destino: "GUALEGUAY", kmReal: 438, kmConv: 440 },
  { origen: "SAN VICENTE", destino: "SANTA ANA", kmReal: 143, kmConv: 145 },
  { origen: "SAN SALVADOR", destino: "SAUCE VIEJO", kmReal: 258, kmConv: 260 },
  { origen: "LIBERTAD", destino: "ALVEAR", kmReal: 577, kmConv: 575 },
  { origen: "VILLA MARIA", destino: "LIBERTAD", kmReal: 797, kmConv: 795 },
  { origen: "DON TORCUATO", destino: "LOMA HERMOSA", kmReal: 16, kmConv: 15 },
  { origen: "GENERAL PACHECO", destino: "ESCOBAR", kmReal: 21, kmConv: 20 },
  { origen: "MONTE GRANDE", destino: "SAN JUSTO", kmReal: 26, kmConv: 25 },
  { origen: "SAN MARTIN", destino: "RIO CUARTO", kmReal: 435, kmConv: 435 },
  { origen: "MONTE GRANDE", destino: "FLORENCIO VARELA", kmReal: 21, kmConv: 20 },
  { origen: "VILLA MARTELLI", destino: "MONTE GRANDE", kmReal: null, kmConv: 40 },
  { origen: "VILLA MARIA", destino: "SAN JOSE", kmReal: 766, kmConv: 765 },
  { origen: "SAN SALVADOR", destino: "ESTEBAN ECHEVERRIA", kmReal: 426, kmConv: 425 },
  { origen: "FREYRE", destino: "SAN VICENTE", kmReal: 1086, kmConv: 1085 },
  { origen: "EZEIZA", destino: "RETIRO", kmReal: 41, kmConv: 40 },
  { origen: "LA PLATA", destino: "RETIRO", kmReal: 58, kmConv: 60 },
  { origen: "9 DE ABRIL", destino: "MATADEROS", kmReal: 16, kmConv: 15 },
  { origen: "GARIN", destino: "CAMPANA", kmReal: 39, kmConv: 40 },
  { origen: "RIO GALLEGOS", destino: "VILLA MERCEDES", kmReal: 2420, kmConv: 2420 },
  { origen: "EZEIZA", destino: "VALENTIN ALSINA", kmReal: 34, kmConv: 35 },
  { origen: "9 DE ABRIL", destino: "EZEIZA", kmReal: 23, kmConv: 25 },
  { origen: "LOS CHARRUAS", destino: "ZONA PORTUARIA", kmReal: 447, kmConv: 445 },
  { origen: "ZONA PORTUARIA", destino: "LOS CHARRUAS", kmReal: 447, kmConv: 445 },
  { origen: "SANTO TOME", destino: "TORTUGUITAS", kmReal: 428, kmConv: 428 },
  { origen: "BAHIA BLANCA", destino: "HURLINGHAM", kmReal: 640, kmConv: 640 },
  { origen: "BAHIA BLANCA", destino: "GARIN", kmReal: 667, kmConv: 670 },
  { origen: "VIEDMA", destino: "BAHIA BLANCA", kmReal: 278, kmConv: 280 },
  { origen: "GENERAL PACHECO", destino: "VIEDMA", kmReal: 937, kmConv: 935 },
  { origen: "BALNEARIA", destino: "GALVEZ", kmReal: 254, kmConv: 255 },
  { origen: "LA FRANCIA", destino: "BALNEARIA", kmReal: 69, kmConv: 70 },
  { origen: "CAPITAN SARMIENTO", destino: "RIO CUARTO", kmReal: 465, kmConv: 465 },
  { origen: "MONTEVIDEO", destino: "CAPITAN SARMIENTO", kmReal: 582, kmConv: 580 },
  { origen: "LOS CARDALES", destino: "VILLA SOLDATI", kmReal: 88, kmConv: 90 },
  { origen: "SAN FRANCISCO", destino: "LOS CARDALES", kmReal: 501, kmConv: 500 },
  { origen: "CAMPO DURAN", destino: "SAN FRANCISCO", kmReal: 1272, kmConv: 1270 },
  { origen: "ITUZAINGO", destino: "EZEIZA", kmReal: 49, kmConv: 50 },
  { origen: "SAN JOSE", destino: "9 DE ABRIL", kmReal: 500, kmConv: 500 },
  { origen: "DOCK SUD", destino: "LA PLATA", kmReal: 50, kmConv: 50 },
  { origen: "MALAGUE&#209;O", destino: "SAN FRANCISCO", kmReal: 248, kmConv: 250 },
  { origen: "MONTE GRANDE", destino: "LUJAN", kmReal: 90, kmConv: 90 },
  { origen: "LA BOCA", destino: "VILLA SOLDATI", kmReal: 15, kmConv: 15 },
  { origen: "ZONA PORTUARIA", destino: "LA BOCA", kmReal: 7, kmConv: 5 },
  { origen: "TIGRE", destino: "CAMPANA", kmReal: 67, kmConv: 65 },
  { origen: "EZPELETA", destino: "VICENTE LOPEZ", kmReal: 40, kmConv: 40 },
  { origen: "SAN JORGE", destino: "GARIN", kmReal: 452, kmConv: 450 },
  { origen: "BARRACAS", destino: "ALEJANDRO ROCA", kmReal: 556, kmConv: 555 },
  { origen: "EL TALAR", destino: "9 DE ABRIL", kmReal: 47, kmConv: 45 },
  { origen: "LONGCHAMPS", destino: "LANUS", kmReal: 18, kmConv: 20 },
  { origen: "SAN SALVADOR", destino: "RIO GALLEGOS", kmReal: 2892, kmConv: 2892 },
  { origen: "VILLA SOLDATI", destino: "VIEDMA", kmReal: 905, kmConv: 905 },
  { origen: "PARQUE PATRICIOS", destino: "ZONA PORTUARIA", kmReal: 10, kmConv: 10 },
  { origen: "SANTO TOME", destino: "LOMAS DE ZAMORA", kmReal: 471, kmConv: 470 },
  { origen: "FORMOSA", destino: "PUERTO PIRAY", kmReal: 694, kmConv: 695 },
  { origen: "SAN ANDRES DE GILES", destino: "RECREO", kmReal: 409, kmConv: 410 },
  { origen: "ZONA PORTUARIA", destino: "LA PLATA", kmReal: 60, kmConv: 60 },
  { origen: "LA PLATA", destino: "VILLA MARIA", kmReal: 610, kmConv: 610 },
  { origen: "ZARATE", destino: "LA PLATA", kmReal: 148, kmConv: 150 },
  { origen: "POSADAS", destino: "PUERTO RICO", kmReal: 140, kmConv: 140 },
  { origen: "CONCORDIA", destino: "MALVINAS ARGENTINAS", kmReal: 397, kmConv: 395 },
  { origen: "EZEIZA", destino: "LA TABLADA", kmReal: 23, kmConv: 25 },
  { origen: "CONCORDIA", destino: "TORTUGUITAS", kmReal: 401, kmConv: 400 },
  { origen: "CARLOS SPEGAZZINI", destino: "EZEIZA", kmReal: 10, kmConv: 10 },
  { origen: "LONGCHAMPS", destino: "9 DE ABRIL", kmReal: 16, kmConv: 15 },
  { origen: "CAMPO DURAN", destino: "CAMPANA", kmReal: 1704, kmConv: 1705 },
  { origen: "SALVADOR MAZZA", destino: "CAMPO DURAN", kmReal: 21, kmConv: 20 },
  { origen: "ORAN", destino: "SALVADOR MAZZA", kmReal: 185, kmConv: 185 },
  { origen: "LOMAS DE ZAMORA", destino: "TAPIALES", kmReal: 15, kmConv: 15 },
  { origen: "SUSANA", destino: "FORMOSA", kmReal: 770, kmConv: 770 },
  { origen: "MAR DEL PLATA", destino: "EZEIZA", kmReal: 411, kmConv: 410 },
  { origen: "VILLA MADERO", destino: "PILAR", kmReal: 62, kmConv: 60 },
  { origen: "SANTA ROSA", destino: "ZARATE", kmReal: 607, kmConv: 605 },
  { origen: "CARLOS SPEGAZZINI", destino: "CAMPANA", kmReal: 120, kmConv: 120 },
  { origen: "CAMPANA", destino: "MONTE GRANDE", kmReal: 106, kmConv: 105 },
  { origen: "LA MATANZA", destino: "TAPIALES", kmReal: 11, kmConv: 10 },
  { origen: "SAN JUSTO", destino: "VICENTE LOPEZ", kmReal: 23, kmConv: 25 },
  { origen: "SALTA", destino: "LA COCHA", kmReal: 434, kmConv: 435 },
  { origen: "SARANDI", destino: "CORDOBA", kmReal: 707, kmConv: 705 },
  { origen: "NEUQUEN", destino: "VILLA MERCEDES", kmReal: 783, kmConv: 785 },
  { origen: "BERAZATEGUI", destino: "ARROYITO", kmReal: 681, kmConv: 680 },
  { origen: "EZEIZA", destino: "BERAZATEGUI", kmReal: 62, kmConv: 60 },
  { origen: "VILLA URQUIZA", destino: "9 DE ABRIL", kmReal: 27, kmConv: 25 },
  { origen: "PABLO NOGUES", destino: "ISIDRO CASANOVA", kmReal: 45, kmConv: 45 },
  { origen: "ESCOBAR", destino: "ZONA PORTUARIA", kmReal: 52, kmConv: 50 },
  { origen: "LOS POLVORINES", destino: "PILAR", kmReal: 28, kmConv: 30 },
  { origen: "CORRAL DE BUSTOS", destino: "ROSARIO", kmReal: 189, kmConv: 190 },
  { origen: "ESCOBAR", destino: "CAPITAN SARMIENTO", kmReal: 118, kmConv: 120 },
  { origen: "TAPIALES", destino: "ZARATE", kmReal: 98, kmConv: 100 },
  { origen: "SAN FRANCISCO", destino: "ORAN", kmReal: 1152, kmConv: 1150 },
  { origen: "AVELLANEDA", destino: "CAMPANA", kmReal: 87, kmConv: 85 },
  { origen: "PABLO NOGUES", destino: "ESCOBAR", kmReal: 22, kmConv: 20 },
  { origen: "RAFAELA", destino: "PABLO NOGUES", kmReal: 508, kmConv: 510 },
  { origen: "LA COCHA", destino: "CAMPANA", kmReal: 1092, kmConv: 1090 },
  { origen: "LANUS", destino: "CORRAL DE BUSTOS", kmReal: 445, kmConv: 445 },
  { origen: "LA MATANZA", destino: "BARADERO", kmReal: 153, kmConv: 155 },
  { origen: "WILDE", destino: "TORTUGUITAS", kmReal: 62, kmConv: 60 },
  { origen: "MONTE GRANDE", destino: "RETIRO", kmReal: 43, kmConv: 45 },
  { origen: "DOCK SUD", destino: "INGENIERO LUIGGI", kmReal: 644, kmConv: 645 },
  { origen: "LOMAS DE ZAMORA", destino: "EZEIZA", kmReal: 16, kmConv: 15 },
  { origen: "VILLA MADERO", destino: "9 DE ABRIL", kmReal: 10, kmConv: 10 },
  { origen: "SUSANA", destino: "TUCUMAN", kmReal: 681, kmConv: 680 },
  { origen: "COMODORO RIVADAVIA", destino: "VILLA MERCEDES", kmReal: 1613, kmConv: 1615 },
  { origen: "DEVOTO", destino: "SAN FRANCISCO", kmReal: 22, kmConv: 20 },
  { origen: "CAMPANA", destino: "LOMAS DEL MIRADOR", kmReal: 80, kmConv: 80 },
  { origen: "SOLDINI", destino: "RAFAELA", kmReal: 251, kmConv: 250 },
  { origen: "COL SANTA ROSA", destino: "CORDOBA", kmReal: 937, kmConv: 935 },
  { origen: "VICENTE LOPEZ", destino: "ESCOBAR", kmReal: 43, kmConv: 45 },
  { origen: "ZARATE", destino: "ARROYITO", kmReal: 567, kmConv: 565 },
  { origen: "MAR DEL PLATA", destino: "MONTE GRANDE", kmReal: 415, kmConv: 415 },
  { origen: "MONTE GRANDE", destino: "MORENO", kmReal: 56, kmConv: 55 },
  { origen: "GOBERNADOR VIRASORO", destino: "COL SANTA ROSA", kmReal: 279, kmConv: 280 },
  { origen: "ELDORADO", destino: "ZONA PORTUARIA", kmReal: 1177, kmConv: 1175 },
  { origen: "PUERTO ESPERANZA", destino: "ELDORADO", kmReal: 47, kmConv: 45 },
  { origen: "GOBERNADOR VIRASORO", destino: "ELDORADO", kmReal: 273, kmConv: 275 },
  { origen: "TAPIALES", destino: "ROSARIO", kmReal: 306, kmConv: 305 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "RIO CUARTO", kmReal: 656, kmConv: 655 },
  { origen: "ZARATE", destino: "APÓSTOLES", kmReal: 856, kmConv: 855 },
  { origen: "SARANDI", destino: "ZARATE", kmReal: 100, kmConv: 100 },
  { origen: "VILLA CRESPO", destino: "VILLA SOLDATI", kmReal: 8, kmConv: 10 },
  { origen: "APÓSTOLES", destino: "DOCK SUD", kmReal: 948, kmConv: 950 },
  { origen: "TUCUMAN", destino: "SANTIAGO DEL ESTERO", kmReal: 162, kmConv: 160 },
  { origen: "SARANDI", destino: "APÓSTOLES", kmReal: 949, kmConv: 949 },
  { origen: "TORTUGUITAS", destino: "BECCAR", kmReal: 25, kmConv: 25 },
  { origen: "SAN JOSE", destino: "CONCEPCION DEL URUGUAY", kmReal: 338, kmConv: 335 },
  { origen: "PUERTO MADRYN", destino: "TRELEW", kmReal: 65, kmConv: 65 },
  { origen: "ZONA PORTUARIA", destino: "PUERTO MADRYN", kmReal: 1303, kmConv: 1305 },
  { origen: "VICENTE LOPEZ", destino: "ZONA PORTUARIA", kmReal: 12, kmConv: 10 },
  { origen: "SAN JOSE", destino: "LANUS", kmReal: 530, kmConv: 530 },
  { origen: "PUERTO IGUAZU", destino: "PUERTO ESPERANZA", kmReal: 57, kmConv: 58 },
  { origen: "SAN JUSTO", destino: "GARIN", kmReal: 48, kmConv: 50 },
  { origen: "TORTUGUITAS", destino: "RETIRO", kmReal: 43, kmConv: 45 },
  { origen: "CAMPANA", destino: "TIO PUJIO", kmReal: 495, kmConv: 495 },
  { origen: "LA PATERNAL", destino: "VICENTE LOPEZ", kmReal: 12, kmConv: 10 },
  { origen: "TIO PUJIO", destino: "LA PATERNAL", kmReal: 563, kmConv: 565 },
  { origen: "PILAR", destino: "RIO CUARTO", kmReal: 553, kmConv: 555 },
  { origen: "GARIN", destino: "PILAR", kmReal: 23, kmConv: 25 },
  { origen: "EZEIZA", destino: "MATADEROS", kmReal: 27, kmConv: 25 },
  { origen: "SAN MARTIN", destino: "VILLA MARIA", kmReal: 567, kmConv: 565 },
  { origen: "CANNING", destino: "TORTUGUITAS", kmReal: 72, kmConv: 70 },
  { origen: "RIO CUARTO", destino: "PABLO NOGUES", kmReal: 575, kmConv: 575 },
  { origen: "TIO PUJIO", destino: "RIO CUARTO", kmReal: 149, kmConv: 150 },
  { origen: "CAMPANA", destino: "RIO CUARTO", kmReal: 553, kmConv: 555 },
  { origen: "MONTE GRANDE", destino: "BARADERO", kmReal: 178, kmConv: 180 },
  { origen: "TIO PUJIO", destino: "SAN JOSE", kmReal: 785, kmConv: 785 },
  { origen: "PUERTO RICO", destino: "PUERTO IGUAZU", kmReal: 170, kmConv: 170 },
  { origen: "LAFERRERE", destino: "9 DE ABRIL", kmReal: 15, kmConv: 15 },
  { origen: "EZEIZA", destino: "VILLA MARIA", kmReal: 578, kmConv: 578 },
  { origen: "ZARATE", destino: "EZEIZA", kmReal: 115, kmConv: 115 },
  { origen: "LA PLATA", destino: "BURZACO", kmReal: 55, kmConv: 55 },
  { origen: "9 DE ABRIL", destino: "BURZACO", kmReal: 14, kmConv: 15 },
  { origen: "JUNIN", destino: "ROSARIO", kmReal: 208, kmConv: 210 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "MONTE GRANDE", kmReal: 7, kmConv: 5 },
  { origen: "VILLA SOLDATI", destino: "LAFERRERE", kmReal: 20, kmConv: 20 },
  { origen: "VILLA MADERO", destino: "LANUS", kmReal: 13, kmConv: 15 },
  { origen: "SUSANA", destino: "VILLA MADERO", kmReal: 532, kmConv: 530 },
  { origen: "SOLDINI", destino: "SUSANA", kmReal: 238, kmConv: 240 },
  { origen: "SAN FRANCISCO", destino: "HAEDO", kmReal: 565, kmConv: 565 },
  { origen: "RIO CUARTO", destino: "SAN AGUSTIN", kmReal: 147, kmConv: 145 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
