/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 9 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "! APOSTOLES", destino: "URUGUAYANA", kmReal: 296, kmConv: 296 },
  { origen: "! ARMSTRONG", destino: "ROSARIO", kmReal: 95, kmConv: 95 },
  { origen: "! SAN FRANCISCO", destino: "ARMSTRONG", kmReal: 200, kmConv: 200 },
  { origen: "MERCEDES", destino: "ROSARIO", kmReal: 250, kmConv: 250 },
  { origen: "! VIRASORO", destino: "URUGUAYANA", kmReal: 265, kmConv: 265 },
  { origen: "RAFAELA", destino: "GOBERNADOR VIRASORO", kmReal: 800, kmConv: 800 },
  { origen: "! EL DORADO", destino: "URUGUAYANA", kmReal: 536, kmConv: 536 },
  { origen: "BUENOS AIRES", destino: "TUCUMAN", kmReal: 1235, kmConv: 1235 },
  { origen: "MERCEDES", destino: "GENERAL RODRIGUEZ", kmReal: 50, kmConv: 50 },
  { origen: "! MERCEDES", destino: "BUENOS AIRES", kmReal: 110, kmConv: 110 },
  { origen: "! SAN PEDRO", destino: "ROSARIO", kmReal: 145, kmConv: 145 },
  { origen: "! ELORTONDO", destino: "URUGUAYANA", kmReal: 712, kmConv: 712 },
  { origen: "! SAN FRANCISCO", destino: "ELORTONDO", kmReal: 325, kmConv: 325 },
  { origen: "! BARADERO", destino: "BUENOS AIRES", kmReal: 150, kmConv: 150 },
  { origen: "! CANDELARIA", destino: "URUGUAYANA", kmReal: 356, kmConv: 356 },
  { origen: "RAFAELA", destino: "CANDELARIA", kmReal: 900, kmConv: 900 },
  { origen: "TUCUMAN", destino: "ROSARIO", kmReal: 960, kmConv: 960 },
  { origen: "! COLONIA CAROYA", destino: "TIO PUJIO", kmReal: 180, kmConv: 180 },
  { origen: "SAN FRANCISCO", destino: "RIO SEGUNDO", kmReal: 210, kmConv: 210 },
  { origen: "RIO SEGUNDO", destino: "CORDOBA", kmReal: 47, kmConv: 47 },
  { origen: "! RAFAELA", destino: "SAN LORENZO", kmReal: 652, kmConv: 652 },
  { origen: "! BARADERO", destino: "RECREO (STA. FE)", kmReal: 345, kmConv: 345 },
  { origen: "! LULES", destino: "BUENOS AIRES", kmReal: 1230, kmConv: 1230 },
  { origen: "! TUCUMÁN", destino: "LULES", kmReal: 20, kmConv: 20 },
  { origen: "CONCORDIA", destino: "TUCUMAN", kmReal: 1070, kmConv: 1070 },
  { origen: "! MERCEDES", destino: "URUGUAYANA", kmReal: 130, kmConv: 130 },
  { origen: "AVELLANEDA", destino: "URUGUAIANA", kmReal: 600, kmConv: 600 },
  { origen: "! SAN SALVADOR DE JUJUY", destino: "BELLA VISTA(TUCUMÁN)", kmReal: 370, kmConv: 370 },
  { origen: "! TUCUMÁN", destino: "BELLA VISTA(TUCUMÁN)", kmReal: 30, kmConv: 30 },
  { origen: "! BELLA VISTA(TUCUMÁN)", destino: "BUENOS AIRES", kmReal: 1220, kmConv: 1220 },
  { origen: "! VILLA MERCEDES", destino: "SAN FRANCISCO", kmReal: 430, kmConv: 430 },
  { origen: "! VILLAGUAY", destino: "SAN FRANCISCO", kmReal: 320, kmConv: 320 },
  { origen: "BARADERO", destino: "ROSARIO", kmReal: 161, kmConv: 160 },
  { origen: "! BRINKMANN", destino: "BUENOS AIRES", kmReal: 630, kmConv: 630 },
  { origen: "SAN FRANCISCO", destino: "BRINKMANN", kmReal: 70, kmConv: 70 },
  { origen: "! PUERTO IGUAZÚ", destino: "URUGUAYANA", kmReal: 635, kmConv: 635 },
  { origen: "! VIRASORO", destino: "RAFAELA", kmReal: 804, kmConv: 800 },
  { origen: "! SAN JUAN", destino: "SAN SALVADOR DE JUJUY", kmReal: 1165, kmConv: 1165 },
  { origen: "! LAS HERAS", destino: "SAN JUAN", kmReal: 165, kmConv: 165 },
  { origen: "SUNCHALES", destino: "VILLAGUAY", kmReal: 333, kmConv: 335 },
  { origen: "! UNQUILLO", destino: "VILLA MERCEDES", kmReal: 420, kmConv: 420 },
  { origen: "CORDOBA", destino: "UNQUILLO", kmReal: 30, kmConv: 30 },
  { origen: "! CHIVILCOY", destino: "PARANÁ", kmReal: 470, kmConv: 470 },
  { origen: "! ORÁN", destino: "TUCUMÁN", kmReal: 500, kmConv: 500 },
  { origen: "! POSADAS", destino: "URUGUAYANA", kmReal: 360, kmConv: 360 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "SAUCE VIEJO", kmReal: 310, kmConv: 310 },
  { origen: "! ITUZAINGO", destino: "RAFAELA", kmReal: 880, kmConv: 880 },
  { origen: "! PUERTO RICO", destino: "URUGUAYANA", kmReal: 470, kmConv: 470 },
  { origen: "AVELLANEDA", destino: "RAFAELA", kmReal: 380, kmConv: 380 },
  { origen: "CORDOBA", destino: "BARADERO", kmReal: 560, kmConv: 560 },
  { origen: "! SUNCHALES", destino: "ORÁN", kmReal: 1155, kmConv: 1155 },
  { origen: "RAFAELA", destino: "PUERTO RICO", kmReal: 1015, kmConv: 1015 },
  { origen: "! OBERÁ", destino: "URUGUAYANA", kmReal: 390, kmConv: 390 },
  { origen: "RAFAELA", destino: "AVELLANEDA", kmReal: 547, kmConv: 545 },
  { origen: "LA PLATA", destino: "CHIVILCOY", kmReal: 220, kmConv: 220 },
  { origen: "! MERCEDES", destino: "SAN SALVADOR", kmReal: 315, kmConv: 315 },
  { origen: "! BELLA VISTA(CORRIENTES)", destino: "MERCEDES", kmReal: 141, kmConv: 141 },
  { origen: "! CORRAL DE BUSTOS", destino: "SAN JORGE", kmReal: 220, kmConv: 220 },
  { origen: "! CAMPANA", destino: "ROSARIO", kmReal: 210, kmConv: 210 },
  { origen: "! ROJAS", destino: "ROSARIO", kmReal: 160, kmConv: 160 },
  { origen: "! RIO GALLEGOS", destino: "SAN FRANCISCO", kmReal: 2720, kmConv: 2720 },
  { origen: "! RIO CUARTO", destino: "CONCEPCION DEL URUGUAY", kmReal: 665, kmConv: 665 },
  { origen: "! APÓSTOLES", destino: "RAFAELA", kmReal: 845, kmConv: 845 },
  { origen: "! BUENOS AIRES", destino: "ROJAS", kmReal: 240, kmConv: 240 },
  { origen: "! RECREO (STA. FE)", destino: "BUENOS AIRES", kmReal: 480, kmConv: 480 },
  { origen: "PORTE&#209;A", destino: "RAFAELA", kmReal: 80, kmConv: 80 },
  { origen: "! RAFAELA", destino: "MERCEDES", kmReal: 585, kmConv: 585 },
  { origen: "! BUENOS AIRES", destino: "COMANDANTE ANDRESITO", kmReal: 1325, kmConv: 1325 },
  { origen: "CHIVILCOY", destino: "SANTA FE", kmReal: 435, kmConv: 435 },
  { origen: "RAFAELA", destino: "APÓSTOLES", kmReal: 845, kmConv: 845 },
  { origen: "! RESISTENCIA", destino: "SAN FRANCISCO", kmReal: 685, kmConv: 685 },
  { origen: "GUALEGUAYCHU", destino: "RAFAELA", kmReal: 656, kmConv: 656 },
  { origen: "SUNCHALES", destino: "RIO GALLEGOS", kmReal: 2830, kmConv: 2830 },
  { origen: "! PERGAMINO", destino: "BUENOS AIRES", kmReal: 230, kmConv: 230 },
  { origen: "! BUENOS AIRES", destino: "PERGAMINO", kmReal: 230, kmConv: 230 },
  { origen: "VILLA MARIA", destino: "ZARATE", kmReal: 470, kmConv: 470 },
  { origen: "! CHARATAS(CHACO)", destino: "RAFAELA", kmReal: 530, kmConv: 530 },
  { origen: "! GALVEZ", destino: "DEVOTO", kmReal: 150, kmConv: 150 },
  { origen: "SUNCHALES", destino: "GALVEZ", kmReal: 150, kmConv: 150 },
  { origen: "! RAFAELA", destino: "CHARATAS(CHACO)", kmReal: 530, kmConv: 530 },
  { origen: "RAFAELA", destino: "GUALEGUAYCHU", kmReal: 450, kmConv: 450 },
  { origen: "CONCORDIA", destino: "RAFAELA", kmReal: 415, kmConv: 415 },
  { origen: "FORMOSA", destino: "URUGUAIANA", kmReal: 560, kmConv: 560 },
  { origen: "! SAN VICENTE", destino: "URUGUAYANA", kmReal: 490, kmConv: 490 },
  { origen: "! CURUZÚ CUATIA", destino: "URUGUAYANA", kmReal: 110, kmConv: 110 },
  { origen: "! SANTO TOME(CORRIENTES)", destino: "URUGUAYANA", kmReal: 200, kmConv: 200 },
  { origen: "! GALVEZ", destino: "SAN FRANCISCO", kmReal: 135, kmConv: 135 },
  { origen: "9 DE JULIO", destino: "JUNIN", kmReal: 105, kmConv: 105 },
  { origen: "! JUNIN", destino: "SAN FRANCISCO", kmReal: 455, kmConv: 455 },
  { origen: "CHACO", destino: "RAFAELA", kmReal: 595, kmConv: 595 },
  { origen: "GALVEZ", destino: "SUNCHALES", kmReal: 150, kmConv: 150 },
  { origen: "! RAFAELA", destino: "CURUZÚ CUATIA", kmReal: 500, kmConv: 500 },
  { origen: "! COMANDANTE ANDRESITO", destino: "BUENOS AIRES", kmReal: 1325, kmConv: 1325 },
  { origen: "! RAFAELA", destino: "SANTO TOME(CORRIENTES)", kmReal: 755, kmConv: 755 },
  { origen: "! LA CRUZ", destino: "URUGUAYANA", kmReal: 110, kmConv: 110 },
  { origen: "! DEVOTO", destino: "TIO PUJIO", kmReal: 185, kmConv: 185 },
  { origen: "! CONCORDIA", destino: "COMANDANTE ANDRESITO", kmReal: 895, kmConv: 895 },
  { origen: "! BUENOS AIRES", destino: "CONCORDIA", kmReal: 430, kmConv: 430 },
  { origen: "! RAFAELA", destino: "CHACO", kmReal: 595, kmConv: 595 },
  { origen: "! RAFAELA", destino: "LA CRUZ", kmReal: 656, kmConv: 656 },
  { origen: "! ETRURIA", destino: "BUENOS AIRES", kmReal: 570, kmConv: 570 },
  { origen: "! BUENOS AIRES", destino: "ETRURIA", kmReal: 570, kmConv: 570 },
  { origen: "GOYA", destino: "RAFAELA", kmReal: 485, kmConv: 485 },
  { origen: "! ARROYITO", destino: "COLONIA CAROYA", kmReal: 170, kmConv: 170 },
  { origen: "! COLONIA CAROYA", destino: "MONTEVIDEO", kmReal: 1060, kmConv: 1060 },
  { origen: "ACHERAL", destino: "TAPSO", kmReal: 160, kmConv: 160 },
  { origen: "TAPSO", destino: "ACHERAL", kmReal: 160, kmConv: 160 },
  { origen: "! SAN JOSÉ DE LAS SALINAS", destino: "SAN JUAN", kmReal: 580, kmConv: 580 },
  { origen: "! BUENOS AIRES", destino: "CHIMBAS", kmReal: 1160, kmConv: 1160 },
  { origen: "! SAENZ PE&#209;A", destino: "RAFAELA", kmReal: 590, kmConv: 590 },
  { origen: "POSADAS", destino: "RAFAELA", kmReal: 905, kmConv: 905 },
  { origen: "ELDORADO", destino: "RAFAELA", kmReal: 1085, kmConv: 1085 },
  { origen: "RAFAELA", destino: "ELDORADO", kmReal: 1085, kmConv: 1085 },
  { origen: "VILLA ANGELA", destino: "RAFAELA", kmReal: 500, kmConv: 500 },
  { origen: "! RAFAELA", destino: "VILLA ANGELA", kmReal: 500, kmConv: 500 },
  { origen: "! BARADERO", destino: "SAN JORGE", kmReal: 355, kmConv: 355 },
  { origen: "! VILLA MERCEDES", destino: "SAN JORGE", kmReal: 465, kmConv: 465 },
  { origen: "ARROYO SECO", destino: "CORDOBA", kmReal: 430, kmConv: 430 },
  { origen: "SAN VICENTE", destino: "RAFAELA", kmReal: 1027, kmConv: 1027 },
  { origen: "OBERA", destino: "RAFAELA", kmReal: 933, kmConv: 935 },
  { origen: "PUERTO IGUAZU", destino: "RAFAELA", kmReal: 1172, kmConv: 1172 },
  { origen: "POSADAS", destino: "SAN FRANCISCO", kmReal: 918, kmConv: 918 },
  { origen: "! BUENOS AIRES", destino: "ARROYO SECO", kmReal: 270, kmConv: 270 },
  { origen: "VILLA MERCEDES", destino: "BARADERO", kmReal: 650, kmConv: 650 },
  { origen: "RAFAELA", destino: "SAN VICENTE", kmReal: 1035, kmConv: 1035 },
  { origen: "RAFAELA", destino: "OBERA", kmReal: 933, kmConv: 935 },
  { origen: "RAFAELA", destino: "PUERTO IGUAZU", kmReal: 1180, kmConv: 1180 },
  { origen: "RAFAELA", destino: "POSADAS", kmReal: 905, kmConv: 905 },
  { origen: "SAN SALVADOR", destino: "CORDOBA", kmReal: 595, kmConv: 595 },
  { origen: "! CORRIENTES", destino: "SAN SALVADOR", kmReal: 550, kmConv: 550 },
  { origen: "ZARATE", destino: "SAN FRANCISCO", kmReal: 477, kmConv: 475 },
  { origen: "! FRAY BENTOS", destino: "CARCARA&#209;A", kmReal: 360, kmConv: 360 },
  { origen: "! BALCARCE", destino: "BUENOS AIRES", kmReal: 415, kmConv: 415 },
  { origen: "! BUENOS AIRES", destino: "BALCARCE", kmReal: 415, kmConv: 415 },
  { origen: "CARCARA&#209;A", destino: "CORDOBA", kmReal: 360, kmConv: 360 },
  { origen: "! BUENOS AIRES", destino: "CARCARA&#209;A", kmReal: 345, kmConv: 345 },
  { origen: "! VILLA MARIA", destino: "FRAY BENTOS", kmReal: 570, kmConv: 570 },
  { origen: "! MONTEVIDEO", destino: "VILLA MARIA", kmReal: 870, kmConv: 870 },
  { origen: "! RECRE (STA. FE)", destino: "SAN JORGE", kmReal: 170, kmConv: 170 },
  { origen: "! RECREO (STA. FE)", destino: "SAN JORGE", kmReal: 170, kmConv: 170 },
  { origen: "! BUENOS AIRES", destino: "RECREO (STA. FE)", kmReal: 480, kmConv: 480 },
  { origen: "! RIO CUARTO", destino: "ROSARIO", kmReal: 390, kmConv: 390 },
  { origen: "CHIVILCOY", destino: "RAFAELA", kmReal: 505, kmConv: 505 },
  { origen: "! FREYRE", destino: "RIO CUARTO", kmReal: 320, kmConv: 320 },
  { origen: "CORDOBA", destino: "GALVEZ", kmReal: 355, kmConv: 355 },
  { origen: "! CALCHAQUI", destino: "URUGUAIANA", kmReal: 671, kmConv: 670 },
  { origen: "SAN FRANCISCO", destino: "CAMPANA", kmReal: 485, kmConv: 485 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN FRANCISCO", kmReal: 540, kmConv: 540 },
  { origen: "! SUSANA", destino: "BUENOS AIRES", kmReal: 528, kmConv: 530 },
  { origen: "! SAN FRANCISCO", destino: "SUSANA", kmReal: null, kmConv: 80 },
  { origen: "CORDOBA", destino: "SUNCHALES", kmReal: 298, kmConv: 300 },
  { origen: "! LUQUE", destino: "URUGUAIANA", kmReal: 745, kmConv: 745 },
  { origen: "! CHIVILCOY", destino: "SAN FRANCISCO", kmReal: 532, kmConv: 535 },
  { origen: "TIO PUJIO", destino: "RAFAELA", kmReal: 325, kmConv: 325 },
  { origen: "! APÓSTOLES", destino: "BUENOS AIRES", kmReal: 953, kmConv: 955 },
  { origen: "! BUENOS AIRES", destino: "APÓSTOLES", kmReal: 953, kmConv: 955 },
  { origen: "! NOGOYA", destino: "TIO PUJIO", kmReal: 385, kmConv: 385 },
  { origen: "ARROYITO", destino: "RAFAELA", kmReal: 180, kmConv: 180 },
  { origen: "! VILLA DEL TOTORAL", destino: "BUENOS AIRES", kmReal: 775, kmConv: 775 },
  { origen: "SANTO TOME", destino: "SUNCHALES", kmReal: 147, kmConv: 150 },
  { origen: "! GENERAL PICO", destino: "BUENOS AIRES", kmReal: 589, kmConv: 590 },
  { origen: "! BUENOS AIRES", destino: "GENERAL PICO", kmReal: 589, kmConv: 590 },
  { origen: "! PASO DE LOS LIBRES", destino: "URUGUAIANA", kmReal: 5, kmConv: 5 },
  { origen: "! SAN JOSE(URUGUAY)", destino: "ROSARIO", kmReal: 520, kmConv: 520 },
  { origen: "! SAN JOSE (URUGUAY)", destino: "TIO PUJIO", kmReal: 785, kmConv: 785 },
  { origen: "! NOGOYA", destino: "URUGUAIANA", kmReal: 461, kmConv: 460 },
  { origen: "CORDOBA", destino: "MORTEROS", kmReal: 298, kmConv: 300 },
  { origen: "RAFAELA", destino: "LEHMANN", kmReal: 19, kmConv: 20 },
  { origen: "! CORRIENTES", destino: "SAN FRANCISCO", kmReal: 710, kmConv: 710 },
  { origen: "RAFAELA", destino: "PARANÁ", kmReal: 150, kmConv: 150 },
  { origen: "9 DE JULIO", destino: "CAMPANA", kmReal: 255, kmConv: 255 },
  { origen: "! BRUSQUE", destino: "URUGUAYANA", kmReal: 1184, kmConv: 1185 },
  { origen: "! JARAGUA DO SUL", destino: "BRUSQUE", kmReal: 120, kmConv: 120 },
  { origen: "! CORRIENTES", destino: "SAN PABLO", kmReal: 1677, kmConv: 1680 },
  { origen: "ROSARIO", destino: "FRANCK", kmReal: 180, kmConv: 180 },
  { origen: "! COLONIA (ZONA FRANCA)", destino: "MONTEVIDEO", kmReal: 180, kmConv: 180 },
  { origen: "! NOGOYA", destino: "MONTEVIDEO", kmReal: 530, kmConv: 530 },
  { origen: "! BUENOS AIRES", destino: "COLONIA (ZONA FRANCA)", kmReal: 485, kmConv: 485 },
  { origen: "ZARATE", destino: "RAFAELA", kmReal: 455, kmConv: 455 },
  { origen: "RAFAELA", destino: "ZARATE", kmReal: 455, kmConv: 455 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "SAN FRANCISCO", kmReal: 440, kmConv: 440 },
  { origen: "! NOGOYÁ", destino: "SAN FRANCISCO", kmReal: 281, kmConv: 280 },
  { origen: "! GOBERNADOR CRESPO", destino: "ROSARIO", kmReal: 321, kmConv: 320 },
  { origen: "! RESISTENCIA", destino: "GOBERNADOR CRESPO", kmReal: 390, kmConv: 390 },
  { origen: "! PERGAMINO", destino: "ROSARIO", kmReal: 113, kmConv: 115 },
  { origen: "PORTE&#209;A", destino: "PERGAMINO", kmReal: 409, kmConv: 410 },
  { origen: "COSQUIN", destino: "CORDOBA", kmReal: 55, kmConv: 55 },
  { origen: "! TIO PUJIO", destino: "SAN JOSE (URUGUAY)", kmReal: 785, kmConv: 785 },
  { origen: "! LA FALDA", destino: "SAN FRANCISCO", kmReal: 274, kmConv: 245 },
  { origen: "ROSARIO", destino: "SUNCHALES", kmReal: 292, kmConv: 295 },
  { origen: "! CHIVILCOY", destino: "LA FALDA", kmReal: 754, kmConv: 760 },
  { origen: "! MERCEDES", destino: "CHIVILCOY", kmReal: 65, kmConv: 70 },
  { origen: "! BUENOSAIRES", destino: "MERCEDES", kmReal: 105, kmConv: 110 },
  { origen: "! CAMPANA", destino: "CARLOS PAZ", kmReal: 658, kmConv: 660 },
  { origen: "NOGOYÁ", destino: "RAFAELA", kmReal: 257, kmConv: 260 },
  { origen: "FREYRE", destino: "SUNCHALES", kmReal: null, kmConv: 80 },
  { origen: "! SAN FRANCISCO", destino: "LEHMANN", kmReal: 107, kmConv: 110 },
  { origen: "! SAN FRANCISCO", destino: "SAN NICOLÁS", kmReal: 355, kmConv: 355 },
  { origen: "FREYRE", destino: "CORDOBA", kmReal: 275, kmConv: 275 },
  { origen: "ZARATE", destino: "CORDOBA", kmReal: 612, kmConv: 615 },
  { origen: "! DESVIÓ ARIJON", destino: "ROSARIO", kmReal: 137, kmConv: 140 },
  { origen: "! CAMPANA", destino: "RIO CEBALLOS", kmReal: 647, kmConv: 650 },
  { origen: "! VILLA MARÍA", destino: "NOGOYÁ", kmReal: 367, kmConv: 370 },
  { origen: "! CÓRDOBA", destino: "CONCEPCIÓN DEL URUGUAY", kmReal: 669, kmConv: 670 },
  { origen: "CONCORDIA", destino: "SAN SALVADOR", kmReal: null, kmConv: 60 },
  { origen: "! CÓRDOBA", destino: "RÍO PRIMERO", kmReal: null, kmConv: 61 },
  { origen: "! TIO PUJIO", destino: "MONTEVIDEO", kmReal: 880, kmConv: 880 },
  { origen: "! BUENOS AIRES", destino: "CORRIENTES", kmReal: 917, kmConv: 920 },
  { origen: "9 DE JULIO", destino: "BUENOS AIRES", kmReal: 280, kmConv: 280 },
  { origen: "! PASCO", destino: "BUENOS AIRES", kmReal: 590, kmConv: 590 },
  { origen: "! BUENOS AIRES", destino: "PASCO", kmReal: 590, kmConv: 590 },
  { origen: "! LEHMANN", destino: "BUENOS AIRES", kmReal: 560, kmConv: 560 },
  { origen: "! BUENOS AIRES", destino: "LEHMANN", kmReal: 560, kmConv: 560 },
  { origen: "! SAENZ PE&#209;A", destino: "URUGUAYANA", kmReal: 552, kmConv: 550 },
  { origen: "! BUENOS AIRES", destino: "BARADERO", kmReal: 150, kmConv: 150 },
  { origen: "BARADERO", destino: "CORDOBA", kmReal: 560, kmConv: 560 },
  { origen: "! ROSARIO", destino: "VILLA MARÍA", kmReal: 260, kmConv: 260 },
  { origen: "RAFAELA", destino: "ROQUE SAENS PE&#209;A", kmReal: 590, kmConv: 590 },
  { origen: "! ITAJAÍ", destino: "JARAGUA DO SUL", kmReal: 100, kmConv: 100 },
  { origen: "! RAMONA", destino: "BUENOS AIRES", kmReal: 590, kmConv: 590 },
  { origen: "SAN FRANCISCO", destino: "RAMONA", kmReal: 60, kmConv: 60 },
  { origen: "! BUENOS AIRES", destino: "ITAJAÍ", kmReal: 1830, kmConv: 1830 },
  { origen: "! CHIVILCOY", destino: "BUENOS AIRES", kmReal: 167, kmConv: 170 },
  { origen: "MORTEROS", destino: "SUNCHALES", kmReal: 75, kmConv: 75 },
  { origen: "! BELLA VISTA (CORRIENTES)", destino: "URUGUAIANA", kmReal: 270, kmConv: 270 },
  { origen: "CORDOBA", destino: "FREYRE", kmReal: 245, kmConv: 245 },
  { origen: "RAFAELA", destino: "BELLA VISTA", kmReal: 565, kmConv: 565 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "SANTO TOME", kmReal: 300, kmConv: 300 },
  { origen: "ZARATE", destino: "SAN JUAN", kmReal: 1095, kmConv: 1095 },
  { origen: "CORRIENTES", destino: "RAFAELA", kmReal: 615, kmConv: 615 },
  { origen: "SANTO TOME", destino: "SAN FRANCISCO", kmReal: 143, kmConv: 145 },
  { origen: "! SANTA FE", destino: "BUENOS AIRES", kmReal: 469, kmConv: 469 },
  { origen: "! SANTO TOME", destino: "SANTA FE", kmReal: 15, kmConv: 15 },
  { origen: "SUNCHALES", destino: "RAFAELA", kmReal: 40, kmConv: 40 },
  { origen: "RESISTENCIA", destino: "RAFAELA", kmReal: 593, kmConv: 593 },
  { origen: "! BUENOS AIRES", destino: "SANTO TOME", kmReal: 455, kmConv: 455 },
  { origen: "A&#209;ELO", destino: "TIO PUJIO", kmReal: 1090, kmConv: 1090 },
  { origen: "! SAUCE VIEJO", destino: "CIUDAD DE BUENOS AIRES", kmReal: 445, kmConv: 445 },
  { origen: "FREYRE", destino: "PORTE&#209;A", kmReal: 18, kmConv: 20 },
  { origen: "! CAMPANA", destino: "LA FALDA", kmReal: 685, kmConv: 685 },
  { origen: "RAFAELA", destino: "SAN JORGE", kmReal: 100, kmConv: 100 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "RAFAELA", kmReal: 395, kmConv: 395 },
  { origen: "! SAN JORGE", destino: "TIO PUJIO", kmReal: 255, kmConv: 255 },
  { origen: "FREYRE", destino: "RAFAELA", kmReal: 60, kmConv: 60 },
  { origen: "! VENADO TUERTO", destino: "SAN FRANCISCO", kmReal: 340, kmConv: 340 },
  { origen: "! SAN FRANCISCO", destino: "VENADO TUERTO", kmReal: 340, kmConv: 340 },
  { origen: "CORDOBA", destino: "MERCEDES", kmReal: 650, kmConv: 650 },
  { origen: "! SAN JOSE (URUGUAY)", destino: "CAMPANA", kmReal: 410, kmConv: 410 },
  { origen: "! SAN JOSE (URUGUAY)", destino: "BUENOS AIRES", kmReal: 490, kmConv: 490 },
  { origen: "! ARROYITO", destino: "DEVOTO", kmReal: 70, kmConv: 70 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "URUGUAIANA", kmReal: 395, kmConv: 395 },
  { origen: "RAFAELA", destino: "SAN JOSE", kmReal: 705, kmConv: 705 },
  { origen: "CATAMARCA", destino: "CORDOBA", kmReal: 450, kmConv: 450 },
  { origen: "CORDOBA", destino: "CATAMARCA", kmReal: 450, kmConv: 450 },
  { origen: "FREYRE", destino: "SAN FRANCISCO", kmReal: 35, kmConv: 35 },
  { origen: "MORTEROS", destino: "PORTE&#209;A", kmReal: 37, kmConv: 37 },
  { origen: "JUNIN", destino: "CORDOBA", kmReal: 550, kmConv: 550 },
  { origen: "! BUENOS AIRES", destino: "JUNIN", kmReal: 267, kmConv: 270 },
  { origen: "! CARMEN DE ARECO", destino: "CHIVILCOY", kmReal: 70, kmConv: 70 },
  { origen: "SAN FRANCISCO", destino: "CARMEN DE ARECO", kmReal: 460, kmConv: 460 },
  { origen: "SAN FRANCISCO", destino: "DESVIO ARIJON", kmReal: 155, kmConv: 155 },
  { origen: "! MARIA JUANA", destino: "SAN FRANCISCO", kmReal: 60, kmConv: 60 },
  { origen: "MARIA JUANA", destino: "CORDOBA", kmReal: 275, kmConv: 275 },
  { origen: "CORDOBA", destino: "MARIA JUANA", kmReal: 275, kmConv: 275 },
  { origen: "! SAN FRANCISCO", destino: "EL TIO", kmReal: 70, kmConv: 70 },
  { origen: "RAFAELA", destino: "ROSARIO", kmReal: 244, kmConv: 244 },
  { origen: "! DEVOTO", destino: "SAN FRANCISCO", kmReal: 20, kmConv: 20 },
  { origen: "ZARATE", destino: "ROSARIO", kmReal: 215, kmConv: 215 },
  { origen: "! LAS VARILLAS", destino: "TIO PUJIO", kmReal: 95, kmConv: 95 },
  { origen: "VILLA CONSTITUCION", destino: "RAFAELA", kmReal: 300, kmConv: 300 },
  { origen: "DEVOTO", destino: "SUNCHALES", kmReal: 130, kmConv: 130 },
  { origen: "SUNCHALES", destino: "DEVOTO", kmReal: 130, kmConv: 130 },
  { origen: "! URUGUAIANA", destino: "ROSARIO", kmReal: 623, kmConv: 625 },
  { origen: "ZARATE", destino: "TIO PUJIO", kmReal: 490, kmConv: 490 },
  { origen: "! SAN JORGE", destino: "ROSARIO", kmReal: 180, kmConv: 180 },
  { origen: "! SAN FRANCISCO", destino: "VILLA CONSTITUCION", kmReal: 320, kmConv: 320 },
  { origen: "CORDOBA", destino: "ACHERAL", kmReal: 538, kmConv: 538 },
  { origen: "ACHERAL", destino: "BUENOS AIRES", kmReal: 1211, kmConv: 1211 },
  { origen: "BUENOS AIRES", destino: "ACHERAL", kmReal: 1211, kmConv: 1211 },
  { origen: "SAN FRANCISCO", destino: "ACHERAL", kmReal: 706, kmConv: 706 },
  { origen: "VILLA MARIA", destino: "ROSARIO", kmReal: 260, kmConv: 260 },
  { origen: "! BUENOS AIRES", destino: "CONCEPCION DEL URUGUAY", kmReal: 295, kmConv: 295 },
  { origen: "! CORRAL DE BUSTOS", destino: "TIO PUJIO", kmReal: 208, kmConv: 210 },
  { origen: "! BUENOS AIRES", destino: "CORRAL DE BUSTOS", kmReal: 422, kmConv: 420 },
  { origen: "! ALTA GRACIA", destino: "BUENOS AIRES", kmReal: 708, kmConv: 710 },
  { origen: "CORDOBA", destino: "ALTA GRACIA", kmReal: 40, kmConv: 40 },
  { origen: "RECREO", destino: "SUNCHALES", kmReal: 125, kmConv: 125 },
  { origen: "! URUGUAIANA", destino: "LUQUE", kmReal: 750, kmConv: 750 },
  { origen: "COLONIA CAROYA", destino: "CORDOBA", kmReal: 53, kmConv: 50 },
  { origen: "ESPERANZA", destino: "RECREO", kmReal: 22, kmConv: 20 },
  { origen: "! GUALEGUAYCHU", destino: "ROSARIO", kmReal: 262, kmConv: 260 },
  { origen: "! SAN NICOLAS", destino: "ROSARIO", kmReal: 72, kmConv: 70 },
  { origen: "! ROSARIO", destino: "SAN NICOLAS", kmReal: 72, kmConv: 70 },
  { origen: "CLUCELLAS", destino: "RAFAELA", kmReal: 42, kmConv: 42 },
  { origen: "! CIPOLLETI", destino: "BUENOS AIRES", kmReal: 1134, kmConv: 1135 },
  { origen: "A&#209;ELO", destino: "CIPOLLETTI", kmReal: 100, kmConv: 100 },
  { origen: "! SANTO TOME", destino: "TIO PUJIO", kmReal: 303, kmConv: 300 },
  { origen: "! BUENOS AIRES", destino: "CLUCELLAS", kmReal: 529, kmConv: 530 },
  { origen: "SANTO TOME", destino: "RAFAELA", kmReal: 108, kmConv: 110 },
  { origen: "RAFAELA", destino: "RESISTENCIA", kmReal: 593, kmConv: 593 },
  { origen: "TIO PUJIO", destino: "ZARATE", kmReal: 486, kmConv: 485 },
  { origen: "SAN FRANCISCO", destino: "TUCUMAN", kmReal: 707, kmConv: 707 },
  { origen: "RECREO", destino: "RAFAELA", kmReal: 80, kmConv: 80 },
  { origen: "CALCHAQUI", destino: "RAFAELA", kmReal: 258, kmConv: 258 },
  { origen: "! SAN FRANCISCO", destino: "CALCHAQUI", kmReal: 330, kmConv: 330 },
  { origen: "CORDOBA", destino: "TUCUMAN", kmReal: 570, kmConv: 570 },
  { origen: "ROSARIO", destino: "RAFAELA", kmReal: 244, kmConv: 245 },
  { origen: "! CONCORDIA", destino: "MONTEVIDEO", kmReal: 525, kmConv: 525 },
  { origen: "! GOYA", destino: "URUGUAIANA", kmReal: 290, kmConv: 290 },
  { origen: "RAFAELA", destino: "GOYA", kmReal: 485, kmConv: 485 },
  { origen: "! RESISTENCIA", destino: "URUGUAIANA", kmReal: 390, kmConv: 390 },
  { origen: "CORDOBA", destino: "VILLA MERCEDES", kmReal: 337, kmConv: 340 },
  { origen: "! CHIVILCOY", destino: "RESISTENCIA", kmReal: 1007, kmConv: 1007 },
  { origen: "! SALTO", destino: "ROSARIO", kmReal: 185, kmConv: 185 },
  { origen: "! MARCOS JUAREZ", destino: "ROSARIO", kmReal: 145, kmConv: 145 },
  { origen: "! ROSARIO", destino: "MARCOS JUAREZ", kmReal: 145, kmConv: 145 },
  { origen: "! SAN JUAN", destino: "BUENOS AIRES", kmReal: 1125, kmConv: 1125 },
  { origen: "! DESVIO ARIJON", destino: "BUENOS AIRES", kmReal: 430, kmConv: 430 },
  { origen: "! BUENOS AIRES", destino: "DESVIO ARIJON", kmReal: 430, kmConv: 430 },
  { origen: "! ARROYITO", destino: "ROSARIO", kmReal: 355, kmConv: 355 },
  { origen: "! ROSARIO", destino: "ARROYITO", kmReal: 355, kmConv: 355 },
  { origen: "RAFAELA", destino: "CONCORDIA", kmReal: 415, kmConv: 415 },
  { origen: "! CORRIENTES", destino: "URUGUAIANA", kmReal: 375, kmConv: 375 },
  { origen: "RAFAELA", destino: "CORRIENTES", kmReal: 613, kmConv: 613 },
  { origen: "! BUENOS AIRES", destino: "VILLA DEL TOTORAL", kmReal: 775, kmConv: 775 },
  { origen: "9 DE JULIO", destino: "URUGUAIANA", kmReal: 850, kmConv: 850 },
  { origen: "FREYRE", destino: "TUCUMAN", kmReal: 676, kmConv: 676 },
  { origen: "! SAN SALVADOR", destino: "BUENOS AIRES", kmReal: 400, kmConv: 400 },
  { origen: "! PARANA", destino: "SAN SALVADOR", kmReal: 208, kmConv: 208 },
  { origen: "! CHACABUCO", destino: "ROSARIO", kmReal: 215, kmConv: 215 },
  { origen: "MONTEVIDEO", destino: "GUALEGUAYCHU", kmReal: 346, kmConv: 345 },
  { origen: "! PARANA", destino: "ROSARIO", kmReal: 200, kmConv: 200 },
  { origen: "! MORTEROS", destino: "PARANA", kmReal: 260, kmConv: 260 },
  { origen: "! GALVEZ", destino: "BUENOS AIRES", kmReal: 428, kmConv: 430 },
  { origen: "SAN FRANCISCO", destino: "GALVEZ", kmReal: 133, kmConv: 135 },
  { origen: "SANTO TOME", destino: "SAN JORGE", kmReal: 145, kmConv: 145 },
  { origen: "! SALTO", destino: "BUENOS AIRES", kmReal: 190, kmConv: 190 },
  { origen: "CHALACEA", destino: "BUENOS AIRES", kmReal: 775, kmConv: 775 },
  { origen: "CORDOBA", destino: "CHALACEA", kmReal: 148, kmConv: 150 },
  { origen: "MENDOZA", destino: "VILLA MERCEDES", kmReal: 355, kmConv: 355 },
  { origen: "! MONTEVIDEO", destino: "URUGUAIANA", kmReal: 708, kmConv: 710 },
  { origen: "! MENDOZA", destino: "TIO PUJIO", kmReal: 622, kmConv: 620 },
  { origen: "SAN JORGE", destino: "SAN FRANCISCO", kmReal: 87, kmConv: 90 },
  { origen: "! RIO CUARTO", destino: "MENDOZA", kmReal: 475, kmConv: 475 },
  { origen: "! SAN FRANCISCO", destino: "PASO DE LOS LIBRES", kmReal: 597, kmConv: 600 },
  { origen: "! VILLA MERCEDES", destino: "COLONIA CAROYA", kmReal: 398, kmConv: 400 },
  { origen: "! CHACABUCO", destino: "URUGUAIANA", kmReal: 750, kmConv: 750 },
  { origen: "! COLONIA CAROYA", destino: "ROSARIO", kmReal: 446, kmConv: 445 },
  { origen: "! JUNIN", destino: "ROSARIO", kmReal: 205, kmConv: 205 },
  { origen: "PARANÁ", destino: "TUCUMAN", kmReal: 810, kmConv: 810 },
  { origen: "! VILLA DEL TOTORAL", destino: "COLONIA CAROYA", kmReal: 39, kmConv: 40 },
  { origen: "RAFAELA", destino: "PORTE&#209;A", kmReal: 78, kmConv: 80 },
  { origen: "CORDOBA", destino: "CHACABUCO", kmReal: 580, kmConv: 580 },
  { origen: "! NEUQUEN", destino: "BUENOS AIRES", kmReal: 1182, kmConv: 1180 },
  { origen: "TUCUMAN", destino: "RAFAELA", kmReal: 675, kmConv: 675 },
  { origen: "MORTEROS", destino: "SAN FRANCISCO", kmReal: 90, kmConv: 90 },
  { origen: "! SALTO", destino: "CAMPANA", kmReal: 147, kmConv: 150 },
  { origen: "RAFAELA", destino: "NEUQUEN", kmReal: 1287, kmConv: 1290 },
  { origen: "RAFAELA", destino: "TUCUMAN", kmReal: 675, kmConv: 675 },
  { origen: "9 DE JULIO", destino: "SALTO", kmReal: 197, kmConv: 200 },
  { origen: "VILLA REGINA", destino: "BUENOS AIRES", kmReal: 1056, kmConv: 1055 },
  { origen: "A&#209;ELO", destino: "VILLA REGINA", kmReal: 184, kmConv: 185 },
  { origen: "! SAN NICOLAS", destino: "BUENOS AIRES", kmReal: 238, kmConv: 240 },
  { origen: "! BUENOS AIRES", destino: "SAN NICOLAS", kmReal: 238, kmConv: 240 },
  { origen: "! MORTEROS", destino: "FREYRE", kmReal: 52, kmConv: 52 },
  { origen: "! SAN RAFAEL", destino: "MENDOZA", kmReal: 233, kmConv: 230 },
  { origen: "RAFAELA", destino: "SAN RAFAEL", kmReal: 880, kmConv: 880 },
  { origen: "! BUENOS AIRES", destino: "MORTEROS", kmReal: 645, kmConv: 645 },
  { origen: "! ROSARIO", destino: "CHIVILCOY", kmReal: 261, kmConv: 261 },
  { origen: "! ROSARIO", destino: "CAMPANA", kmReal: 222, kmConv: 220 },
  { origen: "! CHIVILCOY", destino: "ROSARIO", kmReal: 261, kmConv: 260 },
  { origen: "! ROSARIO", destino: "MORTEROS", kmReal: 350, kmConv: 350 },
  { origen: "! FREYRE", destino: "BUENOS AIRES", kmReal: 605, kmConv: 605 },
  { origen: "SAN FRANCISCO", destino: "FREYRE", kmReal: 35, kmConv: 35 },
  { origen: "RAFAELA", destino: "VILLA MERCEDES", kmReal: 512, kmConv: 512 },
  { origen: "! SAN FRANCISCO", destino: "CONCEPCION DEL URUGUAY", kmReal: 433, kmConv: 430 },
  { origen: "! CHIVILCOY", destino: "MENDOZA", kmReal: 979, kmConv: 980 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "CORDOBA", kmReal: 645, kmConv: 645 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "BUENOS AIRES", kmReal: 296, kmConv: 295 },
  { origen: "MONTEVIDEO", destino: "CONCEPCION DEL URUGUAY", kmReal: 416, kmConv: 415 },
  { origen: "9 DE JULIO", destino: "CHIVILCOY", kmReal: 113, kmConv: 110 },
  { origen: "SAN JUAN", destino: "CORDOBA", kmReal: 587, kmConv: 590 },
  { origen: "RAFAELA", destino: "SAN JUAN", kmReal: 897, kmConv: 895 },
  { origen: "ARROYITO", destino: "9 DE JULIO", kmReal: 627, kmConv: 630 },
  { origen: "MONTEVIDEO", destino: "CAMPANA", kmReal: 496, kmConv: 495 },
  { origen: "! ESPERANZA", destino: "SAN JUAN", kmReal: 968, kmConv: 970 },
  { origen: "ESPERANZA", destino: "RAFAELA", kmReal: 60, kmConv: 60 },
  { origen: "! SALTO", destino: "CHIVILCOY", kmReal: 98, kmConv: 100 },
  { origen: "! CALCHIN", destino: "BUENOS AIRES", kmReal: 660, kmConv: 660 },
  { origen: "! BUENOS AIRES", destino: "CALCHIN", kmReal: 660, kmConv: 660 },
  { origen: "RAFAELA", destino: "MENDOZA", kmReal: 849, kmConv: 855 },
  { origen: "! JUNIN", destino: "CHIVILCOY", kmReal: 104, kmConv: 104 },
  { origen: "! MORTEROS", destino: "BUENOS AIRES", kmReal: 645, kmConv: 645 },
  { origen: "SAN FRANCISCO", destino: "MORTEROS", kmReal: 90, kmConv: 90 },
  { origen: "! MORTEROS", destino: "ROSARIO", kmReal: 350, kmConv: 350 },
  { origen: "ARROYITO", destino: "CORDOBA", kmReal: 117, kmConv: 120 },
  { origen: "! SAN FRANCISCO", destino: "SAN LUIS", kmReal: 514, kmConv: 515 },
  { origen: "! VILLA DEL TOTORAL", destino: "RECREO (CATAMARCA)", kmReal: 205, kmConv: 205 },
  { origen: "ROSARIO", destino: "MONTEVIDEO", kmReal: 602, kmConv: 605 },
  { origen: "! SANTA FE", destino: "CARCARA&#209;A", kmReal: 213, kmConv: 210 },
  { origen: "! ROSARIO", destino: "TIO PUJIO", kmReal: 280, kmConv: 280 },
  { origen: "BUENOS AIRES", destino: "A&#209;ELO", kmReal: 1200, kmConv: 1200 },
  { origen: "! LA FALDA", destino: "COLONIA CAROYA", kmReal: 121, kmConv: 120 },
  { origen: "! SAN LUIS", destino: "COLONIA CAROYA", kmReal: 489, kmConv: 490 },
  { origen: "SANTA FE", destino: "CORDOBA", kmReal: 356, kmConv: 355 },
  { origen: "! SAN LUIS", destino: "VILLA MERCEDES", kmReal: 90, kmConv: 90 },
  { origen: "VILLA MERCEDES", destino: "CORDOBA", kmReal: 337, kmConv: 340 },
  { origen: "SANTA FE", destino: "SAN JORGE", kmReal: 156, kmConv: 155 },
  { origen: "MENDOZA", destino: "BUENOS AIRES", kmReal: 1099, kmConv: 1090 },
  { origen: "! TIO PUJIO", destino: "MENDOZA", kmReal: 621, kmConv: 620 },
  { origen: "! VILLA MERCEDES", destino: "TIO PUJIO", kmReal: 276, kmConv: 275 },
  { origen: "! SAN FRANCISCO", destino: "DIAZ", kmReal: 183, kmConv: 180 },
  { origen: "! COLONIA TIROLESA", destino: "BUENOS AIRES", kmReal: 715, kmConv: 715 },
  { origen: "CORDOBA", destino: "COLONIA TIROLESA", kmReal: 35, kmConv: 35 },
  { origen: "TUCUMAN", destino: "BUENOS AIRES", kmReal: 1235, kmConv: 1235 },
  { origen: "CAMPANA", destino: "CORDOBA", kmReal: 620, kmConv: 620 },
  { origen: "! BUENOS AIRES", destino: "CAMPANA", kmReal: 80, kmConv: 80 },
  { origen: "SALTA", destino: "TUCUMAN", kmReal: 307, kmConv: 310 },
  { origen: "! TIO PUJIO", destino: "SALTA", kmReal: 1001, kmConv: 1000 },
  { origen: "BUENOS AIRES", destino: "LA PLATA", kmReal: 48, kmConv: 50 },
  { origen: "MENDOZA", destino: "CORDOBA", kmReal: 686, kmConv: 685 },
  { origen: "CORDOBA", destino: "LEONES", kmReal: 245, kmConv: 245 },
  { origen: "LEONES", destino: "CORDOBA", kmReal: 245, kmConv: 245 },
  { origen: "TUCUMAN", destino: "MENDOZA", kmReal: 957, kmConv: 960 },
  { origen: "TIO PUJIO", destino: "TUCUMAN", kmReal: 702, kmConv: 700 },
  { origen: "! ROSARIO", destino: "SAN JORGE", kmReal: 183, kmConv: 180 },
  { origen: "LA PLATA", destino: "BUENOS AIRES", kmReal: 48, kmConv: 50 },
  { origen: "! VILLA MERCEDES", destino: "BUENOS AIRES", kmReal: 722, kmConv: 720 },
  { origen: "! DIAZ", destino: "VILLA MERCEDES", kmReal: 486, kmConv: 485 },
  { origen: "! ESPERANZA", destino: "DIAZ", kmReal: 137, kmConv: 140 },
  { origen: "! PARANA", destino: "URUGUAIANA", kmReal: 431, kmConv: 430 },
  { origen: "SAN FRANCISCO", destino: "PARANÁ", kmReal: 169, kmConv: 170 },
  { origen: "CORDOBA", destino: "PARANÁ", kmReal: 395, kmConv: 395 },
  { origen: "! HERNANDO", destino: "TIO PUJIO", kmReal: null, kmConv: 80 },
  { origen: "ZARATE", destino: "BUENOS AIRES", kmReal: 90, kmConv: 90 },
  { origen: "! BUENOS AIRES", destino: "HERNANDO", kmReal: 617, kmConv: 620 },
  { origen: "! ARROYITO", destino: "MONTEVIDEO", kmReal: 892, kmConv: 890 },
  { origen: "SAN FRANCISCO", destino: "ARROYITO", kmReal: 93, kmConv: 90 },
  { origen: "BUENOS AIRES", destino: "ZARATE", kmReal: 90, kmConv: 90 },
  { origen: "CONCORDIA", destino: "SAN FRANCISCO", kmReal: 437, kmConv: 440 },
  { origen: "! BUENOS AIRES", destino: "VILLA MERCEDES", kmReal: 722, kmConv: 720 },
  { origen: "ARROYITO", destino: "SAN FRANCISCO", kmReal: 90, kmConv: 90 },
  { origen: "VILLA DEL TOTORAL", destino: "SAN FRANCISCO", kmReal: 258, kmConv: 260 },
  { origen: "LA FALDA", destino: "CORDOBA", kmReal: 70, kmConv: 70 },
  { origen: "SANTA FE", destino: "SAN FRANCISCO", kmReal: 143, kmConv: 145 },
  { origen: "BECCAR", destino: "PILAR", kmReal: 42, kmConv: 40 },
  { origen: "BUENOS AIRES", destino: "ARROYITO", kmReal: 659, kmConv: 660 },
  { origen: "RECREO", destino: "ROSARIO", kmReal: 188, kmConv: 190 },
  { origen: "SAN LUIS", destino: "BUENOS AIRES", kmReal: 813, kmConv: 810 },
  { origen: "VILLA DEL TOTORAL", destino: "CORDOBA", kmReal: 104, kmConv: 105 },
  { origen: "RIO CUARTO", destino: "CORDOBA", kmReal: 214, kmConv: 215 },
  { origen: "! SAUCE VIEJO", destino: "RECREO (STA. FE)", kmReal: 44, kmConv: 45 },
  { origen: "! BUENOS AIRES", destino: "SAUCE VIEJO", kmReal: 445, kmConv: 445 },
  { origen: "LUQUE", destino: "CORDOBA", kmReal: 102, kmConv: 100 },
  { origen: "! BUENOS AIRES", destino: "MONTEVIDEO", kmReal: 580, kmConv: 580 },
  { origen: "! SAN FRANCISCO", destino: "ESPERANZA", kmReal: 135, kmConv: 135 },
  { origen: "! BUENOS AIRES", destino: "BUENOS AIRES", kmReal: 40, kmConv: 40 },
  { origen: "RAFAELA", destino: "CORDOBA", kmReal: 295, kmConv: 300 },
  { origen: "SANTA FE", destino: "RAFAELA", kmReal: 89, kmConv: 90 },
  { origen: "! BUENOS AIRES", destino: "SANTA FE", kmReal: 469, kmConv: 470 },
  { origen: "! MONTEVIDEO", destino: "SUNCHALES", kmReal: 798, kmConv: 800 },
  { origen: "! ROSARIO", destino: "URUGUAIANA", kmReal: 583, kmConv: 580 },
  { origen: "! MONTEVIDEO", destino: "TIO PUJIO", kmReal: 887, kmConv: 890 },
  { origen: "CRUZ DEL EJE", destino: "CORDOBA", kmReal: 192, kmConv: 190 },
  { origen: "! ARROYITO", destino: "BUENOS AIRES", kmReal: 659, kmConv: 660 },
  { origen: "CORDOBA", destino: "ARROYITO", kmReal: 118, kmConv: 120 },
  { origen: "! FIRMAT", destino: "ROSARIO", kmReal: 115, kmConv: 115 },
  { origen: "PORTE&#209;A", destino: "FIRMAT", kmReal: 331, kmConv: 330 },
  { origen: "ALTA GRACIA", destino: "CORDOBA", kmReal: null, kmConv: 40 },
  { origen: "! MALDONADO", destino: "BUENOS AIRES", kmReal: 685, kmConv: 685 },
  { origen: "CORDOBA", destino: "FRIAS", kmReal: 353, kmConv: 350 },
  { origen: "SAN LUIS", destino: "CORDOBA", kmReal: 428, kmConv: 430 },
  { origen: "CONCORDIA", destino: "SUNCHALES", kmReal: 443, kmConv: 440 },
  { origen: "! SAN LUIS", destino: "TIO PUJIO", kmReal: 370, kmConv: 370 },
  { origen: "! BUENOS AIRES", destino: "MALDONADO", kmReal: 685, kmConv: 685 },
  { origen: "! EL TIO", destino: "DEVOTO", kmReal: 50, kmConv: 50 },
  { origen: "! SAN FRANCISCO", destino: "GOBERNADOR CRESPO", kmReal: 279, kmConv: 280 },
  { origen: "! BUENOS AIRES", destino: "ALTA GRACIA", kmReal: 708, kmConv: 710 },
  { origen: "! REDUCCION", destino: "SAN FRANCISCO", kmReal: 333, kmConv: 330 },
  { origen: "! BUENOS AIRES", destino: "REDUCCION", kmReal: 582, kmConv: 580 },
  { origen: "! EL TIO", destino: "TIO PUJIO", kmReal: 154, kmConv: 155 },
  { origen: "SAN FRANCISCO", destino: "FRANCK", kmReal: 120, kmConv: 120 },
  { origen: "! CRUZ DEL EJE", destino: "RECREO (CATAMARCA)", kmReal: 209, kmConv: 210 },
  { origen: "MONTEVIDEO", destino: "SAN JORGE", kmReal: 789, kmConv: 790 },
  { origen: "RIO CEBALLOS", destino: "CORDOBA", kmReal: 35, kmConv: 35 },
  { origen: "RIO CEBALLOS", destino: "SAN FRANCISCO", kmReal: 237, kmConv: 240 },
  { origen: "! MONTEVIDEO", destino: "BUENOS AIRES", kmReal: 580, kmConv: 580 },
  { origen: "! BUENOS AIRES", destino: "GOBERNADOR CRESPO", kmReal: 616, kmConv: 620 },
  { origen: "! GOBERNADOR CRESPO", destino: "BUENOS AIRES", kmReal: 616, kmConv: 620 },
  { origen: "! URUGUAIANA", destino: "BUENOS AIRES", kmReal: 675, kmConv: 675 },
  { origen: "! FRIAS", destino: "RECREO (CATAMARCA)", kmReal: 74, kmConv: 75 },
  { origen: "CORDOBA", destino: "CRUZ DEL EJE", kmReal: 192, kmConv: 190 },
  { origen: "! MONTEVIDEO", destino: "CHIVILCOY", kmReal: 664, kmConv: 660 },
  { origen: "! BUENOS AIRES", destino: "URUGUAIANA", kmReal: 675, kmConv: 675 },
  { origen: "VILLA MARIA", destino: "TIO PUJIO", kmReal: 18, kmConv: 20 },
  { origen: "CORDOBA", destino: "URUGUAIANA", kmReal: 807, kmConv: 820 },
  { origen: "! BUENOS AIRES", destino: "COLONIA CAROYA", kmReal: 740, kmConv: 740 },
  { origen: "! BUENOS AIRES", destino: "RIO CEBALLOS", kmReal: 723, kmConv: 725 },
  { origen: "PORTE&#209;A", destino: "SAN FRANCISCO", kmReal: 52, kmConv: 55 },
  { origen: "! GALVEZ", destino: "ROSARIO", kmReal: 134, kmConv: 135 },
  { origen: "! BUENOS AIRES", destino: "GALVEZ", kmReal: 428, kmConv: 430 },
  { origen: "! MONTEVIDEO", destino: "SALTO", kmReal: 645, kmConv: 645 },
  { origen: "! VILLA DEL TOTORAL", destino: "DEVOTO", kmReal: 237, kmConv: 240 },
  { origen: "! BUENOS AIRES", destino: "FRANCK", kmReal: 474, kmConv: 480 },
  { origen: "! FRANCK", destino: "BUENOS AIRES", kmReal: 474, kmConv: 480 },
  { origen: "CORDOBA", destino: "RAFAELA", kmReal: 308, kmConv: 310 },
  { origen: "MONTEVIDEO", destino: "ROSARIO", kmReal: 604, kmConv: 605 },
  { origen: "! ESPERANZA", destino: "BUENOS AIRES", kmReal: 493, kmConv: 490 },
  { origen: "! TRES ARROYOS", destino: "COLONIA CAROYA", kmReal: 1075, kmConv: 1080 },
  { origen: "! MAR DEL PLATA", destino: "TRES ARROYOS", kmReal: 270, kmConv: 270 },
  { origen: "! BUENOS AIRES", destino: "ESPERANZA", kmReal: 493, kmConv: 490 },
  { origen: "CORDOBA", destino: "JARAGUÁ DO SUL", kmReal: 2064, kmConv: 2070 },
  { origen: "! SAN LORENZO", destino: "ROSARIO", kmReal: 31, kmConv: 30 },
  { origen: "! BUENOS AIRES", destino: "SAN LORENZO", kmReal: 341, kmConv: 340 },
  { origen: "! SAN FRANCISCO", destino: "JARAGUA DO SUL", kmReal: 1870, kmConv: 1860 },
  { origen: "SAN FRANCISCO", destino: "PORTE&#209;A", kmReal: 52, kmConv: 55 },
  { origen: "COLONIA CAROYA", destino: "PILAR", kmReal: 703, kmConv: 705 },
  { origen: "CORDOBA", destino: "COLONIA CAROYA", kmReal: 53, kmConv: 50 },
  { origen: "SAN FRANCISCO", destino: "CONCORDIA", kmReal: 437, kmConv: 440 },
  { origen: "ZARATE", destino: "CHIVILCOY", kmReal: 161, kmConv: 160 },
  { origen: "! CONCORDIA", destino: "ROSARIO", kmReal: 361, kmConv: 360 },
  { origen: "BUENOS AIRES", destino: "SUNCHALES", kmReal: 566, kmConv: 580 },
  { origen: "ESPERANZA", destino: "SAN FRANCISCO", kmReal: 140, kmConv: 140 },
  { origen: "CORDOBA", destino: "ESPERANZA", kmReal: 360, kmConv: 360 },
  { origen: "ZARATE", destino: "SAN JORGE", kmReal: 410, kmConv: 410 },
  { origen: "SAN JORGE", destino: "ZARATE", kmReal: 410, kmConv: 410 },
  { origen: "! BUENOS AIRES", destino: "DEVOTO", kmReal: 588, kmConv: 590 },
  { origen: "! EL TIO", destino: "BUENOS AIRES", kmReal: 637, kmConv: 640 },
  { origen: "! BUENOS AIRES", destino: "EL TIO", kmReal: 637, kmConv: 640 },
  { origen: "! RECREO (CATAMARCA)", destino: "BUENOS AIRES", kmReal: 959, kmConv: 960 },
  { origen: "CHIVILCOY", destino: "CORDOBA", kmReal: 634, kmConv: 650 },
  { origen: "! BUENOS AIRES", destino: "CHIVILCOY", kmReal: 167, kmConv: 170 },
  { origen: "CORDOBA", destino: "DEVOTO", kmReal: 202, kmConv: 200 },
  { origen: "! DEVOTO", destino: "BUENOS AIRES", kmReal: 588, kmConv: 590 },
  { origen: "SAN FRANCISCO", destino: "DEVOTO", kmReal: null, kmConv: 20 },
  { origen: "SUNCHALES", destino: "BUENOS AIRES", kmReal: 566, kmConv: 580 },
  { origen: "SAN FRANCISCO", destino: "SUNCHALES", kmReal: 112, kmConv: 110 },
  { origen: "! LUQUE", destino: "SAN FRANCISCO", kmReal: 140, kmConv: 140 },
  { origen: "! SAN FRANCISCO", destino: "LUQUE", kmReal: 140, kmConv: 140 },
  { origen: "VILLA MARIA", destino: "CORDOBA", kmReal: 156, kmConv: 160 },
  { origen: "CORDOBA", destino: "VILLA MARIA", kmReal: 156, kmConv: 160 },
  { origen: "VILLA MARIA", destino: "SAN FRANCISCO", kmReal: 164, kmConv: 160 },
  { origen: "SAN FRANCISCO", destino: "VILLA MARIA", kmReal: 164, kmConv: 165 },
  { origen: "! BUENOS AIRES", destino: "VILLA MARIA", kmReal: 552, kmConv: 550 },
  { origen: "! VILLA MARIA", destino: "BUENOS AIRES", kmReal: 552, kmConv: 550 },
  { origen: "! JUNIN", destino: "BUENOS AIRES", kmReal: 268, kmConv: 270 },
  { origen: "! SAN FRANCISCO", destino: "JUNIN", kmReal: 469, kmConv: 470 },
  { origen: "SAN FRANCISCO", destino: "TIO PUJIO", kmReal: 175, kmConv: 175 },
  { origen: "BUENOS AIRES", destino: "RAFAELA", kmReal: 540, kmConv: 540 },
  { origen: "RAFAELA", destino: "BUENOS AIRES", kmReal: 540, kmConv: 540 },
  { origen: "SAN FRANCISCO", destino: "RAFAELA", kmReal: null, kmConv: 85 },
  { origen: "! BUENOS AIRES", destino: "TIO PUJIO", kmReal: 570, kmConv: 570 },
  { origen: "! TIO PUJIO", destino: "BUENOS AIRES", kmReal: 570, kmConv: 570 },
  { origen: "CORDOBA", destino: "TIO PUJIO", kmReal: 134, kmConv: 135 },
  { origen: "BUENOS AIRES", destino: "PORTE&#209;A", kmReal: 620, kmConv: 625 },
  { origen: "PORTE&#209;A", destino: "CORDOBA", kmReal: 259, kmConv: 260 },
  { origen: "! BUENOS AIRES", destino: "SAN JORGE", kmReal: 493, kmConv: 500 },
  { origen: "! BUENOS AIRES", destino: "RIO CUARTO", kmReal: 617, kmConv: 620 },
  { origen: "! RIO CUARTO", destino: "BUENOS AIRES", kmReal: 617, kmConv: 620 },
  { origen: "CORDOBA", destino: "RIO CUARTO", kmReal: 214, kmConv: 215 },
  { origen: "CORDOBA", destino: "PORTE&#209;A", kmReal: 259, kmConv: 260 },
  { origen: "PORTE&#209;A", destino: "BUENOS AIRES", kmReal: 620, kmConv: 625 },
  { origen: "CORDOBA", destino: "SAN JORGE", kmReal: 290, kmConv: 290 },
  { origen: "SAN FRANCISCO", destino: "SAN JORGE", kmReal: 87, kmConv: 90 },
  { origen: "SAN JORGE", destino: "BUENOS AIRES", kmReal: 493, kmConv: 500 },
  { origen: "MAR DEL PLATA", destino: "BUENOS AIRES", kmReal: 414, kmConv: 410 },
  { origen: "CORDOBA", destino: "MENDOZA", kmReal: 686, kmConv: 685 },
  { origen: "CORDOBA", destino: "MAR DEL PLATA", kmReal: 1108, kmConv: 1110 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN LUIS", kmReal: 758, kmConv: 760 },
  { origen: "CONCORDIA", destino: "BUENOS AIRES", kmReal: 429, kmConv: 430 },
  { origen: "! GUALEGUAYCHU", destino: "BUENOS AIRES", kmReal: 232, kmConv: 230 },
  { origen: "! GUALEGUAYCHU", destino: "MONTEVIDEO", kmReal: 346, kmConv: 345 },
  { origen: "CONCORDIA", destino: "URUGUAIANA", kmReal: 261, kmConv: 260 },
  { origen: "CORDOBA", destino: "GUALEGUAYCHU", kmReal: 684, kmConv: 685 },
  { origen: "CORDOBA", destino: "CONCORDIA", kmReal: 664, kmConv: 665 },
  { origen: "! SAN PABLO", destino: "SAN FRANCISCO", kmReal: 2167, kmConv: 2410 },
  { origen: "! SAN PABLO", destino: "URUGUAIANA", kmReal: 1546, kmConv: 1800 },
  { origen: "GENERAL RODRIGUEZ", destino: "COLONIA CAROYA", kmReal: 715, kmConv: 720 },
  { origen: "BUENOS AIRES", destino: "GENERAL RODRIGUEZ", kmReal: null, kmConv: 60 },
  { origen: "BUENOS AIRES", destino: "SALTO", kmReal: 197, kmConv: 180 },
  { origen: "! JARAGUA DO SUL", destino: "SAN FRANCISCO", kmReal: 1870, kmConv: 1860 },
  { origen: "! JARAGUA DO SUL", destino: "URUGUAIANA", kmReal: 1247, kmConv: 1250 },
  { origen: "! MONTEVIDEO", destino: "SAN LUIS", kmReal: 1446, kmConv: 1410 },
  { origen: "! MONTEVIDEO", destino: "COLONIA CAROYA", kmReal: 1060, kmConv: 1050 },
  { origen: "SAN FRANCISCO", destino: "MONTEVIDEO", kmReal: 801, kmConv: 800 },
  { origen: "! MONTEVIDEO", destino: "SAN FRANCISCO", kmReal: 801, kmConv: 800 },
  { origen: "! SALTO", destino: "MONTEVIDEO", kmReal: 645, kmConv: 645 },
  { origen: "BUENOS AIRES", destino: "URUGUAIANA", kmReal: 675, kmConv: 675 },
  { origen: "BUENOS AIRES", destino: "CORDOBA", kmReal: 696, kmConv: 700 },
  { origen: "CORDOBA", destino: "BUENOS AIRES", kmReal: 696, kmConv: 700 },
  { origen: "ROSARIO", destino: "BUENOS AIRES", kmReal: 298, kmConv: 300 },
  { origen: "BUENOS AIRES", destino: "ROSARIO", kmReal: 298, kmConv: 300 },
  { origen: "URUGUAIANA", destino: "SAN FRANCISCO", kmReal: 623, kmConv: 610 },
  { origen: "SAN FRANCISCO", destino: "URUGUAIANA", kmReal: 623, kmConv: 610 },
  { origen: "ROSARIO", destino: "CORDOBA", kmReal: 401, kmConv: 400 },
  { origen: "BUENOS AIRES", destino: "SAN FRANCISCO", kmReal: 568, kmConv: 570 },
  { origen: "SAN FRANCISCO", destino: "BUENOS AIRES", kmReal: 568, kmConv: 570 },
  { origen: "CORDOBA", destino: "ROSARIO", kmReal: 419, kmConv: 400 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
