/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 1 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "CARMEN DE ARECO", destino: "BERAZATEGUI", kmReal: 172, kmConv: 172 },
  { origen: "LIMA", destino: "BERAZATEGUI", kmReal: 137, kmConv: 137 },
  { origen: "GALVEZ", destino: "MAR DEL PLATA", kmReal: 844, kmConv: 845 },
  { origen: "FRANCK", destino: "GALVEZ", kmReal: 68, kmConv: 70 },
  { origen: "VIALE", destino: "FRANCK", kmReal: 113, kmConv: 113 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "SAN MARTIN", kmReal: 40, kmConv: 40 },
  { origen: "9 DE JULIO", destino: "9 DE ABRIL", kmReal: 270, kmConv: 270 },
  { origen: "FRAY LUIS BELTRAN", destino: "HURLINGHAM", kmReal: 1006, kmConv: 1006 },
  { origen: "MENDOZA", destino: "FRAY LUIS BELTRAN", kmReal: null, kmConv: 24 },
  { origen: "GALVEZ", destino: "SAN JORGE", kmReal: 145, kmConv: 145 },
  { origen: "CORDOBA", destino: "ALVEAR", kmReal: 415, kmConv: 415 },
  { origen: "RAFAELA", destino: "9 DE JULIO", kmReal: 570, kmConv: 570 },
  { origen: "FRANCK", destino: "LIMA", kmReal: 375, kmConv: 375 },
  { origen: "ROSARIO", destino: "SAUCE VIEJO", kmReal: 150, kmConv: 150 },
  { origen: "MAIPU", destino: "HURLINGHAM", kmReal: 1025, kmConv: 1025 },
  { origen: "SAN MARTIN", destino: "MAIPU", kmReal: 40, kmConv: 40 },
  { origen: "RAFAELA", destino: "SAN MARTIN", kmReal: 815, kmConv: 815 },
  { origen: "LA HORQUETA", destino: "VILLA SOLDATI", kmReal: 30, kmConv: 30 },
  { origen: "SAN FRANCISCO", destino: "LA HORQUETA", kmReal: 620, kmConv: 620 },
  { origen: "BARRACAS", destino: "GOBERNADOR VIRASORO", kmReal: 912, kmConv: 912 },
  { origen: "ALVEAR", destino: "ROSARIO", kmReal: 20, kmConv: 20 },
  { origen: "HURLINGHAM", destino: "BERAZATEGUI", kmReal: null, kmConv: 55 },
  { origen: "MUNRO", destino: "GALVEZ", kmReal: 412, kmConv: 410 },
  { origen: "HURLINGHAM", destino: "LOMAS DEL MIRADOR", kmReal: null, kmConv: 17 },
  { origen: "ZARATE", destino: "INGENIERO LUIGGI", kmReal: 598, kmConv: 598 },
  { origen: "ELORTONDO", destino: "TIO PUJIO", kmReal: 320, kmConv: 320 },
  { origen: "TORTUGUITAS", destino: "SAN JORGE", kmReal: 460, kmConv: 460 },
  { origen: "ROSARIO", destino: "BERAZATEGUI", kmReal: 328, kmConv: 328 },
  { origen: "CORRAL DE BUSTOS", destino: "ELORTONDO", kmReal: 110, kmConv: 110 },
  { origen: "BARRACAS", destino: "ESPERANZA", kmReal: 498, kmConv: 498 },
  { origen: "SANTA FE", destino: "PORTE&#209;A", kmReal: 192, kmConv: 192 },
  { origen: "BURZACO", destino: "BERAZATEGUI", kmReal: null, kmConv: 22 },
  { origen: "BRAGADO", destino: "EZEIZA", kmReal: 243, kmConv: 243 },
  { origen: "LANUS", destino: "MATADEROS", kmReal: null, kmConv: 16 },
  { origen: "VIALE", destino: "CONCORDIA", kmReal: 213, kmConv: 213 },
  { origen: "PILAR", destino: "BERAZATEGUI", kmReal: null, kmConv: 96 },
  { origen: "SAN JORGE", destino: "CORDOBA", kmReal: 290, kmConv: 290 },
  { origen: "MORENO", destino: "BERAZATEGUI", kmReal: null, kmConv: 68 },
  { origen: "SAN FRANCISCO", destino: "CAPITAN CORTEZ", kmReal: 584, kmConv: 584 },
  { origen: "AVELLANEDA", destino: "FRANCK", kmReal: 332, kmConv: 332 },
  { origen: "FRANCK", destino: "ESTEBAN ECHEVERRIA", kmReal: 502, kmConv: 502 },
  { origen: "CORDOBA", destino: "VIALE", kmReal: 454, kmConv: 454 },
  { origen: "SAN JUAN", destino: "LUJAN DE CUYO", kmReal: 185, kmConv: 185 },
  { origen: "PILAR", destino: "ESPERANZA", kmReal: 453, kmConv: 453 },
  { origen: "ZARATE", destino: "SALTO", kmReal: 151, kmConv: 151 },
  { origen: "FRANCK", destino: "CORDOBA", kmReal: 123, kmConv: 123 },
  { origen: "MENDOZA", destino: "VILLA DEL ROSARIO", kmReal: 722, kmConv: 722 },
  { origen: "3 DE FEBRERO", destino: "3 DE FEBRERO", kmReal: 48, kmConv: 50 },
  { origen: "MERLO", destino: "QUILMES", kmReal: null, kmConv: 60 },
  { origen: "SIERRA DE LOS PADRES", destino: "BURZACO", kmReal: 417, kmConv: 417 },
  { origen: "CIUDADELA", destino: "MATADEROS", kmReal: null, kmConv: 5 },
  { origen: "CANELONES", destino: "VILLA SOLDATI", kmReal: 572, kmConv: 570 },
  { origen: "FLORES", destino: "ZARATE", kmReal: null, kmConv: 95 },
  { origen: "RAFAELA", destino: "FLORES", kmReal: 565, kmConv: 565 },
  { origen: "ALSINA", destino: "CONCORDIA", kmReal: 390, kmConv: 390 },
  { origen: "JUNIN", destino: "ALSINA", kmReal: 225, kmConv: 225 },
  { origen: "ITUZAINGO", destino: "CANELONES", kmReal: 570, kmConv: 570 },
  { origen: "FRANCK", destino: "TANDIL", kmReal: 775, kmConv: 775 },
  { origen: "BARADERO", destino: "GALVEZ", kmReal: 291, kmConv: 290 },
  { origen: "TAPIALES", destino: "JUNIN", kmReal: 260, kmConv: 260 },
  { origen: "JOSE LEON SUAREZ", destino: "JOSE INGENIEROS", kmReal: null, kmConv: 15 },
  { origen: "CHACARITA", destino: "CARLOS PAZ", kmReal: 725, kmConv: 725 },
  { origen: "GENERAL PACHECO", destino: "CHACARITA", kmReal: 25, kmConv: 25 },
  { origen: "CAMPO GRANDE", destino: "SAN FRANCISCO", kmReal: 987, kmConv: 987 },
  { origen: "POSADAS", destino: "CAMPO GRANDE", kmReal: 140, kmConv: 140 },
  { origen: "SAN LUIS", destino: "BURZACO", kmReal: 800, kmConv: 800 },
  { origen: "GALVEZ", destino: "EZEIZA", kmReal: 460, kmConv: 460 },
  { origen: "JOSE LEON SUAREZ", destino: "LAFERRERE", kmReal: null, kmConv: 37 },
  { origen: "RAFAELA", destino: "JOSE LEON SUAREZ", kmReal: 520, kmConv: 520 },
  { origen: "TUCUMAN", destino: "RETIRO", kmReal: 1262, kmConv: 1262 },
  { origen: "CARLOS SPEGAZZINI", destino: "GALVEZ", kmReal: 480, kmConv: 480 },
  { origen: "SAN LUIS", destino: "LOMAS DE ZAMORA", kmReal: 793, kmConv: 793 },
  { origen: "SAN MIGUEL DEL MONTE", destino: "CARLOS SPEGAZZINI", kmReal: 64, kmConv: 65 },
  { origen: "SANTA TERESITA", destino: "SAN MIGUEL DEL MONTE", kmReal: 284, kmConv: 285 },
  { origen: "SAN SALVADOR", destino: "SAN JUSTO", kmReal: 402, kmConv: 402 },
  { origen: "ARROYITO", destino: "LULES", kmReal: 654, kmConv: 654 },
  { origen: "JOSE INGENIEROS", destino: "SAN FRANCISCO", kmReal: 556, kmConv: 556 },
  { origen: "VILLA SOLDATI", destino: "JOSE INGENIEROS", kmReal: null, kmConv: 11 },
  { origen: "ZONA PORTUARIA", destino: "QUILMES", kmReal: null, kmConv: 25 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "QUILMES", kmReal: 60, kmConv: 60 },
  { origen: "ENSENADA", destino: "BARRACAS", kmReal: null, kmConv: 57 },
  { origen: "CORDOBA", destino: "MONTEVIDEO", kmReal: 1025, kmConv: 1025 },
  { origen: "MONTEVIDEO", destino: "CORDOBA", kmReal: 1025, kmConv: 1025 },
  { origen: "LEANDRO N ALEM", destino: "SAN FRANCISCO", kmReal: 921, kmConv: 921 },
  { origen: "OBERA", destino: "LEANDRO N ALEM", kmReal: null, kmConv: 28 },
  { origen: "SAN LUIS", destino: "MATADEROS", kmReal: 782, kmConv: 782 },
  { origen: "MORON", destino: "TAPIALES", kmReal: 15, kmConv: 15 },
  { origen: "FRANCK", destino: "9 DE ABRIL", kmReal: 487, kmConv: 487 },
  { origen: "VILLA MERCEDES", destino: "TIGRE", kmReal: 727, kmConv: 727 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "RANELAGH", kmReal: null, kmConv: 69 },
  { origen: "MAGDALENA", destino: "ZARATE", kmReal: 194, kmConv: 194 },
  { origen: "ENSENADA", destino: "MUNRO", kmReal: 78, kmConv: 78 },
  { origen: "MENDOZA", destino: "VILLA MARTELLI", kmReal: 1079, kmConv: 1079 },
  { origen: "SAN FRANCISCO", destino: "ENSENADA", kmReal: 621, kmConv: 621 },
  { origen: "PORTE&#209;A", destino: "MAGDALENA", kmReal: 713, kmConv: 713 },
  { origen: "LA PLATA", destino: "ESPERANZA", kmReal: 561, kmConv: 561 },
  { origen: "9 DE ABRIL", destino: "ROSARIO", kmReal: 310, kmConv: 310 },
  { origen: "RECREO", destino: "SAN LUIS", kmReal: 669, kmConv: 669 },
  { origen: "ITUZAINGO", destino: "BARRACAS", kmReal: null, kmConv: 35 },
  { origen: "VILLA SOLDATI", destino: "SALTO", kmReal: 182, kmConv: 180 },
  { origen: "FRANCK", destino: "MENDOZA", kmReal: 884, kmConv: 885 },
  { origen: "LINIERS", destino: "VILLA SOLDATI", kmReal: null, kmConv: 9 },
  { origen: "SANTO TOME", destino: "FREYRE", kmReal: 163, kmConv: 163 },
  { origen: "PILAR", destino: "ITUZAINGO", kmReal: null, kmConv: 42 },
  { origen: "LINIERS", destino: "LANUS", kmReal: 18, kmConv: 18 },
  { origen: "VILLA DEL PARQUE", destino: "LINIERS", kmReal: 7, kmConv: 7 },
  { origen: "VILLA MERCEDES", destino: "LUJAN", kmReal: 630, kmConv: 630 },
  { origen: "ZARATE", destino: "GENERAL RODRIGUEZ", kmReal: 70, kmConv: 70 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN MIGUEL", kmReal: 36, kmConv: 36 },
  { origen: "PORTE&#209;A", destino: "BERAZATEGUI", kmReal: 639, kmConv: 639 },
  { origen: "CORONEL SUAREZ", destino: "VILLA SOLDATI", kmReal: 535, kmConv: 535 },
  { origen: "FREYRE", destino: "GENERAL RODRIGUEZ", kmReal: 589, kmConv: 589 },
  { origen: "GENERAL PACHECO", destino: "PABLO NOGUES", kmReal: 10, kmConv: 10 },
  { origen: "EZEIZA", destino: "FATIMA", kmReal: 90, kmConv: 90 },
  { origen: "MAR DEL PLATA", destino: "DOCK SUD", kmReal: 408, kmConv: 408 },
  { origen: "SARANDI", destino: "MAR DEL PLATA", kmReal: 406, kmConv: 406 },
  { origen: "CRESPO", destino: "SAN FRANCISCO", kmReal: 209, kmConv: 209 },
  { origen: "CRESPO", destino: "CONCORDIA", kmReal: 251, kmConv: 251 },
  { origen: "CHACARITA", destino: "CORDOBA", kmReal: 690, kmConv: 690 },
  { origen: "VILLA SOLDATI", destino: "CHACARITA", kmReal: 10, kmConv: 10 },
  { origen: "SARANDI", destino: "DESVIO ARIJON", kmReal: 451, kmConv: 451 },
  { origen: "PORTE&#209;A", destino: "BARRACAS", kmReal: 615, kmConv: 615 },
  { origen: "JOSE LEON SUAREZ", destino: "EZEIZA", kmReal: null, kmConv: 46 },
  { origen: "DOCK SUD", destino: "CRESPO", kmReal: 456, kmConv: 456 },
  { origen: "SAN FRANCISCO", destino: "CORONEL SUAREZ", kmReal: 811, kmConv: 811 },
  { origen: "CORDOBA", destino: "CRESPO", kmReal: 421, kmConv: 421 },
  { origen: "ALSINA", destino: "VILLA SOLDATI", kmReal: 140, kmConv: 140 },
  { origen: "SAN PEDRO", destino: "CAMPANA", kmReal: 95, kmConv: 95 },
  { origen: "FRANCK", destino: "CIUDADELA", kmReal: 471, kmConv: 471 },
  { origen: "VILLA CONSTITUCION", destino: "SAN FRANCISCO", kmReal: 322, kmConv: 322 },
  { origen: "CAMPANA", destino: "VILLA CONSTITUCION", kmReal: 180, kmConv: 180 },
  { origen: "CAPITAN CORTEZ", destino: "ARROYITO", kmReal: 656, kmConv: 656 },
  { origen: "LAS HERAS", destino: "ESTEBAN ECHEVERRIA", kmReal: 1068, kmConv: 1068 },
  { origen: "MAR DEL PLATA", destino: "BARADERO", kmReal: 564, kmConv: 564 },
  { origen: "SAN FRANCISCO", destino: "JUNIN", kmReal: 470, kmConv: 470 },
  { origen: "MUNRO", destino: "ZONA PORTUARIA", kmReal: null, kmConv: 18 },
  { origen: "RECREO", destino: "BARRACAS", kmReal: 488, kmConv: 488 },
  { origen: "BARRACAS", destino: "BERAZATEGUI", kmReal: null, kmConv: 30 },
  { origen: "SAN JUAN", destino: "SAN FRANCISCO", kmReal: 802, kmConv: 802 },
  { origen: "TRES ARROYOS", destino: "9 DE ABRIL", kmReal: 480, kmConv: 480 },
  { origen: "MONTE GRANDE", destino: "CIUDADELA", kmReal: null, kmConv: 33 },
  { origen: "TAPIALES", destino: "TRES ARROYOS", kmReal: 480, kmConv: 480 },
  { origen: "TAPIALES", destino: "BAHIA BLANCA", kmReal: 620, kmConv: 620 },
  { origen: "BERISSO", destino: "QUILMES", kmReal: 45, kmConv: 45 },
  { origen: "SAN LUIS", destino: "ZONA PORTUARIA", kmReal: 802, kmConv: 802 },
  { origen: "GONZALEZ CATAN", destino: "DOCK SUD", kmReal: null, kmConv: 39 },
  { origen: "WILDE", destino: "SAUCE VIEJO", kmReal: 458, kmConv: 458 },
  { origen: "DOCK SUD", destino: "WILDE", kmReal: null, kmConv: 8 },
  { origen: "MORON", destino: "CAMPANA", kmReal: 90, kmConv: 90 },
  { origen: "SAN FRANCISCO", destino: "RECREO", kmReal: 155, kmConv: 155 },
  { origen: "SARANDI", destino: "TIO PUJIO", kmReal: 591, kmConv: 591 },
  { origen: "LA PATERNAL", destino: "MORON", kmReal: 20, kmConv: 20 },
  { origen: "BARRACAS", destino: "HURLINGHAM", kmReal: null, kmConv: 33 },
  { origen: "MENDOZA", destino: "BARRACAS", kmReal: 1053, kmConv: 1053 },
  { origen: "EZPELETA", destino: "VILLA SOLDATI", kmReal: 40, kmConv: 40 },
  { origen: "LAFERRERE", destino: "GONZALEZ CATAN", kmReal: null, kmConv: 7 },
  { origen: "FRANCK", destino: "LANUS", kmReal: 488, kmConv: 488 },
  { origen: "AVELLANEDA", destino: "EZPELETA", kmReal: 35, kmConv: 35 },
  { origen: "VILLA SOLDATI", destino: "LUIS GUILLON", kmReal: 20, kmConv: 20 },
  { origen: "VILLA DEVOTO", destino: "VILLA SOLDATI", kmReal: null, kmConv: 14 },
  { origen: "PUERTO PIRAY", destino: "VILLA DEVOTO", kmReal: 1165, kmConv: 1165 },
  { origen: "GENERAL RODRIGUEZ", destino: "DOCK SUD", kmReal: null, kmConv: 62 },
  { origen: "JUNIN", destino: "FATIMA", kmReal: 220, kmConv: 220 },
  { origen: "GENERAL PACHECO", destino: "LUIS GUILLON", kmReal: null, kmConv: 55 },
  { origen: "FLORENCIO VARELA", destino: "BERAZATEGUI", kmReal: null, kmConv: 8 },
  { origen: "CONCORDIA", destino: "FLORENCIO VARELA", kmReal: 456, kmConv: 456 },
  { origen: "CONCORDIA", destino: "BERAZATEGUI", kmReal: 456, kmConv: 456 },
  { origen: "MONTE GRANDE", destino: "MUNRO", kmReal: null, kmConv: 47 },
  { origen: "FRANCK", destino: "POSADAS", kmReal: 819, kmConv: 819 },
  { origen: "BARRACAS", destino: "9 DE ABRIL", kmReal: null, kmConv: 19 },
  { origen: "ZONA PORTUARIA", destino: "SAN LUIS", kmReal: 833, kmConv: 833 },
  { origen: "SARANDI", destino: "INGENIERO LUIGGI", kmReal: 647, kmConv: 647 },
  { origen: "WENCESLAO ESCALANTE", destino: "RIO CUARTO", kmReal: 160, kmConv: 160 },
  { origen: "GUALEGUAY", destino: "WENCESLAO ESCALANTE", kmReal: 445, kmConv: 445 },
  { origen: "PUERTO ESPERANZA", destino: "WILDE", kmReal: 1242, kmConv: 1242 },
  { origen: "GOBERNADOR VIRASORO", destino: "PUERTO ESPERANZA", kmReal: 319, kmConv: 319 },
  { origen: "DOCK SUD", destino: "MENDOZA", kmReal: 1050, kmConv: 1050 },
  { origen: "ALSINA", destino: "ZARATE", kmReal: null, kmConv: 50 },
  { origen: "ALSINA", destino: "ZONA PORTUARIA", kmReal: 134, kmConv: 134 },
  { origen: "VILLA SOLDATI", destino: "SAN MARTIN", kmReal: 17, kmConv: 15 },
  { origen: "ZARATE", destino: "VICENTE LOPEZ", kmReal: 80, kmConv: 80 },
  { origen: "MENDOZA", destino: "ESTEBAN ECHEVERRIA", kmReal: 1070, kmConv: 1070 },
  { origen: "PUERTO PIRAY", destino: "GENERAL RODRIGUEZ", kmReal: 1151, kmConv: 1151 },
  { origen: "SAN MIGUEL", destino: "PUERTO PIRAY", kmReal: 396, kmConv: 396 },
  { origen: "CAPITAN CORTEZ", destino: "ZARATE", kmReal: null, kmConv: 94 },
  { origen: "VILLA SOLDATI", destino: "SAN MIGUEL", kmReal: 954, kmConv: 954 },
  { origen: "FRANCK", destino: "MAR DEL PLATA", kmReal: 889, kmConv: 889 },
  { origen: "BANFIELD", destino: "BOSQUES", kmReal: null, kmConv: 23 },
  { origen: "RECREO", destino: "RIO CUARTO", kmReal: 448, kmConv: 448 },
  { origen: "SAN JUSTO", destino: "PABLO NOGUES", kmReal: null, kmConv: 41 },
  { origen: "FRANCK", destino: "CONCORDIA", kmReal: 329, kmConv: 329 },
  { origen: "SAUCE VIEJO", destino: "ROSARIO", kmReal: 149, kmConv: 149 },
  { origen: "FRANCK", destino: "PUERTO ESPERANZA", kmReal: 1044, kmConv: 1044 },
  { origen: "GENERAL RODRIGUEZ", destino: "FRANCK", kmReal: 452, kmConv: 452 },
  { origen: "JOSE C. PAZ", destino: "ZARATE", kmReal: null, kmConv: 69 },
  { origen: "GENERAL RODRIGUEZ", destino: "EZEIZA", kmReal: null, kmConv: 71 },
  { origen: "COLONIA", destino: "BARADERO", kmReal: 420, kmConv: 420 },
  { origen: "SAN JUAN", destino: "ZARATE", kmReal: 1095, kmConv: 1095 },
  { origen: "VILLA URQUIZA", destino: "DOCK SUD", kmReal: null, kmConv: 31 },
  { origen: "RIO CUARTO", destino: "PILAR", kmReal: 555, kmConv: 555 },
  { origen: "CONCORDIA", destino: "AVELLANEDA", kmReal: 436, kmConv: 436 },
  { origen: "MENDOZA", destino: "JOSE C. PAZ", kmReal: 1015, kmConv: 1015 },
  { origen: "SAN JORGE", destino: "CARLOS PAZ", kmReal: 310, kmConv: 310 },
  { origen: "SANTA ANA", destino: "ESCOBAR", kmReal: 969, kmConv: 969 },
  { origen: "GENERAL RODRIGUEZ", destino: "VILLA MERCEDES", kmReal: 645, kmConv: 645 },
  { origen: "VILLA TESEI", destino: "GENERAL RODRIGUEZ", kmReal: null, kmConv: 32 },
  { origen: "VIRREY DEL PINO", destino: "MERLO", kmReal: null, kmConv: 29 },
  { origen: "VILLA SOLDATI", destino: "VIRREY DEL PINO", kmReal: 42, kmConv: 42 },
  { origen: "ESPERANZA", destino: "COLONIA", kmReal: 565, kmConv: 565 },
  { origen: "SUSANA", destino: "PORTE&#209;A", kmReal: null, kmConv: 85 },
  { origen: "ESPERANZA", destino: "MONTEVIDEO", kmReal: 700, kmConv: 700 },
  { origen: "BRAGADO", destino: "BERAZATEGUI", kmReal: 243, kmConv: 243 },
  { origen: "EZEIZA", destino: "TEMPERLEY", kmReal: 18, kmConv: 18 },
  { origen: "CHACABUCO", destino: "BRAGADO", kmReal: null, kmConv: 59 },
  { origen: "CHACABUCO", destino: "9 DE ABRIL", kmReal: 212, kmConv: 212 },
  { origen: "ITUZAINGO", destino: "PABLO NOGUES", kmReal: 39, kmConv: 39 },
  { origen: "LA FALDA", destino: "SAN FRANCISCO", kmReal: 285, kmConv: 285 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "APÓSTOLES", kmReal: 656, kmConv: 656 },
  { origen: "LA MENDIETA", destino: "SAN FRANCISCO", kmReal: 974, kmConv: 974 },
  { origen: "CHACABUCO", destino: "GENERAL PACHECO", kmReal: 209, kmConv: 209 },
  { origen: "BERNAL OESTE", destino: "GENERAL PACHECO", kmReal: null, kmConv: 55 },
  { origen: "BARRACAS", destino: "ZONA PORTUARIA", kmReal: null, kmConv: 10 },
  { origen: "JUNIN", destino: "ALVEAR", kmReal: 214, kmConv: 215 },
  { origen: "SAN FRANCISCO", destino: "CHACABUCO", kmReal: 499, kmConv: 499 },
  { origen: "ROSARIO", destino: "9 DE ABRIL", kmReal: 312, kmConv: 312 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "LA MENDIETA", kmReal: null, kmConv: 64 },
  { origen: "JUNIN", destino: "MORENO", kmReal: 227, kmConv: 227 },
  { origen: "MALVINAS ARGENTINAS", destino: "RETIRO", kmReal: null, kmConv: 37 },
  { origen: "NUEVA POMPEYA", destino: "VILLA SOLDATI", kmReal: null, kmConv: 2 },
  { origen: "MUNRO", destino: "DON TORCUATO", kmReal: null, kmConv: 16 },
  { origen: "BENITO JUAREZ", destino: "MALVINAS ARGENTINAS", kmReal: 434, kmConv: 435 },
  { origen: "BAHIA BLANCA", destino: "BENITO JUAREZ", kmReal: 290, kmConv: 290 },
  { origen: "PILAR", destino: "GENERAL PACHECO", kmReal: null, kmConv: 30 },
  { origen: "MERLO", destino: "SAN JUSTO", kmReal: null, kmConv: 18 },
  { origen: "SAN PEDRO", destino: "MERLO", kmReal: 175, kmConv: 175 },
  { origen: "ALVEAR", destino: "COLONIA CAROYA", kmReal: 460, kmConv: 460 },
  { origen: "LAVALLOL", destino: "ZARATE", kmReal: 109, kmConv: 109 },
  { origen: "SAN JOSE", destino: "VILLA SOLDATI", kmReal: 514, kmConv: 515 },
  { origen: "VILLA DOMINICO", destino: "9 DE ABRIL", kmReal: null, kmConv: 34 },
  { origen: "TORTUGUITAS", destino: "LAVALLOL", kmReal: null, kmConv: 62 },
  { origen: "CASEROS", destino: "MENDOZA", kmReal: 1029, kmConv: 1029 },
  { origen: "QUILMES", destino: "CASEROS", kmReal: null, kmConv: 40 },
  { origen: "SAUCE VIEJO", destino: "ALVEAR", kmReal: 164, kmConv: 165 },
  { origen: "LOMA HERMOSA", destino: "SAN FRANCISCO", kmReal: 546, kmConv: 545 },
  { origen: "MENDOZA", destino: "VILLA DOMINICO", kmReal: 1060, kmConv: 1060 },
  { origen: "SAUCE VIEJO", destino: "FRANCK", kmReal: null, kmConv: 36 },
  { origen: "FRANCK", destino: "SALTA", kmReal: 1021, kmConv: 1020 },
  { origen: "TIO PUJIO", destino: "ESTEBAN ECHEVERRIA", kmReal: 600, kmConv: 600 },
  { origen: "CORDOBA", destino: "INGENIERO LUIGGI", kmReal: 602, kmConv: 600 },
  { origen: "HURLINGHAM", destino: "GENERAL PACHECO", kmReal: 28, kmConv: 28 },
  { origen: "ESCOBAR", destino: "MALVINAS ARGENTINAS", kmReal: null, kmConv: 32 },
  { origen: "GARIN", destino: "HURLINGHAM", kmReal: null, kmConv: 32 },
  { origen: "AVELLANEDA", destino: "RIO CUARTO", kmReal: 674, kmConv: 675 },
  { origen: "CIUDADELA", destino: "TAPIALES", kmReal: 10, kmConv: 10 },
  { origen: "CAMPANA", destino: "SUNCHALES", kmReal: 505, kmConv: 505 },
  { origen: "LA MATANZA", destino: "BERAZATEGUI", kmReal: null, kmConv: 60 },
  { origen: "VILLA MARIA", destino: "VENADO TUERTO", kmReal: 259, kmConv: 260 },
  { origen: "SALTO", destino: "POSADAS", kmReal: 1061, kmConv: 1060 },
  { origen: "PERGAMINO", destino: "SALTO", kmReal: null, kmConv: 55 },
  { origen: "VILLA TESEI", destino: "GENERAL PACHECO", kmReal: 28, kmConv: 30 },
  { origen: "GENERAL PACHECO", destino: "SANTO TOME", kmReal: 424, kmConv: 425 },
  { origen: "PEREZ", destino: "ROSARIO", kmReal: null, kmConv: 9 },
  { origen: "ZARATE", destino: "LOMA HERMOSA", kmReal: 80, kmConv: 80 },
  { origen: "FRANCK", destino: "MORENO", kmReal: 477, kmConv: 475 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "TORTUGUITAS", kmReal: 265, kmConv: 265 },
  { origen: "ZONA PORTUARIA", destino: "INGENIERO LUIGGI", kmReal: 646, kmConv: 645 },
  { origen: "LONGCHAMPS", destino: "GENERAL PACHECO", kmReal: 65, kmConv: 65 },
  { origen: "GENERAL RODRIGUEZ", destino: "GENERAL PACHECO", kmReal: 55, kmConv: 55 },
  { origen: "EZEIZA", destino: "GENERAL PACHECO", kmReal: 61, kmConv: 60 },
  { origen: "DON TORCUATO", destino: "MATADEROS", kmReal: 32, kmConv: 30 },
  { origen: "MENDOZA", destino: "ESPERANZA", kmReal: 904, kmConv: 905 },
  { origen: "VILLA SOLDATI", destino: "ISIDRO CASANOVA", kmReal: 20, kmConv: 20 },
  { origen: "CARLOS SPEGAZZINI", destino: "MUNRO", kmReal: 60, kmConv: 60 },
  { origen: "ALVEAR", destino: "DON TORCUATO", kmReal: 259, kmConv: 260 },
  { origen: "MATADEROS", destino: "MORENO", kmReal: 30, kmConv: 30 },
  { origen: "CORRAL DE BUSTOS", destino: "ALVEAR", kmReal: 205, kmConv: 205 },
  { origen: "MARCOS JUAREZ", destino: "CORRAL DE BUSTOS", kmReal: 85, kmConv: 85 },
  { origen: "CORDOBA", destino: "MARCOS JUAREZ", kmReal: 265, kmConv: 265 },
  { origen: "RAFAELA", destino: "BARRACAS", kmReal: 546, kmConv: 545 },
  { origen: "ISIDRO CASANOVA", destino: "CORDOBA", kmReal: 705, kmConv: 705 },
  { origen: "EZEIZA", destino: "ISIDRO CASANOVA", kmReal: 25, kmConv: 25 },
  { origen: "DOCK SUD", destino: "EZEIZA", kmReal: 40, kmConv: 40 },
  { origen: "ZONA PORTUARIA", destino: "MATADEROS", kmReal: 20, kmConv: 20 },
  { origen: "CARLOS PAZ", destino: "LA FALDA", kmReal: 50, kmConv: 50 },
  { origen: "RECREO", destino: "MAR DEL PLATA", kmReal: 897, kmConv: 895 },
  { origen: "TUCUMAN", destino: "CONCORDIA", kmReal: 1071, kmConv: 1070 },
  { origen: "QUILMES", destino: "MENDOZA", kmReal: 1066, kmConv: 1065 },
  { origen: "HURLINGHAM", destino: "QUILMES", kmReal: 48, kmConv: 50 },
  { origen: "GENERAL PACHECO", destino: "SAUCE VIEJO", kmReal: 412, kmConv: 410 },
  { origen: "LA PLATA", destino: "GENERAL PACHECO", kmReal: 95, kmConv: 95 },
  { origen: "RECREO", destino: "VIRREY DEL PINO", kmReal: 521, kmConv: 520 },
  { origen: "VALENTIN ALSINA", destino: "VILLA SOLDATI", kmReal: 5, kmConv: 5 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "GENERAL PACHECO", kmReal: 64, kmConv: 65 },
  { origen: "GENERAL JUAN MADARIAGA", destino: "TORTUGUITAS", kmReal: 374, kmConv: 375 },
  { origen: "BERAZATEGUI", destino: "APÓSTOLES", kmReal: 977, kmConv: 975 },
  { origen: "SAN FRANCISCO", destino: "GENERAL JUAN MADARIAGA", kmReal: 891, kmConv: 890 },
  { origen: "MONTE GRANDE", destino: "BERAZATEGUI", kmReal: 29, kmConv: 30 },
  { origen: "CIUDADELA", destino: "9 DE ABRIL", kmReal: 18, kmConv: 20 },
  { origen: "CORRAL DE BUSTOS", destino: "SAN JORGE", kmReal: 211, kmConv: 210 },
  { origen: "MUNRO", destino: "CIUDADELA", kmReal: 15, kmConv: 15 },
  { origen: "TUCUMAN", destino: "JUJUY", kmReal: 334, kmConv: 335 },
  { origen: "VILLA FIORITO", destino: "BERAZATEGUI", kmReal: 45, kmConv: 45 },
  { origen: "VILLA URQUIZA", destino: "PABLO NOGUES", kmReal: 26, kmConv: 25 },
  { origen: "ISIDRO CASANOVA", destino: "MORON", kmReal: 8, kmConv: 10 },
  { origen: "MORENO", destino: "VILLA NUEVA", kmReal: 555, kmConv: 555 },
  { origen: "ARROYITO", destino: "TUCUMAN", kmReal: 668, kmConv: 670 },
  { origen: "MENDOZA", destino: "VILLA FIORITO", kmReal: 1046, kmConv: 1045 },
  { origen: "PUERTO BOSSETTI", destino: "PILAR", kmReal: 1206, kmConv: 1205 },
  { origen: "RESISTENCIA", destino: "PUERTO BOSSETTI", kmReal: 597, kmConv: 595 },
  { origen: "GENERAL LAS HERAS", destino: "ZARATE", kmReal: 106, kmConv: 105 },
  { origen: "RECREO", destino: "GENERAL LAS HERAS", kmReal: 497, kmConv: 495 },
  { origen: "RIO CUARTO", destino: "CAPILLA DEL MONTE", kmReal: 294, kmConv: 295 },
  { origen: "HURLINGHAM", destino: "SAN JUSTO", kmReal: 16, kmConv: 15 },
  { origen: "RECREO", destino: "LAS HERAS", kmReal: 931, kmConv: 930 },
  { origen: "RAFAELA", destino: "MUNRO", kmReal: 524, kmConv: 524 },
  { origen: "VILLA MERCEDES", destino: "LANUS", kmReal: 700, kmConv: 700 },
  { origen: "LONGCHAMPS", destino: "RANELAGH", kmReal: 26, kmConv: 25 },
  { origen: "SAN CARLOS", destino: "RAFAELA", kmReal: 85, kmConv: 85 },
  { origen: "CORDOBA", destino: "SANFORD", kmReal: 257, kmConv: 257 },
  { origen: "EZEIZA", destino: "MUNRO", kmReal: 44, kmConv: 45 },
  { origen: "CONCORDIA", destino: "ZARATE", kmReal: 345, kmConv: 345 },
  { origen: "MORENO", destino: "ARROYITO", kmReal: 658, kmConv: 660 },
  { origen: "CARLOS SPEGAZZINI", destino: "MORENO", kmReal: 43, kmConv: 45 },
  { origen: "VILLA MERCEDES", destino: "SAN CARLOS", kmReal: 529, kmConv: 530 },
  { origen: "BERAZATEGUI", destino: "BARRACAS", kmReal: 31, kmConv: 30 },
  { origen: "VILLA MARIA", destino: "PERGAMINO", kmReal: 335, kmConv: 335 },
  { origen: "SANTOS LUGARES", destino: "TORTUGUITAS", kmReal: 33, kmConv: 35 },
  { origen: "LLAVALLOL", destino: "CORDOBA", kmReal: 715, kmConv: 715 },
  { origen: "ESPERANZA", destino: "VIRREY DEL PINO", kmReal: 531, kmConv: 530 },
  { origen: "QUILMES", destino: "MUNRO", kmReal: 40, kmConv: 40 },
  { origen: "SINSACATE", destino: "SAN FRANCISCO", kmReal: 274, kmConv: 275 },
  { origen: "SAN JUSTO", destino: "WILDE", kmReal: 38, kmConv: 40 },
  { origen: "CANDELARIA", destino: "COL SANTA ROSA", kmReal: 284, kmConv: 285 },
  { origen: "PUERTO ESPERANZA", destino: "SINSACATE", kmReal: 1520, kmConv: 1520 },
  { origen: "CHACARITA", destino: "9 DE ABRIL", kmReal: 24, kmConv: 25 },
  { origen: "VILLA MERCEDES", destino: "GENERAL RODRIGUEZ", kmReal: 646, kmConv: 645 },
  { origen: "MONTE GRANDE", destino: "LA PLATA", kmReal: 62, kmConv: 60 },
  { origen: "RECONQUISTA", destino: "POSADAS", kmReal: 561, kmConv: 560 },
  { origen: "MENDOZA", destino: "RECONQUISTA", kmReal: 1228, kmConv: 1230 },
  { origen: "SAN MARTIN", destino: "MENDOZA", kmReal: 44, kmConv: 45 },
  { origen: "JOSE INGENIEROS", destino: "TORTUGUITAS", kmReal: 38, kmConv: 40 },
  { origen: "PUERTO MADRYN", destino: "DOCK SUD", kmReal: 1302, kmConv: 1300 },
  { origen: "FRANCK", destino: "OBERA", kmReal: 849, kmConv: 850 },
  { origen: "FRANCK", destino: "SAN MARTIN", kmReal: 842, kmConv: 840 },
  { origen: "CAMPANA", destino: "MERCEDES", kmReal: 87, kmConv: 85 },
  { origen: "VILLA MERCEDES", destino: "MUNRO", kmReal: 726, kmConv: 725 },
  { origen: "GOBERNADOR VIRASORO", destino: "MUNRO", kmReal: 891, kmConv: 890 },
  { origen: "MORENO", destino: "MERLO", kmReal: 7, kmConv: 5 },
  { origen: "LAS VARILLAS", destino: "LA FRANCIA", kmReal: 58, kmConv: 60 },
  { origen: "CIPOLLETTI", destino: "GUAYMALLEN", kmReal: 784, kmConv: 785 },
  { origen: "WILDE", destino: "MENDOZA", kmReal: 1060, kmConv: 1060 },
  { origen: "MERCEDES", destino: "WILDE", kmReal: 117, kmConv: 115 },
  { origen: "RIO CUARTO", destino: "BRINKMANN", kmReal: 356, kmConv: 355 },
  { origen: "GUALEGUAY", destino: "RIO CUARTO", kmReal: 570, kmConv: 570 },
  { origen: "MONTE GRANDE", destino: "ZONA PORTUARIA", kmReal: 45, kmConv: 45 },
  { origen: "MORENO", destino: "PABLO NOGUES", kmReal: 25, kmConv: 25 },
  { origen: "BAHIA BLANCA", destino: "DOCK SUD", kmReal: 677, kmConv: 675 },
  { origen: "SARANDI", destino: "BAHIA BLANCA", kmReal: 684, kmConv: 685 },
  { origen: "JUSTINIANO POSSE", destino: "SAN FRANCISCO", kmReal: 201, kmConv: 200 },
  { origen: "SAN FRANCISCO", destino: "JUSTINIANO POSSE", kmReal: 201, kmConv: 200 },
  { origen: "SAN MARTIN", destino: "CAMPANA", kmReal: 89, kmConv: 90 },
  { origen: "GUAYMALLEN", destino: "HURLINGHAM", kmReal: 1156, kmConv: 1155 },
  { origen: "MENDOZA", destino: "GUAYMALLEN", kmReal: 5, kmConv: 5 },
  { origen: "DOCK SUD", destino: "APÓSTOLES", kmReal: 947, kmConv: 945 },
  { origen: "BARRACAS", destino: "TRES ARROYOS", kmReal: 522, kmConv: 520 },
  { origen: "TRES ARROYOS", destino: "ZONA PORTUARIA", kmReal: 529, kmConv: 530 },
  { origen: "DOCK SUD", destino: "TRES ARROYOS", kmReal: 518, kmConv: 520 },
  { origen: "TICINO", destino: "ZONA PORTUARIA", kmReal: 608, kmConv: 610 },
  { origen: "VILLA SOLDATI", destino: "TICINO", kmReal: 597, kmConv: 595 },
  { origen: "CORDOBA", destino: "MARCOS PAZ", kmReal: 709, kmConv: 710 },
  { origen: "RIO CUARTO", destino: "BARADERO", kmReal: 521, kmConv: 520 },
  { origen: "ROSARIO", destino: "RETIRO", kmReal: 351, kmConv: 350 },
  { origen: "FRANCK", destino: "GENERAL RODRIGUEZ", kmReal: 453, kmConv: 455 },
  { origen: "JOSE C. PAZ", destino: "ITUZAINGO", kmReal: 24, kmConv: 25 },
  { origen: "VILLA MERCEDES", destino: "RECREO", kmReal: 579, kmConv: 580 },
  { origen: "ZARATE", destino: "LAS VARILLAS", kmReal: 500, kmConv: 500 },
  { origen: "PABLO NOGUES", destino: "ESPERANZA", kmReal: 461, kmConv: 460 },
  { origen: "QUILMES", destino: "9 DE ABRIL", kmReal: 41, kmConv: 40 },
  { origen: "PUERTO PIRAY", destino: "RIO TERCERO", kmReal: 1343, kmConv: 1345 },
  { origen: "ROSARIO", destino: "GALVEZ", kmReal: 133, kmConv: 135 },
  { origen: "LUJAN DE CUYO", destino: "9 DE ABRIL", kmReal: 1061, kmConv: 1060 },
  { origen: "BERAZATEGUI", destino: "ESPERANZA", kmReal: 532, kmConv: 530 },
  { origen: "SAN JAVIER", destino: "POSADAS", kmReal: 128, kmConv: 130 },
  { origen: "LAS HERAS", destino: "9 DE ABRIL", kmReal: 1054, kmConv: 1055 },
  { origen: "PUERTO PIRAY", destino: "QUILMES", kmReal: 1196, kmConv: 1195 },
  { origen: "COLONIA", destino: "CAMPANA", kmReal: 425, kmConv: 425 },
  { origen: "PABLO NOGUES", destino: "BARRACAS", kmReal: 52, kmConv: 55 },
  { origen: "DEVOTO", destino: "GENERAL RODRIGUEZ", kmReal: 564, kmConv: 565 },
  { origen: "MUNRO", destino: "ESCOBAR", kmReal: 39, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "GOBERNADOR CRESPO", kmReal: 622, kmConv: 620 },
  { origen: "LA PLATA", destino: "RANELAGH", kmReal: 33, kmConv: 35 },
  { origen: "SAN FRANCISCO", destino: "COLONIA", kmReal: 660, kmConv: 661 },
  { origen: "PORTE&#209;A", destino: "GENERAL PACHECO", kmReal: 578, kmConv: 580 },
  { origen: "SAUCE VIEJO", destino: "BERAZATEGUI", kmReal: 474, kmConv: 475 },
  { origen: "ZONA PORTUARIA", destino: "SAUCE VIEJO", kmReal: 443, kmConv: 445 },
  { origen: "LINCOL", destino: "CHACARITA", kmReal: 320, kmConv: 320 },
  { origen: "FREYRE", destino: "LINCOL", kmReal: 503, kmConv: 505 },
  { origen: "MORENO", destino: "ITUZAINGO", kmReal: 25, kmConv: 25 },
  { origen: "SAUCE VIEJO", destino: "PORTE&#209;A", kmReal: 369, kmConv: 370 },
  { origen: "BENAVIDEZ", destino: "MATADEROS", kmReal: 45, kmConv: 45 },
  { origen: "ZONA PORTUARIA", destino: "BENAVIDEZ", kmReal: 42, kmConv: 40 },
  { origen: "APÓSTOLES", destino: "PUERTO ESPERANZA", kmReal: 294, kmConv: 295 },
  { origen: "LAS HERAS", destino: "BENAVIDEZ", kmReal: 1066, kmConv: 1065 },
  { origen: "SAN FRANCISCO", destino: "SAN FERNANDO", kmReal: 546, kmConv: 545 },
  { origen: "LAS HERAS", destino: "SAUCE VIEJO", kmReal: 914, kmConv: 915 },
  { origen: "GUALEGUAY", destino: "SANTIAGO DEL ESTERO", kmReal: 911, kmConv: 910 },
  { origen: "DOCK SUD", destino: "BENAVIDEZ", kmReal: 51, kmConv: 50 },
  { origen: "MORENO", destino: "LAVALLOL", kmReal: 49, kmConv: 50 },
  { origen: "TUCUMAN", destino: "MONTEROS", kmReal: 63, kmConv: 65 },
  { origen: "BERAZATEGUI", destino: "SAN RAFAEL", kmReal: 1009, kmConv: 1010 },
  { origen: "CORDOBA", destino: "ESCOBAR", kmReal: 644, kmConv: 645 },
  { origen: "MONTEROS", destino: "RAFAELA", kmReal: 680, kmConv: 680 },
  { origen: "BARADERO", destino: "CARLOS PAZ", kmReal: 594, kmConv: 595 },
  { origen: "BERAZATEGUI", destino: "EZEIZA", kmReal: 64, kmConv: 65 },
  { origen: "MONTE VERA", destino: "FREYRE", kmReal: 188, kmConv: 190 },
  { origen: "CAMPANA", destino: "LA PLATA", kmReal: 135, kmConv: 135 },
  { origen: "DON TORCUATO", destino: "NUEVA POMPEYA", kmReal: 40, kmConv: 40 },
  { origen: "EZEIZA", destino: "LA PLATA", kmReal: 80, kmConv: 80 },
  { origen: "RECREO", destino: "GALVEZ", kmReal: 103, kmConv: 105 },
  { origen: "JOSE LEON SUAREZ", destino: "SAN MIGUEL", kmReal: 929, kmConv: 930 },
  { origen: "BARADERO", destino: "SAN NICOLAS", kmReal: 101, kmConv: 100 },
  { origen: "SAN FRANCISCO", destino: "LONGCHAMPS", kmReal: 591, kmConv: 590 },
  { origen: "ESCOBAR", destino: "MERCEDES", kmReal: 93, kmConv: 95 },
  { origen: "VILLA URQUIZA", destino: "LA PLATA", kmReal: 80, kmConv: 80 },
  { origen: "MONTE VERA", destino: "RECREO", kmReal: 7, kmConv: 5 },
  { origen: "VILLA TESEI", destino: "QUILMES", kmReal: 47, kmConv: 45 },
  { origen: "DESVIO ARIJON", destino: "ZARATE", kmReal: 348, kmConv: 350 },
  { origen: "ZARATE", destino: "DESVIO ARIJON", kmReal: 348, kmConv: 350 },
  { origen: "SAN JUSTO", destino: "QUILMES", kmReal: 45, kmConv: 45 },
  { origen: "EZEIZA", destino: "QUILMES", kmReal: 55, kmConv: 55 },
  { origen: "MONTE VERA", destino: "SUSANA", kmReal: 125, kmConv: 125 },
  { origen: "LONGCHAMPS", destino: "LA PLATA", kmReal: 65, kmConv: 65 },
  { origen: "MONTEVIDEO", destino: "FATIMA", kmReal: 524, kmConv: 524 },
  { origen: "VILLA TESEI", destino: "LA PLATA", kmReal: 80, kmConv: 80 },
  { origen: "TORTUGUITAS", destino: "FREYRE", kmReal: 560, kmConv: 560 },
  { origen: "MORENO", destino: "LA PLATA", kmReal: 95, kmConv: 95 },
  { origen: "LA PLATA", destino: "MONTE VERA", kmReal: 550, kmConv: 550 },
  { origen: "GONZALEZ CATAN", destino: "LA PLATA", kmReal: 95, kmConv: 95 },
  { origen: "JOSE C. PAZ", destino: "GONZALEZ CATAN", kmReal: 55, kmConv: 55 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "ROSARIO", kmReal: 275, kmConv: 275 },
  { origen: "LA PLATA", destino: "SANTA FE", kmReal: 525, kmConv: 525 },
  { origen: "ZARATE", destino: "SAN RAFAEL", kmReal: 940, kmConv: 940 },
  { origen: "ALVEAR", destino: "BRINKMANN", kmReal: 345, kmConv: 345 },
  { origen: "ROSARIO", destino: "ALVEAR", kmReal: 20, kmConv: 20 },
  { origen: "MONTE VERA", destino: "ROSARIO", kmReal: 190, kmConv: 190 },
  { origen: "QUILMES", destino: "MONTE VERA", kmReal: 505, kmConv: 505 },
  { origen: "PARQUE PATRICIOS", destino: "QUILMES", kmReal: 20, kmConv: 20 },
  { origen: "JOSE INGENIEROS", destino: "LOMAS DEL MIRADOR", kmReal: 7, kmConv: 7 },
  { origen: "LA PLATA", destino: "SANTO TOME", kmReal: 515, kmConv: 515 },
  { origen: "TOSTADO", destino: "RAFAELA", kmReal: 265, kmConv: 265 },
  { origen: "SIERRA DE LOS PADRES", destino: "TOSTADO", kmReal: 1194, kmConv: 1195 },
  { origen: "QUILMES", destino: "BERAZATEGUI", kmReal: 5, kmConv: 5 },
  { origen: "ESCOBAR", destino: "QUILMES", kmReal: 85, kmConv: 85 },
  { origen: "DOCK SUD", destino: "BURZACO", kmReal: 30, kmConv: 30 },
  { origen: "FATIMA", destino: "LA FRANCIA", kmReal: 569, kmConv: 570 },
  { origen: "TAPIALES", destino: "TIO PUJIO", kmReal: 580, kmConv: 580 },
  { origen: "PILAR", destino: "LA FRANCIA", kmReal: 577, kmConv: 575 },
  { origen: "ISIDRO CASANOVA", destino: "GENERAL PACHECO", kmReal: 52, kmConv: 50 },
  { origen: "SAN JOSE", destino: "CONCORDIA", kmReal: 109, kmConv: 110 },
  { origen: "SIERRA DE LOS PADRES", destino: "TOTORAS", kmReal: 771, kmConv: 770 },
  { origen: "GENERAL PACHECO", destino: "COLONIA CAROYA", kmReal: 710, kmConv: 710 },
  { origen: "GALVEZ", destino: "SAN JUSTO", kmReal: 432, kmConv: 430 },
  { origen: "SAN FRANCISCO", destino: "SAN JOSE", kmReal: 415, kmConv: 415 },
  { origen: "TRES ARROYOS", destino: "VILLA SOLDATI", kmReal: 488, kmConv: 490 },
  { origen: "CAMPANA", destino: "NUEVA POMPEYA", kmReal: 86, kmConv: 85 },
  { origen: "TIGRE", destino: "TRES ARROYOS", kmReal: 518, kmConv: 520 },
  { origen: "BENAVIDEZ", destino: "TIGRE", kmReal: 14, kmConv: 15 },
  { origen: "VILLA SOLDATI", destino: "VICENTE LOPEZ", kmReal: null, kmConv: 25 },
  { origen: "VILLA SOLDATI", destino: "BENAVIDEZ", kmReal: 48, kmConv: 50 },
  { origen: "LAS HERAS", destino: "VILLA SOLDATI", kmReal: 1046, kmConv: 1045 },
  { origen: "JOSE C. PAZ", destino: "BERAZATEGUI", kmReal: 80, kmConv: 80 },
  { origen: "DOCK SUD", destino: "MATADEROS", kmReal: 20, kmConv: 20 },
  { origen: "OLAVARRIA", destino: "TANDIL", kmReal: 140, kmConv: 140 },
  { origen: "CARMEN DE ARECO", destino: "CAMPANA", kmReal: 105, kmConv: 105 },
  { origen: "BERAZATEGUI", destino: "TIO PUJIO", kmReal: 600, kmConv: 600 },
  { origen: "CAMPANA", destino: "CAPILLA DEL SE&#209;OR", kmReal: 30, kmConv: 30 },
  { origen: "RECREO", destino: "ESPERANZA", kmReal: 21, kmConv: 20 },
  { origen: "MENDOZA", destino: "VICENTE LOPEZ", kmReal: 1045, kmConv: 1045 },
  { origen: "SANTO TOME", destino: "GENERAL RODRIGUEZ", kmReal: 425, kmConv: 425 },
  { origen: "RETIRO", destino: "MORTEROS", kmReal: 650, kmConv: 650 },
  { origen: "PERGAMINO", destino: "TORTUGUITAS", kmReal: 190, kmConv: 190 },
  { origen: "VILLA DEL ROSARIO", destino: "LA FRANCIA", kmReal: 115, kmConv: 115 },
  { origen: "APÓSTOLES", destino: "SARANDI", kmReal: 950, kmConv: 950 },
  { origen: "EZEIZA", destino: "SARANDI", kmReal: 40, kmConv: 40 },
  { origen: "MATADEROS", destino: "VICENTE LOPEZ", kmReal: 19, kmConv: 20 },
  { origen: "MUNRO", destino: "FATIMA", kmReal: 50, kmConv: 50 },
  { origen: "DOCK SUD", destino: "LA FRANCIA", kmReal: 625, kmConv: 625 },
  { origen: "RAFAELA", destino: "DOLORES", kmReal: 755, kmConv: 755 },
  { origen: "MENDOZA", destino: "SAUCE VIEJO", kmReal: 910, kmConv: 910 },
  { origen: "CAPILLA DEL SE&#209;OR", destino: "CORDOBA", kmReal: 630, kmConv: 630 },
  { origen: "SIERRA DE LOS PADRES", destino: "MUNRO", kmReal: 435, kmConv: 435 },
  { origen: "TAPIALES", destino: "COLONIA CAROYA", kmReal: 748, kmConv: 750 },
  { origen: "CORDOBA", destino: "QUILMES", kmReal: 720, kmConv: 720 },
  { origen: "DOCK SUD", destino: "CAPILLA DEL SE&#209;OR", kmReal: 90, kmConv: 90 },
  { origen: "GENERAL JUAN MADARIAGA", destino: "VILLA SOLDATI", kmReal: 370, kmConv: 370 },
  { origen: "NUEVA POMPEYA", destino: "CORDOBA", kmReal: 700, kmConv: 700 },
  { origen: "QUILMES", destino: "MORON", kmReal: 45, kmConv: 45 },
  { origen: "VILLA NUEVA", destino: "RIO CUARTO", kmReal: 132, kmConv: 130 },
  { origen: "ESCOBAR", destino: "VILLA NUEVA", kmReal: 502, kmConv: 505 },
  { origen: "MONTEVIDEO", destino: "ESCOBAR", kmReal: 520, kmConv: 520 },
  { origen: "BERAZATEGUI", destino: "SANTA FE", kmReal: 500, kmConv: 500 },
  { origen: "PILAR", destino: "NUEVA POMPEYA", kmReal: 65, kmConv: 65 },
  { origen: "ROSARIO", destino: "GENERAL JUAN MADARIAGA", kmReal: 630, kmConv: 630 },
  { origen: "RAFAELA", destino: "SARANDI", kmReal: 550, kmConv: 550 },
  { origen: "SAN MARTIN", destino: "MORTEROS", kmReal: 810, kmConv: 810 },
  { origen: "PUERTO MADERO", destino: "BERAZATEGUI", kmReal: 27, kmConv: 27 },
  { origen: "LONGCHAMPS", destino: "MORON", kmReal: 30, kmConv: 30 },
  { origen: "VILLA CRESPO", destino: "AVELLANEDA", kmReal: 13, kmConv: 15 },
  { origen: "MONTE VERA", destino: "SAN FRANCISCO", kmReal: 160, kmConv: 160 },
  { origen: "MONTE VERA", destino: "SANTA FE", kmReal: 10, kmConv: 10 },
  { origen: "BERAZATEGUI", destino: "MONTE VERA", kmReal: 515, kmConv: 515 },
  { origen: "SANTO TOME", destino: "PORTE&#209;A", kmReal: 180, kmConv: 180 },
  { origen: "OLAVARRIA", destino: "TAPIALES", kmReal: 335, kmConv: 335 },
  { origen: "LANUS", destino: "PABLO PODESTA", kmReal: 34, kmConv: 35 },
  { origen: "SAN FRANCISCO", destino: "ARROYO SECO", kmReal: 297, kmConv: 295 },
  { origen: "EZEIZA", destino: "VILLA ALSINA", kmReal: 35, kmConv: 35 },
  { origen: "VILLA LURO", destino: "MATADEROS", kmReal: 5, kmConv: 5 },
  { origen: "ESCOBAR", destino: "RIO CUARTO", kmReal: 580, kmConv: 580 },
  { origen: "PABLO NOGUES", destino: "VILLA LURO", kmReal: 36, kmConv: 35 },
  { origen: "ESCOBAR", destino: "VILLA MARIA", kmReal: 501, kmConv: 500 },
  { origen: "MAR DEL PLATA", destino: "SAN JUSTO", kmReal: 435, kmConv: 435 },
  { origen: "TIGRE", destino: "MORENO", kmReal: 45, kmConv: 45 },
  { origen: "RECREO", destino: "SAN FRANCISCO", kmReal: 155, kmConv: 155 },
  { origen: "SAN FRANCISCO", destino: "SAN NICOLAS", kmReal: 350, kmConv: 350 },
  { origen: "LA CALERA", destino: "SAN FRANCISCO", kmReal: 245, kmConv: 245 },
  { origen: "CHASCOMUS", destino: "MALAGUE&#209;O", kmReal: 845, kmConv: 845 },
  { origen: "LONGCHAMPS", destino: "SAN JUSTO", kmReal: 25, kmConv: 25 },
  { origen: "MONTE GRANDE", destino: "QUILMES", kmReal: 60, kmConv: 60 },
  { origen: "SAN JORGE", destino: "SANTA FE", kmReal: 155, kmConv: 155 },
  { origen: "FRIAS", destino: "SAN FRANCISCO", kmReal: 546, kmConv: 545 },
  { origen: "SAN MARTIN", destino: "LA CALERA", kmReal: 704, kmConv: 705 },
  { origen: "TAPIALES", destino: "FLORENCIO VARELA", kmReal: 34, kmConv: 35 },
  { origen: "JAMES CRAIK", destino: "SAN FRANCISCO", kmReal: 190, kmConv: 190 },
  { origen: "VILLA TESEI", destino: "EZEIZA", kmReal: 40, kmConv: 40 },
  { origen: "MAR DE AJO", destino: "VILLA SOLDATI", kmReal: 375, kmConv: 375 },
  { origen: "SAN MARTIN", destino: "9 DE ABRIL", kmReal: 25, kmConv: 25 },
  { origen: "LAS HERAS", destino: "JAMES CRAIK", kmReal: 645, kmConv: 645 },
  { origen: "RIO TERCERO", destino: "VILLA MARIA", kmReal: 106, kmConv: 105 },
  { origen: "CAMPANA", destino: "RIO TERCERO", kmReal: 610, kmConv: 610 },
  { origen: "VILLA SOLDATI", destino: "GOBERNADOR VIRASORO", kmReal: 910, kmConv: 910 },
  { origen: "GALVEZ", destino: "MAR DE AJO", kmReal: 790, kmConv: 790 },
  { origen: "BENAVIDEZ", destino: "VILLA MARIA", kmReal: 515, kmConv: 515 },
  { origen: "MUNRO", destino: "BERAZATEGUI", kmReal: 55, kmConv: 55 },
  { origen: "GARIN", destino: "LUJAN", kmReal: 56, kmConv: 55 },
  { origen: "PABLO PODESTA", destino: "BARADERO", kmReal: 138, kmConv: 140 },
  { origen: "JOSE LEON SUAREZ", destino: "ALEJANDRO ROCA", kmReal: 530, kmConv: 530 },
  { origen: "SAN PEDRO", destino: "LA REJA", kmReal: 165, kmConv: 165 },
  { origen: "MERLO", destino: "9 DE ABRIL", kmReal: 40, kmConv: 40 },
  { origen: "ESCOBAR", destino: "MERLO", kmReal: 55, kmConv: 55 },
  { origen: "DOCK SUD", destino: "GOBERNADOR VIRASORO", kmReal: 915, kmConv: 915 },
  { origen: "ZONA PORTUARIA", destino: "GOBERNADOR VIRASORO", kmReal: 905, kmConv: 905 },
  { origen: "GOBERNADOR VIRASORO", destino: "ZONA PORTUARIA", kmReal: 905, kmConv: 905 },
  { origen: "SAN FRANCISCO", destino: "JOSE C. PAZ", kmReal: 540, kmConv: 540 },
  { origen: "VILLA URQUIZA", destino: "MUNRO", kmReal: 10, kmConv: 10 },
  { origen: "TUCUMAN", destino: "LA MENDIETA", kmReal: 325, kmConv: 325 },
  { origen: "LUJAN DE CUYO", destino: "LOMAS DE ZAMORA", kmReal: 1062, kmConv: 1060 },
  { origen: "MORTEROS", destino: "SANTO TOME", kmReal: 215, kmConv: 215 },
  { origen: "MONTE VERA", destino: "FRANCK", kmReal: 52, kmConv: 50 },
  { origen: "MENDOZA", destino: "COSQUIN", kmReal: 725, kmConv: 725 },
  { origen: "VILLA SOLDATI", destino: "SAN RAFAEL", kmReal: 975, kmConv: 975 },
  { origen: "SAN JORGE", destino: "VILLA SOLDATI", kmReal: 498, kmConv: 500 },
  { origen: "RIO TERCERO", destino: "TIO PUJIO", kmReal: 89, kmConv: 90 },
  { origen: "SAUCE VIEJO", destino: "MONTE VERA", kmReal: 45, kmConv: 45 },
  { origen: "QUILMES", destino: "SAUCE VIEJO", kmReal: 475, kmConv: 475 },
  { origen: "CAMPANA", destino: "RIO SEGUNDO", kmReal: 580, kmConv: 580 },
  { origen: "SAN FERNANDO", destino: "9 DE ABRIL", kmReal: 43, kmConv: 45 },
  { origen: "CAPITAN CORTEZ", destino: "TIO PUJIO", kmReal: 575, kmConv: 575 },
  { origen: "ROSARIO", destino: "PABLO NOGUES", kmReal: 266, kmConv: 265 },
  { origen: "TAPIALES", destino: "DOCK SUD", kmReal: 23, kmConv: 25 },
  { origen: "PABLO NOGUES", destino: "SAN FERNANDO", kmReal: 20, kmConv: 20 },
  { origen: "PABLO NOGUES", destino: "MALVINAS ARGENTINAS", kmReal: 59, kmConv: 60 },
  { origen: "SUNCHALES", destino: "SAN JORGE", kmReal: 117, kmConv: 115 },
  { origen: "GENERAL RODRIGUEZ", destino: "MUNRO", kmReal: 55, kmConv: 55 },
  { origen: "CATAMARCA", destino: "SAN JORGE", kmReal: 735, kmConv: 735 },
  { origen: "SAN FRANCISCO", destino: "EL TALAR", kmReal: 530, kmConv: 530 },
  { origen: "ROSARIO", destino: "MAR DEL PLATA", kmReal: 714, kmConv: 715 },
  { origen: "LAS HERAS", destino: "LA PLATA", kmReal: 1109, kmConv: 1110 },
  { origen: "LANUS", destino: "PILAR", kmReal: 70, kmConv: 70 },
  { origen: "ROSARIO", destino: "SANTA TERESITA", kmReal: 645, kmConv: 645 },
  { origen: "ROSARIO", destino: "VILLA GESELL", kmReal: 675, kmConv: 675 },
  { origen: "MORENO", destino: "GENERAL PACHECO", kmReal: 40, kmConv: 40 },
  { origen: "VILLA SOLDATI", destino: "TIO PUJIO", kmReal: 577, kmConv: 575 },
  { origen: "DEVOTO", destino: "VILLA SOLDATI", kmReal: 593, kmConv: 595 },
  { origen: "RECREO", destino: "PASO DEL REY", kmReal: 484, kmConv: 485 },
  { origen: "VILLA NUEVA", destino: "CORDOBA", kmReal: 155, kmConv: 155 },
  { origen: "TIO PUJIO", destino: "MATADEROS", kmReal: 572, kmConv: 570 },
  { origen: "BERAZATEGUI", destino: "ZONA PORTUARIA", kmReal: 32, kmConv: 30 },
  { origen: "GENERAL PACHECO", destino: "TUCUMAN", kmReal: 1215, kmConv: 1215 },
  { origen: "NU&#209;EZ", destino: "VILLA SOLDATI", kmReal: 23, kmConv: 25 },
  { origen: "GENERAL ROCA", destino: "TIO PUJIO", kmReal: 157, kmConv: 155 },
  { origen: "ROSARIO", destino: "LA PLATA", kmReal: 357, kmConv: 355 },
  { origen: "GERLI", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "PUERTO PIRAY", destino: "VILLA MAIPU", kmReal: 1162, kmConv: 1160 },
  { origen: "MENDOZA", destino: "ROSARIO", kmReal: 876, kmConv: 875 },
  { origen: "CATRILO", destino: "GERLI", kmReal: 534, kmConv: 535 },
  { origen: "SALTO", destino: "GENERAL ROCA", kmReal: 259, kmConv: 260 },
  { origen: "CAMPANA", destino: "SALTO", kmReal: 155, kmConv: 155 },
  { origen: "NEUQUEN", destino: "RIO CUARTO", kmReal: 901, kmConv: 900 },
  { origen: "SAN FRANCISCO", destino: "NU&#209;EZ", kmReal: 551, kmConv: 550 },
  { origen: "VILLA GOBERNADOR GALVEZ", destino: "CAMPANA", kmReal: 212, kmConv: 210 },
  { origen: "VILLA GOBERNADOR GALVEZ", destino: "SAN JORGE", kmReal: 209, kmConv: 210 },
  { origen: "ZARATE", destino: "VILLA GOBERNADOR GALVEZ", kmReal: 205, kmConv: 205 },
  { origen: "TOTORAS", destino: "CORDOBA", kmReal: 378, kmConv: 380 },
  { origen: "RECREO", destino: "TOTORAS", kmReal: 158, kmConv: 160 },
  { origen: "AVELLANEDA", destino: "BURZACO", kmReal: 21, kmConv: 20 },
  { origen: "MORENO", destino: "RECONQUISTA", kmReal: 782, kmConv: 780 },
  { origen: "GARIN", destino: "ESCOBAR", kmReal: 15, kmConv: 15 },
  { origen: "MORENO", destino: "COLONIA CAROYA", kmReal: 733, kmConv: 735 },
  { origen: "PABLO PODESTA", destino: "VILLA SOLDATI", kmReal: 22, kmConv: 20 },
  { origen: "TAPIALES", destino: "VILLA GRANADEROS DE SAN MARTIN", kmReal: 23, kmConv: 25 },
  { origen: "LA FRANCIA", destino: "SANTO TOME", kmReal: 187, kmConv: 185 },
  { origen: "LANUS", destino: "CAMPANA", kmReal: 93, kmConv: 95 },
  { origen: "VILLA TESEI", destino: "LANUS", kmReal: 29, kmConv: 30 },
  { origen: "GENERAL RODRIGUEZ", destino: "VILLA TESEI", kmReal: 32, kmConv: 30 },
  { origen: "ESCOBAR", destino: "CASEROS", kmReal: 51, kmConv: 50 },
  { origen: "ARROYITO", destino: "CHACARITA", kmReal: 642, kmConv: 640 },
  { origen: "LOMAS DEL MIRADOR", destino: "MUNRO", kmReal: 19, kmConv: 20 },
  { origen: "VILLA GRANADEROS DE SAN MARTIN", destino: "SAN FRANCISCO", kmReal: 548, kmConv: 550 },
  { origen: "VILLA URQUIZA", destino: "VILLA GRANADEROS DE SAN MARTIN", kmReal: 6, kmConv: 5 },
  { origen: "CAMPANA", destino: "AVELLANEDA", kmReal: 86, kmConv: 85 },
  { origen: "LONGCHAMPS", destino: "AVELLANEDA", kmReal: 25, kmConv: 25 },
  { origen: "EZEIZA", destino: "SAN FRANCISCO", kmReal: 621, kmConv: 620 },
  { origen: "SAN FRANCISCO", destino: "EZEIZA", kmReal: 621, kmConv: 620 },
  { origen: "CAPITAN CORTEZ", destino: "VILLA MARIA", kmReal: 556, kmConv: 555 },
  { origen: "CORONEL PRINGLES", destino: "RAFAELA", kmReal: 934, kmConv: 935 },
  { origen: "RAFAELA", destino: "CORONEL PRINGLES", kmReal: 934, kmConv: 935 },
  { origen: "MATADEROS", destino: "SAN FRANCISCO", kmReal: 562, kmConv: 560 },
  { origen: "DEVOTO", destino: "ARROYITO", kmReal: 80, kmConv: 80 },
  { origen: "GENERAL RODRIGUEZ", destino: "RAFAELA", kmReal: 519, kmConv: 520 },
  { origen: "RAFAELA", destino: "GENERAL RODRIGUEZ", kmReal: 519, kmConv: 520 },
  { origen: "RAFAELA", destino: "MADARIAGA", kmReal: 552, kmConv: 555 },
  { origen: "RAFAELA", destino: "JOSE C. PAZ", kmReal: 517, kmConv: 520 },
  { origen: "RAFAELA", destino: "TORTUGUITAS", kmReal: 508, kmConv: 510 },
  { origen: "RAFAELA", destino: "BECCAR", kmReal: 521, kmConv: 525 },
  { origen: "RAFAELA", destino: "VILLA CRESPO", kmReal: 538, kmConv: 540 },
  { origen: "SAN JUSTO", destino: "RAFAELA", kmReal: 150, kmConv: 150 },
  { origen: "RAFAELA", destino: "SAN JUSTO", kmReal: 544, kmConv: 545 },
  { origen: "RAFAELA", destino: "GENERAL PACHECO", kmReal: 507, kmConv: 510 },
  { origen: "RAFAELA", destino: "GARIN", kmReal: 499, kmConv: 500 },
  { origen: "DON TORCUATO", destino: "RAFAELA", kmReal: 512, kmConv: 515 },
  { origen: "RAFAELA", destino: "DON TORCUATO", kmReal: 512, kmConv: 515 },
  { origen: "RAFAELA", destino: "GENERAL LAGOS", kmReal: 268, kmConv: 270 },
  { origen: "RAFAELA", destino: "MONTE GRANDE", kmReal: 565, kmConv: 565 },
  { origen: "RAFAELA", destino: "VILLA SOLDATI", kmReal: 545, kmConv: 545 },
  { origen: "LA PLATA", destino: "RAFAELA", kmReal: 597, kmConv: 600 },
  { origen: "RAFAELA", destino: "LA PLATA", kmReal: 597, kmConv: 600 },
  { origen: "RAFAELA", destino: "TANDIL", kmReal: 835, kmConv: 835 },
  { origen: "RAFAELA", destino: "VIRREYES", kmReal: 516, kmConv: 520 },
  { origen: "RAFAELA", destino: "LUCILA DEL MAR", kmReal: 898, kmConv: 900 },
  { origen: "GALVEZ", destino: "PABLO PODESTA", kmReal: 414, kmConv: 415 },
  { origen: "PABLO PODESTA", destino: "LANUS", kmReal: 31, kmConv: 30 },
  { origen: "LA FRANCIA", destino: "DEVOTO", kmReal: 34, kmConv: 35 },
  { origen: "ZONA PORTUARIA", destino: "LA FRANCIA", kmReal: 617, kmConv: 615 },
  { origen: "SAN FRANCISCO", destino: "VILLA MAIPU", kmReal: 550, kmConv: 550 },
  { origen: "SAN FRANCISCO", destino: "VILLA CRESPO", kmReal: 554, kmConv: 555 },
  { origen: "SAN FRANCISCO", destino: "VICENTE LOPEZ", kmReal: 0, kmConv: 0 },
  { origen: "SAN FRANCISCO", destino: "VERSALLES", kmReal: 557, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "TRUJUI", kmReal: 558, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "TORTUGUITAS", kmReal: 530, kmConv: 530 },
  { origen: "SAN FRANCISCO", destino: "TEMPERLEY", kmReal: 580, kmConv: 580 },
  { origen: "SAN FRANCISCO", destino: "SAN PEDRO", kmReal: 408, kmConv: 410 },
  { origen: "SAN NICOLAS", destino: "SAN FRANCISCO", kmReal: 350, kmConv: 350 },
  { origen: "SAN FRANCISCO", destino: "SAN JUSTO", kmReal: 566, kmConv: 570 },
  { origen: "AROCENA", destino: "SANTA FE", kmReal: 68, kmConv: 70 },
  { origen: "SAN FRANCISCO", destino: "SAN FRANCISCO SOLANO", kmReal: 587, kmConv: 590 },
  { origen: "RAFAELA", destino: "AROCENA", kmReal: 138, kmConv: 140 },
  { origen: "SAN FRANCISCO", destino: "SAAVEDRA", kmReal: 547, kmConv: 550 },
  { origen: "SAN FRANCISCO", destino: "PATERNAL", kmReal: 554, kmConv: 555 },
  { origen: "TAPIALES", destino: "GENERAL PACHECO", kmReal: 44, kmConv: 45 },
  { origen: "VILLA LUZURIAGA", destino: "MATADEROS", kmReal: 10, kmConv: 10 },
  { origen: "SAN FRANCISCO", destino: "MONTECASTRO", kmReal: 557, kmConv: 555 },
  { origen: "SAN FRANCISCO", destino: "MERCEDES", kmReal: 604, kmConv: 605 },
  { origen: "VILLA LURO", destino: "VILLA LUZURIAGA", kmReal: 9, kmConv: 10 },
  { origen: "SAN FRANCISCO", destino: "MARCOS PAZ", kmReal: 577, kmConv: 575 },
  { origen: "RAFAELA", destino: "VILLA LURO", kmReal: 539, kmConv: 540 },
  { origen: "SAN FRANCISCO", destino: "MAR DEL PLATA", kmReal: 976, kmConv: 975 },
  { origen: "SAN FRANCISCO", destino: "LOMAS DEL MIRADOR", kmReal: 562, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "INGENIERO BUDGE", kmReal: 572, kmConv: 575 },
  { origen: "SAN FRANCISCO", destino: "HUDSON", kmReal: 596, kmConv: 595 },
  { origen: "SAN FRANCISCO", destino: "GONZALEZ CATAN", kmReal: 585, kmConv: 585 },
  { origen: "SAN FRANCISCO", destino: "GENERAL PACHECO", kmReal: 529, kmConv: 530 },
  { origen: "SAN FRANCISCO", destino: "ESTEBAN ECHEVERRIA", kmReal: 589, kmConv: 590 },
  { origen: "SAN FRANCISCO", destino: "ELORTONDO", kmReal: 301, kmConv: 300 },
  { origen: "SAN FRANCISCO", destino: "3 DE FEBRERO", kmReal: 562, kmConv: 560 },
  { origen: "9 DE ABRIL", destino: "SAN FRANCISCO", kmReal: 574, kmConv: 575 },
  { origen: "9 DE JULIO", destino: "SAN FRANCISCO", kmReal: 522, kmConv: 520 },
  { origen: "SAN FRANCISCO", destino: "9 DE JULIO", kmReal: 522, kmConv: 520 },
  { origen: "SAN FRANCISCO", destino: "CHACARITA", kmReal: 553, kmConv: 555 },
  { origen: "SAN FRANCISCO", destino: "CASEROS", kmReal: 559, kmConv: 560 },
  { origen: "CARCARA&#209;A", destino: "SAN FRANCISCO", kmReal: 222, kmConv: 220 },
  { origen: "SAN FRANCISCO", destino: "CARCARA&#209;A", kmReal: 222, kmConv: 220 },
  { origen: "ARRECIFES", destino: "SAN FRANCISCO", kmReal: 418, kmConv: 420 },
  { origen: "SAN FRANCISCO", destino: "ARRECIFES", kmReal: 418, kmConv: 420 },
  { origen: "SARANDI", destino: "SAN RAFAEL", kmReal: 991, kmConv: 990 },
  { origen: "TAPIALES", destino: "ISIDRO CASANOVA", kmReal: 11, kmConv: 10 },
  { origen: "BURZACO", destino: "SAN FRANCISCO", kmReal: 585, kmConv: 585 },
  { origen: "RAFAELA", destino: "VICENTE LOPEZ", kmReal: 529, kmConv: 530 },
  { origen: "HURLINGHAM", destino: "SAN FRANCISCO", kmReal: 550, kmConv: 550 },
  { origen: "RAFAELA", destino: "BURZACO", kmReal: 563, kmConv: 565 },
  { origen: "PILAR", destino: "SAN FRANCISCO", kmReal: 98, kmConv: 100 },
  { origen: "BARRACAS", destino: "SAN FRANCISCO", kmReal: 567, kmConv: 570 },
  { origen: "SUSANA", destino: "JUNIN", kmReal: 439, kmConv: 440 },
  { origen: "SAN ANDRES DE GILES", destino: "RAFAELA", kmReal: 467, kmConv: 465 },
  { origen: "SAN FRANCISCO", destino: "ROSARIO", kmReal: 267, kmConv: 270 },
  { origen: "BERAZATEGUI", destino: "SAN FRANCISCO", kmReal: 590, kmConv: 590 },
  { origen: "SARANDI", destino: "SAN FRANCISCO", kmReal: 572, kmConv: 575 },
  { origen: "VILLA SOLDATI", destino: "SAN FRANCISCO", kmReal: 567, kmConv: 570 },
  { origen: "SAN FRANCISCO", destino: "MUNRO", kmReal: 545, kmConv: 545 },
  { origen: "FREYRE", destino: "ROSARIO", kmReal: 296, kmConv: 295 },
  { origen: "PORTE&#209;A", destino: "TORTUGUITAS", kmReal: 679, kmConv: 680 },
  { origen: "LA PLATA", destino: "PORTE&#209;A", kmReal: 668, kmConv: 670 },
  { origen: "SAN FRANCISCO", destino: "TAPIALES", kmReal: 568, kmConv: 570 },
  { origen: "PORTE&#209;A", destino: "LA PLATA", kmReal: 668, kmConv: 670 },
  { origen: "SAN FRANCISCO", destino: "HURLINGHAM", kmReal: 550, kmConv: 550 },
  { origen: "SAN FRANCISCO", destino: "PILAR", kmReal: 523, kmConv: 525 },
  { origen: "PORTE&#209;A", destino: "MORENO", kmReal: 613, kmConv: 615 },
  { origen: "SAN FRANCISCO", destino: "BARRACAS", kmReal: 567, kmConv: 570 },
  { origen: "ROSARIO", destino: "PORTE&#209;A", kmReal: 316, kmConv: 315 },
  { origen: "SAN FRANCISCO", destino: "GENERAL RODRIGUEZ", kmReal: 540, kmConv: 540 },
  { origen: "ZARATE", destino: "PORTE&#209;A", kmReal: 525, kmConv: 525 },
  { origen: "DOCK SUD", destino: "PORTE&#209;A", kmReal: 619, kmConv: 620 },
  { origen: "ZONA PORTUARIA", destino: "PORTE&#209;A", kmReal: 610, kmConv: 610 },
  { origen: "PORTE&#209;A", destino: "LONGCHAMPS", kmReal: 642, kmConv: 640 },
  { origen: "PORTE&#209;A", destino: "ZARATE", kmReal: 526, kmConv: 525 },
  { origen: "SAN FRANCISCO", destino: "LA PLATA", kmReal: 620, kmConv: 620 },
  { origen: "PORTE&#209;A", destino: "DOCK SUD", kmReal: 619, kmConv: 620 },
  { origen: "SAN FRANCISCO", destino: "ITUZAINGO", kmReal: 563, kmConv: 565 },
  { origen: "PORTE&#209;A", destino: "ZONA PORTUARIA", kmReal: 610, kmConv: 610 },
  { origen: "SAN FRANCISCO", destino: "MERLO", kmReal: 565, kmConv: 565 },
  { origen: "ROSARIO", destino: "SAN FRANCISCO", kmReal: 267, kmConv: 270 },
  { origen: "SAN FRANCISCO", destino: "SARANDI", kmReal: 572, kmConv: 575 },
  { origen: "DOCK SUD", destino: "SAN RAFAEL", kmReal: 987, kmConv: 985 },
  { origen: "LOMA HERMOSA", destino: "9 DE ABRIL", kmReal: 29, kmConv: 30 },
  { origen: "EL SOBERBIO", destino: "SAN VICENTE", kmReal: 49, kmConv: 50 },
  { origen: "ESCOBAR", destino: "LOMA HERMOSA", kmReal: 40, kmConv: 40 },
  { origen: "EL SOBERBIO", destino: "PUERTO PIRAY", kmReal: 153, kmConv: 155 },
  { origen: "SALADAS", destino: "ELDORADO", kmReal: 520, kmConv: 520 },
  { origen: "ITA-IBATE", destino: "SALADAS", kmReal: 260, kmConv: 260 },
  { origen: "SANTO TOME", destino: "ITA-IBATE", kmReal: 725, kmConv: 725 },
  { origen: "OBERA", destino: "EL SOBERBIO", kmReal: 125, kmConv: 125 },
  { origen: "TIGRE", destino: "JOSE C. PAZ", kmReal: 30, kmConv: 30 },
  { origen: "HURLINGHAM", destino: "EZEIZA", kmReal: 43, kmConv: 45 },
  { origen: "PILAR", destino: "EZEIZA", kmReal: 85, kmConv: 85 },
  { origen: "RAFAELA", destino: "OLIVOS", kmReal: 525, kmConv: 525 },
  { origen: "RIO CEBALLOS", destino: "TIO PUJIO", kmReal: 160, kmConv: 160 },
  { origen: "SANTA CLARA SAGUIER", destino: "DOCK SUD", kmReal: 559, kmConv: 560 },
  { origen: "SAN FRANCISCO", destino: "SANTA CLARA SAGUIER", kmReal: 39, kmConv: 40 },
  { origen: "RAFAELA", destino: "SANTA CLARA SAGUIER", kmReal: 45, kmConv: 45 },
  { origen: "LA MENDIETA", destino: "JUJUY", kmReal: 67, kmConv: 65 },
  { origen: "SAN FERNANDO", destino: "LANUS", kmReal: 44, kmConv: 45 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
