/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 2 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "LONGCHAMPS", destino: "MATADEROS", kmReal: 30, kmConv: 30 },
  { origen: "LA FRANCIA", destino: "RAFAELA", kmReal: 140, kmConv: 140 },
  { origen: "EZPELETA", destino: "TAPIALES", kmReal: 40, kmConv: 40 },
  { origen: "JUJUY", destino: "LA MENDIETA", kmReal: 67, kmConv: 65 },
  { origen: "LOMAS DE ZAMORA", destino: "MORENO", kmReal: 44, kmConv: 45 },
  { origen: "SALTO", destino: "CORDOBA", kmReal: 538, kmConv: 540 },
  { origen: "SALTA", destino: "CORDOBA", kmReal: 876, kmConv: 880 },
  { origen: "BARADERO", destino: "SALTA", kmReal: 1330, kmConv: 1330 },
  { origen: "GENERAL RODRIGUEZ", destino: "MORENO", kmReal: 18, kmConv: 20 },
  { origen: "CORDOBA", destino: "GENERAL RODRIGUEZ", kmReal: 675, kmConv: 675 },
  { origen: "RIO CEBALLOS", destino: "COLONIA CAROYA", kmReal: 55, kmConv: 55 },
  { origen: "WILLIAM MORRIS", destino: "VILLA SOLDATI", kmReal: 38, kmConv: 40 },
  { origen: "MONTEVIDEO", destino: "LUJAN", kmReal: 558, kmConv: 560 },
  { origen: "BERAZATEGUI", destino: "DOCK SUD", kmReal: 24, kmConv: 25 },
  { origen: "MENDOZA", destino: "WILLIAM MORRIS", kmReal: 1025, kmConv: 1025 },
  { origen: "SAN RAFAEL", destino: "ZONA PORTUARIA", kmReal: 990, kmConv: 990 },
  { origen: "ZONA PORTUARIA", destino: "SAN RAFAEL", kmReal: 990, kmConv: 990 },
  { origen: "MERLO", destino: "MARCOS PAZ", kmReal: 15, kmConv: 15 },
  { origen: "SAN JORGE", destino: "SANTO TOME", kmReal: 145, kmConv: 145 },
  { origen: "VILLA SOLDATI", destino: "VILLA CRESPO", kmReal: 9, kmConv: 10 },
  { origen: "TORTUGUITAS", destino: "MONTEVIDEO", kmReal: 563, kmConv: 565 },
  { origen: "CAPITAN CORTEZ", destino: "GOBERNADOR CRESPO", kmReal: 621, kmConv: 620 },
  { origen: "LANUS", destino: "MONTEVIDEO", kmReal: 609, kmConv: 610 },
  { origen: "GUATIMOZIN", destino: "SUSANA", kmReal: 331, kmConv: 330 },
  { origen: "FONTANA", destino: "PUERTO PIRAY", kmReal: 532, kmConv: 530 },
  { origen: "VILLA TESEI", destino: "MUNRO", kmReal: 17, kmConv: 15 },
  { origen: "SUNCHALES", destino: "ROSARIO", kmReal: 285, kmConv: 285 },
  { origen: "LANUS", destino: "GENERAL PACHECO", kmReal: 63, kmConv: 65 },
  { origen: "VILLA SOLDATI", destino: "LUJAN", kmReal: 66, kmConv: 65 },
  { origen: "MENDOZA", destino: "FONTANA", kmReal: 1446, kmConv: 1445 },
  { origen: "PABLO NOGUES", destino: "PILAR", kmReal: 23, kmConv: 25 },
  { origen: "MONTEVIDEO", destino: "MORENO", kmReal: 570, kmConv: 570 },
  { origen: "APÓSTOLES", destino: "SANTA ANA", kmReal: 89, kmConv: 90 },
  { origen: "CASEROS", destino: "MATADEROS", kmReal: 11, kmConv: 10 },
  { origen: "PILAR", destino: "SANTA FE", kmReal: 601, kmConv: 600 },
  { origen: "ZONA PORTUARIA", destino: "GENERAL LAGOS", kmReal: 276, kmConv: 275 },
  { origen: "MENDOZA", destino: "PILAR", kmReal: 867, kmConv: 865 },
  { origen: "TORTUGUITAS", destino: "MENDOZA", kmReal: 1051, kmConv: 1050 },
  { origen: "FRONTERA", destino: "RAFAELA", kmReal: 79, kmConv: 80 },
  { origen: "SAN JORGE", destino: "FRONTERA", kmReal: 84, kmConv: 85 },
  { origen: "PUERTO PIRAY", destino: "CASEROS", kmReal: 1170, kmConv: 1170 },
  { origen: "WILDE", destino: "EZEIZA", kmReal: 51, kmConv: 50 },
  { origen: "RIO CUARTO", destino: "MENDOZA", kmReal: 475, kmConv: 475 },
  { origen: "BARADERO", destino: "SAN JORGE", kmReal: 355, kmConv: 355 },
  { origen: "BERAZATEGUI", destino: "VILLA MARIA", kmReal: 582, kmConv: 580 },
  { origen: "PUERTO RICO", destino: "ELDORADO", kmReal: 74, kmConv: 75 },
  { origen: "SAN FRANCISCO", destino: "PUERTO RICO", kmReal: 1036, kmConv: 1035 },
  { origen: "PUERTO MADERO", destino: "VILLA SOLDATI", kmReal: 14, kmConv: 15 },
  { origen: "MORENO", destino: "REMEDIOS DE ESCALADA", kmReal: 44, kmConv: 45 },
  { origen: "ESPERANZA", destino: "PUERTO MADERO", kmReal: 494, kmConv: 495 },
  { origen: "RAFAELA", destino: "RIO CUARTO", kmReal: 381, kmConv: 380 },
  { origen: "GOBERNADOR CRESPO", destino: "9 DE ABRIL", kmReal: 630, kmConv: 630 },
  { origen: "TAPIALES", destino: "MERCEDES", kmReal: 16, kmConv: 15 },
  { origen: "CHACARITA", destino: "FLORENCIO VARELA", kmReal: 34, kmConv: 35 },
  { origen: "BERAZATEGUI", destino: "MORTEROS", kmReal: 677, kmConv: 675 },
  { origen: "VILLA MARIA", destino: "BERAZATEGUI", kmReal: 581, kmConv: 580 },
  { origen: "SAN JORGE", destino: "MONTEVIDEO", kmReal: 813, kmConv: 815 },
  { origen: "RIO CEBALLOS", destino: "SAN JORGE", kmReal: 306, kmConv: 305 },
  { origen: "VILLA LA RIVERA", destino: "SAN FRANCISCO", kmReal: 226, kmConv: 225 },
  { origen: "SAN FRANCISCO", destino: "VILLA LA RIVERA", kmReal: 226, kmConv: 225 },
  { origen: "GENERAL RODRIGUEZ", destino: "ISIDRO CASANOVA", kmReal: 43, kmConv: 45 },
  { origen: "GENERAL PACHECO", destino: "ZONA PORTUARIA", kmReal: null, kmConv: 35 },
  { origen: "ESCOBAR", destino: "VALENTIN ALSINA", kmReal: 65, kmConv: 65 },
  { origen: "VILLA SOLDATI", destino: "ARROYITO", kmReal: 656, kmConv: 655 },
  { origen: "BARRACAS", destino: "BASAVILBASO", kmReal: 321, kmConv: 320 },
  { origen: "HURLINGHAM", destino: "PABLO NOGUES", kmReal: 16, kmConv: 15 },
  { origen: "VILLA CRESPO", destino: "CORDOBA", kmReal: 691, kmConv: 690 },
  { origen: "MERCEDES", destino: "VILLA CRESPO", kmReal: 97, kmConv: 95 },
  { origen: "TIGRE", destino: "MATADEROS", kmReal: 34, kmConv: 35 },
  { origen: "ITUZAINGO", destino: "SAN FRANCISCO", kmReal: 565, kmConv: 565 },
  { origen: "VILLA SOLDATI", destino: "ITUZAINGO", kmReal: 25, kmConv: 25 },
  { origen: "MARCOS PAZ", destino: "VILLA SOLDATI", kmReal: null, kmConv: 60 },
  { origen: "MANUEL CAMPOS", destino: "EZEIZA", kmReal: 624, kmConv: 625 },
  { origen: "EZPELETA", destino: "SAN JUSTO", kmReal: 50, kmConv: 50 },
  { origen: "VICENTE LOPEZ", destino: "SARANDI", kmReal: 24, kmConv: 25 },
  { origen: "JUNIN", destino: "ARRECIFES", kmReal: 129, kmConv: 130 },
  { origen: "RETIRO", destino: "MANUEL CAMPOS", kmReal: 662, kmConv: 660 },
  { origen: "VILLA SOLDATI", destino: "GALVEZ", kmReal: 433, kmConv: 435 },
  { origen: "SAN PEDRO", destino: "ZONA PORTUARIA", kmReal: 171, kmConv: 170 },
  { origen: "DOCK SUD", destino: "SAN PEDRO", kmReal: 179, kmConv: 180 },
  { origen: "SAN FRANCISCO", destino: "GOBERNADOR VIRASORO", kmReal: 831, kmConv: 830 },
  { origen: "RECREO", destino: "MARCOS PAZ", kmReal: 498, kmConv: 500 },
  { origen: "DEVOTO", destino: "CORDOBA", kmReal: 201, kmConv: 200 },
  { origen: "SARANDI", destino: "DEVOTO", kmReal: 598, kmConv: 598 },
  { origen: "RESISTENCIA", destino: "POSADAS", kmReal: 340, kmConv: 340 },
  { origen: "VILLA SOLDATI", destino: "RANELAGH", kmReal: 44, kmConv: 45 },
  { origen: "BURZACO", destino: "MUNRO", kmReal: 45, kmConv: 45 },
  { origen: "VILLA LA RIVERA", destino: "DOCK SUD", kmReal: 346, kmConv: 345 },
  { origen: "GUALEGUAYCHU", destino: "VILLA LA RIVERA", kmReal: 278, kmConv: 280 },
  { origen: "RAFAELA", destino: "VILLA LA RIVERA", kmReal: 205, kmConv: 205 },
  { origen: "RECREO", destino: "SARANDI", kmReal: 492, kmConv: 490 },
  { origen: "GENERAL RODRIGUEZ", destino: "RANELAGH", kmReal: 88, kmConv: 90 },
  { origen: "GENERAL RODRIGUEZ", destino: "GARIN", kmReal: 39, kmConv: 40 },
  { origen: "VILLA MERCEDES", destino: "MENDOZA", kmReal: 355, kmConv: 355 },
  { origen: "RIO CUARTO", destino: "ROSARIO", kmReal: 390, kmConv: 390 },
  { origen: "ZARATE", destino: "SAN ANDRES DE GILES", kmReal: 59, kmConv: 60 },
  { origen: "ISIDRO CASANOVA", destino: "SAN MARTIN", kmReal: 30, kmConv: 30 },
  { origen: "GOBERNADOR CRESPO", destino: "CAMPANA", kmReal: 539, kmConv: 540 },
  { origen: "CAMPANA", destino: "SANTO TOME", kmReal: 380, kmConv: 380 },
  { origen: "RIO CUARTO", destino: "CAPITAN CORTEZ", kmReal: 618, kmConv: 620 },
  { origen: "HURLINGHAM", destino: "MATADEROS", kmReal: 18, kmConv: 20 },
  { origen: "TANDIL", destino: "VILLA SOLDATI", kmReal: 342, kmConv: 340 },
  { origen: "MORENO", destino: "CIUDADELA", kmReal: 25, kmConv: 25 },
  { origen: "MENDOZA", destino: "COLONIA LAS ROSAS", kmReal: 91, kmConv: 90 },
  { origen: "CORDOBA", destino: "CAPITAN CORTEZ", kmReal: 701, kmConv: 700 },
  { origen: "LA BANDA", destino: "TUCUMAN", kmReal: 176, kmConv: 175 },
  { origen: "ESPERANZA", destino: "ROSARIO", kmReal: 202, kmConv: 200 },
  { origen: "COLONIA LAS ROSAS", destino: "TAPIALES", kmReal: 1138, kmConv: 1140 },
  { origen: "HAEDO", destino: "GONZALEZ CATAN", kmReal: 20, kmConv: 20 },
  { origen: "VILLA MERCEDES", destino: "HAEDO", kmReal: 680, kmConv: 680 },
  { origen: "SANTIAGO DEL ESTERO", destino: "LA BANDA", kmReal: null, kmConv: 5 },
  { origen: "LULES", destino: "CORDOBA", kmReal: 545, kmConv: 545 },
  { origen: "CAPITAN CORTEZ", destino: "BRINKMANN", kmReal: 631, kmConv: 630 },
  { origen: "DOCK SUD", destino: "CAPITAN CORTEZ", kmReal: 10, kmConv: 10 },
  { origen: "CONCORDIA", destino: "GARIN", kmReal: 388, kmConv: 390 },
  { origen: "BARRACAS", destino: "SAN JUSTO", kmReal: 28, kmConv: 30 },
  { origen: "RIVERA", destino: "SAN ANDRES DE GILES", kmReal: 538, kmConv: 540 },
  { origen: "ISIDRO CASANOVA", destino: "SAN JUSTO", kmReal: 5, kmConv: 5 },
  { origen: "ALEJANDRO ROCA", destino: "CORDOBA", kmReal: 282, kmConv: 280 },
  { origen: "PABLO NOGUES", destino: "SAN MARTIN", kmReal: 30, kmConv: 30 },
  { origen: "LUJAN", destino: "BURZACO", kmReal: 88, kmConv: 90 },
  { origen: "LULES", destino: "BERAZATEGUI", kmReal: 1262, kmConv: 1262 },
  { origen: "LULES", destino: "BARRACAS", kmReal: 1238, kmConv: 1240 },
  { origen: "VILLA SOLDATI", destino: "ALEJANDRO ROCA", kmReal: 555, kmConv: 555 },
  { origen: "CARMEN DE ARECO", destino: "VILLA SOLDATI", kmReal: 138, kmConv: 140 },
  { origen: "RETIRO", destino: "RIVERA", kmReal: 582, kmConv: 580 },
  { origen: "VICENTE LOPEZ", destino: "RETIRO", kmReal: 13, kmConv: 15 },
  { origen: "PILAR", destino: "RAFAELA", kmReal: 498, kmConv: 500 },
  { origen: "WARNES", destino: "VICENTE LOPEZ", kmReal: 11, kmConv: 10 },
  { origen: "TIO PUJIO", destino: "WARNES", kmReal: 565, kmConv: 565 },
  { origen: "GOBERNADOR VIRASORO", destino: "PILAR", kmReal: 761, kmConv: 760 },
  { origen: "ESCOBAR", destino: "MATADEROS", kmReal: 56, kmConv: 55 },
  { origen: "EZEIZA", destino: "RANELAGH", kmReal: 66, kmConv: 65 },
  { origen: "BAHIA BLANCA", destino: "CAMPANA", kmReal: 680, kmConv: 680 },
  { origen: "LUJAN", destino: "GENERAL PACHECO", kmReal: 62, kmConv: 60 },
  { origen: "MORENO", destino: "LUJAN", kmReal: 35, kmConv: 35 },
  { origen: "COL SANTA ROSA", destino: "PUERTO PIRAY", kmReal: 457, kmConv: 455 },
  { origen: "GARIN", destino: "EZEIZA", kmReal: 77, kmConv: 75 },
  { origen: "GENERAL PACHECO", destino: "FREYRE", kmReal: 558, kmConv: 560 },
  { origen: "MENDOZA", destino: "RESISTENCIA", kmReal: 1478, kmConv: 1480 },
  { origen: "SANFORD", destino: "SAN FRANCISCO", kmReal: 251, kmConv: 250 },
  { origen: "MUNRO", destino: "SAN FRANCISCO", kmReal: 547, kmConv: 545 },
  { origen: "GLEW", destino: "LANUS", kmReal: 21, kmConv: 20 },
  { origen: "MUNRO", destino: "GLEW", kmReal: 75, kmConv: 75 },
  { origen: "BELLA ITALIA", destino: "MENDOZA", kmReal: 856, kmConv: 855 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "SARANDI", kmReal: 46, kmConv: 45 },
  { origen: "TUCUMAN", destino: "DON TORCUATO", kmReal: 1229, kmConv: 1230 },
  { origen: "SANFORD", destino: "ROSARIO", kmReal: 83, kmConv: 85 },
  { origen: "CORDOBA", destino: "SANTIAGO DEL ESTERO", kmReal: 447, kmConv: 445 },
  { origen: "VALENTIN ALSINA", destino: "SANFORD", kmReal: 369, kmConv: 370 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "CAMPANA", kmReal: 217, kmConv: 215 },
  { origen: "RETIRO", destino: "EZEIZA", kmReal: 40, kmConv: 40 },
  { origen: "RIO CUARTO", destino: "TUCUMAN", kmReal: 764, kmConv: 765 },
  { origen: "ANGUIL", destino: "RIO CUARTO", kmReal: 427, kmConv: 425 },
  { origen: "ANGUIL", destino: "MENDOZA", kmReal: 766, kmConv: 765 },
  { origen: "RECREO", destino: "ARROYO SECO", kmReal: 217, kmConv: 215 },
  { origen: "MONTEVIDEO", destino: "COLONIA CAROYA", kmReal: 1066, kmConv: 1065 },
  { origen: "REMEDIOS DE ESCALADA", destino: "9 DE ABRIL", kmReal: 10, kmConv: 10 },
  { origen: "BURZACO", destino: "CAMPANA", kmReal: 103, kmConv: 105 },
  { origen: "ROSARIO", destino: "DOCK SUD", kmReal: 307, kmConv: 305 },
  { origen: "ARROYITO", destino: "ITUZAINGO", kmReal: 652, kmConv: 650 },
  { origen: "MUNRO", destino: "REMEDIOS DE ESCALADA", kmReal: 33, kmConv: 35 },
  { origen: "PARANÁ", destino: "MONTEVIDEO", kmReal: 624, kmConv: 625 },
  { origen: "ROSARIO", destino: "FREYRE", kmReal: 295, kmConv: 295 },
  { origen: "VILLA MERCEDES", destino: "ESCOBAR", kmReal: 710, kmConv: 710 },
  { origen: "PASO DEL REY", destino: "SAN ANDRES DE GILES", kmReal: 72, kmConv: 70 },
  { origen: "CHIVILCOY", destino: "9 DE ABRIL", kmReal: 167, kmConv: 165 },
  { origen: "GENERAL RODRIGUEZ", destino: "LANUS", kmReal: 58, kmConv: 60 },
  { origen: "GENERAL PACHECO", destino: "MUNRO", kmReal: 19, kmConv: 20 },
  { origen: "VILLA MARIA", destino: "VILLA SOLDATI", kmReal: 556, kmConv: 555 },
  { origen: "GENERAL ROCA", destino: "CHIVILCOY", kmReal: 939, kmConv: 940 },
  { origen: "BARROS BLANCOS", destino: "SAN FRANCISCO", kmReal: 810, kmConv: 810 },
  { origen: "COLONIA", destino: "BARROS BLANCOS", kmReal: 200, kmConv: 200 },
  { origen: "ELENA", destino: "SANTA FE", kmReal: 446, kmConv: 445 },
  { origen: "ALEJANDRO ROCA", destino: "ELENA", kmReal: 138, kmConv: 140 },
  { origen: "CARMEN DE ARECO", destino: "SAN JUSTO", kmReal: 138, kmConv: 140 },
  { origen: "MERLO", destino: "FREYRE", kmReal: 593, kmConv: 595 },
  { origen: "CAMPANA", destino: "MERLO", kmReal: 81, kmConv: 80 },
  { origen: "GENERAL PICO", destino: "VILLA SOLDATI", kmReal: 580, kmConv: 580 },
  { origen: "CONCORDIA", destino: "COLONIA CAROYA", kmReal: 701, kmConv: 700 },
  { origen: "9 DE ABRIL", destino: "ALEJANDRO ROCA", kmReal: 564, kmConv: 565 },
  { origen: "MUNRO", destino: "RANELAGH", kmReal: 54, kmConv: 55 },
  { origen: "FRAY  BENTOS", destino: "CORDOBA", kmReal: 715, kmConv: 715 },
  { origen: "MONTEVIDEO", destino: "FRAY  BENTOS", kmReal: 307, kmConv: 305 },
  { origen: "FRAY  BENTOS", destino: "MONTEVIDEO", kmReal: 307, kmConv: 305 },
  { origen: "GENERAL PACHECO", destino: "FRAY  BENTOS", kmReal: 260, kmConv: 260 },
  { origen: "GUATIMOZIN", destino: "ROSARIO", kmReal: 232, kmConv: 230 },
  { origen: "CORRIENTES", destino: "COL SANTA ROSA", kmReal: 159, kmConv: 160 },
  { origen: "ANGUIL", destino: "SAN LUIS", kmReal: 533, kmConv: 535 },
  { origen: "MANUEL CAMPOS", destino: "GENERAL PICO", kmReal: 146, kmConv: 145 },
  { origen: "ZONA PORTUARIA", destino: "RANELAGH", kmReal: 36, kmConv: 35 },
  { origen: "ZONA PORTUARIA", destino: "GENERAL RODRIGUEZ", kmReal: 71, kmConv: 70 },
  { origen: "SANTO TOME", destino: "ARROYO SECO", kmReal: 191, kmConv: 190 },
  { origen: "GARIN", destino: "GENERAL PACHECO", kmReal: 10, kmConv: 10 },
  { origen: "SAAVEDRA", destino: "SARANDI", kmReal: 28, kmConv: 30 },
  { origen: "ZARATE", destino: "GENERAL ROCA", kmReal: 1085, kmConv: 1085 },
  { origen: "VILLA TESEI", destino: "VALENTIN ALSINA", kmReal: 26, kmConv: 25 },
  { origen: "CAPITAN CORTEZ", destino: "VILLA SOLDATI", kmReal: 10, kmConv: 10 },
  { origen: "PARANÁ", destino: "COLONIA", kmReal: 494, kmConv: 495 },
  { origen: "VILLA MERCEDES", destino: "LAVALLOL", kmReal: 706, kmConv: 705 },
  { origen: "LUJAN", destino: "VILLA SOLDATI", kmReal: 66, kmConv: 65 },
  { origen: "WILLIAM MORRIS", destino: "BARRACAS", kmReal: 35, kmConv: 35 },
  { origen: "ARRECIFES", destino: "VILLA SOLDATI", kmReal: 186, kmConv: 185 },
  { origen: "CAMPANA", destino: "ARRECIFES", kmReal: 123, kmConv: 125 },
  { origen: "ZONA PORTUARIA", destino: "SAN JUSTO", kmReal: 31, kmConv: 30 },
  { origen: "VIRREY DEL PINO", destino: "9 DE ABRIL", kmReal: 35, kmConv: 35 },
  { origen: "CONCORDIA", destino: "VIRREY DEL PINO", kmReal: 468, kmConv: 470 },
  { origen: "ESCOBAR", destino: "LUJAN", kmReal: 55, kmConv: 55 },
  { origen: "RAFAELA", destino: "WILLIAM MORRIS", kmReal: 529, kmConv: 530 },
  { origen: "ANGUIL", destino: "VILLA MERCEDES", kmReal: 442, kmConv: 440 },
  { origen: "CIUDADELA", destino: "RAFAELA", kmReal: 537, kmConv: 535 },
  { origen: "EZEIZA", destino: "CIUDADELA", kmReal: 30, kmConv: 30 },
  { origen: "VILLA NUEVA", destino: "SAN FRANCISCO", kmReal: 167, kmConv: 165 },
  { origen: "RIO CUARTO", destino: "VILLA NUEVA", kmReal: 132, kmConv: 130 },
  { origen: "ESPERANZA", destino: "ZONA PORTUARIA", kmReal: 491, kmConv: 490 },
  { origen: "CAPITAN CORTEZ", destino: "SAN FRANCISCO", kmReal: 565, kmConv: 565 },
  { origen: "MORENO", destino: "RAMOS MEJIA", kmReal: 28, kmConv: 30 },
  { origen: "VILLA SOLDATI", destino: "CAPITAN CORTEZ", kmReal: null, kmConv: 10 },
  { origen: "ESPERANZA", destino: "CAPITAN CORTEZ", kmReal: 495, kmConv: 495 },
  { origen: "CAPITAN CORTEZ", destino: "ESPERANZA", kmReal: 495, kmConv: 495 },
  { origen: "GENERAL PACHECO", destino: "MONTEVIDEO", kmReal: 537, kmConv: 535 },
  { origen: "BAHIA BLANCA", destino: "GENERAL PACHECO", kmReal: 658, kmConv: 660 },
  { origen: "RETIRO", destino: "SAN ANDRES DE GILES", kmReal: 115, kmConv: 115 },
  { origen: "SAN RAFAEL", destino: "DOCK SUD", kmReal: 987, kmConv: 990 },
  { origen: "BARRACAS", destino: "SAN RAFAEL", kmReal: 985, kmConv: 985 },
  { origen: "ZONA PORTUARIA", destino: "ESPERANZA", kmReal: 491, kmConv: 490 },
  { origen: "BASAVILBASO", destino: "GENERAL PACHECO", kmReal: 327, kmConv: 325 },
  { origen: "GENERAL PACHECO", destino: "ZARATE", kmReal: 57, kmConv: 55 },
  { origen: "DOCK SUD", destino: "ESPERANZA", kmReal: 510, kmConv: 510 },
  { origen: "DOCK SUD", destino: "SANTA FE", kmReal: 476, kmConv: 475 },
  { origen: "ARROYITO", destino: "MONTEVIDEO", kmReal: 903, kmConv: 905 },
  { origen: "CORDOBA", destino: "SINSACATE", kmReal: 69, kmConv: 70 },
  { origen: "MERLO", destino: "VILLA MERCEDES", kmReal: 197, kmConv: 195 },
  { origen: "ESCOBAR", destino: "ROSARIO", kmReal: 247, kmConv: 245 },
  { origen: "CHASCOMUS", destino: "MERLO", kmReal: 939, kmConv: 940 },
  { origen: "9 DE ABRIL", destino: "ESCOBAR", kmReal: 74, kmConv: 75 },
  { origen: "CARLOS SPEGAZZINI", destino: "SAN JUSTO", kmReal: 34, kmConv: 35 },
  { origen: "HAEDO", destino: "SAN FRANCISCO", kmReal: 570, kmConv: 570 },
  { origen: "CAMPANA", destino: "RECREO", kmReal: 406, kmConv: 405 },
  { origen: "TIO PUJIO", destino: "ROSARIO", kmReal: 275, kmConv: 275 },
  { origen: "LANUS", destino: "BARADERO", kmReal: 165, kmConv: 165 },
  { origen: "TIO PUJIO", destino: "CAMPANA", kmReal: 495, kmConv: 495 },
  { origen: "BASAVILBASO", destino: "DOCK SUD", kmReal: 370, kmConv: 370 },
  { origen: "DOCK SUD", destino: "BASAVILBASO", kmReal: 370, kmConv: 370 },
  { origen: "CHACABUCO", destino: "ROSARIO", kmReal: 237, kmConv: 235 },
  { origen: "RAMOS MEJIA", destino: "LANUS", kmReal: 22, kmConv: 20 },
  { origen: "GALVEZ", destino: "RAMOS MEJIA", kmReal: 430, kmConv: 430 },
  { origen: "MENDOZA", destino: "TORTUGUITAS", kmReal: 1052, kmConv: 1055 },
  { origen: "ORAN", destino: "TAPIALES", kmReal: 1665, kmConv: 1665 },
  { origen: "JUJUY", destino: "ORAN", kmReal: 241, kmConv: 240 },
  { origen: "VILLA DEL PARQUE", destino: "WILDE", kmReal: 31, kmConv: 30 },
  { origen: "GUAYMALLEN", destino: "9 DE ABRIL", kmReal: 1044, kmConv: 1045 },
  { origen: "FORMOSA", destino: "CONCORDIA", kmReal: 690, kmConv: 690 },
  { origen: "LOS CARDALES", destino: "ZARATE", kmReal: 30, kmConv: 30 },
  { origen: "ALSINA", destino: "SAN ANDRES DE GILES", kmReal: 83, kmConv: 85 },
  { origen: "DESPE&#209;ADEROS", destino: "TIO PUJIO", kmReal: 154, kmConv: 155 },
  { origen: "BELLA ITALIA", destino: "GUAYMALLEN", kmReal: 852, kmConv: 850 },
  { origen: "GENERAL RODRIGUEZ", destino: "PABLO NOGUES", kmReal: 30, kmConv: 30 },
  { origen: "MONTEVIDEO", destino: "DESPE&#209;ADEROS", kmReal: 1028, kmConv: 1030 },
  { origen: "SAN FRANCISCO", destino: "LOMA HERMOSA", kmReal: 548, kmConv: 550 },
  { origen: "TUCUMAN", destino: "BELLA ITALIA", kmReal: 680, kmConv: 680 },
  { origen: "CONCORDIA", destino: "ALSINA", kmReal: 392, kmConv: 390 },
  { origen: "SAN LUIS", destino: "COLONIA CAROYA", kmReal: 444, kmConv: 445 },
  { origen: "LAVALLOL", destino: "9 DE ABRIL", kmReal: 10, kmConv: 10 },
  { origen: "SAN FRANCISCO", destino: "LAFERRERE", kmReal: 564, kmConv: 565 },
  { origen: "LOS CARDALES", destino: "MONTEVIDEO", kmReal: 524, kmConv: 525 },
  { origen: "GENERAL PACHECO", destino: "LOS CARDALES", kmReal: 43, kmConv: 45 },
  { origen: "RETIRO", destino: "GENERAL RODRIGUEZ", kmReal: 62, kmConv: 60 },
  { origen: "VALENTIN ALSINA", destino: "SAN JUSTO", kmReal: 21, kmConv: 20 },
  { origen: "PABLO PODESTA", destino: "MORENO", kmReal: 22, kmConv: 20 },
  { origen: "CONCORDIA", destino: "VALENTIN ALSINA", kmReal: 439, kmConv: 440 },
  { origen: "VILLA TESEI", destino: "WILDE", kmReal: 40, kmConv: 40 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN ANDRES DE GILES", kmReal: 53, kmConv: 55 },
  { origen: "CAMPANA", destino: "SARANDI", kmReal: 90, kmConv: 90 },
  { origen: "SAN LUIS", destino: "SAN FRANCISCO", kmReal: 514, kmConv: 515 },
  { origen: "PASO DEL REY", destino: "ROSARIO", kmReal: 302, kmConv: 300 },
  { origen: "MENDOZA", destino: "GARIN", kmReal: 1055, kmConv: 1055 },
  { origen: "GENERAL RODRIGUEZ", destino: "PABLO PODESTA", kmReal: 38, kmConv: 40 },
  { origen: "GALVEZ", destino: "GENERAL RODRIGUEZ", kmReal: 444, kmConv: 445 },
  { origen: "RETIRO", destino: "CONCEPCION DEL URUGUAY", kmReal: 294, kmConv: 295 },
  { origen: "RAMOS MEJIA", destino: "PILAR", kmReal: null, kmConv: 55 },
  { origen: "LUIS BURELA", destino: "ZONA PORTUARIA", kmReal: 1505, kmConv: 1505 },
  { origen: "CORDOBA", destino: "LUIS BURELA", kmReal: 922, kmConv: 920 },
  { origen: "PILAR", destino: "SAN LUIS", kmReal: 778, kmConv: 780 },
  { origen: "LOMAS DE ZAMORA", destino: "LA PLATA", kmReal: 80, kmConv: 80 },
  { origen: "GARIN", destino: "LA PLATA", kmReal: 101, kmConv: 100 },
  { origen: "COL SANTA ROSA", destino: "PILAR", kmReal: 649, kmConv: 650 },
  { origen: "OBERA", destino: "COL SANTA ROSA", kmReal: 355, kmConv: 355 },
  { origen: "VILLA CRESPO", destino: "LANUS", kmReal: 20, kmConv: 20 },
  { origen: "PILAR", destino: "PARANÁ", kmReal: 459, kmConv: 460 },
  { origen: "ESPERANZA", destino: "DOCK SUD", kmReal: 500, kmConv: 500 },
  { origen: "SARANDI", destino: "ESPERANZA", kmReal: 503, kmConv: 505 },
  { origen: "DOCK SUD", destino: "VILLA DEL TOTORAL", kmReal: 783, kmConv: 785 },
  { origen: "SANTA ROSA", destino: "NEUQUEN", kmReal: 529, kmConv: 530 },
  { origen: "RAFAELA", destino: "SANTA ROSA", kmReal: 849, kmConv: 850 },
  { origen: "TORTUGUITAS", destino: "EZEIZA", kmReal: 69, kmConv: 70 },
  { origen: "ISIDRO CASANOVA", destino: "CAMPANA", kmReal: 87, kmConv: 85 },
  { origen: "CONSTITUCION", destino: "TORTUGUITAS", kmReal: 48, kmConv: 50 },
  { origen: "SANTA RITA", destino: "PUERTO PIRAY", kmReal: 151, kmConv: 150 },
  { origen: "SAN SALVADOR", destino: "ESPERANZA", kmReal: 275, kmConv: 275 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "SAN SALVADOR", kmReal: 114, kmConv: 115 },
  { origen: "VALENTIN ALSINA", destino: "SAN JORGE", kmReal: 505, kmConv: 505 },
  { origen: "PABLO NOGUES", destino: "SAN PEDRO", kmReal: 140, kmConv: 140 },
  { origen: "CARLOS PAZ", destino: "SAN FRANCISCO", kmReal: 264, kmConv: 265 },
  { origen: "SAN PEDRO", destino: "SAUCE VIEJO", kmReal: 292, kmConv: 290 },
  { origen: "ZARATE", destino: "SAN PEDRO", kmReal: 87, kmConv: 90 },
  { origen: "TIGRE", destino: "SAN FRANCISCO", kmReal: 547, kmConv: 545 },
  { origen: "RAFAELA", destino: "PUERTO ESPERANZA", kmReal: 1129, kmConv: 1130 },
  { origen: "ZONA PORTUARIA", destino: "MUNRO", kmReal: 18, kmConv: 18 },
  { origen: "JUNIN", destino: "MUNRO", kmReal: 265, kmConv: 265 },
  { origen: "VALENTIN ALSINA", destino: "SAN FRANCISCO", kmReal: 595, kmConv: 595 },
  { origen: "VILLA SOLDATI", destino: "VILLA ALSINA", kmReal: 5, kmConv: 5 },
  { origen: "GENERAL RODRIGUEZ", destino: "SAN NICOLAS", kmReal: 218, kmConv: 220 },
  { origen: "BURZACO", destino: "GENERAL RODRIGUEZ", kmReal: 67, kmConv: 65 },
  { origen: "PASO DEL REY", destino: "DOCK SUD", kmReal: 46, kmConv: 45 },
  { origen: "SARANDI", destino: "GOBERNADOR CRESPO", kmReal: 627, kmConv: 630 },
  { origen: "GOBERNADOR VIRASORO", destino: "POSADAS", kmReal: 94, kmConv: 95 },
  { origen: "POSADAS", destino: "SANTA RITA", kmReal: 155, kmConv: 155 },
  { origen: "VILLA LUZURIAGA", destino: "TORTUGUITAS", kmReal: 51, kmConv: 50 },
  { origen: "LA PAMPA", destino: "NEUQUEN", kmReal: 381, kmConv: 380 },
  { origen: "NEUQUEN", destino: "BARILOCHE", kmReal: 439, kmConv: 440 },
  { origen: "GENERAL PACHECO", destino: "MATADEROS", kmReal: 37, kmConv: 40 },
  { origen: "SAN FRANCISCO", destino: "VILLA LUZURIAGA", kmReal: 568, kmConv: 570 },
  { origen: "JUNIN", destino: "TORTUGUITAS", kmReal: 242, kmConv: 240 },
  { origen: "EZEIZA", destino: "MORON", kmReal: null, kmConv: 30 },
  { origen: "LUCILA DEL MAR", destino: "9 DE ABRIL", kmReal: 379, kmConv: 380 },
  { origen: "LAVALLOL", destino: "EZEIZA", kmReal: null, kmConv: 10 },
  { origen: "BARRACAS", destino: "LLAVALLOL", kmReal: 20, kmConv: 20 },
  { origen: "RAFAELA", destino: "LA LUCILA DEL MAR", kmReal: 800, kmConv: 800 },
  { origen: "CASEROS", destino: "SAN FRANCISCO", kmReal: 558, kmConv: 560 },
  { origen: "COLONIA CAROYA", destino: "MORENO", kmReal: 744, kmConv: 745 },
  { origen: "LUJAN", destino: "QUILMES", kmReal: 93, kmConv: 95 },
  { origen: "PARANÁ", destino: "LIBERTAD", kmReal: 571, kmConv: 570 },
  { origen: "CATRILO", destino: "MALVINAS ARGENTINAS", kmReal: 546, kmConv: 545 },
  { origen: "CAMPANA", destino: "CATRILO", kmReal: 513, kmConv: 515 },
  { origen: "LEZAMA", destino: "EZEIZA", kmReal: 159, kmConv: 160 },
  { origen: "3 DE FEBRERO", destino: "VILLA SOLDATI", kmReal: 25, kmConv: 25 },
  { origen: "TORTUGUITAS", destino: "MUNRO", kmReal: 27, kmConv: 30 },
  { origen: "GARIN", destino: "MENDOZA", kmReal: 1054, kmConv: 1055 },
  { origen: "DOCK SUD", destino: "GARIN", kmReal: 51, kmConv: 50 },
  { origen: "VILLA MERCEDES", destino: "3 DE FEBRERO", kmReal: 700, kmConv: 700 },
  { origen: "SANTO TOME", destino: "APÓSTOLES", kmReal: 726, kmConv: 725 },
  { origen: "RECREO", destino: "AROCENA", kmReal: 82, kmConv: 80 },
  { origen: "VILLA MERCEDES", destino: "MONTEVIDEO", kmReal: 1145, kmConv: 1145 },
  { origen: "TUCUMAN", destino: "FRANCK", kmReal: 768, kmConv: 770 },
  { origen: "FRIAS", destino: "TUCUMAN", kmReal: 215, kmConv: 215 },
  { origen: "AVELLANEDA", destino: "RETIRO", kmReal: 8, kmConv: 10 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "MORENO", kmReal: 56, kmConv: 55 },
  { origen: "MENDOZA", destino: "BRINKMANN", kmReal: 835, kmConv: 835 },
  { origen: "WILDE", destino: "BRINKMANN", kmReal: 645, kmConv: 645 },
  { origen: "CAMPANA", destino: "WILDE", kmReal: 95, kmConv: 95 },
  { origen: "MORON", destino: "MORENO", kmReal: 20, kmConv: 20 },
  { origen: "CORDOBA", destino: "MORON", kmReal: 702, kmConv: 700 },
  { origen: "COLONIA CAROYA", destino: "MONTEVIDEO", kmReal: 968, kmConv: 970 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "GENERAL RODRIGUEZ", kmReal: 1514, kmConv: 1515 },
  { origen: "VENADO TUERTO", destino: "ROSARIO", kmReal: 167, kmConv: 165 },
  { origen: "LUJAN", destino: "CAMPANA", kmReal: 48, kmConv: 50 },
  { origen: "LAFERRERE", destino: "EZEIZA", kmReal: 26, kmConv: 25 },
  { origen: "CAPITAN CORTEZ", destino: "CORDOBA", kmReal: 700, kmConv: 700 },
  { origen: "ZARATE", destino: "CAPITAN CORTEZ", kmReal: null, kmConv: 95 },
  { origen: "BARRACAS", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1549, kmConv: 1550 },
  { origen: "LA FRANCIA", destino: "MALAGUE&#209;O", kmReal: 188, kmConv: 200 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "BERAZATEGUI", kmReal: 63, kmConv: 65 },
  { origen: "PABLO NOGUES", destino: "ESTEBAN ECHEVERRIA", kmReal: 69, kmConv: 70 },
  { origen: "SANTA ROSA", destino: "VILLA MERCEDES", kmReal: 430, kmConv: 430 },
  { origen: "LANUS", destino: "LA MATANZA", kmReal: 51, kmConv: 50 },
  { origen: "GALVEZ", destino: "LANUS", kmReal: 443, kmConv: 445 },
  { origen: "VILLA DEL ROSARIO", destino: "MALAGUE&#209;O", kmReal: 102, kmConv: 100 },
  { origen: "LEZAMA", destino: "VILLA SOLDATI", kmReal: 172, kmConv: 170 },
  { origen: "VILLA CRESPO", destino: "TAPIALES", kmReal: 17, kmConv: 15 },
  { origen: "CORDOBA", destino: "LEZAMA", kmReal: 857, kmConv: 855 },
  { origen: "CHACABUCO", destino: "VILLA SOLDATI", kmReal: 204, kmConv: 205 },
  { origen: "WILDE", destino: "SAN FRANCISCO", kmReal: 578, kmConv: 580 },
  { origen: "NOGOYÁ", destino: "ARROYO SECO", kmReal: 147, kmConv: 145 },
  { origen: "SAN JUAN", destino: "MENDOZA", kmReal: 170, kmConv: 170 },
  { origen: "VICENTE LOPEZ", destino: "MORON", kmReal: null, kmConv: 25 },
  { origen: "CIUDADELA", destino: "ZARATE", kmReal: null, kmConv: 88 },
  { origen: "BURZACO", destino: "LA PLATA", kmReal: 59, kmConv: 60 },
  { origen: "BERNARDINO RIVARAVIA", destino: "BARRACAS", kmReal: 1123, kmConv: 1125 },
  { origen: "OBERA", destino: "BERNARDINO RIVARAVIA", kmReal: 87, kmConv: 85 },
  { origen: "SAN FRANCISCO", destino: "SAN JUAN", kmReal: 801, kmConv: 800 },
  { origen: "CAMPANA", destino: "MATADEROS", kmReal: 81, kmConv: 84 },
  { origen: "CARMEN DE ARECO", destino: "BARRACAS", kmReal: 148, kmConv: 150 },
  { origen: "LANUS", destino: "PORTE&#209;A", kmReal: 623, kmConv: 625 },
  { origen: "BARADERO", destino: "VILLA CARLOS PAZ", kmReal: 596, kmConv: 595 },
  { origen: "PABLO NOGUES", destino: "GENERAL RODRIGUEZ", kmReal: 29, kmConv: 30 },
  { origen: "CARCARA&#209;A", destino: "RAFAELA", kmReal: 216, kmConv: 215 },
  { origen: "MENDOZA", destino: "SANTA FE", kmReal: 912, kmConv: 910 },
  { origen: "GENERAL ROCA", destino: "MENDOZA", kmReal: 829, kmConv: 830 },
  { origen: "CIUDADELA", destino: "PILAR", kmReal: 53, kmConv: 55 },
  { origen: "HAEDO", destino: "GENERAL RODRIGUEZ", kmReal: 35, kmConv: 35 },
  { origen: "DON TORCUATO", destino: "GENERAL RODRIGUEZ", kmReal: 48, kmConv: 50 },
  { origen: "LA MATANZA", destino: "HAEDO", kmReal: 21, kmConv: 20 },
  { origen: "CORDOBA", destino: "REMEDIOS DE ESCALADA", kmReal: 725, kmConv: 725 },
  { origen: "COLONIA CAROYA", destino: "MALAGUE&#209;O", kmReal: 67, kmConv: 65 },
  { origen: "RETIRO", destino: "TORTUGUITAS", kmReal: 44, kmConv: 45 },
  { origen: "CAMPANA", destino: "MALAGUE&#209;O", kmReal: 640, kmConv: 640 },
  { origen: "MALAGUE&#209;O", destino: "CAMPANA", kmReal: 640, kmConv: 640 },
  { origen: "SAN FRANCISCO", destino: "MALAGUE&#209;O", kmReal: 247, kmConv: 245 },
  { origen: "SAN JAVIER", destino: "PUERTO PIRAY", kmReal: 233, kmConv: 235 },
  { origen: "RECONQUISTA", destino: "SAN JORGE", kmReal: 473, kmConv: 475 },
  { origen: "PILAR", destino: "RECONQUISTA", kmReal: 746, kmConv: 745 },
  { origen: "NEUQUEN", destino: "MENDOZA", kmReal: 788, kmConv: 790 },
  { origen: "RETIRO", destino: "GENERAL ROCA", kmReal: 1101, kmConv: 1100 },
  { origen: "GENERAL PACHECO", destino: "SAN ANDRES DE GILES", kmReal: null, kmConv: 90 },
  { origen: "BENAVIDEZ", destino: "VILLA SOLDATI", kmReal: null, kmConv: 50 },
  { origen: "FREYRE", destino: "BENAVIDEZ", kmReal: 576, kmConv: 575 },
  { origen: "RAFAELA", destino: "SAN JAVIER", kmReal: 889, kmConv: 890 },
  { origen: "SAN FRANCISCO", destino: "CORRIENTES", kmReal: 700, kmConv: 700 },
  { origen: "LUJAN DE CUYO", destino: "GENERAL PACHECO", kmReal: 1074, kmConv: 1075 },
  { origen: "LAFERRERE", destino: "TORTUGUITAS", kmReal: 60, kmConv: 60 },
  { origen: "CORDOBA", destino: "ITUZAINGO", kmReal: 697, kmConv: 695 },
  { origen: "MARCOS PAZ", destino: "PILAR", kmReal: null, kmConv: 65 },
  { origen: "PORTE&#209;A", destino: "ESCOBAR", kmReal: 593, kmConv: 595 },
  { origen: "SUSANA", destino: "BELL VILLE", kmReal: 253, kmConv: 255 },
  { origen: "LA PLATA", destino: "LOBOS", kmReal: 124, kmConv: 125 },
  { origen: "DOCK SUD", destino: "RETIRO", kmReal: 9, kmConv: 10 },
  { origen: "NECOCHEA", destino: "LANUS", kmReal: 509, kmConv: 510 },
  { origen: "VENADO TUERTO", destino: "DOCK SUD", kmReal: 379, kmConv: 380 },
  { origen: "AVELLANEDA", destino: "SAN JORGE", kmReal: 515, kmConv: 515 },
  { origen: "BARRACAS", destino: "INGENIERO LUIGGI", kmReal: 641, kmConv: 640 },
  { origen: "RETIRO", destino: "BARRACAS", kmReal: null, kmConv: 10 },
  { origen: "MAR DEL PLATA", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1947, kmConv: 1945 },
  { origen: "BURZACO", destino: "MAR DEL PLATA", kmReal: 414, kmConv: 415 },
  { origen: "REMEDIOS DE ESCALADA", destino: "MONTE GRANDE", kmReal: 16, kmConv: 15 },
  { origen: "DOCK SUD", destino: "VENADO TUERTO", kmReal: 379, kmConv: 380 },
  { origen: "PABLO NOGUES", destino: "ITUZAINGO", kmReal: 39, kmConv: 40 },
  { origen: "CAMPANA", destino: "MORON", kmReal: null, kmConv: 90 },
  { origen: "PASO DEL REY", destino: "LANUS", kmReal: null, kmConv: 45 },
  { origen: "TEMPERLEY", destino: "REMEDIOS DE ESCALADA", kmReal: null, kmConv: 10 },
  { origen: "POZO DEL MOLLE", destino: "DOCK SUD", kmReal: 600, kmConv: 600 },
  { origen: "SARANDI", destino: "POZO DEL MOLLE", kmReal: 602, kmConv: 605 },
  { origen: "VIRREYES", destino: "PABLO NOGUES", kmReal: 18, kmConv: 20 },
  { origen: "MUNRO", destino: "VILLA URQUIZA", kmReal: 8, kmConv: 10 },
  { origen: "CIUDADELA", destino: "MONTE GRANDE", kmReal: 31, kmConv: 30 },
  { origen: "EL COLORADO", destino: "SAN FRANCISCO", kmReal: 782, kmConv: 780 },
  { origen: "POSADAS", destino: "SAN VICENTE", kmReal: 190, kmConv: 190 },
  { origen: "CARMEN DE ARECO", destino: "9 DE ABRIL", kmReal: 146, kmConv: 145 },
  { origen: "TIGRE", destino: "PABLO NOGUES", kmReal: null, kmConv: 25 },
  { origen: "LUJAN", destino: "GENERAL RODRIGUEZ", kmReal: 18, kmConv: 20 },
  { origen: "ESCOBAR", destino: "LA PLATA", kmReal: 112, kmConv: 110 },
  { origen: "GARIN", destino: "PABLO NOGUES", kmReal: 10, kmConv: 10 },
  { origen: "ZONA PORTUARIA", destino: "EL COLORADO", kmReal: 1074, kmConv: 1075 },
  { origen: "LANUS", destino: "ESCOBAR", kmReal: 66, kmConv: 65 },
  { origen: "PUERTO ESPERANZA", destino: "SAN LUIS", kmReal: 1768, kmConv: 1770 },
  { origen: "ESTEBAN ECHEVERRIA", destino: "SAN ANDRES DE GILES", kmReal: 141, kmConv: 140 },
  { origen: "VILLA URQUIZA", destino: "RETIRO", kmReal: null, kmConv: 20 },
  { origen: "HURLINGHAM", destino: "MUNRO", kmReal: null, kmConv: 25 },
  { origen: "CORDOBA", destino: "HURLINGHAM", kmReal: 684, kmConv: 685 },
  { origen: "EL JAGUEL", destino: "BARRACAS", kmReal: null, kmConv: 35 },
  { origen: "GALVEZ", destino: "ISIDRO CASANOVA", kmReal: 435, kmConv: 435 },
  { origen: "CATRILO", destino: "VILLA SOLDATI", kmReal: 522, kmConv: 520 },
  { origen: "RETIRO", destino: "OLAVARRIA", kmReal: null, kmConv: 5 },
  { origen: "SARANDI", destino: "RETIRO", kmReal: 13, kmConv: 15 },
  { origen: "DOCK SUD", destino: "MUNRO", kmReal: null, kmConv: 30 },
  { origen: "GUATIMOZIN", destino: "SAN ANDRES DE GILES", kmReal: 348, kmConv: 350 },
  { origen: "VALENTIN ALSINA", destino: "GUATIMOZIN", kmReal: 453, kmConv: 455 },
  { origen: "LONGCHAMPS", destino: "VALENTIN ALSINA", kmReal: 30, kmConv: 30 },
  { origen: "AVELLANEDA", destino: "CATRILO", kmReal: 532, kmConv: 530 },
  { origen: "BERNAL OESTE", destino: "AVELLANEDA", kmReal: null, kmConv: 15 },
  { origen: "VICENTE LOPEZ", destino: "HAEDO", kmReal: null, kmConv: 25 },
  { origen: "TEMPERLEY", destino: "MONTE GRANDE", kmReal: null, kmConv: 12 },
  { origen: "GUALEGUAY", destino: "SANTO TOME", kmReal: 316, kmConv: 315 },
  { origen: "MARCOS JUAREZ", destino: "SAN FRANCISCO", kmReal: 230, kmConv: 230 },
  { origen: "MENDOZA", destino: "LA FRANCIA", kmReal: 750, kmConv: 750 },
  { origen: "CHACARITA", destino: "MATADEROS", kmReal: null, kmConv: 15 },
  { origen: "CAMPANA", destino: "CARLOS SPEGAZZINI", kmReal: 119, kmConv: 120 },
  { origen: "PASO DEL REY", destino: "EZEIZA", kmReal: null, kmConv: 40 },
  { origen: "VILLA MERCEDES", destino: "MALVINAS ARGENTINAS", kmReal: 713, kmConv: 715 },
  { origen: "CATRILO", destino: "RAFAELA", kmReal: 786, kmConv: 785 },
  { origen: "BAHIA BLANCA", destino: "CATRILO", kmReal: 336, kmConv: 335 },
  { origen: "BERAZATEGUI", destino: "MARCOS JUAREZ", kmReal: 470, kmConv: 470 },
  { origen: "SARANDI", destino: "RANELAGH", kmReal: 25, kmConv: 25 },
  { origen: "BERAZATEGUI", destino: "BURZACO", kmReal: 22, kmConv: 20 },
  { origen: "CARMEN DE ARECO", destino: "MONTE GRANDE", kmReal: 160, kmConv: 160 },
  { origen: "BELLA VISTA", destino: "ZONA PORTUARIA", kmReal: 1219, kmConv: 1220 },
  { origen: "SALTA", destino: "BELLA VISTA", kmReal: 341, kmConv: 340 },
  { origen: "CHACARITA", destino: "RETIRO", kmReal: null, kmConv: 10 },
  { origen: "ESCOBAR", destino: "VILLA SOLDATI", kmReal: null, kmConv: 65 },
  { origen: "CAMPANA", destino: "BAHIA BLANCA", kmReal: 682, kmConv: 680 },
  { origen: "CHACARITA", destino: "CAMPANA", kmReal: null, kmConv: 75 },
  { origen: "CHACARITA", destino: "VILLA MERCEDES", kmReal: 736, kmConv: 735 },
  { origen: "MORENO", destino: "CHACARITA", kmReal: 35, kmConv: 35 },
  { origen: "CHACARITA", destino: "GARIN", kmReal: null, kmConv: 35 },
  { origen: "RETIRO", destino: "MAR DEL PLATA", kmReal: 416, kmConv: 415 },
  { origen: "LONGCHAMPS", destino: "SARANDI", kmReal: 28, kmConv: 30 },
  { origen: "MAR DEL PLATA", destino: "SARANDI", kmReal: 405, kmConv: 405 },
  { origen: "LONGCHAMPS", destino: "BARRACAS", kmReal: null, kmConv: 25 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "LONGCHAMPS", kmReal: 1564, kmConv: 1565 },
  { origen: "PILAR", destino: "ALTA GRACIA", kmReal: 666, kmConv: 665 },
  { origen: "CAMPANA", destino: "MAR DEL PLATA", kmReal: 495, kmConv: 495 },
  { origen: "MORON", destino: "ZARATE", kmReal: null, kmConv: 100 },
  { origen: "SAN JUSTO", destino: "TIGRE", kmReal: null, kmConv: 35 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "CHACARITA", kmReal: 1549, kmConv: 1550 },
  { origen: "MENDOZA", destino: "MORON", kmReal: 1026, kmConv: 1025 },
  { origen: "VILLA TESEI", destino: "RETIRO", kmReal: null, kmConv: 30 },
  { origen: "CORRAL DE BUSTOS", destino: "SAN FRANCISCO", kmReal: 304, kmConv: 305 },
  { origen: "GENERAL PACHECO", destino: "MONTE GRANDE", kmReal: null, kmConv: 60 },
  { origen: "AVELLANEDA", destino: "LANUS", kmReal: 6, kmConv: 5 },
  { origen: "CORDOBA", destino: "AVELLANEDA", kmReal: 758, kmConv: 760 },
  { origen: "GENERAL PACHECO", destino: "SARANDI", kmReal: null, kmConv: 55 },
  { origen: "MENDOZA", destino: "GENERAL PACHECO", kmReal: 1063, kmConv: 1065 },
  { origen: "BAJO HONDO", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 422, kmConv: 420 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "BAJO HONDO", kmReal: 422, kmConv: 420 },
  { origen: "TIGRE", destino: "BAJO HONDO", kmReal: 513, kmConv: 515 },
  { origen: "SUSANA", destino: "PERGAMINO", kmReal: 344, kmConv: 345 },
  { origen: "MORENO", destino: "VILLA LUZURIAGA", kmReal: null, kmConv: 20 },
  { origen: "MONTE GRANDE", destino: "TIGRE", kmReal: null, kmConv: 60 },
  { origen: "SAN GUILLERMO", destino: "PORTE&#209;A", kmReal: null, kmConv: 80 },
  { origen: "JUJUY", destino: "CORDOBA", kmReal: 900, kmConv: 900 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "SAN JUSTO", kmReal: 1540, kmConv: 1540 },
  { origen: "RETIRO", destino: "TIGRE", kmReal: null, kmConv: 30 },
  { origen: "EZEIZA", destino: "TIGRE", kmReal: null, kmConv: 55 },
  { origen: "GENERAL PIRAN", destino: "9 DE ABRIL", kmReal: 350, kmConv: 350 },
  { origen: "ZONA PORTUARIA", destino: "MENDOZA", kmReal: 1090, kmConv: 1090 },
  { origen: "CATAMARCA", destino: "JUJUY", kmReal: 563, kmConv: 565 },
  { origen: "CORDOBA", destino: "GRAND BOURG", kmReal: 665, kmConv: 665 },
  { origen: "GRAND BOURG", destino: "MUNRO", kmReal: 26, kmConv: 25 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "RETIRO", kmReal: 1534, kmConv: 1535 },
  { origen: "NECOCHEA", destino: "VILLA SOLDATI", kmReal: 497, kmConv: 500 },
  { origen: "ZONA PORTUARIA", destino: "DON TORCUATO", kmReal: null, kmConv: 30 },
  { origen: "MARCOS PAZ", destino: "EZEIZA", kmReal: 43, kmConv: 45 },
  { origen: "SAN JUSTO", destino: "EL PALOMAR", kmReal: 10, kmConv: 10 },
  { origen: "RAFAELA", destino: "NECOCHEA", kmReal: 984, kmConv: 985 },
  { origen: "SAN SALVADOR", destino: "EZEIZA", kmReal: 424, kmConv: 425 },
  { origen: "PASO DEL REY", destino: "9 DE ABRIL", kmReal: null, kmConv: 45 },
  { origen: "MORENO", destino: "LOMAS DE ZAMORA", kmReal: 42, kmConv: 40 },
  { origen: "PILAR", destino: "RANELAGH", kmReal: 102, kmConv: 100 },
  { origen: "TIGRE", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 1530, kmConv: 1530 },
  { origen: "PASO DEL REY", destino: "TIGRE", kmReal: null, kmConv: 40 },
  { origen: "SARANDI", destino: "DOCK SUD", kmReal: null, kmConv: 4 },
  { origen: "SAN JERONIMO", destino: "ROSARIO", kmReal: 35, kmConv: 35 },
  { origen: "GENERAL PACHECO", destino: "RETIRO", kmReal: 35, kmConv: 35 },
  { origen: "LAS GRUTAS", destino: "ZARATE", kmReal: 1123, kmConv: 1125 },
  { origen: "RETIRO", destino: "LAS GRUTAS", kmReal: 1058, kmConv: 1060 },
  { origen: "JUNIN", destino: "LANUS", kmReal: 267, kmConv: 265 },
  { origen: "EZEIZA", destino: "DOCK SUD", kmReal: 40, kmConv: 40 },
  { origen: "LAFERRERE", destino: "VILLA SOLDATI", kmReal: 7, kmConv: 5 },
  { origen: "VILLA ALLENDE", destino: "TIO PUJIO", kmReal: 151, kmConv: 150 },
  { origen: "SANTIAGO DEL ESTERO", destino: "CORDOBA", kmReal: 437, kmConv: 440 },
  { origen: "LIBERTAD", destino: "VILLAGUAY", kmReal: 436, kmConv: 435 },
  { origen: "VILLAGUAY", destino: "BARADERO", kmReal: 357, kmConv: 360 },
  { origen: "LIBERTAD", destino: "BARADERO", kmReal: 512, kmConv: 510 },
  { origen: "GRAND BOURG", destino: "SAN LUIS", kmReal: 798, kmConv: 800 },
  { origen: "ESCOBAR", destino: "LAFERRERE", kmReal: null, kmConv: 55 },
  { origen: "GARIN", destino: "MUNRO", kmReal: null, kmConv: 25 },
  { origen: "ESCOBAR", destino: "JOSE C. PAZ", kmReal: 31, kmConv: 30 },
  { origen: "LUJAN DE CUYO", destino: "GARIN", kmReal: 1066, kmConv: 1065 },
  { origen: "PUERTO ESPERANZA", destino: "SAN FRANCISCO", kmReal: 1142, kmConv: 1140 },
  { origen: "GENERAL LAVALLE", destino: "EZEIZA", kmReal: 307, kmConv: 305 },
  { origen: "RAFAELA", destino: "SANTIAGO DEL ESTERO", kmReal: 511, kmConv: 510 },
  { origen: "DOLORES", destino: "ZARATE", kmReal: 308, kmConv: 310 },
  { origen: "RANELAGH", destino: "ARROYITO", kmReal: 686, kmConv: 686 },
  { origen: "MATADEROS", destino: "RANELAGH", kmReal: 47, kmConv: 45 },
  { origen: "MONTEVIDEO", destino: "ARROYO SECO", kmReal: 686, kmConv: 685 },
  { origen: "JUJUY", destino: "RAFAELA", kmReal: 955, kmConv: 955 },
  { origen: "GENERAL MOSCONI", destino: "JUJUY", kmReal: 295, kmConv: 295 },
  { origen: "MALVINAS ARGENTINAS", destino: "9 DE ABRIL", kmReal: null, kmConv: 10 },
  { origen: "CORRIENTES", destino: "SAN JORGE", kmReal: 712, kmConv: 710 },
  { origen: "SANTA VICTORIA ESTE", destino: "TUCUMAN", kmReal: 737, kmConv: 740 },
  { origen: "SALTA", destino: "JUJUY", kmReal: 124, kmConv: 125 },
  { origen: "TORTUGUITAS", destino: "CATRILO", kmReal: 502, kmConv: 500 },
  { origen: "SAN FRANCISCO", destino: "SANTA VICTORIA ESTE", kmReal: 1393, kmConv: 1395 },
  { origen: "VILLA DEL ROSARIO", destino: "SAN FRANCISCO", kmReal: 169, kmConv: 170 },
  { origen: "LA MENDIETA", destino: "RAFAELA", kmReal: 950, kmConv: 950 },
  { origen: "SALTA", destino: "LA MENDIETA", kmReal: 120, kmConv: 120 },
  { origen: "CAMPANA", destino: "LOBOS", kmReal: 140, kmConv: 140 },
  { origen: "AROCENA", destino: "ROSARIO", kmReal: 110, kmConv: 110 },
  { origen: "ORAN", destino: "GENERAL MOSCONI", kmReal: 122, kmConv: 120 },
  { origen: "SALTA", destino: "ORAN", kmReal: 277, kmConv: 280 },
  { origen: "EL TIO", destino: "CORRIENTES", kmReal: 753, kmConv: 755 },
  { origen: "CORDOBA", destino: "EL TIO", kmReal: 145, kmConv: 145 },
  { origen: "SAN MARTIN", destino: "VILLA DEL ROSARIO", kmReal: 694, kmConv: 695 },
  { origen: "TORTUGUITAS", destino: "VILLA URQUIZA", kmReal: 32, kmConv: 30 },
  { origen: "GUALEGUAYCHU", destino: "SANTO TOME", kmReal: 324, kmConv: 325 },
  { origen: "PASO DE LOS LIBRES", destino: "GUALEGUAYCHU", kmReal: 451, kmConv: 450 },
  { origen: "PUERTO BOSSETTI", destino: "CORDOBA", kmReal: 1397, kmConv: 1395 },
  { origen: "SAN VICENTE", destino: "PUERTO BOSSETTI", kmReal: 178, kmConv: 180 },
  { origen: "QUILMES", destino: "EZEIZA", kmReal: 55, kmConv: 55 },
  { origen: "ESCOBAR", destino: "SAN ANDRES DE GILES", kmReal: 90, kmConv: 90 },
  { origen: "LANUS", destino: "MONTE GRANDE", kmReal: 18, kmConv: 20 },
  { origen: "GALVEZ", destino: "SAN FRANCISCO", kmReal: 133, kmConv: 135 },
  { origen: "SAN JORGE", destino: "GALVEZ", kmReal: 79, kmConv: 80 },
  { origen: "LONGCHAMPS", destino: "ZONA PORTUARIA", kmReal: 45, kmConv: 45 },
  { origen: "SAN FRANCISCO", destino: "QUILMES", kmReal: 585, kmConv: 585 },
  { origen: "VILLA SAN JOSE", destino: "CAMPANA", kmReal: 459, kmConv: 460 },
  { origen: "SANTO TOME", destino: "VILLA SAN JOSE", kmReal: 105, kmConv: 105 },
  { origen: "CONSTITUCION", destino: "9 DE ABRIL", kmReal: 23, kmConv: 25 },
  { origen: "SAN JOSE", destino: "ARROYO SECO", kmReal: 669, kmConv: 700 },
  { origen: "VILLA URQUIZA", destino: "SARANDI", kmReal: 36, kmConv: 35 },
  { origen: "BOSQUES", destino: "BURZACO", kmReal: 23, kmConv: 25 },
  { origen: "TANDIL", destino: "LANUS", kmReal: null, kmConv: 15 },
  { origen: "FLORENCIO VARELA", destino: "ZONA PORTUARIA", kmReal: null, kmConv: 30 },
  { origen: "GENERAL RODRIGUEZ", destino: "ZONA PORTUARIA", kmReal: 71, kmConv: 70 },
  { origen: "VILLA URQUIZA", destino: "BARRACAS", kmReal: null, kmConv: 30 },
  { origen: "PILAR", destino: "BARRACAS", kmReal: null, kmConv: 75 },
  { origen: "PILAR", destino: "SARANDI", kmReal: null, kmConv: 80 },
  { origen: "VILLA MERCEDES", destino: "CONSTITUCION", kmReal: 698, kmConv: 700 },
  { origen: "ESPERANZA", destino: "LOS POLVORINES", kmReal: 480, kmConv: 480 },
  { origen: "CORDOBA", destino: "SARANDI", kmReal: 709, kmConv: 710 },
  { origen: "BERAZATEGUI", destino: "9 DE ABRIL", kmReal: null, kmConv: 50 },
  { origen: "MONTE GRANDE", destino: "LOBOS", kmReal: 76, kmConv: 75 },
  { origen: "TAPIALES", destino: "SAN JORGE", kmReal: 500, kmConv: 500 },
  { origen: "SAN FRANCISCO", destino: "CARLOS PAZ", kmReal: 264, kmConv: 265 },
  { origen: "ESCOBAR", destino: "BERAZATEGUI", kmReal: 50, kmConv: 50 },
  { origen: "GENERAL RODRIGUEZ", destino: "BERAZATEGUI", kmReal: 83, kmConv: 85 },
  { origen: "LA PATERNAL", destino: "CANNING", kmReal: 41, kmConv: 40 },
  { origen: "ESCOBAR", destino: "VILLA LUZURIAGA", kmReal: 65, kmConv: 65 },
  { origen: "GARIN", destino: "FLORENCIO VARELA", kmReal: 71, kmConv: 70 },
  { origen: "HURLINGHAM", destino: "BURZACO", kmReal: null, kmConv: 40 },
  { origen: "PILAR", destino: "VALENTIN ALSINA", kmReal: null, kmConv: 70 },
  { origen: "CORRAL DE BUSTOS", destino: "CORDOBA", kmReal: 333, kmConv: 335 },
  { origen: "EZEIZA", destino: "CORRAL DE BUSTOS", kmReal: 469, kmConv: 470 },
  { origen: "GONZALEZ CATAN", destino: "9 DE ABRIL", kmReal: 21, kmConv: 20 },
  { origen: "CORRIENTES", destino: "PUERTO ESPERANZA", kmReal: 558, kmConv: 560 },
  { origen: "LA PLATA", destino: "EZEIZA", kmReal: null, kmConv: 80 },
  { origen: "HURLINGHAM", destino: "LANUS", kmReal: null, kmConv: 30 },
  { origen: "TUCUMAN", destino: "MORENO", kmReal: 1258, kmConv: 1260 },
  { origen: "BURZACO", destino: "BARADERO", kmReal: 174, kmConv: 175 },
  { origen: "VILLA MARIA", destino: "SARANDI", kmReal: 565, kmConv: 565 },
  { origen: "ARROYITO", destino: "SARANDI", kmReal: 664, kmConv: 665 },
  { origen: "SARANDI", destino: "ZONA PORTUARIA", kmReal: null, kmConv: 15 },
  { origen: "PORTE&#209;A", destino: "SARANDI", kmReal: 624, kmConv: 625 },
  { origen: "TAPIALES", destino: "LA PLATA", kmReal: null, kmConv: 72 },
  { origen: "AMERICA", destino: "VILLA MERCEDES", kmReal: 408, kmConv: 410 },
  { origen: "GRAND BOURG", destino: "GENERAL RODRIGUEZ", kmReal: 28, kmConv: 28 },
  { origen: "VIEDMA", destino: "ZARATE", kmReal: 970, kmConv: 970 },
  { origen: "OLAVARRIA", destino: "EZEIZA", kmReal: 321, kmConv: 320 },
  { origen: "SAUCE VIEJO", destino: "SARANDI", kmReal: 455, kmConv: 455 },
  { origen: "SAN FRANCISCO", destino: "GRAND BOURG", kmReal: 530, kmConv: 530 },
  { origen: "PUERTO ESPERANZA", destino: "MORENO", kmReal: 1228, kmConv: 1228 },
  { origen: "RETIRO", destino: "PARANÁ", kmReal: null, kmConv: 500 },
  { origen: "VILLA SOLDATI", destino: "BAHIA BLANCA", kmReal: 628, kmConv: 628 },
  { origen: "SANTO TOME", destino: "GOBERNADOR VIRASORO", kmReal: null, kmConv: 695 },
  { origen: "CORDOBA", destino: "SANTO TOME", kmReal: 351, kmConv: 355 },
  { origen: "CORRIENTES", destino: "FRANCK", kmReal: 569, kmConv: 570 },
  { origen: "CORDOBA", destino: "CORRIENTES", kmReal: 889, kmConv: 890 },
  { origen: "SAN FRANCISCO", destino: "OLAVARRIA", kmReal: 750, kmConv: 750 },
  { origen: "FRIAS", destino: "PORTE&#209;A", kmReal: 502, kmConv: 502 },
  { origen: "GOBERNADOR VIRASORO", destino: "PUERTO PIRAY", kmReal: 265, kmConv: 265 },
  { origen: "JUNIN", destino: "AMERICA", kmReal: 256, kmConv: 255 },
  { origen: "RETIRO", destino: "JUNIN", kmReal: 274, kmConv: 275 },
  { origen: "SANTIAGO DEL ESTERO", destino: "RECREO", kmReal: 220, kmConv: 220 },
  { origen: "TUCUMAN", destino: "TORTUGUITAS", kmReal: 1228, kmConv: 1230 },
  { origen: "NEUQUEN", destino: "CONCARAN", kmReal: null, kmConv: 925 },
  { origen: "NEUQUEN", destino: "SAN LUIS", kmReal: 769, kmConv: 770 },
  { origen: "RAWSON", destino: "VIEDMA", kmReal: 507, kmConv: 507 },
  { origen: "TRELEW", destino: "RAWSON", kmReal: 22, kmConv: 22 },
  { origen: "VILLA DEL PARQUE", destino: "RETIRO", kmReal: null, kmConv: 14 },
  { origen: "AVELLANEDA", destino: "VALENTIN ALSINA", kmReal: null, kmConv: 5 },
  { origen: "BAHIA BLANCA", destino: "SAN ANDRES DE GILES", kmReal: 650, kmConv: 650 },
  { origen: "LA PLATA", destino: "VILLA LUZURIAGA", kmReal: null, kmConv: 82 },
  { origen: "VILLA LUZURIAGA", destino: "LA PLATA", kmReal: null, kmConv: 82 },
  { origen: "LA REJA", destino: "BARRACAS", kmReal: 51, kmConv: 50 },
  { origen: "VILLA LUZURIAGA", destino: "COLONIA CAROYA", kmReal: 752, kmConv: 750 },
  { origen: "LOBOS", destino: "CORDOBA", kmReal: 719, kmConv: 720 },
  { origen: "EZEIZA", destino: "LOBOS", kmReal: 74, kmConv: 75 },
  { origen: "FREYRE", destino: "SANTIAGO DEL ESTERO", kmReal: 513, kmConv: 513 },
  { origen: "GENERAL RODRIGUEZ", destino: "SANTA FE", kmReal: 446, kmConv: 446 },
  { origen: "MOISES VILLE", destino: "SUSANA", kmReal: 88, kmConv: 88 },
  { origen: "LULES", destino: "RAFAELA", kmReal: 668, kmConv: 668 },
  { origen: "TUCUMAN", destino: "LULES", kmReal: null, kmConv: 21 },
  { origen: "30 DE AGOSTO", destino: "SAN ANDRES DE GILES", kmReal: 431, kmConv: 431 },
  { origen: "MAR DEL PLATA", destino: "LANUS", kmReal: 411, kmConv: 411 },
  { origen: "CORONEL DORREGO", destino: "BAHIA BLANCA", kmReal: null, kmConv: 95 },
  { origen: "RETIRO", destino: "CORONEL DORREGO", kmReal: 600, kmConv: 600 },
  { origen: "BURZACO", destino: "FATIMA", kmReal: null, kmConv: 89 },
  { origen: "MALVINAS ARGENTINAS", destino: "CAMPANA", kmReal: 104, kmConv: 104 },
  { origen: "SAN FRANCISCO", destino: "LA REJA", kmReal: 554, kmConv: 555 },
  { origen: "CORDOBA", destino: "MOISES VILLE", kmReal: 343, kmConv: 340 },
  { origen: "TRENQUE LAUQUEN", destino: "30 DE AGOSTO", kmReal: null, kmConv: 60 },
  { origen: "RETIRO", destino: "TRENQUE LAUQUEN", kmReal: 454, kmConv: 455 },
  { origen: "MUNRO", destino: "RETIRO", kmReal: null, kmConv: 20 },
  { origen: "BURZACO", destino: "PILAR", kmReal: 81, kmConv: 80 },
  { origen: "EZEIZA", destino: "PILAR", kmReal: null, kmConv: 86 },
  { origen: "LOMAS DE ZAMORA", destino: "SAN JUSTO", kmReal: 22, kmConv: 20 },
  { origen: "TRELEW", destino: "VILLA SOLDATI", kmReal: 1344, kmConv: 1345 },
  { origen: "SAN JORGE", destino: "RIO CUARTO", kmReal: 338, kmConv: 340 },
  { origen: "LUJAN", destino: "MUNRO", kmReal: 72, kmConv: 70 },
  { origen: "CORDOBA", destino: "LUJAN", kmReal: 666, kmConv: 665 },
  { origen: "GOBERNADOR VIRASORO", destino: "LA PLATA", kmReal: 964, kmConv: 965 },
  { origen: "GOBERNADOR VIRASORO", destino: "CORRIENTES", kmReal: 327, kmConv: 325 },
  { origen: "MUNRO", destino: "SAN LUIS", kmReal: 818, kmConv: 820 },
  { origen: "CAMPANA", destino: "MUNRO", kmReal: null, kmConv: 65 },
  { origen: "CONCEPCION", destino: "RAFAELA", kmReal: 690, kmConv: 690 },
  { origen: "SAN ANDRES DE GILES", destino: "TUCUMAN", kmReal: 1175, kmConv: 1175 },
  { origen: "TAFI VIEJO", destino: "CONCEPCION", kmReal: 99, kmConv: 100 },
  { origen: "CORDOBA", destino: "TAFI VIEJO", kmReal: 591, kmConv: 590 },
  { origen: "MALVINAS ARGENTINAS", destino: "SAN JUSTO", kmReal: 20, kmConv: 20 },
  { origen: "GALVEZ", destino: "ROSARIO", kmReal: 133, kmConv: 135 },
  { origen: "HURLINGHAM", destino: "PILAR", kmReal: null, kmConv: 50 },
  { origen: "CAMPANA", destino: "SAN ANDRES DE GILES", kmReal: 63, kmConv: 65 },
  { origen: "SAN JORGE", destino: "MALVINAS ARGENTINAS", kmReal: 515, kmConv: 515 },
  { origen: "GONZALEZ CATAN", destino: "VALENTIN ALSINA", kmReal: 30, kmConv: 30 },
  { origen: "CATRILO", destino: "GONZALEZ CATAN", kmReal: 544, kmConv: 545 },
  { origen: "RETIRO", destino: "GALVEZ", kmReal: 428, kmConv: 430 },
  { origen: "MORENO", destino: "MUNRO", kmReal: 40, kmConv: 40 },
  { origen: "ZONA PORTUARIA", destino: "PILAR", kmReal: 59, kmConv: 60 },
  { origen: "CLORINDA", destino: "SANTA ANA", kmReal: 657, kmConv: 655 },
  { origen: "MORTEROS", destino: "SUSANA", kmReal: 121, kmConv: 120 },
  { origen: "SAN LUIS", destino: "PILAR", kmReal: 736, kmConv: 735 },
  { origen: "SAN MARTIN", destino: "LANUS", kmReal: 28, kmConv: 30 },
  { origen: "TORTUGUITAS", destino: "ESPERANZA", kmReal: 462, kmConv: 460 },
  { origen: "CAPILLA DEL MONTE", destino: "COLONIA CAROYA", kmReal: 119, kmConv: 120 },
  { origen: "EZEIZA", destino: "SAN MARTIN", kmReal: 36, kmConv: 35 },
  { origen: "SAN FERNANDO", destino: "LOMAS DEL MIRADOR", kmReal: 30, kmConv: 30 },
  { origen: "CONCORDIA", destino: "SAN FERNANDO", kmReal: 412, kmConv: 410 },
  { origen: "SAN JUSTO", destino: "CATRILO", kmReal: 514, kmConv: 515 },
  { origen: "COLONIA CAROYA", destino: "SAN LUIS", kmReal: 446, kmConv: 445 },
  { origen: "PASO DE LOS LIBRES", destino: "CONCORDIA", kmReal: 258, kmConv: 260 },
  { origen: "RECREO", destino: "DON TORCUATO", kmReal: 933, kmConv: 935 },
  { origen: "ISIDRO CASANOVA", destino: "MALVINAS ARGENTINAS", kmReal: 55, kmConv: 55 },
  { origen: "RIO GALLEGOS", destino: "SAN LUIS", kmReal: 2480, kmConv: 2480 },
  { origen: "SAN JAVIER", destino: "PUERTO ESPERANZA", kmReal: 285, kmConv: 285 },
  { origen: "EZEIZA", destino: "EL PALOMAR", kmReal: 40, kmConv: 40 },
  { origen: "MAR DEL PLATA", destino: "ZONA PORTUARIA", kmReal: 416, kmConv: 416 },
  { origen: "ZONA PORTUARIA", destino: "MAR DEL PLATA", kmReal: 416, kmConv: 416 },
  { origen: "LIBERTAD", destino: "VILLA SOLDATI", kmReal: 550, kmConv: 550 },
  { origen: "APÓSTOLES", destino: "SAN JAVIER", kmReal: 76, kmConv: 75 },
  { origen: "SAN FRANCISCO", destino: "APÓSTOLES", kmReal: 864, kmConv: 865 },
  { origen: "NASCHEL", destino: "VILLA MERCEDES", kmReal: 97, kmConv: 95 },
  { origen: "ZONA PORTUARIA", destino: "PABLO NOGUES", kmReal: 35, kmConv: 35 },
  { origen: "PABLO NOGUES", destino: "VILLA MARTELLI", kmReal: 24, kmConv: 25 },
  { origen: "ROSARIO", destino: "GENERAL PACHECO", kmReal: 267, kmConv: 265 },
  { origen: "SALTO", destino: "BARADERO", kmReal: 111, kmConv: 110 },
  { origen: "RECREO", destino: "GENERAL PACHECO", kmReal: 928, kmConv: 930 },
  { origen: "TUCUMAN", destino: "RECREO", kmReal: 297, kmConv: 298 },
  { origen: "RETIRO", destino: "BAHIA BLANCA", kmReal: 638, kmConv: 640 },
  { origen: "CARMEN DE ARECO", destino: "EZEIZA", kmReal: 172, kmConv: 170 },
  { origen: "MONTEVIDEO", destino: "SANTA FE", kmReal: 654, kmConv: 655 },
  { origen: "SAN LUIS", destino: "SALTO", kmReal: 635, kmConv: 635 },
  { origen: "RODEO DE LA CRUZ", destino: "SAN LUIS", kmReal: 248, kmConv: 250 },
  { origen: "MENDOZA", destino: "RODEO DE LA CRUZ", kmReal: 13, kmConv: 15 },
  { origen: "PUESTO VIEJO", destino: "SAN FRANCISCO", kmReal: 952, kmConv: 950 },
  { origen: "PUESTO VIEJO", destino: "ZONA PORTUARIA", kmReal: 1455, kmConv: 1455 },
  { origen: "CORDOBA", destino: "PUESTO VIEJO", kmReal: 864, kmConv: 865 },
  { origen: "MORTEROS", destino: "BAHIA BLANCA", kmReal: 1023, kmConv: 1025 },
  { origen: "RAFAELA", destino: "MORTEROS", kmReal: 114, kmConv: 115 },
  { origen: "SAN LUIS", destino: "ARROYITO", kmReal: 525, kmConv: 525 },
  { origen: "MARCOS PAZ", destino: "TORTUGUITAS", kmReal: 64, kmConv: 65 },
  { origen: "SAN VICENTE", destino: "MARCOS PAZ", kmReal: 70, kmConv: 70 },
  { origen: "SAN FRANCISCO", destino: "SAN VICENTE", kmReal: 1056, kmConv: 1055 },
  { origen: "VILLA TESEI", destino: "9 DE ABRIL", kmReal: 28, kmConv: 30 },
  { origen: "SAN JUSTO", destino: "BERAZATEGUI", kmReal: 51, kmConv: 50 },
  { origen: "BERAZATEGUI", destino: "PUERTO PIRAY", kmReal: 1200, kmConv: 1200 },
  { origen: "CAMPANA", destino: "BERAZATEGUI", kmReal: 109, kmConv: 110 },
  { origen: "CONCORDIA", destino: "SALSIPUEDE", kmReal: 426, kmConv: 425 },
  { origen: "FREYRE", destino: "MORTEROS", kmReal: 55, kmConv: 55 },
  { origen: "GENERAL PACHECO", destino: "FATIMA", kmReal: 36, kmConv: 35 },
  { origen: "ARROYITO", destino: "SAN LUIS", kmReal: 528, kmConv: 530 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
