/// <reference path="../pb_data/types.d.ts" />
// Carga de rutas reales (planilla del otro sistema, AlertasDeStock.xls),
// parte 8 de 9. Un registro por par origen/destino
// unico (si el nombre se repetia con distintos km, se quedo con la
// ULTIMA aparicion del archivo). Las que en el sistema original tenian
// un "!" adelante del nombre se cargan igual, con el "!" incluido en el
// origen (es una marca propia de ese sistema, no algo nuestro).
migrate((db) => {
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("rutas");

  const rutas = [
  { origen: "SANTO TOME", destino: "PARANÁ", kmReal: 40, kmConv: 40 },
  { origen: "! PUERTO PIRAY", destino: "SANTO TOME", kmReal: 960, kmConv: 960 },
  { origen: "! SALTO(URUGUAY)", destino: "ROSARIO", kmReal: 400, kmConv: 400 },
  { origen: "! BARADERO", destino: "AROCENA", kmReal: 270, kmConv: 270 },
  { origen: "! MERCEDES(BS AS)", destino: "VILLA MARIA", kmReal: 500, kmConv: 500 },
  { origen: "! GARUPA", destino: "PUERTO PIRAY", kmReal: 186, kmConv: 190 },
  { origen: "RAFAELA", destino: "RECREO", kmReal: 80, kmConv: 80 },
  { origen: "! COMODORO RIVADAVIA", destino: "SANTA ISABEL", kmReal: 1480, kmConv: 1480 },
  { origen: "! SANTA ISABEL", destino: "ROSARIO", kmReal: 813, kmConv: 815 },
  { origen: "! MENDOZA", destino: "GARUPA", kmReal: 1777, kmConv: 1780 },
  { origen: "RECREO", destino: "PORTE&#209;A", kmReal: 158, kmConv: 160 },
  { origen: "LA FRANCIA", destino: "SAN FRANCISCO", kmReal: 53, kmConv: 55 },
  { origen: "PORTE&#209;A", destino: "URUGUAIANA", kmReal: 650, kmConv: 650 },
  { origen: "! BUENOS AIRES", destino: "MAR DEL PLATA", kmReal: 415, kmConv: 415 },
  { origen: "PORTE&#209;A", destino: "RECREO", kmReal: 158, kmConv: 160 },
  { origen: "PORTE&#209;A", destino: "SAN PABLO", kmReal: 2410, kmConv: 2410 },
  { origen: "! SAN JOSE(URUGUAY)", destino: "URUGUAIANA", kmReal: 614, kmConv: 615 },
  { origen: "! BALCARCE", destino: "SAN JOSE(URUGUAY)", kmReal: 904, kmConv: 905 },
  { origen: "! OLAVARRIA", destino: "BUENOS AIRES", kmReal: 355, kmConv: 355 },
  { origen: "LUJAN", destino: "CORDOBA", kmReal: 656, kmConv: 660 },
  { origen: "! HUMBOLDT", destino: "BELLA ITALIA", kmReal: 44, kmConv: 44 },
  { origen: "! AROCENA", destino: "BUENOS AIRES", kmReal: 407, kmConv: 410 },
  { origen: "! FRANCK", destino: "AROCENA", kmReal: 75, kmConv: 75 },
  { origen: "AROCENA", destino: "CORDOBA", kmReal: 385, kmConv: 385 },
  { origen: "! URUGUAIANA", destino: "VILLA MARIA", kmReal: 763, kmConv: 765 },
  { origen: "! SAN FRANCISCO", destino: "PUERTO ESPERANZA", kmReal: 1150, kmConv: 1150 },
  { origen: "! LOS BERROS", destino: "SAN FRANCISCO", kmReal: 869, kmConv: 870 },
  { origen: "! NEUQUEN", destino: "LOS BERROS", kmReal: 924, kmConv: 925 },
  { origen: "! VILLA CONSTITUCION", destino: "BUENOS AIRES", kmReal: 257, kmConv: 260 },
  { origen: "! TRELEW", destino: "BUENOS AIRES", kmReal: 1354, kmConv: 1355 },
  { origen: "! SANTO TOME(CTES)", destino: "SANTA ANA", kmReal: 188, kmConv: 190 },
  { origen: "SUNCHALES", destino: "FORMOSA", kmReal: 747, kmConv: 750 },
  { origen: "! GOYA", destino: "PASO DE LOS LIBRES", kmReal: 384, kmConv: 385 },
  { origen: "! LA FRANCIA", destino: "FRANCK", kmReal: 176, kmConv: 180 },
  { origen: "! AVELLANEDA(SANTA FE)", destino: "LOS BERROS", kmReal: 1178, kmConv: 1180 },
  { origen: "! URUGUAYANA", destino: "VILLA CONSTITUCION", kmReal: 635, kmConv: 635 },
  { origen: "! BUENOS AIRES", destino: "OLAVARRIA", kmReal: 350, kmConv: 350 },
  { origen: "! TRELEW", destino: "MAR DEL PLATA", kmReal: 2765, kmConv: 2765 },
  { origen: "! COMODORO RIVADAVIA", destino: "TRELEW", kmReal: 375, kmConv: 375 },
  { origen: "PUERTO ESPERANZA", destino: "AVELLANEDA", kmReal: 800, kmConv: 800 },
  { origen: "! MONTEVIDEO", destino: "LA FRANCIA", kmReal: 853, kmConv: 855 },
  { origen: "! SAN FRANCISCO", destino: "LA CRUZ", kmReal: 674, kmConv: 675 },
  { origen: "! SANTO TOME", destino: "URUGUAIANA", kmReal: 462, kmConv: 465 },
  { origen: "! SAN FRANCISCO", destino: "PEAJE FRANCK", kmReal: 111, kmConv: 110 },
  { origen: "FRANCK", destino: "LA PLATA", kmReal: 527, kmConv: 530 },
  { origen: "! PEAJE FRANCK", destino: "POSADAS", kmReal: 815, kmConv: 815 },
  { origen: "RAFAELA", destino: "FRANCK", kmReal: 77, kmConv: 80 },
  { origen: "! LABOULAYE", destino: "ROSARIO", kmReal: 329, kmConv: 330 },
  { origen: "! ROSARIO", destino: "LABOULAYE", kmReal: 329, kmConv: 330 },
  { origen: "SANTO TOME", destino: "ROSARIO", kmReal: 162, kmConv: 165 },
  { origen: "! PUERTO ESPERANZA", destino: "LOS BERROS", kmReal: 1993, kmConv: 1995 },
  { origen: "! GUALEGUAYCHU", destino: "PILAR", kmReal: 193, kmConv: 195 },
  { origen: "! CHACABUCO", destino: "BUENOS AIRES", kmReal: 225, kmConv: 225 },
  { origen: "! VENADO TUERTO", destino: "PILAR", kmReal: 317, kmConv: 320 },
  { origen: "! RECREO(SANTA FE)", destino: "FRANCK", kmReal: 37, kmConv: 40 },
  { origen: "! CANDELARIA", destino: "PUERTO PIRAY", kmReal: 175, kmConv: 175 },
  { origen: "! ITUZAINGÓ", destino: "POSADAS", kmReal: 93, kmConv: 93 },
  { origen: "GUALEGUAYCHU", destino: "SAN FRANCISCO", kmReal: 450, kmConv: 450 },
  { origen: "! MAR DE AJO", destino: "BUENOS AIRES", kmReal: 365, kmConv: 365 },
  { origen: "! SAN FRANCISCO", destino: "HUMBOLDT", kmReal: 127, kmConv: 130 },
  { origen: "RAFAELA", destino: "SAN BERNARDO", kmReal: 900, kmConv: 900 },
  { origen: "! FIGHIERA", destino: "ROSARIO", kmReal: 35, kmConv: 35 },
  { origen: "! AROCENA", destino: "SAN FRANCISCO", kmReal: 160, kmConv: 160 },
  { origen: "! MAR DEL PLATA", destino: "NAVARRO", kmReal: 420, kmConv: 420 },
  { origen: "! SAN JUAN", destino: "LOS BERROS", kmReal: 75, kmConv: 75 },
  { origen: "BARILOCHE", destino: "CORDOBA", kmReal: 1574, kmConv: 1575 },
  { origen: "CORDOBA", destino: "BARILOCHE", kmReal: 1574, kmConv: 1575 },
  { origen: "! PUERTO ESPERANZA", destino: "EL ALCAZAR", kmReal: 91, kmConv: 90 },
  { origen: "! EL ALCAZAR", destino: "BUENOS AIRES", kmReal: 1139, kmConv: 1140 },
  { origen: "! BUENOS AIRES", destino: "EL ALCAZAR", kmReal: 1139, kmConv: 1140 },
  { origen: "! ROSARIO", destino: "CORONDA", kmReal: 126, kmConv: 125 },
  { origen: "! FIGHIERA", destino: "TIO PUJIO", kmReal: 305, kmConv: 305 },
  { origen: "JAMES CRAIK", destino: "CORDOBA", kmReal: 118, kmConv: 120 },
  { origen: "SAN PEDRO", destino: "CORDOBA", kmReal: 544, kmConv: 545 },
  { origen: "COLONIA TIROLESA", destino: "CORDOBA", kmReal: 33, kmConv: 33 },
  { origen: "! LOS BERROS", destino: "PUERTO ESPERANZA", kmReal: 1993, kmConv: 1995 },
  { origen: "! MENDOZA", destino: "LOS BERROS", kmReal: 136, kmConv: 140 },
  { origen: "SAN FRANCISCO", destino: "LA FRANCIA", kmReal: 53, kmConv: 55 },
  { origen: "! COMODORO RIVADAVIA", destino: "LOS ANTIGUOS", kmReal: 439, kmConv: 440 },
  { origen: "! LOS ANTIGUOS", destino: "BUENOS AIRES", kmReal: 2109, kmConv: 2110 },
  { origen: "! SALSIPUEDES", destino: "SAN FRANCISCO", kmReal: 253, kmConv: 255 },
  { origen: "CORDOBA", destino: "SALSIPUEDE", kmReal: null, kmConv: 50 },
  { origen: "SAN FRANCISCO", destino: "SANTO TOME", kmReal: 773, kmConv: 775 },
  { origen: "MAR DE AJO", destino: "ZARATE", kmReal: 455, kmConv: 455 },
  { origen: "SAN JUAN", destino: "PUERTO ESPERANZA", kmReal: 1985, kmConv: 1985 },
  { origen: "RAFAELA", destino: "MAR DE AJO", kmReal: 904, kmConv: 905 },
  { origen: "NAVARRO", destino: "ROSARIO", kmReal: 329, kmConv: 330 },
  { origen: "NAVARRO", destino: "RAFAELA", kmReal: 567, kmConv: 570 },
  { origen: "SAN FRANCISCO", destino: "PUERTO BOSSETTI", kmReal: 1170, kmConv: 1170 },
  { origen: "PUERTO BOSSETTI", destino: "SAN FRANCISCO", kmReal: 1170, kmConv: 1170 },
  { origen: "! PUERTO ESPERANZA", destino: "PUERTO BOSETTI", kmReal: 25, kmConv: 25 },
  { origen: "CONCEPCION DEL URUGUAY", destino: "SANTA FE", kmReal: 290, kmConv: 290 },
  { origen: "PILAR", destino: "BARADERO", kmReal: 115, kmConv: 115 },
  { origen: "CORDOBA", destino: "GUI&#209;AZU", kmReal: 25, kmConv: 25 },
  { origen: "GUI&#209;AZU", destino: "CORDOBA", kmReal: 25, kmConv: 25 },
  { origen: "MERCEDES", destino: "PILAR", kmReal: 75, kmConv: 75 },
  { origen: "CORDOBA", destino: "SAN RAFAEL", kmReal: 707, kmConv: 710 },
  { origen: "CHICHINALES", destino: "VILLA REGINA", kmReal: 14, kmConv: 0 },
  { origen: "! RECREO", destino: "GOBERNADOR CRESPO", kmReal: 136, kmConv: 140 },
  { origen: "GUALEGUAYCHU", destino: "CORDOBA", kmReal: 684, kmConv: 685 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "PUERTO ESPERANZA", kmReal: 930, kmConv: 930 },
  { origen: "BAHIA BLANCA", destino: "CORDOBA", kmReal: 936, kmConv: 935 },
  { origen: "CORDOBA", destino: "BAHIA BLANCA", kmReal: 936, kmConv: 935 },
  { origen: "CONCORDIA", destino: "CORDOBA", kmReal: 664, kmConv: 665 },
  { origen: "VILLA DOLORES", destino: "SAN FRANCISCO", kmReal: 413, kmConv: 415 },
  { origen: "! CORRIENTES", destino: "PUERTO ESPERANZA", kmReal: 558, kmConv: 560 },
  { origen: "BRINKMANN", destino: "FREYRE", kmReal: null, kmConv: 40 },
  { origen: "CORDOBA", destino: "FRANCK", kmReal: 348, kmConv: 350 },
  { origen: "! LEONES", destino: "ROSARIO", kmReal: 163, kmConv: 165 },
  { origen: "! ESQUEL", destino: "CIPOLLETTI", kmReal: 728, kmConv: 730 },
  { origen: "SUNCHALES", destino: "MAR DEL PLATA", kmReal: 1001, kmConv: 1005 },
  { origen: "SAN FRANCISCO", destino: "BALNEARIA", kmReal: 120, kmConv: 120 },
  { origen: "RESISTENCIA", destino: "SANTA ANA", kmReal: 389, kmConv: 390 },
  { origen: "CORONDA", destino: "SAN FRANCISCO", kmReal: 169, kmConv: 170 },
  { origen: "! BUENOS AIRES", destino: "CORONDA", kmReal: 421, kmConv: 425 },
  { origen: "SANTIAGO TEMPLE", destino: "CORDOBA", kmReal: 88, kmConv: 90 },
  { origen: "CORDOBA", destino: "SANTIAGO TEMPLE", kmReal: 88, kmConv: 90 },
  { origen: "! POSADAS", destino: "ITUZAINGO", kmReal: null, kmConv: 95 },
  { origen: "MONTEVIDEO", destino: "GENERAL RODRIGUEZ", kmReal: 550, kmConv: 550 },
  { origen: "EMBALSE", destino: "CORDOBA", kmReal: 112, kmConv: 115 },
  { origen: "CORDOBA", destino: "EMBALSE", kmReal: 112, kmConv: 115 },
  { origen: "DESVIO ARIJON", destino: "SAN FRANCISCO", kmReal: 155, kmConv: 155 },
  { origen: "! SALTA", destino: "POSADAS", kmReal: 1156, kmConv: 1160 },
  { origen: "NAVARRO", destino: "CORDOBA", kmReal: 723, kmConv: 725 },
  { origen: "! BUENOS AIRES", destino: "NAVARRO", kmReal: 108, kmConv: 110 },
  { origen: "TRELEW", destino: "CORDOBA", kmReal: 1451, kmConv: 1455 },
  { origen: "CORDOBA", destino: "TRELEW", kmReal: 1451, kmConv: 1455 },
  { origen: "VILLA REGINA", destino: "VILLA MARIA", kmReal: 1087, kmConv: 1090 },
  { origen: "! MADARIAGA", destino: "BUENOS AIRES", kmReal: 331, kmConv: 330 },
  { origen: "OBERA", destino: "POSADAS", kmReal: 99, kmConv: 100 },
  { origen: "SAN JERONIMO", destino: "RAFAELA", kmReal: 83, kmConv: 85 },
  { origen: "! SAN FRANCISCO", destino: "BARRACAS", kmReal: 175, kmConv: 175 },
  { origen: "9 DE JULIO", destino: "TIO PUJIO", kmReal: 514, kmConv: 515 },
  { origen: "! MERCEDES", destino: "SAN JORGE", kmReal: 444, kmConv: 445 },
  { origen: "! BUENOS AIRES", destino: "MERCEDES", kmReal: 110, kmConv: 110 },
  { origen: "! SANTO TOME", destino: "BUENOS AIRES", kmReal: 460, kmConv: 460 },
  { origen: "! GOBERNADOR CRESPO", destino: "SANTO TOME", kmReal: 162, kmConv: 160 },
  { origen: "CORDOBA", destino: "COMODORO RIVADAVIA", kmReal: 1809, kmConv: 1810 },
  { origen: "! FRIAS", destino: "SAN FRANCISCO", kmReal: 536, kmConv: 535 },
  { origen: "ZARATE", destino: "SANTA FE", kmReal: 384, kmConv: 385 },
  { origen: "PUERTO RICO", destino: "PUERTO PIRAY", kmReal: null, kmConv: 65 },
  { origen: "RIO TERCERO", destino: "CORDOBA", kmReal: 97, kmConv: 100 },
  { origen: "SUNCHALES", destino: "RESISTENCIA", kmReal: 580, kmConv: 580 },
  { origen: "! PARANA", destino: "MONTEVIDEO", kmReal: 632, kmConv: 635 },
  { origen: "! LASPIUR", destino: "SAN FRANCISCO", kmReal: 53, kmConv: 55 },
  { origen: "PORTE&#209;A", destino: "SATURNINO M LASPIUR", kmReal: 106, kmConv: 105 },
  { origen: "! GENERAL ROCA", destino: "BUENOS AIRES", kmReal: 1100, kmConv: 1100 },
  { origen: "! SUARDI", destino: "BUENOS AIRES", kmReal: 686, kmConv: 685 },
  { origen: "! JAMES CRAIK", destino: "VILLA MARIA", kmReal: 44, kmConv: 45 },
  { origen: "! TARTAGAL", destino: "VILLA MERCEDES", kmReal: 1486, kmConv: 1490 },
  { origen: "! SALTA", destino: "TARTAGAL", kmReal: 356, kmConv: 360 },
  { origen: "VENADO TUERTO", destino: "CORDOBA", kmReal: 403, kmConv: 405 },
  { origen: "CORDOBA", destino: "VENADO TUERTO", kmReal: 403, kmConv: 405 },
  { origen: "MENDOZA", destino: "SAN FRANCISCO", kmReal: 773, kmConv: 775 },
  { origen: "SANTO TOME", destino: "CORDOBA", kmReal: 351, kmConv: 355 },
  { origen: "ZARATE", destino: "SAN JERONIMO", kmReal: 407, kmConv: 410 },
  { origen: "! BUENOS AIRES", destino: "DALMACIO VELEZ", kmReal: 593, kmConv: 595 },
  { origen: "! DALMACIO VELEZ", destino: "BUENOS AIRES", kmReal: 593, kmConv: 595 },
  { origen: "CORDOBA", destino: "SAN JUAN", kmReal: 590, kmConv: 590 },
  { origen: "CORDOBA", destino: "SAN LUIS", kmReal: 428, kmConv: 430 },
  { origen: "! CUATRO BOCAS", destino: "POSADAS", kmReal: 450, kmConv: 450 },
  { origen: "AVELLANEDA", destino: "SAN FRANCISCO", kmReal: 450, kmConv: 450 },
  { origen: "! LIBERTADOR GENERAL SAN MARTIN", destino: "CAMPANA", kmReal: 1455, kmConv: 1455 },
  { origen: "ZARATE", destino: "CAMPANA", kmReal: 12, kmConv: 10 },
  { origen: "! CHICHINALES", destino: "VILLA MARIA", kmReal: 967, kmConv: 970 },
  { origen: "TUCUMAN", destino: "SALTA", kmReal: 306, kmConv: 310 },
  { origen: "TUCUMAN", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 373, kmConv: 375 },
  { origen: "URUGUAIANA", destino: "CORDOBA", kmReal: 812, kmConv: 810 },
  { origen: "! LEANDRO N. ALEM", destino: "URUGUAIANA", kmReal: 362, kmConv: 365 },
  { origen: "! LAS ROSAS", destino: "SAN FRANCISCO", kmReal: 159, kmConv: 160 },
  { origen: "! CORREA", destino: "LAS ROSAS", kmReal: 70, kmConv: 70 },
  { origen: "! ROSARIO", destino: "CORREA", kmReal: null, kmConv: 60 },
  { origen: "! LAS ROSAS", destino: "BUENOS AIRES", kmReal: 419, kmConv: 420 },
  { origen: "RAFAELA", destino: "LAS ROSAS", kmReal: 175, kmConv: 175 },
  { origen: "! CORONEL BELISLE", destino: "BUENOS AIRES", kmReal: 975, kmConv: 975 },
  { origen: "! BARILOCHE", destino: "CORONEL BELISLE", kmReal: 630, kmConv: 630 },
  { origen: "! VIEDMA", destino: "RIO COLORADO", kmReal: 305, kmConv: 305 },
  { origen: "! MONTEVIDEO", destino: "CONCORDIA", kmReal: 541, kmConv: 540 },
  { origen: "LUJAN", destino: "TUCUMAN", kmReal: 1220, kmConv: 1220 },
  { origen: "! RAFAELA", destino: "ALEM", kmReal: 908, kmConv: 910 },
  { origen: "RAFAELA", destino: "BARILOCHE", kmReal: 1759, kmConv: 1760 },
  { origen: "! MINAS", destino: "SAN FRANCISCO", kmReal: 866, kmConv: 870 },
  { origen: "! RECREO (STA FE)", destino: "DESVIO ARIJON", kmReal: null, kmConv: 55 },
  { origen: "! CUATRO BOCAS", destino: "CANDELARIA", kmReal: 450, kmConv: 450 },
  { origen: "! RAFAELA", destino: "CUATRO BOCAS", kmReal: 446, kmConv: 450 },
  { origen: "! CUATRO BOCAS", destino: "SAN FRANCISCO", kmReal: 513, kmConv: 515 },
  { origen: "! URUGUAIANA", destino: "CUATRO BOCAS", kmReal: 107, kmConv: 110 },
  { origen: "! SANTA CATARINA", destino: "URUGUAIANA", kmReal: 893, kmConv: 0 },
  { origen: "! CRUCE RUTA 9 Y 178", destino: "TIO PUJIO", kmReal: 190, kmConv: 190 },
  { origen: "! BUENOS AIRES", destino: "CRUCE RUTA 9 Y 178", kmReal: 379, kmConv: 380 },
  { origen: "AVELLANEDA", destino: "FREYRE", kmReal: 435, kmConv: 435 },
  { origen: "! PUERTO PIRAY", destino: "ROSARIO", kmReal: 1077, kmConv: 1080 },
  { origen: "! GENERAL SAN MARTIN (JUJUY)", destino: "ORAN", kmReal: 113, kmConv: 115 },
  { origen: "SALTA", destino: "LIBERTADOR GRAL SAN MARTIN", kmReal: 164, kmConv: 165 },
  { origen: "PUERTO PIRAY", destino: "MENDOZA", kmReal: 1859, kmConv: 1860 },
  { origen: "! PUERTO BOSETTI", destino: "SAN LUIS", kmReal: 1672, kmConv: 1675 },
  { origen: "! SAN VICENTE", destino: "PUERTO BOSETTI", kmReal: 176, kmConv: 180 },
  { origen: "! URUGUAIANA", destino: "GUALEGUAYCHU", kmReal: 454, kmConv: 455 },
  { origen: "SANTA ROSA DE CALAMUCHITA", destino: "SAN FRANCISCO", kmReal: 321, kmConv: 320 },
  { origen: "RAFAELA", destino: "CAMPANA", kmReal: 463, kmConv: 465 },
  { origen: "! SAN NICOLAS", destino: "GENERAL SAN MARTIN", kmReal: 1300, kmConv: 1300 },
  { origen: "LIBERTADOR GRAL SAN MARTIN", destino: "TUCUMAN", kmReal: 375, kmConv: 375 },
  { origen: "! ARROYO SECO", destino: "BUENOS AIRES", kmReal: 270, kmConv: 270 },
  { origen: "! URUGUAIANA", destino: "JARAGUA DO SUL", kmReal: 1247, kmConv: 1250 },
  { origen: "! SAN PEDRO", destino: "MONTEVIDEO", kmReal: 591, kmConv: 595 },
  { origen: "! ORAN", destino: "BUENOS AIRES", kmReal: 1678, kmConv: 1680 },
  { origen: "ARROYITO", destino: "SAN JORGE", kmReal: 171, kmConv: 170 },
  { origen: "SANTA ROSA DE CALAMUCHITA", destino: "CORDOBA", kmReal: null, kmConv: 100 },
  { origen: "CORDOBA", destino: "SANTA ROSA DE CALAMUCHITA", kmReal: null, kmConv: 100 },
  { origen: "! PUERTO IGUAZU", destino: "PUERTO PIRAY", kmReal: 116, kmConv: 120 },
  { origen: "! VILLA MARIA", destino: "MERCEDES (BS AS)", kmReal: 505, kmConv: 505 },
  { origen: "SALTA", destino: "ACHERAL", kmReal: 356, kmConv: 360 },
  { origen: "SAN FRANCISCO", destino: "SAUCE VIEJO", kmReal: 143, kmConv: 145 },
  { origen: "! PERGAMINO", destino: "CHIVILCOY", kmReal: 147, kmConv: 150 },
  { origen: "PUERTO PIRAY", destino: "RAFAELA", kmReal: 1067, kmConv: 1070 },
  { origen: "! JUJUY", destino: "FAIMALLA", kmReal: 378, kmConv: 380 },
  { origen: "! MINAS", destino: "SAN SALVADOR", kmReal: 583, kmConv: 585 },
  { origen: "BELL VILLE", destino: "CORDOBA", kmReal: 208, kmConv: 210 },
  { origen: "SAN FRANCISCO", destino: "BELL VILLE", kmReal: 180, kmConv: 180 },
  { origen: "ROSARIO DE LA FRONTERA", destino: "TUCUMAN", kmReal: 132, kmConv: 135 },
  { origen: "! CLORINDA", destino: "SANTA ANA", kmReal: 671, kmConv: 675 },
  { origen: "! FAIMALLA", destino: "ROSARIO", kmReal: 925, kmConv: 925 },
  { origen: "! BUENOS AIRES", destino: "ROSARIO DE LA FRONTERA", kmReal: 1293, kmConv: 1295 },
  { origen: "! PLAZA CLUCELLAS", destino: "RAMONA", kmReal: null, kmConv: 75 },
  { origen: "! CAXIAS DO SUL", destino: "URUGUAIANA", kmReal: 680, kmConv: 0 },
  { origen: "! BUENOS AIRES", destino: "PLAZA CLUCELLAS", kmReal: 529, kmConv: 530 },
  { origen: "CHICHINALES", destino: "CORDOBA", kmReal: 1045, kmConv: 1045 },
  { origen: "PORTE&#209;A", destino: "SUNCHALES", kmReal: null, kmConv: 65 },
  { origen: "ZARATE", destino: "POSADAS", kmReal: 917, kmConv: 920 },
  { origen: "! SAN LUIS", destino: "MENDOZA", kmReal: 258, kmConv: 260 },
  { origen: "! RAMONA", destino: "SAN FRANCISCO", kmReal: 60, kmConv: 60 },
  { origen: "! BALCARCE", destino: "CAMPANA", kmReal: 459, kmConv: 460 },
  { origen: "SANTA TERESITA", destino: "ZARATE", kmReal: 435, kmConv: 435 },
  { origen: "! ALLEN", destino: "CINCO SALTOS", kmReal: null, kmConv: 35 },
  { origen: "! NEUQUEN", destino: "BALCARCE", kmReal: 962, kmConv: 965 },
  { origen: "! CAMPO GRANDE", destino: "URUGUAIANA", kmReal: 427, kmConv: 430 },
  { origen: "! PUERTO ESPERANZA", destino: "SAN LUIS", kmReal: 1653, kmConv: 1655 },
  { origen: "RIO COLORADO", destino: "CORDOBA", kmReal: 889, kmConv: 890 },
  { origen: "! COMODORO RIVADAVIA", destino: "RIO COLORADO", kmReal: 924, kmConv: 925 },
  { origen: "PEDRO LURO", destino: "CORDOBA", kmReal: 1124, kmConv: 1125 },
  { origen: "! COMODORO RIVADAVIA", destino: "PEDRO LURO", kmReal: 1117, kmConv: 1120 },
  { origen: "! COMODORO RIVADAVIA", destino: "BUENOS AIRES", kmReal: 1728, kmConv: 1730 },
  { origen: "TUCUMAN", destino: "FAMAILLA", kmReal: 46, kmConv: 45 },
  { origen: "! FAIMALLA", destino: "SAN PEDRO", kmReal: 1064, kmConv: 1065 },
  { origen: "! BALCARCE", destino: "MAR DEL PLATA", kmReal: 55, kmConv: 55 },
  { origen: "! OBERA", destino: "PUERTO BOSETTI", kmReal: 236, kmConv: 240 },
  { origen: "RAFAELA", destino: "CAMPO GRANDE", kmReal: 974, kmConv: 975 },
  { origen: "! OBERA", destino: "PUERTO ESPERANZA", kmReal: 217, kmConv: 220 },
  { origen: "! BAHIA BLANCA", destino: "CAMPANA", kmReal: 887, kmConv: 890 },
  { origen: "MAR DEL PLATA", destino: "SIERRA DE LOS PADRES", kmReal: 28, kmConv: 30 },
  { origen: "! SIERRA DE LOS PADRES", destino: "BUENOS AIRES", kmReal: 418, kmConv: 420 },
  { origen: "! FRAY BENTOS", destino: "CONCEPCION DEL URUGUAY", kmReal: 115, kmConv: 115 },
  { origen: "! ROSARIO", destino: "GUALEGUAYCHU", kmReal: 260, kmConv: 260 },
  { origen: "SAN FRANCISCO", destino: "COLONIA CAROYA", kmReal: 260, kmConv: 260 },
  { origen: "ALVEAR", destino: "BUENOS AIRES", kmReal: 287, kmConv: 290 },
  { origen: "! SAENZ PE&#209;A", destino: "PASO DE LOS LIBRES", kmReal: 549, kmConv: 550 },
  { origen: "! LIB. GRAL SAN MARTIN", destino: "SAN FRANCISCO", kmReal: 1029, kmConv: 1030 },
  { origen: "! CIPOLLETTI", destino: "GENERAL CONESA", kmReal: 396, kmConv: 400 },
  { origen: "! SAN VICENTE", destino: "SANTA ANA", kmReal: 142, kmConv: 145 },
  { origen: "! SALTA", destino: "ORAN", kmReal: 299, kmConv: 300 },
  { origen: "RAFAELA", destino: "CIPOLLETTI", kmReal: 1307, kmConv: 1310 },
  { origen: "! SALTA", destino: "FAIMALLA", kmReal: 347, kmConv: 350 },
  { origen: "! SANTA TERESITA", destino: "BUENOS AIRES", kmReal: 345, kmConv: 345 },
  { origen: "RAFAELA", destino: "SANTA TERESITA", kmReal: 881, kmConv: 885 },
  { origen: "! PERGAMINO", destino: "SAN FRANCISCO", kmReal: 377, kmConv: 380 },
  { origen: "LA RIOJA", destino: "TUCUMAN", kmReal: 729, kmConv: 730 },
  { origen: "SAN JUAN", destino: "TUCUMAN", kmReal: 1168, kmConv: 1170 },
  { origen: "RAFAELA", destino: "JUJUY", kmReal: 967, kmConv: 970 },
  { origen: "! SANTA CLARA DE BUENA VISTA", destino: "RAFAELA", kmReal: 78, kmConv: 80 },
  { origen: "! BUENOS AIRES", destino: "SANTA CLARA DE BUENA VISTA", kmReal: 462, kmConv: 465 },
  { origen: "RAFAELA", destino: "LA RIOJA", kmReal: 699, kmConv: 700 },
  { origen: "! SAN ANDRES DE GILES", destino: "SAN JUAN", kmReal: 1008, kmConv: 1010 },
  { origen: "! BUENOS AIRES", destino: "SAN ANDRES DE GILES", kmReal: 109, kmConv: 110 },
  { origen: "! JUSTINIANO POSSE", destino: "SAN FRANCISCO", kmReal: 212, kmConv: 215 },
  { origen: "! LAS VARILLAS", destino: "JUSTINIANO POSSE", kmReal: 135, kmConv: 135 },
  { origen: "! PUERTO PIRAY", destino: "SAN JUAN", kmReal: 1921, kmConv: 1925 },
  { origen: "PUERTO ESPERANZA", destino: "PUERTO PIRAY", kmReal: 64, kmConv: 65 },
  { origen: "VILLA MARIA", destino: "TUCUMAN", kmReal: 702, kmConv: 705 },
  { origen: "! CONCEPCION DEL URUGUAY", destino: "PUERTO PIRAY", kmReal: 891, kmConv: 895 },
  { origen: "! MERCEDES(BS AS)", destino: "MONTEVIDEO", kmReal: 587, kmConv: 590 },
  { origen: "PUERTO PIRAY", destino: "CORDOBA", kmReal: 1308, kmConv: 1310 },
  { origen: "! BAHIA BLANCA", destino: "BUENOS AIRES", kmReal: 635, kmConv: 635 },
  { origen: "! ALVEAR", destino: "ROSARIO", kmReal: 20, kmConv: 20 },
  { origen: "AVELLANEDA", destino: "SUNCHALES", kmReal: 365, kmConv: 365 },
  { origen: "! POSADAS", destino: "PUERTO ESPERANZA", kmReal: 255, kmConv: 255 },
  { origen: "ZARATE", destino: "MONTEVIDEO", kmReal: 507, kmConv: 510 },
  { origen: "! BAHIA BLANCA", destino: "BALCARCE", kmReal: 428, kmConv: 430 },
  { origen: "NEUQUEN", destino: "VILLA REGINA", kmReal: 89, kmConv: 90 },
  { origen: "! ALLEN", destino: "VILLA MARIA", kmReal: 1048, kmConv: 1050 },
  { origen: "ROSARIO", destino: "BARADERO", kmReal: 161, kmConv: 160 },
  { origen: "BARADERO", destino: "SAN FRANCISCO", kmReal: 442, kmConv: 440 },
  { origen: "! COMODORO RIVADAVIA", destino: "GENERAL ROCA", kmReal: 1059, kmConv: 1060 },
  { origen: "! ESQUEL", destino: "GUARDIA MITRE", kmReal: 945, kmConv: 945 },
  { origen: "! GUARDIA MITRE", destino: "PARANA", kmReal: 1295, kmConv: 1295 },
  { origen: "! GENERAL CONESA", destino: "PARANA", kmReal: 1244, kmConv: 1245 },
  { origen: "! ESQUEL", destino: "GENERAL CONESA", kmReal: 859, kmConv: 860 },
  { origen: "! VILLA MANZANO", destino: "CINCO SALTOS", kmReal: 25, kmConv: 25 },
  { origen: "! ALLEN", destino: "VILLA MANZANO", kmReal: 55, kmConv: 55 },
  { origen: "RAFAELA", destino: "ESQUEL", kmReal: 2035, kmConv: 2035 },
  { origen: "ELORTONDO", destino: "RAFAELA", kmReal: 332, kmConv: 335 },
  { origen: "! MAR DEL PLATA", destino: "BALCARCE", kmReal: 74, kmConv: 75 },
  { origen: "! FAIMALLA", destino: "BUENOS AIRES", kmReal: 1217, kmConv: 1220 },
  { origen: "RAFAELA", destino: "MAR DEL PLATA", kmReal: 955, kmConv: 955 },
  { origen: "! MENDOZA", destino: "SAN JORGE", kmReal: 798, kmConv: 800 },
  { origen: "! GENERAL CONESA", destino: "ROSARIO", kmReal: 1043, kmConv: 1045 },
  { origen: "! NEUQUEN", destino: "GENERAL CONESA", kmReal: 402, kmConv: 405 },
  { origen: "! COLONIA (ZONA FRANCA)", destino: "BUENOS AIRES", kmReal: 485, kmConv: 485 },
  { origen: "! TAFI VIEJO", destino: "BUENOS AIRES", kmReal: 1269, kmConv: 1270 },
  { origen: "! SALTA", destino: "TAFI VIEJO", kmReal: 305, kmConv: 305 },
  { origen: "RAFAELA", destino: "BAHIA BLANCA", kmReal: 995, kmConv: 995 },
  { origen: "ARMSTRONG", destino: "RAFAELA", kmReal: 208, kmConv: 210 },
  { origen: "SUNCHALES", destino: "CLORINDA", kmReal: 863, kmConv: 865 },
  { origen: "! GENERAL PIRAN", destino: "BUENOS AIRES", kmReal: 329, kmConv: 330 },
  { origen: "! MEDANOS", destino: "SANTA FE", kmReal: 1328, kmConv: 1330 },
  { origen: "! CHICHINALES", destino: "MEDANOS", kmReal: 386, kmConv: 390 },
  { origen: "! NEUQUEN", destino: "PUELCHES", kmReal: 268, kmConv: 270 },
  { origen: "! PUELCHES", destino: "SAN FRANCISCO", kmReal: 960, kmConv: 960 },
  { origen: "SUNCHALES", destino: "SAN FRANCISCO", kmReal: 112, kmConv: 113 },
  { origen: "ROQUE SAENS PE&#209;A", destino: "SUNCHALES", kmReal: 550, kmConv: 550 },
  { origen: "ROSARIO", destino: "MENDOZA", kmReal: 883, kmConv: 885 },
  { origen: "MORTEROS", destino: "RAFAELA", kmReal: 113, kmConv: 115 },
  { origen: "ZARATE", destino: "ESPERANZA", kmReal: 409, kmConv: 410 },
  { origen: "! GENERAL ROCA", destino: "RECREO (CATAMARCA)", kmReal: 1377, kmConv: 1380 },
  { origen: "! FREYRE", destino: "SALTA", kmReal: 932, kmConv: 935 },
  { origen: "! PUERTO PIRAY", destino: "NEUQUEN", kmReal: 2233, kmConv: 2235 },
  { origen: "! ARISTOBULO DEL VALLE", destino: "PUERTO PIRAY", kmReal: 107, kmConv: 110 },
  { origen: "VERA", destino: "RAFAELA", kmReal: 308, kmConv: 310 },
  { origen: "! SAN FRANCISCO", destino: "VERA", kmReal: 397, kmConv: 400 },
  { origen: "! LIB. GRAL SAN MARTIN", destino: "BUENOS AIRES", kmReal: 1539, kmConv: 1540 },
  { origen: "! BUENOS AIRES", destino: "LIB. GRAL SAN MARTIN", kmReal: 1539, kmConv: 1540 },
  { origen: "! VIEDMA", destino: "BUENOS AIRES", kmReal: 915, kmConv: 915 },
  { origen: "! RAFAELA", destino: "ARISTOBULO DEL VALLE", kmReal: 993, kmConv: 995 },
  { origen: "! NEUQUEN", destino: "VIEDMA", kmReal: 556, kmConv: 560 },
  { origen: "! FIGHIERA", destino: "SAN FRANCISCO", kmReal: 302, kmConv: 305 },
  { origen: "! BUENOS AIRES", destino: "SAN JUAN", kmReal: 1121, kmConv: 1125 },
  { origen: "! NOGOYA", destino: "BUENOS AIRES", kmReal: 382, kmConv: 385 },
  { origen: "! BUENOS AIRES", destino: "NOGOYA", kmReal: 382, kmConv: 385 },
  { origen: "! VILLA MARIA", destino: "RIO CUARTO", kmReal: 133, kmConv: 135 },
  { origen: "LA QUIACA", destino: "TUCUMAN", kmReal: 627, kmConv: 630 },
  { origen: "! BUENOS AIRES", destino: "PUERTO ESPERANZA", kmReal: 1225, kmConv: 1225 },
  { origen: "PERGAMINO", destino: "RAFAELA", kmReal: 355, kmConv: 355 },
  { origen: "! SAN FRANCISCO", destino: "NEUQUEN", kmReal: 1270, kmConv: 1270 },
  { origen: "MERCEDES", destino: "BARADERO", kmReal: 101, kmConv: 100 },
  { origen: "MENDOZA", destino: "LA QUIACA", kmReal: 1583, kmConv: 1585 },
  { origen: "! SAN LUIS", destino: "LEONES", kmReal: 454, kmConv: 455 },
  { origen: "! ROSARIO", destino: "FIGHIERA", kmReal: 40, kmConv: 40 },
  { origen: "COLONIA CAROYA", destino: "SAN FRANCISCO", kmReal: 256, kmConv: 260 },
  { origen: "VIEDMA", destino: "CORDOBA", kmReal: 1200, kmConv: 1200 },
  { origen: "! COMODORO RIVADAVIA", destino: "VIEDMA", kmReal: 865, kmConv: 865 },
  { origen: "9 DE JULIO", destino: "ROSARIO", kmReal: 309, kmConv: 310 },
  { origen: "! EL TALAR", destino: "SAN FRANCISCO", kmReal: 1157, kmConv: 1160 },
  { origen: "RAFAELA", destino: "SAN LUIS", kmReal: 600, kmConv: 600 },
  { origen: "ALVEAR", destino: "RAFAELA", kmReal: 260, kmConv: 260 },
  { origen: "PUERTO PIRAY", destino: "TUCUMAN", kmReal: 1292, kmConv: 1295 },
  { origen: "BRAGADO", destino: "ALVEAR", kmReal: 287, kmConv: 290 },
  { origen: "! BUENOS AIRES", destino: "AROCENA", kmReal: 407, kmConv: 410 },
  { origen: "! VIEDMA", destino: "MEDANOS", kmReal: 243, kmConv: 245 },
  { origen: "! VILLA ANGELA", destino: "SANTA ANA", kmReal: 637, kmConv: 640 },
  { origen: "! SAN PEDRO", destino: "SAN JORGE", kmReal: 340, kmConv: 340 },
  { origen: "! BUENOS AIRES", destino: "EL TALAR (JUJUY)", kmReal: 1606, kmConv: 1610 },
  { origen: "GENERAL ROCA", destino: "CORDOBA", kmReal: 1098, kmConv: 1100 },
  { origen: "! NEUQUEN", destino: "GENERAL ROCA", kmReal: 45, kmConv: 45 },
  { origen: "! JAMES CRAIK", destino: "TIO PUJIO", kmReal: 18, kmConv: 20 },
  { origen: "! ARROYITO", destino: "BRINKMANN", kmReal: 141, kmConv: 145 },
  { origen: "SANTIAGO DEL ESTERO", destino: "TUCUMAN", kmReal: 162, kmConv: 165 },
  { origen: "! BUENOS AIRES", destino: "JAMES CRAIK", kmReal: 589, kmConv: 590 },
  { origen: "! RAMALLO", destino: "ROSARIO", kmReal: 103, kmConv: 105 },
  { origen: "ZARATE", destino: "SANTIAGO DEL ESTERO", kmReal: 963, kmConv: 965 },
  { origen: "! VILLA MERCEDES", destino: "CONCARAN", kmReal: 142, kmConv: 145 },
  { origen: "! CONCARAN", destino: "BUENOS AIRES", kmReal: 780, kmConv: 780 },
  { origen: "! SANTA FE", destino: "RECREO (STA FE)", kmReal: 17, kmConv: 20 },
  { origen: "! JUAREZ CELMAN", destino: "COLONIA CAROYA", kmReal: 33, kmConv: 35 },
  { origen: "RECREO", destino: "CORDOBA", kmReal: 350, kmConv: 350 },
  { origen: "RAFAELA", destino: "URUGUAIANA", kmReal: 558, kmConv: 560 },
  { origen: "! SAN JERONIMO DEL SAUCE", destino: "RAFAELA", kmReal: 73, kmConv: 75 },
  { origen: "! SAN FRANCISCO", destino: "SAN JERONIMO DEL SAUCE", kmReal: 95, kmConv: 95 },
  { origen: "PUERTO PIRAY", destino: "ZARATE", kmReal: 1088, kmConv: 1090 },
  { origen: "CORDOBA", destino: "SANTA FE", kmReal: 370, kmConv: 370 },
  { origen: "! BUENOS AIRES", destino: "JUAREZ CELMAN", kmReal: 709, kmConv: 710 },
  { origen: "! BLUMENAU", destino: "URUGUAIANA", kmReal: null, kmConv: 0 },
  { origen: "! PILAR", destino: "MONTEVIDEO", kmReal: 552, kmConv: 550 },
  { origen: "TUCUMAN", destino: "TIO PUJIO", kmReal: 695, kmConv: 695 },
  { origen: "SAN FRANCISCO", destino: "MENDOZA", kmReal: 773, kmConv: 775 },
  { origen: "! CAMPANA", destino: "MONTEVIDEO", kmReal: 511, kmConv: 515 },
  { origen: "ZARATE", destino: "VILLA MARIA", kmReal: 469, kmConv: 470 },
  { origen: "! SAN FRANCISCO", destino: "RAMALLO", kmReal: 350, kmConv: 350 },
  { origen: "! RAMALLO", destino: "SAN FRANCISCO", kmReal: 350, kmConv: 350 },
  { origen: "! BUENOS AIRES", destino: "RAMALLO", kmReal: 218, kmConv: 220 },
  { origen: "! RAMALLO", destino: "BUENOS AIRES", kmReal: 218, kmConv: 220 },
  { origen: "ZARATE", destino: "RECREO", kmReal: 398, kmConv: 400 },
  { origen: "ROSARIO", destino: "ZARATE", kmReal: 215, kmConv: 215 },
  { origen: "CIPOLLETTI", destino: "CORDOBA", kmReal: 1110, kmConv: 1110 },
  { origen: "! VILLA MARIA", destino: "DEVOTO", kmReal: 172, kmConv: 175 },
  { origen: "! MENDOZA", destino: "MAR DEL PLATA", kmReal: 1330, kmConv: 1330 },
  { origen: "! RIO TERCERO", destino: "BUENOS AIRES", kmReal: 687, kmConv: 690 },
  { origen: "! FREYRE", destino: "ROSARIO", kmReal: 296, kmConv: 300 },
  { origen: "! VILLA MARIA", destino: "SAN JOSE", kmReal: 765, kmConv: 765 },
  { origen: "! SAN RAFAEL", destino: "SAN FRANCISCO", kmReal: 792, kmConv: 795 },
  { origen: "! FRAY BENTOS", destino: "SAN FRANCISCO", kmReal: 494, kmConv: 495 },
  { origen: "! MONTEVIDEO", destino: "FRAY BENTOS", kmReal: 305, kmConv: 305 },
  { origen: "MENDOZA", destino: "SAN JUAN", kmReal: 170, kmConv: 170 },
  { origen: "! PARANA", destino: "RECREO (SANTA FE)", kmReal: null, kmConv: 60 },
  { origen: "SAN FRANCISCO", destino: "LAS VARILLAS", kmReal: null, kmConv: 85 },
  { origen: "SANTA ANA", destino: "SAN FRANCISCO", kmReal: 937, kmConv: 940 },
  { origen: "! SAENZ PE&#209;A", destino: "SANTA ANA", kmReal: 551, kmConv: 555 },
  { origen: "! ELORTONDO", destino: "ROSARIO", kmReal: 177, kmConv: 180 },
  { origen: "! SANTO TOME", destino: "GALVEZ", kmReal: 77, kmConv: 80 },
  { origen: "! PILAR", destino: "CLUCELLAS", kmReal: 490, kmConv: 490 },
  { origen: "PUERTO ESPERANZA", destino: "RAFAELA", kmReal: 1120, kmConv: 1120 },
  { origen: "JUJUY", destino: "TUCUMAN", kmReal: 338, kmConv: 340 },
  { origen: "! GUALEGUAYCHU", destino: "URUGUAIANA", kmReal: 453, kmConv: 455 },
  { origen: "SAN FRANCISCO", destino: "GUALEGUAYCHU", kmReal: 459, kmConv: 460 },
  { origen: "! MEDANOS", destino: "SAN FRANCISCO", kmReal: 982, kmConv: 985 },
  { origen: "ZARATE", destino: "PUERTO ESPERANZA", kmReal: 1142, kmConv: 1145 },
  { origen: "! SARMIENTO", destino: "MEDANOS", kmReal: 1152, kmConv: 1155 },
  { origen: "ZARATE", destino: "TUCUMAN", kmReal: 1163, kmConv: 1165 },
  { origen: "! PASO DE LOS LIBRES", destino: "SAN FRANCISCO", kmReal: 589, kmConv: 590 },
  { origen: "! CONCORDIA", destino: "PASO DE LOS LIBRES", kmReal: 258, kmConv: 260 },
  { origen: "! ROSARIO", destino: "LAS PAREJAS", kmReal: null, kmConv: 100 },
  { origen: "! SALTA", destino: "JUJUY", kmReal: null, kmConv: 90 },
  { origen: "! PUERTO BOSETTI", destino: "SANTA ANA", kmReal: 226, kmConv: 230 },
  { origen: "PERGAMINO", destino: "CAMPANA", kmReal: 170, kmConv: 170 },
  { origen: "SUARDI", destino: "RAFAELA", kmReal: 135, kmConv: 135 },
  { origen: "SALTA", destino: "SAN FRANCISCO", kmReal: 964, kmConv: 965 },
  { origen: "! ALLEN", destino: "BUENOS AIRES", kmReal: 1122, kmConv: 1125 },
  { origen: "! CHINCHINALES", destino: "ALLEN", kmReal: null, kmConv: 90 },
  { origen: "! SUSANA", destino: "SAN FRANCISCO", kmReal: null, kmConv: 80 },
  { origen: "! FRAY BENTOS", destino: "MONTEVIDEO", kmReal: 312, kmConv: 315 },
  { origen: "! SAN JOSE (URUGUAY)", destino: "FRAY BENTOS", kmReal: 223, kmConv: 225 },
  { origen: "TUCUMAN", destino: "VILLA MARIA", kmReal: 714, kmConv: 715 },
  { origen: "! BELTRAN", destino: "ALLEN", kmReal: 219, kmConv: 220 },
  { origen: "! COMODORO RIVADAVIA", destino: "BELTRAN", kmReal: 875, kmConv: 875 },
  { origen: "! FIGHIERA", destino: "BUENOS AIRES", kmReal: 265, kmConv: 265 },
  { origen: "! SAN FRANCISCO", destino: "FIGHIERA", kmReal: 302, kmConv: 305 },
  { origen: "! FIGHIERA", destino: "RECREO", kmReal: 223, kmConv: 225 },
  { origen: "! BUENOS AIRES", destino: "FIGHIERA", kmReal: 265, kmConv: 265 },
  { origen: "SASTRE", destino: "RAFAELA", kmReal: 82, kmConv: 85 },
  { origen: "! BENTO GON&#199;ALVES", destino: "URUGUAIANA", kmReal: 515, kmConv: 0 },
  { origen: "PUERTO ESPERANZA", destino: "ZARATE", kmReal: 1142, kmConv: 1145 },
  { origen: "TUCUMAN", destino: "SAN FRANCISCO", kmReal: 707, kmConv: 710 },
  { origen: "! PUERTO BOSETTI", destino: "BUENOS AIRES", kmReal: 1245, kmConv: 1245 },
  { origen: "SAN JUSTO", destino: "ZARATE", kmReal: 94, kmConv: 95 },
  { origen: "! PUERTO BOSETTI", destino: "PUERTO PIRAY", kmReal: 83, kmConv: 85 },
  { origen: "! COMODORO RIVADAVIA", destino: "CHINCHINALES", kmReal: 1000, kmConv: 1000 },
  { origen: "PUERTO ESPERANZA", destino: "SAN JUSTO", kmReal: 1231, kmConv: 1235 },
  { origen: "SAN PEDRO", destino: "RAFAELA", kmReal: 387, kmConv: 390 },
  { origen: "SAN PEDRO", destino: "VILLA SOLDATI", kmReal: 188, kmConv: 190 },
  { origen: "! BUENOS AIRES", destino: "SAN PEDRO", kmReal: 171, kmConv: 175 },
  { origen: "! LUQUE", destino: "ARROYITO", kmReal: 57, kmConv: 60 },
  { origen: "! PUERTO BOSATTI", destino: "PUERTO ESPERANZA", kmReal: 24, kmConv: 25 },
  { origen: "! PUERTO ESPERANZA", destino: "BUENOS AIRES", kmReal: 1225, kmConv: 1225 },
  { origen: "ZARATE", destino: "PUERTO BOSSETTI", kmReal: 1161, kmConv: 1160 },
  { origen: "! SAN ANTONIO", destino: "MENDOZA", kmReal: 471, kmConv: 475 },
  { origen: "! SANTIAGO DE CHILE", destino: "SAN ANTONIO", kmReal: 114, kmConv: 115 },
  { origen: "! FORMOSA", destino: "SANTA ANA", kmReal: 557, kmConv: 560 },
  { origen: "CAMPANA", destino: "PILAR", kmReal: 41, kmConv: 40 },
  { origen: "! PILAR", destino: "SAN FRANCISCO", kmReal: 523, kmConv: 525 },
  { origen: "! RIO TERCERO", destino: "SAN FRANCISCO", kmReal: 293, kmConv: 295 },
  { origen: "CORDOBA", destino: "RIO TERCERO", kmReal: 99, kmConv: 100 },
  { origen: "! GENERAL GUEMES", destino: "RAFAELA", kmReal: 889, kmConv: 890 },
  { origen: "! SALTA", destino: "GENERAL GUEMES", kmReal: 58, kmConv: 60 },
  { origen: "! BUENOS AIRES", destino: "PUERTO PIRAY", kmReal: 1172, kmConv: 1175 },
  { origen: "CHILECITO", destino: "CORDOBA", kmReal: 499, kmConv: 500 },
  { origen: "ZARATE", destino: "SALTA", kmReal: 1382, kmConv: 1385 },
  { origen: "! EL DORADO", destino: "SANTA ANA", kmReal: 160, kmConv: 160 },
  { origen: "! CRUCE DE ANGELICA", destino: "RAFAELA", kmReal: 35, kmConv: 35 },
  { origen: "! SAN FRANCISCO", destino: "CRUCE DE ANGELICA", kmReal: 68, kmConv: 68 },
  { origen: "! CRUCE DE ANGELICA", destino: "SAN FRANCISCO", kmReal: 68, kmConv: 68 },
  { origen: "! BUENOS AIRES", destino: "CRUCE DE ANGELICA", kmReal: 500, kmConv: 500 },
  { origen: "SAN FRANCISCO", destino: "RESISTENCIA", kmReal: 668, kmConv: 670 },
  { origen: "! CARMEN DE ARECO", destino: "BUENOS AIRES", kmReal: 147, kmConv: 150 },
  { origen: "! GENERAL PIRAN", destino: "BALCARCE", kmReal: 89, kmConv: 90 },
  { origen: "PUERTO PIRAY", destino: "SANTA FE", kmReal: 951, kmConv: 955 },
  { origen: "! MONTEVIDEO", destino: "SAN SALVADOR", kmReal: 480, kmConv: 480 },
  { origen: "! SAN FRANCISCO", destino: "VILLA DE MARIA", kmReal: 317, kmConv: 320 },
  { origen: "CORDOBA", destino: "VILLA EL TOTORAL", kmReal: 90, kmConv: 90 },
  { origen: "! CA&#209;ADA DE GOMEZ", destino: "SUNCHALES", kmReal: 243, kmConv: 245 },
  { origen: "PERGAMINO", destino: "PILAR", kmReal: 172, kmConv: 170 },
  { origen: "! PILAR", destino: "BUENOS AIRES", kmReal: 59, kmConv: 60 },
  { origen: "! CANDELARIA", destino: "SANTA ANA", kmReal: 39, kmConv: 40 },
  { origen: "! SANTA CLARA DEL MAR", destino: "SIERRA DE LOS PADRES", kmReal: 38, kmConv: 40 },
  { origen: "! SIERRA DE LOS PADRES", destino: "SANTA FE", kmReal: 878, kmConv: 880 },
  { origen: "CORDOBA", destino: "JUAREZ CELMAN", kmReal: 35, kmConv: 35 },
  { origen: "JUAREZ CELMAN", destino: "CORDOBA", kmReal: 35, kmConv: 35 },
  { origen: "! NEUQUEN", destino: "CIPOLETTI", kmReal: 10, kmConv: 10 },
  { origen: "! COMODORO RIVADAVIA", destino: "ROSARIO", kmReal: 1845, kmConv: 1845 },
  { origen: "FORMOSA", destino: "RAFAELA", kmReal: 910, kmConv: 910 },
  { origen: "! PUERTO PIRAY", destino: "URUGUAIANA", kmReal: 529, kmConv: 530 },
  { origen: "SAN FRANCISCO", destino: "FRONTERA", kmReal: 3, kmConv: 3 },
  { origen: "RAFAELA", destino: "FORMOSA", kmReal: 760, kmConv: 760 },
  { origen: "MALAGUE&#209;O", destino: "CORDOBA", kmReal: 27, kmConv: 30 },
  { origen: "! COMODORO RIVADAVIA", destino: "LAMARQUE", kmReal: 860, kmConv: 860 },
  { origen: "! VILLA DE MARIA", destino: "BUENOS AIRES", kmReal: 872, kmConv: 875 },
  { origen: "! TIO PUJIO", destino: "SAN NICOLÁS", kmReal: 343, kmConv: 345 },
  { origen: "! QUILMES", destino: "BRINKMANN", kmReal: 658, kmConv: 660 },
  { origen: "! SAN NICOLAS", destino: "SAN FRANCISCO", kmReal: 334, kmConv: 335 },
  { origen: "! VILLA DE MARÍA", destino: "SAN FRANCISCO", kmReal: 317, kmConv: 315 },
  { origen: "! BUENOS AIRES", destino: "VILLA DE MARIA", kmReal: 872, kmConv: 870 },
  { origen: "! SAN JORGE", destino: "RECREO (STA FE)", kmReal: 170, kmConv: 170 },
  { origen: "! ARROYITO", destino: "TIO PUJIO", kmReal: 133, kmConv: 135 },
  { origen: "! SAN MARTIN N&#176;2", destino: "RAFAELA", kmReal: 897, kmConv: 900 },
  { origen: "! MINAS", destino: "MONTEVIDEO", kmReal: 121, kmConv: 120 },
  { origen: "! CLORINDA", destino: "SAN MARTIN N&#176;2", kmReal: 250, kmConv: 250 },
  { origen: "FORMOSA", destino: "CLORINDA", kmReal: 117, kmConv: 120 },
  { origen: "RECONQUISTA", destino: "FORMOSA", kmReal: 388, kmConv: 390 },
  { origen: "SUNCHALES", destino: "RECONQUISTA", kmReal: 362, kmConv: 365 },
  { origen: "SALSIPUEDE", destino: "CORDOBA", kmReal: 35, kmConv: 35 },
  { origen: "! GOYA", destino: "SAN FRANCISCO", kmReal: 521, kmConv: 520 },
  { origen: "! CRUCE DE ANGELICA", destino: "BUENOS AIRES", kmReal: 510, kmConv: 510 },
  { origen: "! RAFAELA", destino: "CRUCE DE ANGELICA", kmReal: 30, kmConv: 30 },
  { origen: "! PUERTO IGUAZU", destino: "SANTA ANA", kmReal: 259, kmConv: 260 },
  { origen: "! SAN FRANCISCO", destino: "APOSTOLES", kmReal: 873, kmConv: 875 },
  { origen: "TUCUMAN", destino: "DEVOTO", kmReal: 704, kmConv: 705 },
  { origen: "! LUJAN", destino: "MINAS", kmReal: 626, kmConv: 625 },
  { origen: "! DIAMANTE", destino: "ROSARIO", kmReal: 150, kmConv: 150 },
  { origen: "! GENERAL PICO", destino: "LUJAN", kmReal: 516, kmConv: 515 },
  { origen: "9 DE JULIO", destino: "SAN JORGE", kmReal: 500, kmConv: 500 },
  { origen: "! SASTRE", destino: "MONTEVIDEO", kmReal: 810, kmConv: 810 },
  { origen: "CORDOBA", destino: "SASTRE", kmReal: 292, kmConv: 290 },
  { origen: "! NEUQUEN", destino: "ALLEN", kmReal: 23, kmConv: 25 },
  { origen: "! SAN FRANCISCO", destino: "LAS PAREJAS", kmReal: 184, kmConv: 190 },
  { origen: "CORRIENTES", destino: "SANTA ANA", kmReal: 370, kmConv: 370 },
  { origen: "! BUENOS AIRES", destino: "PILAR", kmReal: 60, kmConv: 60 },
  { origen: "ZARATE", destino: "MENDOZA", kmReal: 1000, kmConv: 1000 },
  { origen: "! ARROYO SECO", destino: "SAN JORGE", kmReal: 228, kmConv: 230 },
  { origen: "CLORINDA", destino: "RAFAELA", kmReal: 875, kmConv: 875 },
  { origen: "! GOYA", destino: "BS AS", kmReal: 720, kmConv: 720 },
  { origen: "! MAR DEL TUYU", destino: "BUENOS AIRES", kmReal: 350, kmConv: 350 },
  { origen: "VILLA REGINA", destino: "CORDOBA", kmReal: 1060, kmConv: 1060 },
  { origen: "! BUENOS AIRES", destino: "LUJAN", kmReal: 75, kmConv: 75 },
  { origen: "! CHARATA", destino: "BUENOS AIRES", kmReal: 1050, kmConv: 1050 },
  { origen: "PUERTO PIRAY", destino: "SAN FRANCISCO", kmReal: 1100, kmConv: 1100 },
  { origen: "! MINAS", destino: "BUENOS AIRES", kmReal: 660, kmConv: 660 },
  { origen: "! CHARATA", destino: "SAN FRANCISCO", kmReal: 560, kmConv: 560 },
  { origen: "! FRONTERA", destino: "BUENOS AIRES", kmReal: 560, kmConv: 560 },
  { origen: "FORMOSA", destino: "SAN FRANCISCO", kmReal: 850, kmConv: 850 },
  { origen: "! OBERA", destino: "SAN FRANCISCO", kmReal: 950, kmConv: 950 },
  { origen: "POSADAS", destino: "BUENOS AIRES", kmReal: 1000, kmConv: 1000 },
  { origen: "! SAN FRANCISCO", destino: "EL DORADO", kmReal: 1100, kmConv: 1100 },
  { origen: "! ITUZAINGÓ", destino: "SAN FRANCISCO", kmReal: 900, kmConv: 900 },
  { origen: "! CLORINDA", destino: "SAN FRANCISCO", kmReal: 950, kmConv: 950 },
  { origen: "FRONTERA", destino: "SAN FRANCISCO", kmReal: 3, kmConv: 3 },
  { origen: "! LA CRUZ", destino: "SAN FRANCISCO", kmReal: 668, kmConv: 670 },
  { origen: "SAN MIGUEL DE TUCUMAN", destino: "SAN FRANCISCO", kmReal: 707, kmConv: 710 },
  { origen: "! ITUZAINGO", destino: "SANTA ANA", kmReal: 220, kmConv: 220 },
  { origen: "! BUENOS AIRES", destino: "SAN MIGUEL DE TUCUMÁN", kmReal: 1219, kmConv: 1220 },
  { origen: "CAMPANA", destino: "SAN FRANCISCO", kmReal: 485, kmConv: 485 },
  { origen: "! SAN FRANCISCO", destino: "GOYA", kmReal: 529, kmConv: 530 },
  { origen: "! SAN FRANCISCO", destino: "SAENZ PE&#209;A", kmReal: 625, kmConv: 625 },
  { origen: "! MENDOZA", destino: "SAN JUSTO", kmReal: 994, kmConv: 995 },
  { origen: "! LA CRUZ", destino: "SANTA ANA", kmReal: 276, kmConv: 280 },
  { origen: "POSADAS", destino: "PUERTO PIRAY", kmReal: 200, kmConv: 200 },
  { origen: "OBERA", destino: "PUERTO PIRAY", kmReal: 163, kmConv: 165 },
  { origen: "POSADAS", destino: "SANTA ANA", kmReal: 65, kmConv: 65 },
  { origen: "OBERA", destino: "SANTA ANA", kmReal: 53, kmConv: 55 },
  { origen: "! SANTA ANA", destino: "FRONTERA", kmReal: 934, kmConv: 935 },
  { origen: "! IGUAZU", destino: "PUERTO PIRAY", kmReal: 116, kmConv: 116 },
  { origen: "SAN VICENTE", destino: "PUERTO PIRAY", kmReal: 104, kmConv: 105 },
  { origen: "COMODORO RIVADAVIA", destino: "VILLA REGINA", kmReal: 1013, kmConv: 1015 },
  { origen: "! PUERTO PIRAY", destino: "BUENOS AIRES", kmReal: 1172, kmConv: 1175 },
  { origen: "ROSARIO", destino: "PILAR", kmReal: 260, kmConv: 260 },
  { origen: "! COMODORO RIVADAVIA", destino: "CHICHINALES", kmReal: 1000, kmConv: 1000 },
  { origen: "! SAN RAFAEL", destino: "CARLOS PAZ", kmReal: 650, kmConv: 650 },
  { origen: "! SAN RAFAEL", destino: "VILLA MARIA", kmReal: 630, kmConv: 630 },
  { origen: "! LAS VARILLAS", destino: "SAN FRANCISCO", kmReal: 82, kmConv: 85 },
  { origen: "! POSADAS", destino: "PASO DE LOS LIBRES", kmReal: 355, kmConv: 355 },
  { origen: "! CLUCELLAS", destino: "SAN FRANCISCO", kmReal: 40, kmConv: 40 },
  { origen: "! SAN JOSE", destino: "MONTEVIDEO", kmReal: 93, kmConv: 90 },
  { origen: "! BUENOS AIRES", destino: "LAS VARILLAS", kmReal: 567, kmConv: 565 },
  { origen: "! SAN FRANCISCO", destino: "VILLA ANGELA", kmReal: 530, kmConv: 530 },
  { origen: "LUQUE", destino: "RAFAELA", kmReal: 236, kmConv: 235 },
  { origen: "! JUNIN", destino: "MERCEDES", kmReal: 165, kmConv: 165 },
  { origen: "! MINAS", destino: "URUGUAYANA", kmReal: 750, kmConv: 750 },
  { origen: "NEUQUEN", destino: "CORDOBA", kmReal: 1110, kmConv: 1110 },
  { origen: "! TIO PUJIO", destino: "NEUQUEN", kmReal: 1105, kmConv: 1105 },
  { origen: "! BUENOS AIRES", destino: "MINAS", kmReal: 658, kmConv: 660 },
  { origen: "! GOBERNADOR CRESPO", destino: "SAN FRANCISCO", kmReal: 279, kmConv: 280 },
  { origen: "! HERNANDO", destino: "BUENOS AIRES", kmReal: 617, kmConv: 620 },
  { origen: "CORDOBA", destino: "LAS PAREJAS", kmReal: 333, kmConv: 335 },
  { origen: "! LAS PAREJAS", destino: "BUENOS AIRES", kmReal: 395, kmConv: 395 },
  { origen: "! LUQUE", destino: "VILLA MARIA", kmReal: 112, kmConv: 110 },
  { origen: "! SAN FRANCISCO", destino: "LEONES", kmReal: 265, kmConv: 265 },
  { origen: "! COMODORO RIVADAVIA", destino: "SAN FRANCISCO", kmReal: 1900, kmConv: 1900 },
  { origen: "! RIO CEBALLOS", destino: "SAN AGUSTIN", kmReal: 110, kmConv: 110 },
  { origen: "POZO DEL TIGRE", destino: "CORDOBA", kmReal: 44, kmConv: 44 },
  { origen: "SUNCHALES", destino: "GOYA", kmReal: 535, kmConv: 535 },
  { origen: "! RIO CUARTO", destino: "SAN AGUSTIN", kmReal: 147, kmConv: 150 },
  { origen: "RAFAELA", destino: "SANTA ROSA DE CALCHINES", kmReal: 148, kmConv: 150 },
  { origen: "GENERAL RODRIGUEZ", destino: "BUENOS AIRES", kmReal: 58, kmConv: 60 },
  { origen: "! SUARDI", destino: "SAN FRANCISCO", kmReal: 108, kmConv: 110 },
  { origen: "SAN FRANCISCO", destino: "SUARDI", kmReal: 108, kmConv: 110 },
  { origen: "! SAN GUILLERMO", destino: "SAN FRANCISCO", kmReal: 127, kmConv: 130 },
  { origen: "! SAN FRANCISCO", destino: "SAN GUILLERMO", kmReal: 127, kmConv: 130 },
  { origen: "! LEONES", destino: "BUENOS AIRES", kmReal: 457, kmConv: 460 },
  { origen: "! VILLA MARIA", destino: "LEONES", kmReal: 100, kmConv: 100 },
  { origen: "! ROSARIO", destino: "SAN NICOLAS DE LOS ARROYOS", kmReal: 72, kmConv: 72 },
  { origen: "! PASO DE LOS LIBRES", destino: "BUENOS AIRES", kmReal: 673, kmConv: 675 },
  { origen: "! CORRIENTES", destino: "PASO DE LOS LIBRES", kmReal: 370, kmConv: 370 },
  { origen: "SANTA ROSA DE CALCHINES", destino: "BUENOS AIRES", kmReal: 510, kmConv: 510 },
  { origen: "SANTA FE", destino: "SANTA ROSA DE CALCHINES", kmReal: 48, kmConv: 50 },
  { origen: "! SAN ANTONIO DE ARECO", destino: "BRINKMANN", kmReal: 530, kmConv: 530 },
  { origen: "SANTA FE", destino: "SUNCHALES", kmReal: 144, kmConv: 145 },
  { origen: "COMODORO RIVADAVIA", destino: "CORDOBA", kmReal: 1810, kmConv: 1810 },
  { origen: "SAN ANTONIO DE ARECO", destino: "POZO DEL TIGRE", kmReal: 636, kmConv: 636 },
  { origen: "! BUENOS AIRES", destino: "SAN ANTONIO DE ARECO", kmReal: 117, kmConv: 120 },
  { origen: "! S&#195;O LEOPOLDO", destino: "URUGUAIANA", kmReal: 664, kmConv: 665 },
  { origen: "! MERCEDES (BS AS)", destino: "JUNIN", kmReal: 165, kmConv: 165 },
  { origen: "! SAN AGUSTIN", destino: "BUENOS AIRES", kmReal: 684, kmConv: 685 },
  { origen: "CORDOBA", destino: "SAN AGUSTIN", kmReal: 70, kmConv: 70 },
  { origen: "MENDOZA", destino: "LA PLATA", kmReal: 1110, kmConv: 1110 },
  { origen: "! CALETA OLIVIA", destino: "CA&#209;ADA DE GOMEZ", kmReal: 1845, kmConv: 1845 },
  { origen: "! COMODORO RIVADAVIA", destino: "CALETA OLIVIA", kmReal: 78, kmConv: 78 },
  { origen: "! CHIVILCOY", destino: "CORRIENTES", kmReal: 988, kmConv: 990 },
  { origen: "! CHIVILCOY", destino: "POSADAS", kmReal: 1072, kmConv: 1073 },
  { origen: "MENDOZA", destino: "GENERAL RODRIGUEZ", kmReal: 994, kmConv: 995 },
  { origen: "! BUENOS AIRES", destino: "RESISTENCIA", kmReal: 935, kmConv: 935 },
  { origen: "CRESPO", destino: "RAFAELA", kmReal: 165, kmConv: 165 },
  { origen: "ZARATE", destino: "CRESPO", kmReal: 355, kmConv: 355 },
  { origen: "! CARMEN DE ARECO", destino: "ROSARIO", kmReal: 198, kmConv: 200 },
  { origen: "! COMODORO RIVADAVIA", destino: "TIO PUJIO", kmReal: 1750, kmConv: 1750 },
  { origen: "! MENDOZA", destino: "ROSARIO", kmReal: 877, kmConv: 877 },
  { origen: "! CLORINDA", destino: "URUGUAIANA", kmReal: 675, kmConv: 675 },
  { origen: "CORDOBA", destino: "SALTA", kmReal: 880, kmConv: 880 },
  { origen: "RAFAELA", destino: "CLORINDA", kmReal: 875, kmConv: 875 },
  { origen: "! CA&#209;ADA DE GOMEZ", destino: "URUGUAIANA", kmReal: 645, kmConv: 0 },
  { origen: "CORDOBA", destino: "JUNIN", kmReal: 633, kmConv: 640 },
  { origen: "! COMODORO RIVADAVIA", destino: "SAN JORGE", kmReal: 1920, kmConv: 1920 },
  { origen: "AGUILARES", destino: "CORDOBA", kmReal: 560, kmConv: 560 },
  { origen: "! CHARATA", destino: "URUGUAYANA", kmReal: 659, kmConv: 660 },
  { origen: "! VILLA CONSTITUCION", destino: "ROSARIO", kmReal: 60, kmConv: 60 },
  { origen: "! ROSARIO", destino: "VILLA CONSTITUCION", kmReal: 60, kmConv: 60 },
  { origen: "! COMODORO RIVADAVIA", destino: "CIPOLLETTI", kmReal: 1100, kmConv: 1100 },
  { origen: "SAN FRANCISCO", destino: "POSADAS", kmReal: 926, kmConv: 925 },
  { origen: "! VIEDMA", destino: "CIPOLLETTI", kmReal: 550, kmConv: 550 },
  { origen: "! CARMEN DE ARECO", destino: "CHILECITO", kmReal: 1090, kmConv: 1090 },
  { origen: "! BUENOS AIRES", destino: "CARMEN DE ARECO", kmReal: 147, kmConv: 147 },
  { origen: "! ROSARIO", destino: "ANGELICA", kmReal: 215, kmConv: 215 },
  { origen: "! CA&#209;ADA DE GOMEZ", destino: "ROSARIO", kmReal: 73, kmConv: 73 },
  { origen: "! ANGELICA", destino: "ROSARIO", kmReal: 215, kmConv: 215 },
  { origen: "ANGELICA", destino: "RAFAELA", kmReal: 38, kmConv: 38 },
  { origen: "! SAN FRANCISCO", destino: "ANGELICA", kmReal: 58, kmConv: 58 },
  { origen: "! VILLA MARIA", destino: "VILLA CONSTITUCION", kmReal: 312, kmConv: 312 },
  { origen: "! BUENOS AIRES", destino: "VIEDMA", kmReal: 915, kmConv: 915 },
  { origen: "! PARANA", destino: "SAN JORGE", kmReal: 180, kmConv: 180 },
  { origen: "! COMODORO RIVADAVIA", destino: "CINCO SALTOS", kmReal: 1110, kmConv: 1110 },
  { origen: "! SAN FRANCISCO", destino: "SAN RAFAEL (VÍA REALICÓ)", kmReal: 950, kmConv: 950 },
  { origen: "SAN JORGE", destino: "SALTA", kmReal: 1032, kmConv: 1030 },
  { origen: "! RAFAELA", destino: "SAN PEDRO", kmReal: 1078, kmConv: 1080 },
  { origen: "VILLA BELGRANO", destino: "RAFAELA", kmReal: 392, kmConv: 392 },
  { origen: "SAN SALVADOR", destino: "TUCUMAN", kmReal: 1010, kmConv: 1010 },
  { origen: "CORDOBA", destino: "VILLA GENERAL BELGRANO", kmReal: 97, kmConv: 97 },
  { origen: "! LUJAN", destino: "BUENOS AIRES", kmReal: 75, kmConv: 75 },
  { origen: "CORDOBA", destino: "RECREO", kmReal: 384, kmConv: 385 },
  { origen: "9 DE JULIO", destino: "GENERAL RODRIGUEZ", kmReal: 215, kmConv: 215 },
  { origen: "! VILLA MERCEDES", destino: "RIO CUARTO", kmReal: 130, kmConv: 130 },
  { origen: "! FRANCK", destino: "LUJAN", kmReal: 445, kmConv: 445 },
  { origen: "COMODORO RIVADAVIA", destino: "RAFAELA", kmReal: 1980, kmConv: 1980 },
  { origen: "BRINKMANN", destino: "SAN FRANCISCO", kmReal: 70, kmConv: 70 },
  { origen: "RAFAELA", destino: "COMODORO RIVADAVIA", kmReal: 1980, kmConv: 1980 },
  { origen: "RAFAELA", destino: "BRINKMANN", kmReal: 95, kmConv: 95 },
  { origen: "CORDOBA", destino: "RIO CEBALLOS", kmReal: 35, kmConv: 35 },
  { origen: "! LUJAN DE CUYO", destino: "SAN FRANCISCO", kmReal: 778, kmConv: 780 },
  { origen: "! MENDOZA", destino: "LUJAN DE CUYO", kmReal: 20, kmConv: 20 },
  { origen: "! MENDOZA", destino: "PARANA", kmReal: 950, kmConv: 950 },
  { origen: "! RAFAELA", destino: "SAN RAFAEL (VÍA REALICO)", kmReal: 1030, kmConv: 1030 },
  { origen: "! RIO GALLEGOS", destino: "BAHIA BLANCA", kmReal: 1870, kmConv: 1870 },
  { origen: "! BAHIA BLANCA", destino: "SAN LUIS", kmReal: 860, kmConv: 860 },
  { origen: "! BUENOS AIRES", destino: "MENDOZA", kmReal: 1100, kmConv: 1100 },
  { origen: "! SAN FRANCISCO", destino: "CORRIENTES", kmReal: 688, kmConv: 690 },
  { origen: "BRINKMANN", destino: "SUNCHALES", kmReal: 60, kmConv: 60 },
  { origen: "! SAN RAFAEL", destino: "BUENOS AIRES", kmReal: 990, kmConv: 990 },
  { origen: "! FREYRE", destino: "URUGUAYANA", kmReal: 630, kmConv: 630 },
  { origen: "! BUENOS AIRES", destino: "FREYRE", kmReal: 605, kmConv: 605 },
  { origen: "CORDOBA", destino: "BRINKMANN", kmReal: 250, kmConv: 250 },
  { origen: "! ITUZAINGO", destino: "URUGUAIANA", kmReal: 364, kmConv: 365 },
  { origen: "! SAN JAVIER", destino: "URUGUAIANA", kmReal: 355, kmConv: 355 },
  { origen: "! VILLA MERCEDES", destino: "ROSARIO", kmReal: 530, kmConv: 530 },
  { origen: "! VILLA MINETTI", destino: "RAFAELA", kmReal: 340, kmConv: 340 },
  { origen: "! SANTIAGO DE CHILE", destino: "MENDOZA", kmReal: 365, kmConv: 365 },
  { origen: "! RAFAELA", destino: "SAN JAVIER", kmReal: 867, kmConv: 870 },
  { origen: "CORDOBA", destino: "SANTIAGO DE CHILE", kmReal: 1040, kmConv: 1040 },
  { origen: "! MENDOZA", destino: "VILLA MINETTI", kmReal: 1145, kmConv: 1145 },
  { origen: "! SAENZ PE&#209;A", destino: "SAN FRANCISCO", kmReal: 625, kmConv: 625 },
  { origen: "CERES", destino: "PORTE&#209;A", kmReal: 154, kmConv: 155 },
  { origen: "! ROSARIO", destino: "VILLA MERCEDES", kmReal: 530, kmConv: 530 },
  { origen: "MONTEVIDEO", destino: "RAFAELA", kmReal: 750, kmConv: 750 },
  { origen: "! JUNIN", destino: "URUGUAIANA", kmReal: 810, kmConv: 810 },
  { origen: "CORDOBA", destino: "CHIVILCOY", kmReal: 650, kmConv: 650 },
  { origen: "! MENDOZA", destino: "CERES", kmReal: 975, kmConv: 975 },
  { origen: "SAN RAFAEL", destino: "CORDOBA", kmReal: 707, kmConv: 710 },
  { origen: "! VILLA OCAMPO", destino: "RAFAELA", kmReal: 460, kmConv: 460 },
  { origen: "! MENDOZA", destino: "VILLA OCAMPO", kmReal: 1300, kmConv: 1300 },
  { origen: "CORDOBA", destino: "RESISTENCIA", kmReal: 890, kmConv: 890 },
  { origen: "MENDOZA", destino: "RAFAELA", kmReal: 862, kmConv: 862 },
  { origen: "! SAN RAFAEL", destino: "VILLA MERCEDES", kmReal: 370, kmConv: 370 },
  { origen: "! TIO PUJIO", destino: "SAN FRANCISCO", kmReal: 175, kmConv: 175 },
  { origen: "! SAN JOSE (URUGUAY)", destino: "CONCEPCION DEL URUGUAY", kmReal: 325, kmConv: 325 },
  { origen: "! ROSARIO", destino: "RECREO (STA FE)", kmReal: 188, kmConv: 188 },
  { origen: "! MORTEROS", destino: "SAN JORGE", kmReal: 170, kmConv: 170 },
  { origen: "! CHACO", destino: "URUGUAYANA", kmReal: 395, kmConv: 395 },
  { origen: "LA PLATA", destino: "SAN JUSTO", kmReal: 79, kmConv: 80 },
  { origen: "MERCEDES", destino: "RAFAELA", kmReal: 490, kmConv: 490 },
  { origen: "! MENDOZA", destino: "SANTA FE", kmReal: 915, kmConv: 915 },
  { origen: "! SAN JUAN", destino: "ESPERANZA", kmReal: 937, kmConv: 937 },
  { origen: "MENDOZA", destino: "MORTEROS", kmReal: 860, kmConv: 860 },
  { origen: "! SAN JUAN", destino: "MENDOZA", kmReal: 170, kmConv: 170 },
  { origen: "! MERCEDES (BS AS)", destino: "SAN JORGE", kmReal: 440, kmConv: 440 },
  { origen: "! BAHIA BLANCA", destino: "SAN JUAN", kmReal: 1176, kmConv: 1176 },
  { origen: "! VIEDMA", destino: "BAHIA BLANCA", kmReal: 278, kmConv: 278 },
  { origen: "RAFAELA", destino: "SUNCHALES", kmReal: 42, kmConv: 42 },
  { origen: "FRANCK", destino: "SAN FRANCISCO", kmReal: 140, kmConv: 140 },
  { origen: "! SAN FRANCISCO", destino: "VIEDMA", kmReal: 1218, kmConv: 1218 },
  { origen: "! ARROYO SECO", destino: "SAN JUAN", kmReal: 950, kmConv: 950 },
  { origen: "! SAN FRANCISCO", destino: "ARROYO SECO", kmReal: 315, kmConv: 315 },
  { origen: "MERCEDES", destino: "CAMPANA", kmReal: 90, kmConv: 90 },
  { origen: "SAUCE VIEJO", destino: "RAFAELA", kmReal: 120, kmConv: 120 },
  { origen: "BRINKMANN", destino: "RAFAELA", kmReal: 95, kmConv: 95 },
  { origen: "! SAN FRANCISCO", destino: "CA&#209;ADA DE GOMEZ", kmReal: 187, kmConv: 187 },
  { origen: "! CA&#209;ADA DE GOMEZ", destino: "SAN JORGE", kmReal: 126, kmConv: 126 },
  { origen: "TUCUMAN", destino: "CAMPANA", kmReal: 1130, kmConv: 1130 },
  { origen: "! PUERTO MADRYN", destino: "MENDOZA", kmReal: 1509, kmConv: 1510 },
  { origen: "! BUENOS AIRES", destino: "BRINKMANN", kmReal: 630, kmConv: 630 },
  { origen: "MENDOZA", destino: "TUCUMAN", kmReal: 955, kmConv: 955 },
  { origen: "! CAMPANA", destino: "BUENOS AIRES", kmReal: 80, kmConv: 80 },
  { origen: "! RIO GALLEGOS", destino: "PUERTO MADRYN", kmReal: 1217, kmConv: 1217 },
  { origen: "! VILLA ANGELA", destino: "URUGUAYANA", kmReal: 585, kmConv: 585 },
  { origen: "SUNCHALES", destino: "VILLA DOLORES", kmReal: 490, kmConv: 490 },
  { origen: "! PUERTO MADRYN", destino: "BUENOS AIRES", kmReal: 1300, kmConv: 1300 },
  { origen: "! BALNEARIA", destino: "BUENOS AIRES", kmReal: 700, kmConv: 700 },
  { origen: "CORDOBA", destino: "BALNEARIA", kmReal: 185, kmConv: 185 },
  { origen: "! SAN JOSE (URUGUAY)", destino: "SAN JORGE", kmReal: 690, kmConv: 690 },
  { origen: "POSADAS", destino: "SUNCHALES", kmReal: 930, kmConv: 0 },
  { origen: "! BAHIA BLANCA", destino: "PERGAMINO", kmReal: 640, kmConv: 640 },
  { origen: "! RAWSON", destino: "BAHIA BLANCA", kmReal: 735, kmConv: 735 },
  { origen: "SAN PEDRO", destino: "SAN FRANCISCO", kmReal: 410, kmConv: 410 },
  { origen: "! JARDIN AMERICA", destino: "URUGUAYANA", kmReal: 431, kmConv: 431 },
  { origen: "RAFAELA", destino: "CONCEPCION DEL URUGUAY", kmReal: 393, kmConv: 393 },
  { origen: "! RAFAELA", destino: "JARDIN AMERICA", kmReal: 955, kmConv: 955 },
  { origen: "SAN LUIS", destino: "ZARATE", kmReal: 750, kmConv: 750 },
  { origen: "! RAFAELA", destino: "RAWSON", kmReal: 1660, kmConv: 1660 },
  { origen: "! BELLA VISTA(CORRIENTES)", destino: "RAFAELA", kmReal: 565, kmConv: 565 },
  { origen: "! RAFAELA", destino: "VIEDMA", kmReal: 1280, kmConv: 1280 },
  { origen: "! RAFAELA", destino: "RIO GALLEGOS", kmReal: 2800, kmConv: 2800 },
  { origen: "RAFAELA", destino: "SALTA", kmReal: 930, kmConv: 930 },
  { origen: "ZARATE", destino: "SAN LUIS", kmReal: 750, kmConv: 750 },
  { origen: "! CORRAL DE BUSTOS", destino: "ROSARIO", kmReal: 190, kmConv: 190 },
  { origen: "! SAN PEDRO", destino: "CAMPANA", kmReal: 90, kmConv: 90 },
  { origen: "! SAN RAFAEL", destino: "RIO CUARTO", kmReal: 490, kmConv: 490 },
  { origen: "SAN RAFAEL", destino: "RAFAELA", kmReal: 880, kmConv: 880 },
  { origen: "! LULES", destino: "RAFAELA", kmReal: 670, kmConv: 670 },
  ];

  for (const r of rutas) {
    try {
      const record = new Record(collection, {
        origen: r.origen,
        destino: r.destino,
        km_reales: r.kmReal,
        km_convenio: r.kmConv,
        activo: true,
      });
      dao.saveRecord(record);
    } catch (e) {
      // un registro que falle no debe frenar a los demas.
    }
  }

  return null;
}, (db) => {
  return null; // no se revierte (des-hacer 750 altas por nombre no vale la pena)
})
